### ISSUE TITLE
New compiled server closes after Loading lua libs

### ISSUE THREAD

**Issue by FearLucien** [opentibiabr/otservbr-global-archived#100]
**Describe the bug**
Server closes when trying to loading lua libs on new compile, old compiled server from 
 source: https://otland.net/threads/new-ot-project-otservbr-global-10x-outdated-with-sprites-12-15.264701/ win 64bit load fine.

**To Reproduce**
Compile server from current source, try to launch.

**Screenshots**
![server auto closes](https://user-images.githubusercontent.com/51265848/58751413-0cf18500-846c-11e9-9848-b6cebe7e5afa.png)
closes right after.

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10

**Additional context**
Compiled with TFS SDK v3.2(libraries) and boost_1_66_0

**Comment by gpedro** [comment]
Can you provide more information? Which dlls are you using? @MajestyOTBR have compiled using 
TFS SDK 3.2 + Boost 1_66 - x64 and works fine.

**Comment by dudantas** [comment]
@FearLucien you using otbr full pack ?
if you not using, it's need... 
Because the pack have modifications.

**Comment by FearLucien** [comment]
@eduardodantas95, @gpedro 
Using the full pack from here, it compiles fine with visual studio 2017, using TFS SDK 3.2 + Boost 1_66 - x64.
When you launch server it crashes after loading lua libs. I have used the server that was compiled on otland post in same folder it loads up and lua libs load. There are no compiling errors. 
![compile](https://user-images.githubusercontent.com/51265848/58753869-ecd5bc00-8493-11e9-83b1-00b1b03857df.png)
![server auto closes](https://user-images.githubusercontent.com/51265848/58753872-f3643380-8493-11e9-8554-e885d03f01cd.png)
up is server compiled today 6-1-19
down is screenshot of server compiled on 5-27-19 using the new data pack/source(from this github earlier today)(just placed server in same folder as the new server for testing)
![May 27th compiled](https://user-images.githubusercontent.com/51265848/58753910-9321c180-8494-11e9-8508-855f99e24699.png)

**Comment by FearLucien** [comment]
Using Appveyor compiled it and it loads fine. When using Visual studio and tutorial to compile the server requires more libs. to be included into the folder with server. 
When using Visual studio 2017 directly. Server requires. Dlls listed belowed in order to load.(which were in output x64/release folder of server)
libmysql.dll
boost_iostreams.dll
boost_filesystem-vc141-mt-x64-1_70
zlib1.dll
bz2.dll
lzma.dll
zstd.dll

Using appveyor requires only
libmysql.dll

**Comment by gpedro** [comment]
can you run on prompt command instance to see if throws an exception?

note: we are on discord, https://discord.gg/3NxYnyV

**Comment by FearLucien** [comment]
joined discord

**Comment by FearLucien** [comment]
vcpkg and libs worked together causing error. Unistalled vcpkg and only used TFS SDK 3.2 + Boost 1_66 - x64 worked correctly.

**Comment by eduardodantas95** [comment]
Solved?
