### ISSUE TITLE
Boss Urmahlullu the Immaculate

### ISSUE THREAD

**Issue by gabz182** [opentibiabr/otservbr-global-archived#1003]
**Describe the bug**
Após você entrar na sala e matar o boss Urmahlullu the Immaculate, ele vira sangue impossibilitando de pegar loot.

After you enter the room and kill the boss Urmahlullu the Immaculate, he becomes blood making it impossible to get loot.

https://i.imgur.com/owMxo0L.jpg

**Comment by Oliveiralt** [comment]
it happens because it doesn't have the transformation script

**Comment by travisani** [comment]
Loot id: 36248

**Comment by dudantas** [comment]
Moved for the #726, thanks

**Comment by ivansho92** [comment]
i have already thats script but idk how post here in correct way.
