### ISSUE TITLE
Extended OP Code

### ISSUE THREAD

**Issue by Peixonauta2** [opentibiabr/otservbr-global-archived#1009]
Existem algum bug referente à Extended OPCodes na source, acredito eu.
Testei aqui numa TFS 1.2 e funcionou, entretanto, os mesmos códigos nessas sources não funcionaram.
Sempre me retornam o mesmo erro:
```
ERROR: Unable to send extended opcode 1, extended opcodes are not enabled on this server.
ERROR: Unable to send extended opcode 201, extended opcodes are not enabled on this server.
ERROR: Unable to send extended opcode 110, extended opcodes are not enabled on this server.
```
Por que isso acontece? Onde ativo as Extended Opcodes que dizem estar desativadas? Isso é um bug, certo?

**Comment by gpedro** [comment]
extended opcodes are not implemented yet

**Comment by Peixonauta2** [comment]
Is there any plans for that?

**Comment by gpedro** [comment]
currently, we are focusing to implement a newer feature, items, quests, and mechanisms

**Comment by dudantas** [comment]
@peixonauta2 Look this: https://github.com/opentibiabr/otservbr-global/pull/1018
