### ISSUE TITLE
1500 oz "Sorry not possible" on move

### ISSUE THREAD

**Issue by FearLucien** [opentibiabr/otservbr-global-archived#101]
**Describe the bug**
Can't move >= 1500 oz off of character, or move on ground to another tile on ground. Can move off on ground tile to backpack. In protection zone or non protection zone same results.

**To Reproduce**
Use 50 dragon ham which is exactly 1500 oz.

**Expected behavior**
Should be able to move that much cap. on real tibia, maybe in place to restrict an ot server bug?
Don't know cap. restricts of current tibia version. Just that I was able to when Tibia 11 first came out.

**Additional context**
code located in tile.cpp search 150000

**Comment by dudantas** [comment]
What is the limit in the global tibia?
We put this limitation because of the WPE program, but it should be 1,000,000 (10k) and not 150,000
I have already modified it, thank you.

**Comment by FearLucien** [comment]
global tibia capacity limit unknown. Searched around could not find anything on limit. Thanks trying to do my best to help.

**Comment by dudantas** [comment]
I believe there is a limit in the global, for example to send in the parcel if I am not mistaken the limit is 5 or 10k

**Comment by dudantas** [comment]
fixed

soon will be up

**Comment by dudantas** [comment]
https://github.com/opentibiabr/OTServBR-Global/commit/55dd4e557914e4f3ca577507254a37a80e58908b
fix
