### ISSUE TITLE
Addons Bought In The Store + Change Sex

### ISSUE THREAD

**Issue by rtsrick2017** [opentibiabr/otservbr-global-archived#1024]
When an outfit/addon is bought through the store, only the outfit for the current character sex is added.

Problem:

If said player changes the sex of the character, the addon for the opposite sex will not be available, thus, he's just lost the product he had bought, because he cannot wear it, and if he wants to wear it ever again, he'll have to buy another sex change, which makes no sense.

This does not happen when acquiring outfits through npcs, because they already give the player the outfit for both.

**Comment by majestyotbr** [comment]
Updated gamestore:
https://github.com/opentibiabr/otservbr-global/blob/develop/data/modules/scripts/gamestore/gamestore.lua
https://github.com/opentibiabr/otservbr-global/blob/develop/data/modules/scripts/gamestore/init.lua
