### ISSUE TITLE
Question about loot colors

### ISSUE THREAD

**Issue by rtsrick2017** [opentibiabr/otservbr-global-archived#1028]
How do I change the color on loot text/item hightlights?

As I have noticed, those are bound to the Cyclopedia's information, but is there a way to change those values myself, as some items are not listed?

It should instead check the prices from the market and npcs to determine the color, and if the item has a color or not.

The problem with that is: falcon, cobra, gnome sets and other rares (robe of the ice queen, etc...) are displayer without a color both in text and around the item.

If I missed something, I apologize, but just can't find a way.

**Comment by dudztroyer** [comment]
that's how tibia works... global is like that. if there is not market offer, then the item is grayed out. 

In global you can set a custom value for the item inside the item's cyclipedia.. Not sure if the OT is working like that, tho

**Comment by gerotib** [comment]
@dudztroyer yeah you can set your own value and it works fine

**Comment by rtsrick2017** [comment]
I know, but I have attempted that, and it didn't work, for some reason. Do I need to leave that offer until I restart the server or something? @dudztroyer

**Comment by rtsrick2017** [comment]
Oh, I see! But regarding the market offers, it's not working for me, it does not display the avarage price, do I need to leave that offer for a while, untin the server is re started? Or even having more than one being bought?

Nevermind, just had to close and open the client and it changed haha
