### ISSUE TITLE
crinsom sword

### ISSUE THREAD

**Issue by granoob** [opentibiabr/otservbr-global-archived#103]
segundo tibia wiki, crisom sword tem atk 28, tem uma no item xml tem duas porem uma com, 18atk , justamente que vende no npc, correcao somente muda pra 28atk

**Comment by dudantas** [comment]
vende em qual npc ?

**Comment by granoob** [comment]
thais por exemplo, mais dropa tb e ta dropando a de 18atk, so alterar no xml, pq de 18 nao existe isso antigo

**Comment by dudantas** [comment]
https://www.tibiawiki.com.br/wiki/Crimson_Sword_(Rashid) a de 18 atk é essa

**Comment by granoob** [comment]
sim mas ela atualmente nao existe mais veja 
https://www.tibiawiki.com.br/wiki/Crimson_Sword

**Comment by dudantas** [comment]
São duas. As duas existem, só que a outra é item de quest 
Vou analisar aqui o que tá ocorrendo blz
Creio que erraram ao registrar as sprites e ambas estão com a mesma sprite e registrado errado nos npcs

**Comment by eduardodantas95** [comment]
fix on https://github.com/opentibiabr/OTServBR-Global/commit/61fe3764c3cd29f3729d9fc11c4858a4f5ba2443
