### ISSUE TITLE
Quickloot issues:

### ISSUE THREAD

**Issue by rtsrick2017** [opentibiabr/otservbr-global-archived#1030]
Quickloot has a couple issues that I've found thus far:

First issue:

If you select a brown backpack inside of your main as the container for "others" category, and you have different backpacks inside of your brown backpack, once the first is filled up, you won't be able to pick up loots, until you put a identical backpack inside of it

ex:

1- select a brown backpack as your 

![image](https://user-images.githubusercontent.com/36482994/79372296-2ab4c500-7f2c-11ea-9552-c55c32e4935d.png)

2- put any other type of backpack inside (beach backpack for example)

![image](https://user-images.githubusercontent.com/36482994/79372609-546dec00-7f2c-11ea-9109-f668d2c4a1f0.png)

3- fill it up with loot

![image](https://user-images.githubusercontent.com/36482994/79373140-a57de000-7f2c-11ea-9f62-ba5e57c06104.png)

4- try to pick up more loot

![image](https://user-images.githubusercontent.com/36482994/79373224-b4649280-7f2c-11ea-84c6-6bfae074feb9.png)
![image](https://user-images.githubusercontent.com/36482994/79373269-bcbccd80-7f2c-11ea-8067-ea3740e3a9e5.png)

5- substitute the beach backpack with another brown backpack and try again

![image](https://user-images.githubusercontent.com/36482994/79373393-e37b0400-7f2c-11ea-89db-a9cb8da96e90.png)
![image](https://user-images.githubusercontent.com/36482994/79373420-ea097b80-7f2c-11ea-834b-cce1e30f7c33.png)
![image](https://user-images.githubusercontent.com/36482994/79373438-f1308980-7f2c-11ea-93b1-d53ec119a948.png)

And as you can see, CAP is not the problem:

![image](https://user-images.githubusercontent.com/36482994/79374548-c6930080-7f2d-11ea-9281-9b93bdf807c2.png)

Second issue:

Another issue related to the last one, as you can see through those images, if your container is filled up, the countable drops will still be sent to the other backpack, instead of keep stacking on the first and so backpacks, even though their 100x limit has not been reached yet.

**Comment by alisonjf** [comment]
My src code can't find method "getCorpseOwner" on thing.cpp, this method only exists in container.cpp, are you having this problem? I am thinking in a way to create the method in thing.cpp so I dont have to change the whole logic in quickloot.lua.

**Comment by rtsrick2017** [comment]
Yes

![image](https://user-images.githubusercontent.com/36482994/79386762-ff88a080-7f40-11ea-8820-794dfbd1150a.png)
