### ISSUE TITLE
10 client kill monster crash

### ISSUE THREAD

**Issue by kozmo604** [opentibiabr/otservbr-global-archived#1043]
In 10 client killing different monsters randomly crashes client.

https://ibb.co/9Y6Y8mF

Windows 10

**Comment by travisani** [comment]
Because bestiary and colorful names loot.
Probably this client is not supported anymore.

**Comment by kozmo604** [comment]
To bad i wanted to use both clients that is okay though i will wait and see if it ever gets fixed thanks.

**Comment by dudantas** [comment]
Client 10 is no longer supported.
We will no longer offer support.
