### ISSUE TITLE
Protocol 12.31 Development

### ISSUE THREAD

**Issue by mattos01dev** [opentibiabr/otservbr-global-archived#1045]
Bug login client 12.31.

Are you expected to enter protocol 12.31, login by email?

**Comment by jlcvp** [comment]
The [OTG-Premium-Version](https://github.com/Johncorex/OTG-Premium-Version) fork already has it, someone can make the diff and port the bytes?

About the login, I've done a version on [this gesior repo](https://github.com/omarcopires/gesior/) and updated the plugin for myAAC [here](https://github.com/OTG-Developers/myaac-tibia12-login). It accepts both username login (12.30-) and email login (12.31+)

**Comment by dudantas** [comment]
Good morning.

Today we have a concern that is the launch of features and bug fixes that we are already aware of. Is launching support for new protocols good? For sure, and we will get there. However, when the protocol advances, new failures are always generated and this is what we intend to avoid at the moment. We will soon work on that, but not now.

I thank @jlcvp for their willingness, we can certainly work together for an even better open tibia.

We will keep the issue open until we have the feature with the label enhancement.

**Comment by majestyotbr** [comment]
Protocol 12.40: https://github.com/opentibiabr/otservbr-global/commit/a9483ac874a05c19b2e02ee794f997bda0980e95
