### ISSUE TITLE
paladin exhaust no ataque ao usar strong mana potion

### ISSUE THREAD

**Issue by gabz182** [opentibiabr/otservbr-global-archived#1052]
**To Reproduce**

Quando você deixar a hotkey de strong mana potion apertada para usar a potion, a spear para de atacar, dá exhaust no ataque.

**Comment by unlineworld** [comment]
È a logica do sistema, voce tem que parar de atacar abrir a garrafa de potion e beber por isso tem exhausted

**Comment by gabz182** [comment]
> È a logica do sistema, voce tem que parar de atacar abrir a garrafa de potion e beber por isso tem exhausted

@unlineworld 
E pq isso não acontece com as outras vocações tipo Knight?
A sua logica era pra funcionar em todas as vocações e não apenas para paladinos.

**Comment by luucassoares** [comment]
eu notei esse comportamento descrito no bug já. parece que vc perde um turno dos ataques com as arrows (ou qlqr outra arma de rp) se vc usar poção ou runa, no global isso não acontece eu acho

**Comment by andersonfaaria** [comment]
This is fixed in #1191 with a more elegant solution rather than just removing the swing entirely.

**Comment by gerotib** [comment]
Isnt that what is `classicAttackSpeed` in config for? It was added in this pr:
https://github.com/otland/forgottenserver/pull/2109

> When this config is true, all the attacks are going to have constant
speed no matter what the player do.

If thats the case then #1175 #1191 could be closed w/o merging.

But well, the thing that its interrupting mainly pally (bows, spears etc), and knight / mages (swords, rods) works fine is kind of annoying.

**Comment by lBaah** [comment]
That how it works in the RL Tibia. This is not a bug.

**Comment by gabz182** [comment]
No global não é assim não, mas enfim...
Deixa assim então.
