### ISSUE TITLE
Munições com duração desaparecendo ao equipar pela Hotkey.

### ISSUE THREAD

**Issue by gabz182** [opentibiabr/otservbr-global-archived#1065]
**Describe the bug**
Munições como spectral bolt e diamond arrow desaparecem quando você equipa elas pela Hotkey.
Isso acontece apenas com munições que tem duração, minuções normais estão corretas.

**To Reproduce**
https://i.imgur.com/wnIdkvD.mp4

OBS: Após remover a duração do Spectral bolt para fazer um teste constatei que a munição parou de sumir ao equipar/desequipar pela hotkey.

**Comment by majestyotbr** [comment]
This was reported before on #836.

Thanks for your report.
