### ISSUE TITLE
minotaur pont

### ISSUE THREAD

**Issue by devdeadpool** [opentibiabr/otservbr-global-archived#1069]
Item ID: 1946
Position: 32428, 32203, 14;
alavanca nos minotaur, que devia criar uma ponte, n funciona kk bug
e logo mais pra frente, descendo a ponte, nao tem respawn de minotaur

![download](https://user-images.githubusercontent.com/63550690/79930120-0706e880-841e-11ea-844f-db92dbb0596d.png)

**Comment by gpedro** [comment]
https://youtu.be/Sh_JvfsN2VE?t=906

**Comment by marcosvf132** [comment]
Due to a huge amount of issues, we are moving all bugs related to quest to one single ISSUE, for future issues related to the quest, please consider reporting it on that specific ISSUE, thanks.
 - Ref: #726
