### ISSUE TITLE
Crash cliente ao vender item

### ISSUE THREAD

**Issue by gabz182** [opentibiabr/otservbr-global-archived#1072]
**Describe the bug**
Quando você vai vender mais de 80 items no NPC o cliente trava e não responde mais.

**To Reproduce**
Faça 80 magma coat com o GM e vá vender no Rashid, quando você clicar para confirmar a venda o seu cliente vai congelar.
OBS: Qualquer item em grande quantidade vai bugar, a magma foi só um exemplo.
-
Edit: Se você comprar 100 items não estacáveis acontece a mesma coisa.

Google trans
Make 80 magma coat with the GM and go sell on Rashid, when you click to confirm the sale your customer will freeze.
NOTE: Any item in large quantities will go bad, magma was just an example.

**Screenshots**
https://prnt.sc/s4d01n

Vídeo
https://youtu.be/an3Mbmuk4YY

**Comment by jlcvp** [comment]
@gabz182 o problema acontece caso o item seja stack? Tipo 90 gold ingot?

**Comment by gabz182** [comment]
@jlcvp são apens em items não stacaveis, achei outra forma que buga tbm.
Depois que você  hi, trade e abre pra vc vender o item , aí vc faz o comando "/i magma coat, 100" , o cliente congela...

**Comment by gabz182** [comment]
@jlcvp
Fiz um vídeo. 
https://youtu.be/an3Mbmuk4YY

**Comment by gpedro** [comment]
confirmado.
irei investigar o motivo

**Comment by Lycanzito** [comment]
Na verdade.. isso dai foi concertado a bastante tempo..

Acho que uns 3~4 mêses atrás, foi arrumado.

![bloggif_5ea798dfe6cd7](https://user-images.githubusercontent.com/52710697/80441405-3f586c00-88e1-11ea-9c55-1ed946c50199.gif)

**Comment by gabz182** [comment]
@Lycanzito os pia falou que não tinha aprovado o PR de quem mandou, então não foi pro merge, o bug continua.
Eu desabilitei a função que o rick me ensinou pra parar de bugar o cliente.

**Comment by Lycanzito** [comment]
> @Lycanzito os pia falou que não tinha aprovado o PR de quem mandou, então não foi pro merge, o bug continua.
> Eu desabilitei a função que o rick me ensinou pra parar de bugar o cliente.

a ok =)!

**Comment by ikaro1997** [comment]
https://github.com/opentibiabr/otservbr-global/pull/810/files

Testado, 100% funcional, resolve o Bug.

**Comment by andersonfaaria** [comment]
check if this solves the issue:
https://github.com/SaiyansKing/optimized_forgottenserver/commit/2ffba16ba0c70c7aab6247a3ed2a0eb9fbd6abe1

**Comment by gerotib** [comment]
@andersonfaaria I was testing this commit and it actually fixes that. Didnt notice any issues caused by these changes.

**Comment by andersonfaaria** [comment]
> @andersonfaaria I was testing this commit and it actually fixes that. Didnt notice any issues caused by these changes.

the one from Sayans? I'll bring this repo later on in case it is

**Comment by gerotib** [comment]
@andersonfaaria yes, along with https://github.com/SaiyansKing/optimized_forgottenserver/commit/a1583cf520f2cc379b98bf0d24162f375b184cd1
but idk if thats necessary
