### ISSUE TITLE
Gold converter

### ISSUE THREAD

**Issue by mgallo17** [opentibiabr/otservbr-global-archived#1073]
Script de converter gold coin pra platinum coin e crystal coin nao funciona.

**Comment by majestyotbr** [comment]
data/actions/actions.xml

`<action itemid="26378" script="others/objects/goldConverter.lua"/>`
`<action itemid="29020" script="others/objects/goldConverter.lua"/>`
`<action itemid="32109" script="others/objects/magicGoldConverter.lua"/>`
`<action itemid="33299" script="others/objects/magicGoldConverter.lua"/>`

Você precisa ter o gold converter ou o magic gold converter.

**Comment by majestyotbr** [comment]
data/modules/scripts/gamestore/gamestore.lua:

Gold Converter: https://github.com/opentibiabr/otservbr-global/blob/develop/data/modules/scripts/gamestore/gamestore.lua#L3709-#L3718

Magic Gold Converter: https://github.com/opentibiabr/otservbr-global/blob/develop/data/modules/scripts/gamestore/gamestore.lua#L3739-#L3748
