### ISSUE TITLE
Dawnport com bug nas portas e impossibilidade de ir pra main

### ISSUE THREAD

**Issue by mgallo17** [opentibiabr/otservbr-global-archived#1074]
Como as portas nao funcionam e so tem uma porta, ao ir pro barco o NPC diz que ja tem uma vocacao e impossibilita o embarque a main

**Comment by htc16** [comment]
Além desses erros que também notei, realizei testes, e a mana e vida que ganha as vocations, em dawnport, é desproporcional ao certo, acho que o cálculo tá errado de todas vocations. 

Para realizar o cálculo e ver a vida e mana de cada level: https://guildstats.eu/character-level?lang=pt
