### ISSUE TITLE
Chiller e scorcher nao sao reconhecidos como items

### ISSUE THREAD

**Issue by mgallo17** [opentibiabr/otservbr-global-archived#1075]
O não reconehcimento como itens impossibilita o player de testar as profissoes de druid e sorcerer.

**Comment by gpedro** [comment]
como assim o não reconhecimento?

```
23:05 You see the chiller.
It can only be wielded properly by druids of level 1 or higher.
It weighs 15.00 oz.
It is a little, well, chilly to the touch.
```

![image](https://user-images.githubusercontent.com/2898638/80170833-e0c88080-85b6-11ea-96d9-ff6d391dffc2.png)

**Comment by YohanAugusto** [comment]
Existem dois Chiller no jogo, quando voce cria o item pelo nome, ele acaba criando o de ID 23804, por isso você não consegue usar.

`<item id="23721" article="the" name="chiller">
		<attribute key="description" value="It is a little, well, chilly to the touch." />
		<attribute key="weight" value="1500" />
		<attribute key="weaponType" value="wand" />
		<attribute key="quicklootcategory" value="weaponwand" />
		<attribute key="shootType" value="smallice" />
		<attribute key="range" value="3" />
	</item>`

`<item id="23804" article="the" name="chiller">
		<attribute key="description" value="Ideally suited to teach young druids the first steps in their craft." />
	</item>`

**Comment by dudantas** [comment]
Sorc:
![image](https://user-images.githubusercontent.com/8551443/80982454-b9b54e80-8e01-11ea-9ff1-8f918030ff8d.png)

Druid:
![image](https://user-images.githubusercontent.com/8551443/80982543-dc476780-8e01-11ea-8043-8326a67f6476.png)


Tested and working.
