### ISSUE TITLE
Imbue backpack

### ISSUE THREAD

**Issue by kozmo604** [opentibiabr/otservbr-global-archived#1088]
When you imbue a backpack it doesn't give extra cap.
Maybe this was fixed and i did not update a file yet?

**Comment by rikemark** [comment]
this has already been solved

**Comment by kozmo604** [comment]
When was it solved what date?

**Comment by rikemark** [comment]
im not sure about the date, but i just tested it and the embuement system is working correctly.
do you have the latest version compiled?
maybe this dont work with GM/GOD

**Comment by kozmo604** [comment]
All imbuements work accept for backpacks it does nothing adds no cap can anyone confirm it actually works cuz i have latest server and is not working.

**Comment by dudantas** [comment]
Duplicated: https://github.com/opentibiabr/otservbr-global/issues/582

You can comment on the other issue.
