### ISSUE TITLE
Mensagem de Erro na distro após o player morrer redskull.

### ISSUE THREAD

**Issue by gabz182** [opentibiabr/otservbr-global-archived#1089]
**Describe the bug**
Após o player morrer redskull aparece o seguinte erro na distro

`Lua Script Error: [CreatureScript Interface]                                    data/creaturescripts/scripts/others/droploot.lua:onDeath                        data/modules/scripts/blessings/blessings.lua:278: attempt to index global 'self' (a nil value)                                                                  stack traceback:                                                                        
[C]: in function '__index'                                                      data/modules/scripts/blessings/blessings.lua:278: in function 'DropLoot'                                                                                        data/modules/scripts/blessings/blessings.lua:345: in function <data/modules/scripts/blessings/blessings.lua:338>`

**To Reproduce**
Pegue redskull e morra com bless.

**Comment by andersonfaaria** [comment]
@gabz182 this still happens?

**Comment by heberholanda** [comment]
Bug no longer exists. Thanks for report.
