### ISSUE TITLE
help with magic wall lasts very little and ends in different times, that is, one magic wall lasts 15 seconds another lasts 18 seconds another lasts 17 seconds so on

### ISSUE THREAD

**Issue by helloween666** [opentibiabr/otservbr-global-archived#1093]
## CAUTION: OUR SERVER IS UPDATED DAILY. MAKE SURE YOU ARE REPORTING SOMETHING ON THE LATEST VERSION OF THE SERVER.

**Describe the bug**

**To Reproduce**
Note: include any configuration/script required to reproduce.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Version: [e.g. 10]

**Additional context**

**Comment by helloween666** [comment]
help with magic wall lasts very little and ends in different times, that is, one magic wall lasts 15 seconds another lasts 18 seconds another lasts 17 seconds so on

**Comment by dudztroyer** [comment]
Hey, why didn't you fill the formulary to explain how to reproduce? You just posted the placeholder...

Btw in global the magic wall are random... This is expected behaviour

**Comment by gpedro** [comment]
just for you know: #635
