### ISSUE TITLE
Appveyor compile problem

### ISSUE THREAD

**Issue by cys9211** [opentibiabr/otservbr-global-archived#1094]
Build execution time has reached the maximum allowed time for your plan (60 minutes).

**Comment by gpedro** [comment]
where this is happening? cuz on our repository is everything working fine.

**Comment by cys9211** [comment]
https://ci.appveyor.com/project/cys9211/otservbr-global-n08du

**Comment by dudantas** [comment]
This is apparently a problem with the appveyor.
Unfortunately, we can't do anything.

I'm closing, if you have more information that can lead us to discover cause, report here and we can reopen.
Thank you for understanding.

**Comment by majestyotbr** [comment]
You can request an increase of build timeout by sending an email to `support@appveyor.com` or using the AppVeyor support center: https://help.appveyor.com/
