### ISSUE TITLE
help with elemental arrows

### ISSUE THREAD

**Issue by helloween666** [opentibiabr/otservbr-global-archived#1099]
## CAUTION: OUR SERVER IS UPDATED DAILY. MAKE SURE YOU ARE REPORTING SOMETHING ON THE LATEST VERSION OF THE SERVER.

**Describe the bug**

**To Reproduce**
Note: include any configuration/script required to reproduce.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Version: [e.g. 10]

**Additional context**

**Comment by helloween666** [comment]
help me plx elemental arrow with attack very low i want normal damage hlp me please

**Comment by majestyotbr** [comment]
Why didn't you fill the formulary to explain how to reproduce?

**Comment by helloween666** [comment]
sorry I'm new on this page I don't know the rules an apology but I really need to fix that error

**Comment by helloween666** [comment]
I want to change or reverse everything in terms of arrows with elements because their damage is really too low so I am not looking to fix a part of some code or lua or src I am looking for a solution to please
