### ISSUE TITLE
Suggestion: Loot Color

### ISSUE THREAD

**Issue by rtsrick2017** [opentibiabr/otservbr-global-archived#1100]
I have a suggestion regarding the loot/items colors.

As it is right now, the information regarding loot colors, is bound to the market prices and the Cyclopedia. Problem is: even if you change the price on the npcs or the item's names on item.xml, it will remain as presented in global tibia. 

****My suggestion is:**
Make the Cyclopedia retrieve data from the npc files instead. This way the administrators can decide the color of the loots, to make it easier for players to spot them.**

I know, I know, this is a global tibia project, but the users should have freedom to tweak with prices as they wish, since most servers do change stuff from real tibia, to make their server more appealing.

Regarding the market option for this:

Since the colors from the market will reset back to white/no color if no more items of that kind are sold within a certain time frame, which is not a viable option in low populated servers.
Why is this an issue, after all?

Well, it makes it harder for players to spot the loot on the spam of the loot message, and makes this feature quite unecessary.

This is just my opinion on the matter, thanks for your attention, anyway!

**Comment by gpedro** [comment]
currently, we cannot do this. if you take a look at PR #969, we just provide clientid before item name and the colorful messages magically happen

https://github.com/opentibiabr/otservbr-global/pull/969/files#diff-5981f489539ad5124d97b7b98053e484R205

**Comment by joseluis2g** [comment]
that information is inside the dat/asset files, its not like you can change this server-side
```{ 
   "id":169,
   "frameGroup":[ 
      { 
         "fixedFrameGroup":"FIXED_FRAME_GROUP_OBJECT_INITIAL",
         "id":2,
         "spriteInfo":{ 
            "patternWidth":1,
            "patternHeight":1,
            "patternDepth":1,
            "layers":1,
            "spriteId":[ 
               110992
            ],
            "boundingBoxPerDirection":[ 
               { 
                  "x":6,
                  "y":4,
                  "width":20,
                  "height":22
               }
            ]
         }
      }
   ],
   "flags":{ 
      "usable":true,
      "take":true,
      "npcsaledata":[ 
         { 
            "name":"Miraia",
            "location":"Darashia City",
            "salePrice":100
         }
      ],
      "cyclopediaitem":{ 
         "cyclopediaType":169
      }
   },
   "name":"scarab cheese"
}```

**Comment by Decretis** [comment]
You need to alter the client dat file (check out this repo: [gunzino/tibia11-nodejs-parser](https://github.com/gunzino/tibia11-nodejs-parser)).

A simple script to change a plate armor value:
```
'use strict';

const fs = require('fs'), 
appearancesLib = require('./src/Appearances');

var appearances = new appearancesLib();
appearances.load().then(function() {
  var plateArmor = appearances.getItemById(3357); //https://opentibiabr.github.io/clientid-finder/

  var testnpc = plateArmor.flags.npcsaledata[0]
      testnpc.name = "Decretis";
      testnpc.location = "GitHub";
      testnpc.buyPrice = 1000000;

  plateArmor.flags.npcsaledata = [testnpc];
  appearances.save('test.dat');
});
```

Copy newly created file (test.dat) to your client assets folder and change its name to match the one in the catalog-content.json file.

![parm1](https://user-images.githubusercontent.com/12548757/80709779-2ffa3e00-8aee-11ea-8a82-3761cb3287ae.png)
![parm2](https://user-images.githubusercontent.com/12548757/80709786-32f52e80-8aee-11ea-9e5d-4fe983a7123a.png)
