### ISSUE TITLE
Op Code

### ISSUE THREAD

**Issue by Peixonauta2** [opentibiabr/otservbr-global-archived#1106]
Hello guys!
I'm developing a new server and I'm using Otclient V8.
I'm using your sources (the best btw) to do so and I noticed that you only allow Extended Op Code when in Debug Mode.
I know that Github is not a support forum but I need to ask you: Do you guys have any plans to allow Extended Op Code when the server isn't in Debug Mode?

**Comment by gpedro** [comment]
It is good to see people using otv8.

The @otcv8 creator (kondrah) is already working on implementing OTCv8 compatibility. Just tell to him how much happy you will be if this project was otcv8 compatibility

**Comment by Peixonauta2** [comment]
I'm sorry by I'm afraid that I didn't understand.
Your sources allow Extended Op Code but the OTClientV8 doesn't?
