### ISSUE TITLE
Client Not responding Client x10

### ISSUE THREAD

**Issue by Paahsz** [opentibiabr/otservbr-global-archived#1107]
## CAUTION: OUR SERVER IS UPDATED DAILY. MAKE SURE YOU ARE REPORTING SOMETHING ON THE LATEST VERSION OF THE SERVER.

**Describe the bug**
I'm testing warzones 4/5/6, but then use the crystal in the geodes, the teleport opens and works perfectly, but then try to enter the teleport the client is not responding. there you have to close the client open again and when you log in your character is already in the boss's room dying.

**Expected behavior**
The char only needs to pass through the created teleport and should not present any problems on the client

**Screenshots**
![image](https://user-images.githubusercontent.com/64566720/80662677-3f36a880-8a68-11ea-8c1f-6dcaa260290d.png)

**Desktop (please complete the following information):**
windows 10

**Comment by dudantas** [comment]
You tested in client 12x ?

**Comment by Paahsz** [comment]
No, i can only use 10x, i dont like so much 12x

**Comment by oualid6496** [comment]
@dudantas I think this can be closed since client 10 isn't supported anymore?
