### ISSUE TITLE
Asura Palace - Door, Ceiling and Crack bugs

### ISSUE THREAD

**Issue by Szulcek69** [opentibiabr/otservbr-global-archived#111]
I've made some more testing and here are some issues I was able to find. 
1) To ceiling in some places around Asura Mirror overlaps the floor. Maybe the solution would be to move whole location one floor below? Screenshot attached.
![mirror ceiling](https://user-images.githubusercontent.com/51335460/58855262-e74cc180-869f-11e9-9921-be867a5ab0a2.PNG)

2) The door in Asura mirror are first rotating with the frame making the unable to walk through and later on opening. Screenchots attached. Location of doors:
a) 32863, 32809, 9
b) 32812, 32812, 9
![door1](https://user-images.githubusercontent.com/51335460/58855359-309d1100-86a0-11e9-9b5c-90c8d880ea8d.PNG)
![door2](https://user-images.githubusercontent.com/51335460/58855366-3135a780-86a0-11e9-9a66-490e38d1b00f.PNG)

3) The cracks on the floor aren't working, but as I'm seeing now they aren't even mapped.

**Comment by dudantas** [comment]
Fixed map bug, thanks

**Comment by dudantas** [comment]
@gpedro solved the doors ?

**Comment by dudantas** [comment]
It's corrected!
