### ISSUE TITLE
Imbuiment system Elemental Damage problem

### ISSUE THREAD

**Issue by unlineworld** [opentibiabr/otservbr-global-archived#1110]
when using a weapon with some element of imbuimet besides reducing the physical damage of the attacks this is also reducing the healing spells

**Comment by Bipbop69** [comment]
> when using a weapon with some element of imbuimet besides reducing the physical damage of the attacks this is also reducing the healing spells

test and this is happening with all elemental weapons.
when equipped the cure drops 50%

@gpedro

**Comment by perron5306987** [comment]
solved? i have the same bug

**Comment by majestyotbr** [comment]
Already fixed.
