### ISSUE TITLE
Unable to send extended opcode number, extended opcodes are not enabled on this server.

### ISSUE THREAD

**Issue by GustavoAkashi** [opentibiabr/otservbr-global-archived#1111]
I've already used OP Codes on my 10.90 server with OTClient and it works, but when i tried to use the same client but with the opentibiabr/otservbr-global sources, it gave me this error:

ERROR: Unable to send extended opcode 110, extended opcodes are not enabled on this server.

Is that a problem of my client or opcodes is missing on this source ?

**Comment by Peixonauta2** [comment]
I have the same problem, can't use opcodes and I don't know why.
What 10.90 server did you use?

**Comment by majestyotbr** [comment]
https://forums.otserv.com.br/index.php?/forums/topic/169346-otservbr-global-otclient/
