### ISSUE TITLE
Error during compilation on Ubuntu 16.04

### ISSUE THREAD

**Issue by jsapparts** [opentibiabr/otservbr-global-archived#1115]
**Describe the bug**
When compiling I get errors due to the inclusion of std algorithm library. When analyzing I discovered that GCC was trying to use an undefined function for IA32 platform while I'm using Ubuntu 16.04 x86_64.

**To Reproduce**
1. Just clone the updated repository and try to build from command line using GCC 5.4.0.

**Expected behavior**
Compilation starts and finish with success.

**Desktop (please complete the following information):**
 - OS: Elementary OS
 - Version: 0.4 Loki (Ubuntu 16.04 based)

**Additional context**
This only happens when using `ccache` with `gcc` and `-march=native` option. Cannot confirm if this also affects `clang` because during compilation it consumes all RAM available forcing excessive swapping and freezing the system.

**Comment by Costallat** [comment]
https://github.com/opentibiabr/otservbr-global/wiki/Build-on-elementaryOS
