### ISSUE TITLE
Retro pvp

### ISSUE THREAD

**Issue by mgallo17** [opentibiabr/otservbr-global-archived#1119]
Colocar a opção do retro pvp para termos a experiência do bom Battle.

**Comment by gabz182** [comment]
Você pode desabilitar o sistema de "mãopvp" em events

	`<event class="Creature" method="onTargetCombat" enabled="1" />`
Apenas mude o valor para "0", então independe de mão fechada ou aberta o player vai poder atacar, e tbm vai funcionar o dano na party.
