### ISSUE TITLE
[Quest] The Dream Courts

### ISSUE THREAD

**Issue by Szulcek69** [opentibiabr/otservbr-global-archived#112]
As the title say. Portal in Venore haunted house isn't working as intended. 

08:13 You see a vortex.
It draws you nearer.
Item ID: 25417
Position: 32720, 32270, 8

![portal2](https://user-images.githubusercontent.com/51335460/58855627-ccc71800-86a0-11e9-8604-05a23b16653f.PNG)

**Comment by dudantas** [comment]
@gpedro I put the action 3250 in the teleport, can you create the script?
