### ISSUE TITLE
Falcon Castle - portals not working 

### ISSUE THREAD

**Issue by Szulcek69** [opentibiabr/otservbr-global-archived#113]
1) Falcon castle should be accessible after clicking the small boat on farmine. 

08:16 You see a small boat.
Item ID: 3587, Action ID: 64007
Position: 33328, 31350, 7
![falcon1](https://user-images.githubusercontent.com/51335460/58855989-b3729b80-86a1-11e9-9080-c862f608a77c.PNG)

2) On the way back its also not working.

08:17 You see a paddle.
Item ID: 3600, Action ID: 57601
Position: 33344, 31348, 7
![falcon2](https://user-images.githubusercontent.com/51335460/58855998-b7062280-86a1-11e9-9ac6-963468d37982.PNG)

3) And another one already on the respawn not working. 

08:19 You see electric sparks.
Item ID: 5069, Action ID: 57602
Position: 33309, 31325, 8
![falcon3](https://user-images.githubusercontent.com/51335460/58856005-ba011300-86a1-11e9-822c-5c2adecdf2ba.PNG)

**Comment by Sargitarium** [comment]
Fixed at #633 tested and WORK fine now
