### ISSUE TITLE
You are not the owner. (reward bosses)

### ISSUE THREAD

**Issue by wirtu777** [opentibiabr/otservbr-global-archived#1131]
## CAUTION: OUR SERVER IS UPDATED DAILY. MAKE SURE YOU ARE REPORTING SOMETHING ON THE LATEST VERSION OF THE SERVER.

**Describe the bug**
After killing a boss, damageMap is checked to apply loot to players that fighted with boss. When boss create summon a bit before its death then no one get loot.

Issue occurs most often for Brokul (because he makes summons as crazy)

**To Reproduce**
1. Create with GM any boss that create summons 
2. one shot the boss immediatly after he creates summon
3. You can't open the boss even you killed it
4. See error (I attach edited boss.lua - it displays on server console when the problem was reproduced
 [boss.txt](https://github.com/opentibiabr/otservbr-global/files/4568438/boss.txt) - change extension to .lua
![image](https://user-images.githubusercontent.com/64702378/80871483-31259980-8cad-11ea-9c02-4d44c5baba78.png)
 )

**Expected behavior**
Killer should get loot

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 / Windows Server 2019

**Additional context**
I was trying to investigate the problem but i'm not very familiar with those mechanics yet. It seems that damageMap is clean for short period of time or wrong damageMap is checked. i'm not sure if i'm going in right direction in my investigation so i post it here

I hope i explained issue clearly

**Comment by majestyotbr** [comment]
Duplicated, #1096

**Comment by dudantas** [comment]
@wirtu777 you can put the informations in one comment on the #1096
