### ISSUE TITLE
imbuements  manaleech & Lifeleech Bug

### ISSUE THREAD

**Issue by gabz182** [opentibiabr/otservbr-global-archived#1141]
**Describe the bug**
A porcentagem de roubo da mana leech e life leech não estão sendo calculadas corretamente de acordo com o imbuements.xml

Exemplo: Se você muda a manaleech para o valor "40" aí sim ele da os 8% certinho do roubo de mana.
Me parece que a função que calcula o roubo de mana está errada.

EDITE: auto ataque com sword ou wands estão dando o bonus corretamente, porém quando você usa uma magia em area acertando vários monstros, o valor de roubo de mana/vida de 8% não é retornado sobre o dano que você deu em todos os monstro atacados com magia em area. 

**To Reproduce**
Coloque um imbuiment nível 3 de manaleech/lifeleech, então feche uma box de bichos e solte uma magia em area, você não vai receber o roubo de mana/vida corretamente de acordo com o dano que vc deu nos bichos.

**Screenshots**
O valor "40" para chegar nos 8% de roubo de mana.
https://i.imgur.com/QGihp04.png

Windows 7

**Comment by rviniciuss** [comment]
Tô com o mesmo problema. 
É como explicado, o dano total não está sendo convertido, mesmo o dando sendo em área o leech só retorna o valor de 1.

**Comment by andersonfaaria** [comment]
@nightmareot  or @gabz182  Could you please implement the PR above e confirm if it fixes the problem?

**Comment by joseluis2g** [comment]
https://tibia.fandom.com/wiki/Formulae#Mana_Leech
