### ISSUE TITLE
Runa soulfire dando hit em turno fixo ao invés de variável de acordo com Level e magic level

### ISSUE THREAD

**Issue by antonioaraujo664** [opentibiabr/otservbr-global-archived#1142]
A runa soulfire esta do jeito que não deveria. 
Atualmente ele ta dando 10 de dando e 10 de turno, independentemente de level e Magic level! 
Ela deveria tirar hit em variável período, por exemplo: 
Level 27 e Magic Level 31 irá causar dano por 20 turnos.
Level 39 e Magic Level 42 irá causar dano por 27 turnos.
Level 61 e Magic Level 65 irá causar dano por 42 turnos.
Level 82 e Magic Level 66 irá causar dano por 49 turnos.
Level 105 e Magic Level 68 irá causar dano por 57 turnos.
Level 173 e Magic Level 82 irá causar dano por 85 turnos.

**Comment by antonioaraujo664** [comment]
Essa solução aqui funcionou

**Comment by antonioaraujo664** [comment]
https://github.com/otland/forgottenserver/blob/9e20782ced67b2d36407e32e30df1b12c6e44c2a/data/spells/scripts/attack/soulfire_rune.lua

**Comment by antonioaraujo664** [comment]
Essa solução aqui funcionou! https://github.com/otland/forgottenserver/blob/9e20782ced67b2d36407e32e30df1b12c6e44c2a/data/spells/scripts/attack/soulfire_rune.lua

**Comment by gpedro** [comment]
@lBaah can you make a PR with these changes from TFS?
