### ISSUE TITLE
Erro distro mazoran fire

### ISSUE THREAD

**Issue by Paahsz** [opentibiabr/otservbr-global-archived#1145]
## CAUTION: OUR SERVER IS UPDATED DAILY. MAKE SURE YOU ARE REPORTING SOMETHING ON THE LATEST VERSION OF THE SERVER.

**Describe the bug**

Lua Script Error: [Spell Interface]
data/spells/scripts/monster/mazoran fire.lua:onCastSpell
LuaScriptInterface::luaAddEvent(). Argument #3 is unsafe
stack traceback:
        [C]: in function 'addEvent'
        data/spells/scripts/monster/mazoran fire.lua:952: in function <data/spells/scripts/monster/mazoran fire.lua:950>

Ao criar o monstro para testar Mazaron.
Você consegue matar ele ok, porem enquanto ele está vivo fica spammando esse erro acima na distro

**Comment by majestyotbr** [comment]
https://github.com/opentibiabr/otservbr-global/commit/b0e0ee293a322c7447b0849bbb795c7dab363bc8
