### ISSUE TITLE
adult/young Goanna speed

### ISSUE THREAD

**Issue by Juanzin93** [opentibiabr/otservbr-global-archived#1152]
## CAUTION: OUR SERVER IS UPDATED DAILY. MAKE SURE YOU ARE REPORTING SOMETHING ON THE LATEST VERSION OF THE SERVER.

**Describe the bug**
a young e adult goanna tem 1 speed boost, ja aplicado porem esta muito lento e ela nao corre como deveria, aumentei a speed dela para 2500(nao eh a velo correta mas ela eh bem rapida) e agora com haste ela anda 5sqm e para 1 e repete

**Expected behavior**
young/adult goanna correr sem travar kkkk

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 
 - Version: 18.04

**Comment by majestyotbr** [comment]
Unconfirmed.
