### ISSUE TITLE
Anihilator doors locked

### ISSUE THREAD

**Issue by YohanAugusto** [opentibiabr/otservbr-global-archived#1157]
## CAUTION: OUR SERVER IS UPDATED DAILY. MAKE SURE YOU ARE REPORTING SOMETHING ON THE LATEST VERSION OF THE SERVER.

**Describe the bug**
Anihilator's reward room doors are locked and not closed. Need to update doors on map.

**To Reproduce**
Finishi anihilator and try to open doors.

**Expected behavior**
Expect to open doors, get reward and leave room.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Version: [e.g. 10]

**Additional context**

**Comment by dudantas** [comment]
> ## CAUTION: OUR SERVER IS UPDATED DAILY. MAKE SURE YOU ARE REPORTING SOMETHING ON THE LATEST VERSION OF THE SERVER.
> **Describe the bug**
> Anihilator's reward room doors are locked and not closed. Need to update doors on map.
> 
> **To Reproduce**
> Finishi anihilator and try to open doors.
> 
> **Expected behavior**
> Expect to open doors, get reward and leave room.
> 
> **Screenshots**
> If applicable, add screenshots to help explain your problem.
> 
> **Desktop (please complete the following information):**
> 
> * OS: [e.g. Windows]
> * Version: [e.g. 10]
> 
> **Additional context**
> Add any other context about the problem here.

ok thanks

**Comment by thatmichaelguy** [comment]
Fixed in #1351

**Comment by dudantas** [comment]
> Fixed in #1351

Thanks for remember
