### ISSUE TITLE
Orc Cult Priest not transforming player in creature

### ISSUE THREAD

**Issue by Juanzin93** [opentibiabr/otservbr-global-archived#1159]
## CAUTION: OUR SERVER IS UPDATED DAILY. MAKE SURE YOU ARE REPORTING SOMETHING ON THE LATEST VERSION OF THE SERVER.

**Describe the bug**
Orc Cult Priest not transforming player in creature

**Expected behavior**
Os andares estarão repletos de orcs, e em cada andar haverá uma barreira que o jogador só conseguirá passar se estiver transformado em um determinado tipo de Orc, por isso a magia do Orc Cult Priest será essencial, portanto evite matá-los. A magia dele transformará o jogador em um Orc normal, um Orc Warlord, um Orc Shaman, ou então em uma Larva.

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04

**Comment by oualid6496** [comment]
I've tested this and it seems to be working as it should. Maybe there has been an update since this issue was created?

**Comment by gpedro** [comment]
unconfirmed.
