### ISSUE TITLE
NPC Angelo - cults of tibia 

### ISSUE THREAD

**Issue by Juanzin93** [opentibiabr/otservbr-global-archived#1160]
## CAUTION: OUR SERVER IS UPDATED DAILY. MAKE SURE YOU ARE REPORTING SOMETHING ON THE LATEST VERSION OF THE SERVER.

**Describe the bug**
npc angelo nao responde nem abre a porta. tbm nao deve dar os items necessarios( Tool for Analyzing Fluids e Pink Fluid)  apos encontrar o oasis
01:51 Angelo: Greetings, Juanzin.
01:51 Juanzin [289]: project
01:51 Juanzin [289]: mission
**Expected behavior**
Para investigar esse culto, procure pelo Npc Angelo nas profundezas da Dark Pyramid e diga "hi - mission - yes"'. Ele dirá que sua equipe estava realizando uma pesquisa no local quando um dos seus cientistas desapareceu e pede a você que investigue o caso. Passe pela porta e siga o caminho por três andares até encontrar um Teleport. Entre nele e encontrará um Oásis, mas nada do cientista desaparecido. Retorne á Angelo e reporte sua missão.

Se você iniciou a missão no Museum of Tibian Arts e não terminou, irá dar conflito e não será possível dizer apenas hi - mission - yes. Precisará dizer "hi - project - MoTA - results - worried - yes "

Depois de analisar a água coletada, você irá receber um Pink Fluid Pink Fluid.gif para usar no Oásis e ver qual o resultado disso. Novamente retorne ao Oásis e aplique o fluído na água. Feito isso, uma tempestade de areia irá destruir os pilares do local e fará a água do Oásis ficar turva. Em consequência a essa destruição, a alavanca que dará acesso ao The Sandking será descoberta.

 O **Tool for Analyzing Fluids** nem o **Pink Fluid** nao fazem nada quando usados na agua,
**Screenshots**
![image](https://user-images.githubusercontent.com/64820180/81259698-81cb2880-9006-11ea-8363-ebc1952acd9b.png)
CORDENADAS: 
Position: 33483, 32277, 10
_________________________
MOTA
Ao chegar em Angelo pergunte a ele por um Magnifier. Ele ficará surpreso em saber de podem existir pinturas falsas e dirá para pegar uma Loupe em uma caixa a direita dele.
03:09 Angelo: How is your mission going?
03:09 Juanzin [291]: mission
03:09 Juanzin [291]: magnifier
03:09 Juanzin [291]: mota
03:09 Juanzin [291]: project
**Desktop (please complete the following information):**
 - OS: UBUNTU 18.04

EDIT: TESTEI O BOSS E FUNCIONA,
EDIT2: TESTEI DEPOIS DE FALAR COM GERIMOR (nao eh preciso fazer isso no global) E O NPC LIBERA ACESSO, POREM QUANDO PASSA NO TELEPORT DO TERCEIRO ANDAR VC CAI DIRETO NO MAPA COM ALAVANCA, E PODE FAZER O BOSS REPETIDAMENTE (CERTO EH A CADA 20H)

**Comment by majestyotbr** [comment]
#726
