### ISSUE TITLE
Npc Corym Ratter & Corym Servant (STONEREFINERS)

### ISSUE THREAD

**Issue by Juanzin93** [opentibiabr/otservbr-global-archived#1162]
## CAUTION: OUR SERVER IS UPDATED DAILY. MAKE SURE YOU ARE REPORTING SOMETHING ON THE LATEST VERSION OF THE SERVER.

**Describe the bug**
npc corym ratter Position: 33034, 32069, 12 nao responde a hi/help/yes e nao da acesso a porta.
npc corym servant Position: 33032, 32009, 12 nao responde a hi/defy/yes e nao da acesso a porta

**Expected behavior**
npc responder certo e dar acesso a porta kkk
Jogador: hi
Corym Ratter: Welcome stranger! You might be surprised that I don't attack you immediately. The point is, that I think you could be useful to me. What you see in front of you is a great mine of the corym! ...
Corym Ratter: We dig up all what mother earth delivers to us, valuable natural resources. But the yield is getting worse and here I need your help.
Jogador: help
Corym Ratter: Recently the amount of delivered ores is decreasing. Could you find out the reason, why the situation has become worse?
Jogador: yes
Corym Ratter: Nice! I have opened the mine for you. But take care of you! The monsters of depth won't spare you.
_____________________
Jogador: hi
Corym Servant: We work as hard we can, my master! Wait, I haven't seen you here before. You were sent by the Corym Ratter, I see. He misses the courage to visit us and find the reason for decreasing resources? He's the coward I have expected.
Jogador: decreasing resources
Corym Servant: You have to know, that our work is very hard and the conditions we have are terrible. The wanted amount is abolutely unrealistic. Beyond that the food we get is never enough. ...
Corym Servant: Our workers should give their best while starving. This is not possible. That's the point to defy the authority.
Jogador: defy
Corym Servant: I see you are interested to change our sitation. The first thing I like you to do is to liberate the jailed coryms. There are three areas with locked doors. You have to find a way to get access. ...
Corym Servant: For this reason I will give you access to the second floor. It was closed because it wasn't possible to continue working at these enourmous high temperatures. Furthermore we were instantly attacked by stonerefiners. So take care of you!

**Desktop (please complete the following information):**
 - OS: UBUNTU 18.04

**Comment by majestyotbr** [comment]
#726 - Hidden Threats Quest
