### ISSUE TITLE
Secret Library quest - NPC Spectulus

### ISSUE THREAD

**Issue by Juanzin93** [opentibiabr/otservbr-global-archived#1163]
## CAUTION: OUR SERVER IS UPDATED DAILY. MAKE SURE YOU ARE REPORTING SOMETHING ON THE LATEST VERSION OF THE SERVER.

**Describe the bug**
apos a primeira missao e usado o livro nos deathlings de tiquanda, o spectulus nao responde mais sobre a quest devido a quest de berengar.
____________
teleports para deathlings de gray island nao funciona
________________
BOSS BROKUL PODE ACESSAR SEM ARRUMAR OS IDOLOS
apos todos sairem da sala o systema diz que ainda tem player lutando contra o brokul

**Desktop (please complete the following information):**
 - OS: ubuntu 18.04

**Comment by majestyotbr** [comment]
#726
