### ISSUE TITLE
secret library quest - NPC Gareth

### ISSUE THREAD

**Issue by Juanzin93** [opentibiabr/otservbr-global-archived#1164]
## CAUTION: OUR SERVER IS UPDATED DAILY. MAKE SURE YOU ARE REPORTING SOMETHING ON THE LATEST VERSION OF THE SERVER.

**Describe the bug**
npc nao responde a hi /extension/ yes para dar acesso as furys

Position: 33306, 32140, 8

**Expected behavior**
Jogador: extension
Gareth: It is planned to extend the MOTA. But this will take time, because our workers have faced a little problem.
Jogador: problem
Gareth: Well, the situation is this: We have explored a portal, I would say a very aggressive, capriciously and dangerous one. Through this gate monsters entered the construction site and attacked our workers. ...
Gareth: With enormous effort they could have been dispersed. When my fellows tried to fill up the portal, it appeared again and again. So the only thing they could do was to stop working for the moment. Are you eventually interested in further investigations?
Jogador: yes
Gareth: You are a true patron of the arts! I have opened the construction site for you. Start your work right now!

 - OS: ubuntu 18.04

**Comment by htc16** [comment]
> 
> ## CAUTION: OUR SERVER IS UPDATED DAILY. MAKE SURE YOU ARE REPORTING SOMETHING ON THE LATEST VERSION OF THE SERVER.
> 
> **Describe the bug**
> npc nao responde a hi /extension/ yes para dar acesso as furys
> 
> Position: 33306, 32140, 8
> 
> **Expected behavior**
> Jogador: extension
> Gareth: It is planned to extend the MOTA. But this will take time, because our workers have faced a little problem.
> Jogador: problem
> Gareth: Well, the situation is this: We have explored a portal, I would say a very aggressive, capriciously and dangerous one. Through this gate monsters entered the construction site and attacked our workers. ...
> Gareth: With enormous effort they could have been dispersed. When my fellows tried to fill up the portal, it appeared again and again. So the only thing they could do was to stop working for the moment. Are you eventually interested in further investigations?
> Jogador: yes
> Gareth: You are a true patron of the arts! I have opened the construction site for you. Start your work right now!
> 
>     * OS: ubuntu 18.04

Para falar com este NPC é necssário ter uma missão anterior, você verificou isso antes?

**Comment by majestyotbr** [comment]
#726
