### ISSUE TITLE
NPC ANDREW LYZE (CARNIVORS)

### ISSUE THREAD

**Issue by Juanzin93** [opentibiabr/otservbr-global-archived#1165]
## CAUTION: OUR SERVER IS UPDATED DAILY. MAKE SURE YOU ARE REPORTING SOMETHING ON THE LATEST VERSION OF THE SERVER.

**Describe the bug**
npc nao responde nada para dar acesso aos carnivors
Position: 32761, 32631, 7

 - OS: ubuntu 18.04

**Comment by majestyotbr** [comment]
#726 - The Dream Courts Quest
