### ISSUE TITLE
MISSING NPC - STRICKEN SOUL

### ISSUE THREAD

**Issue by Juanzin93** [opentibiabr/otservbr-global-archived#1166]
**Is your feature request related to a problem? Please describe.**

## CAUTION: OUR SERVER IS UPDATED DAILY. MAKE SURE YOU ARE REPORTING SOMETHING ON THE LATEST VERSION OF THE SERVER.

NPC STRICKEN SOUL ( GIVES ACCESS TO GAZERS, RIPPER SPECTRES AND BURSTERS SPECTERS) MISSING FROM Position: 32699, 32247, 8

Jogador: hi
Stricken Soul: This place is... haunted... heed my warning... there are... ghooooooosts here...! Why are you giving me that... look? I am certain, there aaaaaaare ghosts here - I've seen them! Do you believe me?
Jogador: yes
Stricken Soul: Yeeeees... you need to help meeeeeee. I want those ghosts gone... this is my home and I need it to teach my students. Will you take care of the... ghosts?
Jogador: yes
Stricken Soul: Excellent... I hope they will haaaaaaunt my house no longer. What was your... naaaaaame again, tell me?
Jogador: <Nome do Jogador>
Stricken Soul: Ah yeeeeees, <Nome do Jogador>... I will remember you. Now, lessons are every day in the morning and once a week in the evening... ...
Stricken Soul: Oh, you're not here for this, are you? So about the ghoooosts, yes. You seeeee, there are 3 secret passages here. ...
Stricken Soul: Thiiiiis is no ordinary house... it is a nexus, a gateway to a once hidden cathedral. Sheltering a small and peaceful society of scholars and monks. Secluded from every distraction. ...
Stricken Soul: I was one of them and ordered to hold contact to the outside woooorld. But then, something... happened. ...
Stricken Soul: Outsiders managed to sneak in, infiltrate and influence the society... for the worse. Who knows for what ends. They chaaaaanged... ...
Stricken Soul: Shortly after, contact was lost... the nexus broken and sealed, ghosts appeared... eeeeeeeverywhere. ...
Stricken Soul: Find the three passages... one is right here in the cellars, one in the jungles of Tiquanda and one in the deserts of Darama. ...
Stricken Soul: Restore their connection and open this nexus to access the buried cathedral and find the cause to this... eliminate all remainders there if you must, <Nome do Jogador>

https://www.tibiawiki.com.br/wiki/The_Dream_Courts_Quest

OTHER NPCS LIKE MYZZI ARE ALSO MISSING,
Position: 33277, 31698, 7

NPC VANYS
Position: 33685, 32181, 8  also doesnt work (maybe missing, i dont remember if i added to my map or if its was already there)

**Comment by majestyotbr** [comment]
#726 - The Dream Courts Quest
