### ISSUE TITLE
the first dragon quest - lever dont work

### ISSUE THREAD

**Issue by Juanzin93** [opentibiabr/otservbr-global-archived#1167]
## CAUTION: OUR SERVER IS UPDATED DAILY. MAKE SURE YOU ARE REPORTING SOMETHING ON THE LATEST VERSION OF THE SERVER.

**Describe the bug**
lever to boss the first dragon dont work

Position: 33583, 30993, 14

**Expected behavior**
https://tibiawiki.com.br/wiki/The_First_Dragon_Quest

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04

**Comment by dudantas** [comment]
You need to occupy all tiles to be able to function.
