### ISSUE TITLE
Faceless Bane - teleport and lever

### ISSUE THREAD

**Issue by Juanzin93** [opentibiabr/otservbr-global-archived#1168]
## CAUTION: OUR SERVER IS UPDATED DAILY. MAKE SURE YOU ARE REPORTING SOMETHING ON THE LATEST VERSION OF THE SERVER.

**Describe the bug**
teleport using the books in the room dont work
![image](https://user-images.githubusercontent.com/64820180/81269730-c27f6d80-9017-11ea-8557-ef202d2a74b4.png) (IGNORE MYSTIC FLAME, I ADDED TO GO TO BOSS LEVER)

lever also dont work
![image](https://user-images.githubusercontent.com/64820180/81269886-f78bc000-9017-11ea-8765-6a4fcae40531.png)

**Expected behavior**
https://www.tibiawiki.com.br/wiki/The_Dream_Courts_Quest

 - OS:ubuntu 18.04

**Comment by fabiobillz** [comment]
https://github.com/opentibiabr/otservbr-global/issues/726

**Comment by majestyotbr** [comment]
Thanks for your report, this quest was added in #726.
