### ISSUE TITLE
[Quest] The Dream Courts

### ISSUE THREAD

**Issue by Szulcek69** [opentibiabr/otservbr-global-archived#117]
Couldn't make the door open. The NPC isn't reacting to any of the lines he should react to. I've checked the action assigned to the door with the actions.xml and it isn't present there. I'm not a specialist but maybe that is an issue.

19:27 You see a closed door.
Item ID: 22821, Action ID: 10250
Position: 32761, 32630, 7

![carnivores](https://user-images.githubusercontent.com/51335460/58900331-455cc180-86ff-11e9-815b-ad5e7c8113ef.PNG)

**Comment by dudantas** [comment]
The scripts for the quest are not made. :(
I will mark as an enhancement

**Comment by Szulcek69** [comment]
You could just change the door for the level 250 level gate untill the quest is done so that the hunting spot can be used untill then.

**Comment by dudantas** [comment]
@Szulcek69 I do not think it is correct to do joke, there are several contributors, it is better to wait for someone to script and go up, until then, each can do what they think best on localhost.
