### ISSUE TITLE
Re-rolling the bonus on the prey system 

### ISSUE THREAD

**Issue by garedgar** [opentibiabr/otservbr-global-archived#1171]
## CAUTION: OUR SERVER IS UPDATED DAILY. MAKE SURE YOU ARE REPORTING SOMETHING ON THE LATEST VERSION OF THE SERVER.

**Describe the bug**
When you re-roll the prey system bonus with wildcards the number of stars (bonus) moves back to less stars as you keep re-rolling. When it only should be getting better number of bonus as you keep rolling bonuses.

**Expected behavior**
When you re-roll prey bonus on the prey system the bonus should only be going up.
Ex.: If i have Loot Bonus 3 stars and i re-roll the bonus, either i can get Exp/Loot/Attack/Defence 4 stars or higher on the next re-roll. And so on, the re-roll always has to be better than the previous stars (like real tibia).

**Comment by rtsrick2017** [comment]
Also, preys are disappearing even when you are not hunting, for some reason. I do not know if this is the expected behavior (like, reset after x hours)

**Comment by lBaah** [comment]
Test this
https://github.com/lBaah/otservbr-global/commit/81352c31e07fcd3493c07c2b51ad445609eb3df6
