### ISSUE TITLE
Meriana Quest is missing

### ISSUE THREAD

**Issue by YohanAugusto** [opentibiabr/otservbr-global-archived#1173]
**Is your feature request related to a problem? Please describe.**
I don't know how or when, but Meriana Quest got lost by the latest commits/merges. (Maybe on #1118)

**Describe the solution you'd like**
It needs to be merged again to be working fine.

**Comment by marcosvf132** [comment]
Due to a huge amount of issues, we are moving all bugs related to quest to one single ISSUE, for future issues related to the quest, please consider reporting it on that specific ISSUE, thanks.
 - Ref: #726
