### ISSUE TITLE
Reward System - Missing Features

### ISSUE THREAD

**Issue by Lycanzito** [opentibiabr/otservbr-global-archived#1177]
1- 
![image](https://user-images.githubusercontent.com/52710697/81344910-fe551a00-908d-11ea-96c6-d9af38edeeae.png)

After you kill a boss, it gives u this bag, when u look at it, it should say the time u killed the creature + 7 days.
(after 7 days it should be removed from this box)

2-
After you kill a boss, it gives u this bag, after u collect everything from it: it should vanish.

![image](https://user-images.githubusercontent.com/52710697/81345039-2ba1c800-908e-11ea-83f3-ed812100a823.png)

**Comment by oualid6496** [comment]
1. Confirmed
2. Not sure if it should disappear right away? Because when you collect all items and relog it does disappear.

**Comment by dex-89** [comment]
We haven't any bug. Checked at real Tibia
