### ISSUE TITLE
Inspect Function - Not Working.

### ISSUE THREAD

**Issue by Lycanzito** [opentibiabr/otservbr-global-archived#1179]
The insepect function is not working.

1- Your own inspect.
![image](https://user-images.githubusercontent.com/52710697/81346156-2d6c8b00-9090-11ea-8f03-dd4e7fcc9935.png)

2- Insepect of others.

![image](https://user-images.githubusercontent.com/52710697/81346239-54c35800-9090-11ea-8987-f557d8536e08.png)

**Comment by heberholanda** [comment]
Working now.
