### ISSUE TITLE
Prey System - All Problems till now.

### ISSUE THREAD

**Issue by Lycanzito** [opentibiabr/otservbr-global-archived#1180]
1- We houldnt use a "rank list" to randomize the creatures;
"
CONST_MONSTER_TIER_BRONZE = 0
CONST_MONSTER_TIER_SILVER = 1
CONST_MONSTER_TIER_GOLD = 2
CONST_MONSTER_TIER_PLATINUM = 3"

we should use all the creatures list.

2- The list should be remade, for example:
rotworm queen/draptor, arent monster that shouldnt be in the list.

2- The timer should decay when the player have a battlesign, independent of the creature/ if you attack it or not, the timer should decay.

but these 2, are differents:
if u have exp prey, only when u kill something. (these 2 , follow yours stamina time).
if u have loot prey, only when u kill something. (these 2 , follow yours stamina time).

![image](https://user-images.githubusercontent.com/52710697/81346613-f480e600-9090-11ea-9ed7-690bea1cb98f.png)

3- These three Features, arent working:

![image](https://user-images.githubusercontent.com/52710697/81346801-4f1a4200-9091-11ea-8860-3f1fa966628b.png)

4- When you have for example 10 stars:

![image](https://user-images.githubusercontent.com/52710697/81346976-a7514400-9091-11ea-8ca7-f7d107436fa5.png)

if u buy a Bonus reroll, it should continue with 10 stars.
but this is happening:

![image](https://user-images.githubusercontent.com/52710697/81347047-c5b73f80-9091-11ea-8e7d-6c54c7f24051.png)

**Comment by Lycanzito** [comment]
Also, talking about the stars.. It should grow (or not )
when u use a bonus reroll.

For example, If you have 2 stars, use a bonus reroll, then it can or not, change the amount of stars, and change or not the bonus (exp to defense or wherever)

**Comment by FakeShinoda** [comment]
Timer should ONLY decay when you kill a foe no matter what bonus you have, it works exactly like your stamina.

**Comment by dudztroyer** [comment]
Not all of the timers should decay when killing a foe. Only EXP and LOOT. The others will decay when you are in battle (damage and defense). It's like this because otherwise you can have defense prey and block strong creatures without losing the prey.

**Comment by FakeShinoda** [comment]
Reviwed: only defense prey is different, it decay when you get damage from something.

**Comment by Juanzin93** [comment]
@Lycanzito yeah the stars should always grow when u use the bonus reroll

**Comment by Lycanzito** [comment]
> Reviwed: only defense prey is different, it decay when you get damage from something.

Im pretty sure that the defense/damage decay when u have sign the battle but, it could be checked.

**Comment by gabz182** [comment]
Any solution prey card creature reroll?

**Comment by lBaah** [comment]
Test this card bonus rolling

https://github.com/lBaah/otservbr-global/commit/81352c31e07fcd3493c07c2b51ad445609eb3df6
