### ISSUE TITLE
MISSING MAP - Feast of Souls Quest

### ISSUE THREAD

**Issue by Juanzin93** [opentibiabr/otservbr-global-archived#1181]
## CAUTION: OUR SERVER IS UPDATED DAILY. MAKE SURE YOU ARE REPORTING SOMETHING ON THE LATEST VERSION OF THE SERVER.

**Describe the bug**
missing map

**To Reproduce**
https://www.tibiawiki.com.br/wiki/Feaster_of_Souls_Quest
https://www.youtube.com/watch?v=Q6s4VAiwB7I
**Screenshots**
![image](https://user-images.githubusercontent.com/64820180/81349513-1fb60600-908e-11ea-9bb4-9e6a4583a3c1.png)
![image](https://user-images.githubusercontent.com/64820180/81349279-b59d6100-908d-11ea-868e-3b413a1889b2.png)
![image](https://user-images.githubusercontent.com/64820180/81349326-cb128b00-908d-11ea-8373-e48654c0d49d.png)
![image](https://user-images.githubusercontent.com/64820180/81349353-d8c81080-908d-11ea-90d0-42c02ebf2f40.png)
![image](https://user-images.githubusercontent.com/64820180/81349407-ed0c0d80-908d-11ea-897e-5091bd9906de.png)
![image](https://user-images.githubusercontent.com/64820180/81349525-25abe700-908e-11ea-9a42-a0d7515eaafe.png)
![image](https://user-images.githubusercontent.com/64820180/81349556-38262080-908e-11ea-957e-babc6b45452f.png)
![image](https://user-images.githubusercontent.com/64820180/81349562-3bb9a780-908e-11ea-99bf-7611907a003b.png)
![image](https://user-images.githubusercontent.com/64820180/81349578-4116f200-908e-11ea-904d-560e9233cd65.png)
![image](https://user-images.githubusercontent.com/64820180/81349652-6a378280-908e-11ea-8432-4039d54ea2a6.png)
![image](https://user-images.githubusercontent.com/64820180/81349671-79b6cb80-908e-11ea-89bb-c8a3d9148949.png)

 - OS: Ubuntu 18.04

**Comment by Briluxxx** [comment]
https://otland.net/threads/11x-map-full-grave-danger-and-feaster-of-souls.270941/
