### ISSUE TITLE
some bug on admins and more.

### ISSUE THREAD

**Issue by Alucard987** [opentibiabr/otservbr-global-archived#1183]
Hello!. it's me, again
I have found more bug than the others.

-The admin cannot move backpacks from their inventory to the ground, I have tried it with several backpacks throwing them on the ground without anything happening, the same thing happens with the items (not tested on players).

>Lua Script Error: [Event Interface]
data/events/scripts/player.lua:Player@onLook
data/events/scripts/player.lua:158: 'for' initial value must be a number
stack traceback:
        [C]: at 0x7ff7b034a6d0
        data/events/scripts/player.lua:158: in function <data/events/scripts/player.lua:92>

> Lua Script Error: [Event Interface]
data/events/scripts/player.lua:Player@onMoveItem
data/events/scripts/player.lua:491: 'for' initial value must be a number
stack traceback:
        [C]: at 0x7ff7b034a6d0
        data/events/scripts/player.lua:491: in function <data/events/scripts/player.lua:291>

-level 8 can't get out of rookgard because they already have vaocation (temporarily fixed with map edit)
-players do not receive initial items.

I'll keep testing
regards

**Comment by majestyotbr** [comment]
Unconfirmed.

Make sure you are using the latest version of the server.

**Comment by Alucard987** [comment]
> Unconfirmed.
> 
> Make sure you are using the latest version of the server.

i'm using last build :( why only happend to me...

**Comment by YohanAugusto** [comment]
1- Edit your Town ID on your website to go to Mainlaind if you dont want to use rook
2- This rep is simulating Tibia, so it's assuming your new character will start in rookgaard by level 0
