### ISSUE TITLE
Lord of the elements - outfit switch

### ISSUE THREAD

**Issue by Juanzin93** [opentibiabr/otservbr-global-archived#1184]
## CAUTION: OUR SERVER IS UPDATED DAILY. MAKE SURE YOU ARE REPORTING SOMETHING ON THE LATEST VERSION OF THE SERVER.

**Describe the bug**
		<defense name="outfit" interval="1500" chance="40" monster="Energy Overlord" duration="3000">
			<attribute key="areaEffect" value="blueshimmer" />
		</defense>
		<defense name="outfit" interval="1500" chance="40" monster="Fire Overlord" duration="3000">
			<attribute key="areaEffect" value="blueshimmer" />
		</defense>
		<defense name="outfit" interval="1500" chance="40" monster="Earth Overlord" duration="3000">
			<attribute key="areaEffect" value="blueshimmer" />
		</defense>
		<defense name="outfit" interval="1500" chance="40" monster="Ice Overlord" duration="3000">
			<attribute key="areaEffect" value="blueshimmer" /> 

this script is not working

1. Go to \otservbr-global-develop\data\monster\bosses
2. Click on 'Lord of the elements

**Expected behavior**
monster must switch outfits and it is not, same thing is happening with orc cult priest, but incredibly old witch works fine

*
ubuntu 18.04

**Comment by Oliveiralt** [comment]
describe how it would work? or rather how his mechanism would be ...

**Comment by majestyotbr** [comment]
Unconfirmed.
