### ISSUE TITLE
correção no #10

### ISSUE THREAD

**Issue by neykos** [opentibiabr/otservbr-global-archived#12]
correção no #10

_Originally posted by @ivenspontes in https://github.com/opentibiabr/OTServBR-Global/issues/9#issuecomment-494187587_

Poderia me informar o que seria #10?

**Comment by gpedro** [comment]
apenas corrige o nome da tabela para `dailyreward_history` de `daily_reward_history` (que é o correto conforme o [schema.sql](https://github.com/opentibiabr/OTServBR-Global/blob/master/schema.sql#L153)).
