### ISSUE TITLE
Skeleton Elite Warriors spawn Darashia - missing spawn

### ISSUE THREAD

**Issue by Szulcek69** [opentibiabr/otservbr-global-archived#120]
There is some missing spawn in Skeleton Elite Warriors respawn in Darashia. Im putting the images below how it should look like. 

![6VmQX3E](https://user-images.githubusercontent.com/51335460/58902741-00875980-8704-11e9-8f8b-0bb2a036897b.jpg)
![iZivKzG](https://user-images.githubusercontent.com/51335460/58902743-011ff000-8704-11e9-85c5-0ee32edd8843.jpg)
![kR6hucg](https://user-images.githubusercontent.com/51335460/58902744-011ff000-8704-11e9-908e-1854b9bd09d7.jpg)

**Comment by dudantas** [comment]
when submit map issue, please put the position too.
Thanks

**Comment by Szulcek69** [comment]
Position: 32952, 32319, 8

**Comment by dudantas** [comment]
I did not understand. I opened the map and saw that it has more respawns than in the photo you sent.

**Comment by dudantas** [comment]
I noticed that your map is different than ours. Which is correct?

**Comment by Szulcek69** [comment]
Ok so:
Floor 8 - needs to be redone using the photo I sent you
Floor 9 - is okay on your map
Floor 10 - needs to be redone using the photo. This is the most important floor as its one of the best hunting spots atm.

**Comment by dudantas** [comment]
@Szulcek69  Could not you send yours? So I just attached it to the map.

**Comment by Szulcek69** [comment]
That's not my map sadly :/ It's some picture I've found on the internet that respresents the spawn of real Tibia best

**Comment by liontts** [comment]
Invalid problem, the tracker automatically fetches respawns, so probably what you see is a customization.

**Comment by Sargitarium** [comment]
Fixed on #633 and now WORK fine... TESTED TODAY.....
