### ISSUE TITLE
Aleta sio permitindo mover/pegar itens da casa.

### ISSUE THREAD

**Issue by gabz182** [opentibiabr/otservbr-global-archived#1203]
O aleta sio está possibilitando que outros jogadores invitados na casa possam mover e pegar items da casa, de acordo com o global o novo sistema de house " que nao é tao novo", não permite que players que foram invitados com "aleta sio" movam/peguem items dentro da casa.

**Comment by gpedro** [comment]
Por que fechou? @gabz182

**Comment by dudztroyer** [comment]
@gpedro porque no global é assim como funciona.
