### ISSUE TITLE
Every kill Minotaur display: "Your questlog has been updated"

### ISSUE THREAD

**Issue by ghost** [opentibiabr/otservbr-global-archived#1211]
"Killing in the Name" 
Every kill Minotaur display: **Your questlog has been updated.**

![image](https://user-images.githubusercontent.com/64913328/81622240-b9641700-93f0-11ea-84d2-ea39b9b38207.png)

**Comment by Lycanzito** [comment]
ward

**Comment by oalbsilva** [comment]
Just for the minotaur task or for any other type?
Another question ... when completing the task, is it necessary to update the quest log?

**Comment by dudantas** [comment]
#1273 reverted in the #1705
