### ISSUE TITLE
Whacking Driller of Fate

### ISSUE THREAD

**Issue by Juanzin93** [opentibiabr/otservbr-global-archived#1215]
## CAUTION: OUR SERVER IS UPDATED DAILY. MAKE SURE YOU ARE REPORTING SOMETHING ON THE LATEST VERSION OF THE SERVER.

**Describe the bug**
Whacking Driller of Fate and the other tools only works as shovel and rope, doesnt work as machete or anything else

**Expected behavior**
https://www.tibiawiki.com.br/wiki/Whacking_Driller_of_Fate
https://www.tibiawiki.com.br/wiki/Squeezing_Gear_of_Girlpower
https://www.tibiawiki.com.br/wiki/Sneaky_Stabber_of_Eliteness

 - OS: ubuntu 18.04

**Comment by FakeShinoda** [comment]
Not confirmed, they working as expected.

**Comment by Juanzin93** [comment]
> Not confirmed, they working as expected.

Did you try to use it as a machete to cut wild growths? Or as a scythe to cut the yellow grass in ab to go to cyclops? I tested this way and it didnt work,

**Comment by oualid6496** [comment]
With a Whacking Driller of Fate you're able to cut wild growths but not the yellow grass as it is in real tibia.
Scroll down https://tibia.fandom.com/wiki/Secret_Service_Quest to see which tool has which function. Like FakeShinoda said they're working as they should.

**Comment by majestyotbr** [comment]
Unconfirmed.

**Comment by EleanorRigby1** [comment]
I took the time to review. And if this bug, none of the 3 works as a machete with that I tell you everything.

**Comment by oualid6496** [comment]
> I took the time to review. And if this bug, none of the 3 works as a machete with that I tell you everything.

Not sure what you mean but it's closed. If you still think there is a bug open a new issue
