### ISSUE TITLE
Cults of Tibia missing creatureEvents

### ISSUE THREAD

**Issue by oualid6496** [opentibiabr/otservbr-global-archived#1219]
**Describe the bug**
The creature script of Cult of Tibia bosses isn't registering I have tested it with several bosses and none seems to be working. It seems to be working fine when I add the script directly to the monster file like this:
event name="healLeiden"
event name="SpawnBoss"

**To Reproduce**
Kill for example Leiden.

**Expected behavior**
When Leiden dies the Ravennous Hunger should spawn.

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10

**Additional context**
I was wondering if the creaturescripts should be directly added to the monster files as previously shown or is there a reason why this isn't done like this? If there isn't let me know and I'll add them.

**Comment by oualid6496** [comment]
Oh I see that someone has started a similar issue #1190

**Comment by majestyotbr** [comment]
#726

**Comment by oualid6496** [comment]
@MajestyOTBR That issue is for quests that needs to be developed. This quest is already developed but bugged thats why I opened a new issue.

**Comment by majestyotbr** [comment]
Quests that need to be developed or revised. This quest needs a revision.

**Comment by oualid6496** [comment]
Ah ok
