### ISSUE TITLE
Selling Big Ammounts of Loot will Crash the Client

### ISSUE THREAD

**Issue by garedgar** [opentibiabr/otservbr-global-archived#1220]
## CAUTION: OUR SERVER IS UPDATED DAILY. MAKE SURE YOU ARE REPORTING SOMETHING ON THE LATEST VERSION OF THE SERVER.

**Describe the bug**
Using the NPC's for example: Rashid, Yasir or a custom made one that buys every type of loot.

Whenever you try to sell a big stack of loot, lets say 100+ or so around that area it will completely lag out your client. The server will work fine just the client bugs out and you have to close it.

I don't believe the client is the problem as its just the original client that you download from OTSERVBR-GLOBAL.

I believe this cant be a client issue tho, as nothing has been changed or modified other than the IP Address. 

**To Reproduce**
1. Go to Rashid or Yasir.
2. Create around 80-100 items of the same name (Ex: Underworld Rods)
3. Sell them all at once.
4. Watch how your client will crash/completely freeze

**Expected behavior**
Should work smoothly when selling, fast in and out whenever using the npc system.

**Screenshots**
![npc sell loot bug](https://user-images.githubusercontent.com/49217978/81855502-0cd78180-9525-11ea-8eea-b68d7b3c7361.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 (Client Running)
 - SERVER: Running on a Windows Server 2019 

**Additional context**
This was tested on multiple accounts/players. The bug actually was reported by a player i came to test it out and verified it was the same.

**Comment by dudantas** [comment]
Thanks for the report, but, your issue is repeated, look this https://github.com/opentibiabr/otservbr-global/issues/1072, you can comment in this issue
