### ISSUE TITLE
Autoloot window doesnt open + Asura mirror cracks

### ISSUE THREAD

**Issue by luucassoares** [opentibiabr/otservbr-global-archived#125]
Hello. 
I recently cloned the repo and successfully build the server. No problem.

Buy autoloot doesnt seem to work. 

I type !autoloot and there is a message saying that my loot list is empty e and i cant find anywhere any commands to try to make it work.

And the cracks in asura mirrir hunt doesnt work as well. At least I couldn't use it.

thanks!!

**Comment by dudantas** [comment]
Autoloot command is: !add monstername

**Comment by luucassoares** [comment]
well here we gooo it worked like a charm, thanks for that. and the cracks worked as well, think i missclicked, sorry about that. thank you
