### ISSUE TITLE
"Double Factor" - bug

### ISSUE THREAD

**Issue by Lycanzito** [opentibiabr/otservbr-global-archived#1254]
Hello OTservBR community!

For example:
Using potions, sometimes it happens twice in the same action;
https://www.youtube.com/watch?v=lUF95nQxrfQ
u guys can see it clearly, when it goes to 88-87 potions;

But there is a lot of others things, that it happens.

For example:
others potions
others runes
calculation of health spells ( giving the double of heall)
calculation of attack spells ( giving the double of the damage)

**Comment by heberholanda** [comment]
![nao repdou](https://user-images.githubusercontent.com/715547/95211305-c845ce80-07c2-11eb-9dba-65a8eb9f8d43.gif)

I was unable to reproduce the bug in the current version, try to update your server.
