### ISSUE TITLE
summon timer bugged

### ISSUE THREAD

**Issue by Juanzin93** [opentibiabr/otservbr-global-archived#1256]
## CAUTION: OUR SERVER IS UPDATED DAILY. MAKE SURE YOU ARE REPORTING SOMETHING ON THE LATEST VERSION OF THE SERVER.

**Describe the bug**
20:28 You see a thundergiant. (Master: Wess Emperor). It will disappear in -5 minutes and 49seconds.
Health: 16657 / 20000.

**Expected behavior**
disapper when time runs out

**Screenshots**
![image](https://user-images.githubusercontent.com/64820180/82618704-d099c600-9ba1-11ea-91f8-1ac91b075153.png)

**Desktop (please complete the following information):**
ubuntu 18/04

**Additional context**

**Comment by oalbsilva** [comment]
Did the summon ever die?
If so, it may have already been fixed in #1240

**Comment by Juanzin93** [comment]
Summon didnt die until much later by monsters
