### ISSUE TITLE
Fix Melfar's trade ability

### ISSUE THREAD

**Issue by nickolasdeluca** [opentibiabr/otservbr-global-archived#1258]
**Is your feature request related to a problem? Please describe.**
Melfar has a trade function, he buys creature drops and sells a quest item.

**Describe the solution you'd like**
I have added the trade function, here is he's XML file: [melfar.zip](https://github.com/opentibiabr/otservbr-global/files/4669390/melfar.zip).

**Describe alternatives you've considered**
No alternatives needed.

**Links**
I got his trade options from Tibia's fandom: [Melfar](https://tibia.fandom.com/wiki/Melfar).

**Additional context**
No additional context needed.

**Comment by dudantas** [comment]
Fixed on https://github.com/opentibiabr/otservbr-global/pull/1269
