### ISSUE TITLE
Fix NPC Shanar trade ability

### ISSUE THREAD

**Issue by nickolasdeluca** [opentibiabr/otservbr-global-archived#1263]
Is your feature request related to a problem? Please describe.
Shanar buys Orcish Axes for 350 gp. This option was missing.

Describe the solution you'd like
I added the option, here is he's XML file: [shanar.zip](https://github.com/opentibiabr/otservbr-global/files/4672498/shanar.zip)

Describe alternatives you've considered
No alternatives needed.

Links
I got his trade options from Tibia's fandom: [Shanar](https://tibia.fandom.com/wiki/Shanar).

Additional context
No additional context needed.

**Comment by Billfabio** [comment]
Create pr with npcs 
https://github.com/opentibiabr/otservbr-global/wiki/How-To-Create-a-Pull-Request

**Comment by nickolasdeluca** [comment]
> Create pr with npcs
> https://github.com/opentibiabr/otservbr-global/wiki/How-To-Create-a-Pull-Request

Done!

**Comment by dudantas** [comment]
Fixed on https://github.com/opentibiabr/otservbr-global/pull/1269
