### ISSUE TITLE
life / manaimbuement % formula needs to be corrected

### ISSUE THREAD

**Issue by Juanzin93** [opentibiabr/otservbr-global-archived#1264]
## CAUTION: OUR SERVER IS UPDATED DAILY. MAKE SURE YOU ARE REPORTING SOMETHING ON THE LATEST VERSION OF THE SERVER.

**Describe the bug**
imbuements are working like this:
(FULL IMBUEMENT EXAMPLE)
Iife = heal 50% of dmg from every monter hit
mana = heal 16% of dmg from every monster hit

**Expected behavior**
if there are 8 monsters around it needs to heal 50% / by 8 monsters
if its 5 monsters , each monster gives 10% heal from hit

**Screenshots**

**Desktop (please complete the following information):**
ubuntu 18.04

**Comment by Lycanzito** [comment]
Seens perfect to me;

![image](https://user-images.githubusercontent.com/52710697/82741794-31550a00-9d2c-11ea-833c-db87915e07f6.png)

![image](https://user-images.githubusercontent.com/52710697/82741801-4893f780-9d2c-11ea-8318-706b072eb7d7.png)

every each one grows the leech a little;

**Comment by Juanzin93** [comment]
https://clips.twitch.tv/StupidWonderfulHyenaStrawBeary < this is how mine is working

**Comment by Bipbop69** [comment]
with the changes it seems that they are not correct at all ..

**Comment by Lycanzito** [comment]
@Juanzin420 mandei sussuro na twitch pra ti

**Comment by majestyotbr** [comment]
https://github.com/opentibiabr/otservbr-global/commit/04b4d997d40a02d379999b12f0b63a5e7a577f46
