### ISSUE TITLE
move up action does not work

### ISSUE THREAD

**Issue by Juanzin93** [opentibiabr/otservbr-global-archived#1265]
## CAUTION: OUR SERVER IS UPDATED DAILY. MAKE SURE YOU ARE REPORTING SOMETHING ON THE LATEST VERSION OF THE SERVER.

**Describe the bug**
does nothing

**Expected behavior**
expected to move the item to the previous backpack

**Screenshots**
![image](https://user-images.githubusercontent.com/64820180/82741066-825d0200-9d1c-11ea-901b-2c7cc4019542.png)

**Desktop (please complete the following information):**
 ubuntu 18.04
client 12

**Additional context**

**Comment by Lycanzito** [comment]
#666 
duplicado

**Comment by dudantas** [comment]
Duplicated: https://github.com/opentibiabr/otservbr-global/issues/666
