### ISSUE TITLE
Imbuement Shrine doesnt open

### ISSUE THREAD

**Issue by luucassoares** [opentibiabr/otservbr-global-archived#127]
Hello, good night. 

Imbuement shrine doesnt open when used with item... i searched if this issue was opened before but didnt find anything.. thats basically it.. i tried with wand of destruction, rod of destruction, blue robe and gnome helmet, when i right-click on the shrine than use it with item, i get the message: you cannot use this object

Thanks in advance, excellent work so far

**Comment by Szulcek69** [comment]
You have to turn 5 Heavy Old Tomes to Albius in temple north of Thais by writing to him:
- Hi
- Temple
- Yes

That should allow you to open to imbuing window. Sadly mana leech, life leech and critical chance aren't working yet.

**Comment by luucassoares** [comment]
Hello, 

Thanks for answering. You know if there is any way to deactivate quest access to do things such as this?

I found a line on config.lua that was setted to true about quest access
`loadQuestLua = true`
but nothing changes after changing it to false.

Thanks in advance and also for answering me before.

**Comment by dudantas** [comment]
It's is on the imbuement script.

**Comment by dudantas** [comment]
Solved question. 
Closing.
