### ISSUE TITLE
Cults Of tibia crash and bug

### ISSUE THREAD

**Issue by Juanzin93** [opentibiabr/otservbr-global-archived#1270]
## CAUTION: OUR SERVER IS UPDATED DAILY. MAKE SURE YOU ARE REPORTING SOMETHING ON THE LATEST VERSION OF THE SERVER.

**Describe the bug**
when walking the boss  Sinister Hermit (dirty) inside the water to clean him up, the whole server crashes
_______________
also the boss Essence Of Malice is not spawning after killing 5 pillars and 5 minibosses on the room
if you kill a second pillar without killing the first mini boss (after killing the first pillar) client with crash
____________________________
the sandking mechanics are not working and can be done multiple times over and over again, also items that teleport to other side dont work Pink Fluid and  Tool for Analyzing Fluids 
___________________________________________________
BOSS THE ARMORED VOIDBORN 
Mechanics stopped working
![image](https://user-images.githubusercontent.com/64820180/82766509-c966f800-9ded-11ea-800b-61ddbb88c39f.png)

**To Reproduce**
1. Go to boss of misguided thief
2. walk the boss to the water

**Expected behavior**
transform boss into his clean form so he can be killed
![image](https://user-images.githubusercontent.com/64820180/82765649-9cfbad80-9de6-11ea-8866-fa50aa8eee18.png)

_________
spawn essence of malice when minibosses are killed and not crash client if kill 2 pillars without killing miniboss
![image](https://user-images.githubusercontent.com/64820180/82765518-9a4c8880-9de5-11ea-906f-821660589d1f.png)
![image](https://user-images.githubusercontent.com/64820180/82765527-b0f2df80-9de5-11ea-90b9-e6f3a62b3d88.png)
________________________________________
![image](https://user-images.githubusercontent.com/64820180/82765588-19da5780-9de6-11ea-9c68-478d472ed239.png)
![image](https://user-images.githubusercontent.com/64820180/82765591-265eb000-9de6-11ea-99ee-022a640f2f6a.png)
![image](https://user-images.githubusercontent.com/64820180/82765616-62921080-9de6-11ea-94ed-a2201ca8da6c.png)
_________________________
armored voidborn: after killing machine the energy walls should disappear (it was working before)

**Screenshots**

**Desktop (please complete the following information):**
 - OS:ubuntu 18.04
tibia 12 and 10

**Additional context**

**Comment by oualid6496** [comment]
Im pretty sure the bugs are related to #1219 and #1190

**Comment by majestyotbr** [comment]
#726
