### ISSUE TITLE
QuickLoot Console Error

### ISSUE THREAD

**Issue by CharlySample** [opentibiabr/otservbr-global-archived#1272]
## CAUTION: OUR SERVER IS UPDATED DAILY. MAKE SURE YOU ARE REPORTING SOMETHING ON THE LATEST VERSION OF THE SERVER.

**Describe the bug**

Sometimes when u quick loot a monster, the next Console error appears.

> Lua Script Error: [Modules Interface]
data/modules/scripts/quickloot/quickloot.lua:onRecvbyte
data/modules/scripts/quickloot/quickloot.lua:130: attempt to call method 'getCorpseOwner' (a nil value)
stack traceback:
        [C]: in function 'getCorpseOwner'
        data/modules/scripts/quickloot/quickloot.lua:130: in function <data/modules/scripts/quickloot/quickloot.lua:74>

**To Reproduce**
1. Kill a Monster
2. Qucik Loot iT
3. Some times that error appears
Note: include any configuration/script required to reproduce.

**Expected behavior**

**Screenshots**

> Lua Script Error: [Modules Interface]
data/modules/scripts/quickloot/quickloot.lua:onRecvbyte
data/modules/scripts/quickloot/quickloot.lua:130: attempt to call method 'getCorpseOwner' (a nil value)
stack traceback:
        [C]: in function 'getCorpseOwner'
        data/modules/scripts/quickloot/quickloot.lua:130: in function <data/modules/scripts/quickloot/quickloot.lua:74>

**Desktop (please complete the following information):**
 - Linux
 - Ubuntu 18.04

**Additional context**

**Comment by CharlySample** [comment]
any?

**Comment by dudantas** [comment]
Repeated #1030
