### ISSUE TITLE
Elemental Imbuements

### ISSUE THREAD

**Issue by Bipbop69** [opentibiabr/otservbr-global-archived#1274]
## CAUTION: OUR SERVER IS UPDATED DAILY. MAKE SURE YOU ARE REPORTING SOMETHING ON THE LATEST VERSION OF THE SERVER.

**Describe the bug**
When the player puts elemental imbuements on his weapon when he uses some healing magic the healing is affected

**Desktop (please complete the following information):**
debian 10

**Comment by majestyotbr** [comment]
Already fixed.
