### ISSUE TITLE
The Shaterrer [Feumbras Ascendant Boss]

### ISSUE THREAD

**Issue by CharlySample** [opentibiabr/otservbr-global-archived#1275]
## CAUTION: OUR SERVER IS UPDATED DAILY. MAKE SURE YOU ARE REPORTING SOMETHING ON THE LATEST VERSION OF THE SERVER.

**Describe the bug**
When u pull the last lever, the boss doesn't come to the map, it's still untargetable.

**To Reproduce**
1. Go to shaterer
2. Pull the 4 levers
3. See error
Note: include any configuration/script required to reproduce.

**Expected behavior**
It's expected to free The Shaterer from his chains. And the combat begins.

**Screenshots**

> Lua Script Error: [Action Interface]
data/actions/scripts/quests/ferumbras_ascendant/the_shatterer_levers.lua:onUse
data/lib/core/game.lua:118: table index is nil
stack traceback:
        [C]: in function '__newindex'
        data/lib/core/game.lua:118: in function 'setStorageValue'
        ...ipts/quests/ferumbras_ascendant/the_shatterer_levers.lua:74: in function <...ipts/quests/ferumbras_ascendant/the_shatterer_levers.lua:40>

**Desktop (please complete the following information):**
 - OS: Linux
 - Version: Ubuntu 18.04

**Additional context**

**Comment by oualid6496** [comment]
Was fixed here #1186 if anyone wants to make a new pr go ahead else I'll do it tonight
