### ISSUE TITLE
Missing Purple butterflies for The Explorer Society Quest

### ISSUE THREAD

**Issue by nickolasdeluca** [opentibiabr/otservbr-global-archived#1276]
**Is your feature request related to a problem? Please describe.**
There are no spawns for purple butterflies on the usual places. Cormaya Garden as an example only has spawns for Blue and Red butterflies, according to [The Explorer Society Quest - TibiaWiki](https://www.tibiawiki.com.br/wiki/The_Explorer_Society_Quest) there was supposed to be a spawn for it. There are other places that they should be spawning but none were found.

**Describe the solution you'd like**
Find the usual places and place a spawn point for them.

**Describe alternatives you've considered**
No alternatives, not that I can think of.

**Links**
[Butterly (Purple)](https://tibia.fandom.com/wiki/Butterfly_(Purple)) - Has the usual spawn points for them: Yalahar, Tiquanda, the Shattered Isles, Alatar Lake, Carlin, Ab'Dendriel and some other places.

**Additional context**
No additional context available.

**Comment by majestyotbr** [comment]
#726
