### ISSUE TITLE
Update Mounts (commit f2b3e48)

### ISSUE THREAD

**Issue by runn3t** [opentibiabr/otservbr-global-archived#1283]
## CAUTION: OUR SERVER IS UPDATED DAILY. MAKE SURE YOU ARE REPORTING SOMETHING ON THE LATEST VERSION OF THE SERVER.

**Describe the bug**

When u start check all mounts in outfits section the client 12 crashed, exactly in a reverse check (left arrow)

**To Reproduce**
1. Go to 'Set Outfit'
2. Click on 'mount'
3. Use left arrow to check all mounts.
Note: include any configuration/script required to reproduce.

**Expected behavior**

I expected that could been seen all mounts.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Ubuntu]
 - Version: [18.04 LTS]

**Additional context**

**Comment by majestyotbr** [comment]
Are you using updated client 12?
https://forums.otserv.com.br/index.php?/forums/topic/167933-otservbr-global-cliente-tibia-12/

**Comment by majestyotbr** [comment]
Every time that items.otb, outfits and mounts are updated, the client 12 is updated too.

**Comment by runn3t** [comment]
Oh, i didn't change it (DUDE sry and thanks for info)

**Comment by majestyotbr** [comment]
Ok.
