### ISSUE TITLE
ubuntu 16.04 - Decrease size of your map or compile in a 64-bit mode.

### ISSUE THREAD

**Issue by Meth28** [opentibiabr/otservbr-global-archived#1286]
https://prnt.sc/sr2irb

I have this problem when trying to open the server

Allocation failed, server out of memory! Decrease size of your map or compile in a 64-bit mode.
i have ubuntu 16.04  8gb RAM
can you help me?

**Comment by dudantas** [comment]
> https://prnt.sc/sr2irb
> 
> I have this problem when trying to open the server
> 
> Allocation failed, server out of memory! Decrease size of your map or compile in a 64-bit mode.
> i have ubuntu 16.04 8gb RAM
> can you help me?

Tried to upgrade to a more current ubuntu?

**Comment by lmiguelm26** [comment]
reinstall linux and be sure to select 64 bit version

**Comment by Meth28** [comment]
it's 64 bit
i reinstalled on 18.04 and it works but the actions.cpp and others message still appears

**Comment by dudztroyer** [comment]
when compiling the sources select 64bit version... You are running out of avaiable memory for the process, which is 4gb maximum to 32bit cpu architeture.

**Comment by Meth28** [comment]
i use the script (recompile.sh ) and my vps has 16gb of ram, i don't know why that happened, that's why i opened this conversation, but it was solved changing the version of ubuntu
