### ISSUE TITLE
Compilado de Errors / Cyclopedia / Market Average value, entre outros.

### ISSUE THREAD

**Issue by Lycanzito** [opentibiabr/otservbr-global-archived#1288]
#978 - Não funcionando a relação do valor médio do market, com a cyclopedia.

![image](https://user-images.githubusercontent.com/52710697/83482825-9240b880-a477-11ea-9c69-a98102187b69.png)

CharacterInfo - 
![image](https://user-images.githubusercontent.com/52710697/83482845-9b318a00-a477-11ea-9e43-06f9a3ebf109.png)

Basic Item Details, não está sendo carregado.

![image](https://user-images.githubusercontent.com/52710697/83482869-aa183c80-a477-11ea-8e67-3e0957b82277.png)

**Comment by Lycanzito** [comment]
atualização:

na verdade, atualizou depois de um tempo.

![image](https://user-images.githubusercontent.com/52710697/83565193-5566d700-a4f4-11ea-947f-346af2e85630.png)

ainda não sei a cada quanto tempo ele atualiza

**Comment by lBaah** [comment]
Atualiza a cada vez que o server é carregado:
https://github.com/opentibiabr/otservbr-global/blob/develop/src/otserv.cpp#L327

**Comment by xsifthewolf** [comment]
como faz pra ter essa pagina de characterinfo funcionando?

**Comment by marcosvf132** [comment]
CharacterInfo is a need to be done system.
