### ISSUE TITLE
Anihilator doors locked.

### ISSUE THREAD

**Issue by nickolasdeluca** [opentibiabr/otservbr-global-archived#1296]
## CAUTION: OUR SERVER IS UPDATED DAILY. MAKE SURE YOU ARE REPORTING SOMETHING ON THE LATEST VERSION OF THE SERVER.

**Describe the bug**
I went in with a group and even after we killed all 6 Angry Demons, the door remained locked. Also the exit door was locked as well.

**To Reproduce**
1. Pull the lever to start the anihilator, kill the demons.
2. Door to the reward room is locked.
3. Get the reward.
4. Door to exit the room is also locked.

**Expected behavior**
Doors should be open, or at least they should trigger a script if all demons need to be killed, which I believe it doesn't.

**Additional context**
Door 1 position: x = 33225; y = 31659; z = 13;
Door 2 position: x = 33235; y = 31659; z = 13;

**Comment by CharlySample** [comment]
I think this was solved in the commits of 29/May and 30/May

**Comment by nickolasdeluca** [comment]
Strange, I have merged my repo with the Jun 1st commit.
I switched the .otbm map as well... 
I don't believe I missed something, but I'll check anyways.

**Comment by nickolasdeluca** [comment]
Yep, just checked, still locked.

**Comment by thatmichaelguy** [comment]
This has been fixed in #1351

**Comment by dudantas** [comment]
> This has been fixed in #1351

Thanks for remember
