### ISSUE TITLE
BUG on 'capacity' attribute.

### ISSUE THREAD

**Issue by marcosvf132** [opentibiabr/otservbr-global-archived#1298]
Hello, i found a problem with the condition **'CAPACITYPERCENT'**, i tryed to change the atribute condition to test if the problem is on my script but, when i changed it to other atribute like 'crit chance', it works perfectly.
```
 local condition = Condition(CONDITION_ATTRIBUTES)
setConditionParam(condition, CONDITION_PARAM_TICKS, 10000)
setConditionParam(condition, CONDITION_PARAM_STAT_CAPACITYPERCENT, 50)
...

     player:addCondition(condition)

...
```
So i think the problem is providing the atribute to the player, my guess is that the server source doesnt apply the capacity buff because its useless at the moment on the server.

**Comment by Bipbop69** [comment]
> So i think the problem is providing the atribute to the player, my guess is that the server source doesnt apply the capacity buff because its useless at the moment on the server

found any solution?

**Comment by marcosvf132** [comment]
No, its still open

**Comment by gpedro** [comment]
can you update the server and test if this still happening?

**Comment by marcosvf132** [comment]
O.o sorry i didn't see your reply, yes its working perfectly now.
