### ISSUE TITLE
Secret Library Earth Section & Entrance - Doot that can't be opened

### ISSUE THREAD

**Issue by Szulcek69** [opentibiabr/otservbr-global-archived#130]
09:09 You see a closed door.
Item ID: 33117
Position: 32623, 32544, 12

09:09 You see a closed door.
Item ID: 33119
Position: 32618, 32538, 12

09:09 You see a closed door.
Item ID: 33117
Position: 32608, 32549, 12

09:09 You see a closed door.
Item ID: 33119
Position: 32598, 32540, 12

09:10 You see a closed door.
Item ID: 33119
Position: 32578, 32540, 12

09:10 You see an item of type 33400.
Item ID: 33400
Position: 32565, 32541, 12

09:12 You see a closed door.
Item ID: 33117
Position: 32629, 32572, 12

09:13 You see a closed door.
Item ID: 33119
Position: 32639, 32579, 12

09:13 You see a closed door.
Item ID: 33117
Position: 32647, 32586, 12

09:13 You see a closed door.
Item ID: 33119
Position: 32644, 32590, 12

09:14 You see a closed door.
Item ID: 33117
Position: 32602, 32618, 13

09:14 You see a closed door.
Item ID: 33117
Position: 32592, 32618, 13

09:15 You see a closed door.
Item ID: 33117
Position: 32550, 32584, 14

09:15 You see a closed door.
Item ID: 33117
Position: 32554, 32584, 14

09:15 You see a closed door.
Item ID: 33117
Position: 32554, 32580, 14

09:15 You see a closed door.
Item ID: 33117
Position: 32550, 32580, 14

09:16 You see a closed door.
Item ID: 33117
Position: 32575, 32580, 14

09:16 You see a closed door.
Item ID: 33117
Position: 32571, 32580, 14

09:16 You see a closed door.
Item ID: 33117
Position: 32571, 32584, 14

09:16 You see a closed door.
Item ID: 33117
Position: 32576, 32584, 14

09:17 You see a closed door.
Item ID: 33119
Position: 32568, 32592, 14

09:17 You see a closed door.
Item ID: 33119
Position: 32605, 32602, 14

09:17 You see a closed door.
Item ID: 33119
Position: 32605, 32590, 14

09:19 You see a closed door.
Item ID: 33117
Position: 32517, 32547, 14

**Comment by Pewm** [comment]
these ports are not working
have to edit (actions.xml) and (transform.lua)
