### ISSUE TITLE
NPC Zurak missing in farmine.

### ISSUE THREAD

**Issue by nickolasdeluca** [opentibiabr/otservbr-global-archived#1302]
**Is your feature request related to a problem? Please describe.**
Zurak, an boatman NPC should be spawned around X: 33155 Y: 31230 Z: 7. The map file has what looks like his spawn point placed but the NPC is not there.

**Describe the solution you'd like**
I'd like the NPC to be placed over there, so that the player can move back and forth.

**Describe alternatives you've considered**
No other alternatives.

**Links**
Here is his fandom page, where it says that he should be there: [Zurak](https://tibia.fandom.com/wiki/Zurak)

**Comment by majestyotbr** [comment]
![image](https://user-images.githubusercontent.com/32709570/88836778-a2da8a00-d1ad-11ea-8233-9b53fc249188.png)
