### ISSUE TITLE
Game.lua Console Error

### ISSUE THREAD

**Issue by CharlySample** [opentibiabr/otservbr-global-archived#1305]
## CAUTION: OUR SERVER IS UPDATED DAILY. MAKE SURE YOU ARE REPORTING SOMETHING ON THE LATEST VERSION OF THE SERVER.

**Describe the bug**
Sometimes at console appears the next error.

**Expected behavior**
The server doesn't crash but the console error appears

**Screenshots**
`data/lib/core/game.lua:118: table index is nil
stack traceback:
        [C]: in function '__newindex'
        data/lib/core/game.lua:118: in function 'setStorageValue'
        data/lib/miscellaneous/050-functions.lua:81: in function <data/lib/miscellaneous/050-functions.lua:62>
`

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version: 18.04

**Additional context**

**Comment by gpedro** [comment]
can you update the server and test if this still happening?
