### ISSUE TITLE
Tibia Error - Debug...

### ISSUE THREAD

**Issue by matheuspergher** [opentibiabr/otservbr-global-archived#1308]
Hey guys. 

I dont know why, but every time now when I try to buy something on Store with Tibia Coins, like mount or itens for house, the client crash, as photos. Does anybody know how to fix that? 

Thank you.

![image](https://user-images.githubusercontent.com/26007416/83967802-1d063500-a908-11ea-933d-8842fca10bd4.png)
![Capturar](https://user-images.githubusercontent.com/26007416/83967806-27c0ca00-a908-11ea-95ac-13e78a96f92b.JPG)

**Comment by MajestyOTBR** [comment]
I tested with latest repository, clean schema.sql, new executable and i don't confirm the debug here.

You probably don't have this table on your database, add:

```
CREATE TABLE IF NOT EXISTS `coins_transactions` (
  `id`          int(11)       UNSIGNED NOT NULL AUTO_INCREMENT,
  `account_id`  int(11)       UNSIGNED NOT NULL,
  `type`        tinyint(1)    UNSIGNED NOT NULL,
  `amount`      int(12)       UNSIGNED NOT NULL,
  `description` varchar(3500) NOT NULL,
  `timestamp`   timestamp     DEFAULT CURRENT_TIMESTAMP,
  INDEX `account_id` (`account_id`),
  CONSTRAINT `coins_transactions_pk` PRIMARY KEY (`id`),
  CONSTRAINT `coins_transactions_account_fk`
    FOREIGN KEY (`account_id`) REFERENCES `accounts` (`id`)
    ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
```

And try again.

**Comment by majestyotbr** [comment]
I tested with latest repository, clean schema.sql, new executable and i don't confirm the debug here.

Few days ago, the schema.sql received update, install it again.
