### ISSUE TITLE
Premdays not removing automatically

### ISSUE THREAD

**Issue by deletera** [opentibiabr/otservbr-global-archived#1309]
I just made a test and after the premdays are over, the character/account still with the premdays, they arent removed automatically 

Here it's my example, the accounts with 2 and 1 premdays should be 0 with the premdays as the client and account managent shows "free account", but they still there:

![image](https://user-images.githubusercontent.com/66503416/83976454-591da380-a8d0-11ea-8633-a173ef35224f.png)

**Comment by lurkgabriel** [comment]
did you check line 98 of config.lua for `freePremium = true`?
if it is true, yeah will be premium forever and it is true by default

**Comment by deletera** [comment]
> did you check line 98 of config.lua for `freePremium = true`?
> if it is true, yeah will be premium forever and it is true by default

It's set as freePremium = false, the premdays shows correctly in site and client, the problem is just that after the premium is finished, the premdays still there, they aren't removed

I think this is related with something about "removepremdays", just don't know yet how to set it and where

**Comment by lurkgabriel** [comment]
I remember seeing this today somewhere around here, take a look at the issues, prs and recent merged stuff I'm sure it was around there. dunno if it fixes the problem tho, maybe they're just aware of it and trying to fix

**Comment by deletera** [comment]
There is this one:

https://github.com/opentibiabr/otservbr-global/pull/1291

So, I made a test by adding premium using an action like this:
`function onUse(cid, item, fromPosition, itemEx, toPosition)
	
	local player, days = Player(cid), 1 -- days of premium
	
	if(player:getPremiumDays() < 360) then
		player:addPremiumDays(days)
	    db.query("UPDATE `accounts` SET `lastday` = ".. os.time() .." WHERE `id` = " .. player:getAccountId())
		player:sendTextMessage(MESSAGE_INFO_DESCR, 'You have bought ' .. days .. ' days of premium account.')
		player:getPosition():sendMagicEffect(CONST_ME_MAGIC_GREEN)
		Item(item.uid):remove(1)
	else			
		player:sendCancelMessage('You can not buy more than 360 days of Premium Account.')
		player:getPosition():sendMagicEffect(CONST_ME_POFF)
	end
	
	return true end`

It works until the premium ends without really end... That's it

**Comment by lurkgabriel** [comment]
you can add an extra storage for control and check on login for your control storage and then remove the premium as a temporary solution

**Comment by deletera** [comment]
Well, I didn't find anything about this in TFS 1.3, so I tried to make a script in globalevents like:

	db.query('UPDATE `accounts` SET `premdays` = 0 WHERE `accounts`.`lastday` <= X')

But im not good with coding and I still wondering what could place the X or even the whole script to do this kind of check...

**Comment by oalbsilva** [comment]
Tibia Client 12 login is provided by the website (myacc for example)
you need to put your logic (remove premmy days, etc) in the login.php file
