### ISSUE TITLE
NPC Uzon missing in the second mission of The Inquisition Quest

### ISSUE THREAD

**Issue by nickolasdeluca** [opentibiabr/otservbr-global-archived#1310]
**Describe the bug**
In the second mission of the Inquisition quest, the NPC Uzon flies you to the top of a mountain where there is a Witches cult. There you have to use holy water and get the grimmoire.
The quest itself is working fine, but Uzon is not there to fly you back to where you came from.

**To Reproduce**
1. Go to Position X: 32660 Y: 31915 Z: 0
Uzon should be here to fly you back.

**Expected behavior**
The NPC should spawn.

**Comment by majestyotbr** [comment]
#726

**Comment by Ghelter** [comment]
There is another bug in the inquisition quest on mission 6. After you kill Ungreez going back to Henricus and saying mission, Henricus does not reply back or gives you the next mission.
