### ISSUE TITLE
In Service of Yalahar Quest Mission 02 should be able to request reports from all NPCs with no specific order.

### ISSUE THREAD

**Issue by nickolasdeluca** [opentibiabr/otservbr-global-archived#1311]
**Describe the bug**
Although the quest is working just fine, in the second step of this quest, Mission 02: Watching the Watchmen, we should be able to request reports from the guards in no specific order. Right now, it needs to be done in a specific order. The order is the exact one described in here: [In Service of Yalahar - Tibia Fandom](https://tibia.fandom.com/wiki/In_Service_of_Yalahar_Quest/Spoiler)

**To Reproduce**
1. Start the quest step, and try to ask the report of a guard that isnt the first one mentioned in the quest tutorial on tibia fandom.

**Expected behavior**
We should be able to request reports from any guard in no particular order. As long as we ask all reports, the quest should be finished anyways.

**Comment by majestyotbr** [comment]
#726
