### ISSUE TITLE
Hirelings store

### ISSUE THREAD

**Issue by lurkgabriel** [opentibiabr/otservbr-global-archived#1315]
## CAUTION: OUR SERVER IS UPDATED DAILY. MAKE SURE YOU ARE REPORTING SOMETHING ON THE LATEST VERSION OF THE SERVER.

**Describe the bug**
cannot buy hirelings from the store, talkaction to create works fine and the hirelings answer and sell currectly still
`Tested both as a god and player. /hireling Name, Sex works tho, you can summon him in your house buy his stuff (didn't try the cooking skill because I can't use the store to buy)

Even if you, as a god, give yourself a hireling and summon him in your house you **still won't be able to buy custom stuff at the store**`

**To Reproduce**
1. Log in
2. Open the store, hirelings tab
3. Unable to buy, `The product is currently not available for this character. See the Buy button tooltip for details.`

**Expected behavior**
being able to buy hirelings + hirelings customizables

**Screenshots**
![image](https://user-images.githubusercontent.com/54478023/84062340-7c5e5680-a995-11ea-8b30-867e29164c3a.png)

**Comment by perron5306987** [comment]
the same error happens with the golden addon, lion of war 
and the newest

**Comment by lurkgabriel** [comment]
I didn't find a single mount I couldn't buy but Yeah the golden outfit has the same problem

**Comment by Lycanzito** [comment]
cant reproduce it.

try use the THE LATEST VERSION OF THE SERVER.

also, golden outfit isnt avaliable in the gamestore.

but, if u want to make it "custom"

follow these steps to add it on yours store.

https://github.com/opentibiabr/otservbr-global/tree/develop/data/modules/scripts/gamestore

**Comment by lurkgabriel** [comment]
I added the golden outfit to the store and I am using the latest version.... anyway I'll try again and update this comment 

literally just downloaded again and I have the same issue. maybe it's a conflict that happened because of some recent merge. are you using the latest edition as well?
![image](https://user-images.githubusercontent.com/54478023/84082147-b9d2dc00-a9b5-11ea-8144-6b1d9215ae59.png)

**the most influential change that happened and comes to my mind as possible reason in dropping support for the 10 and 11 protocol, maybe something vital to the store have been removed?** or maybe a recent file commit conflict?

**Comment by majestyotbr** [comment]
https://github.com/opentibiabr/otservbr-global/pull/1316

**Comment by lurkgabriel** [comment]
for the golden outfit:
`{
            icons = { "Outfit_Golden_Male_Addon_3.png", "Outfit_Golden_Female_Addon_3.png" },
            name = "Full Golden Outfit",
            price = 870,
            sexId = {female = 1211, male = 1210},
            addon = 3,
            description = "- only usable by purchasing character\n- colours can be changed using the Outfit dialog\n- includes basic outfit and 2 addons which can be selected individually\n\nFight your bloody battles in the arena and become a darling of the crowd. Once you have made it to the top and everyone is cheering your name, the fashionable outfit of an Arena Champion will show the world what you are made of.",
            type = GameStore.OfferTypes.OFFER_TYPE_OUTFIT,
        },`
in the gamestore.lua and check outfit.xml
<outfit type="1" looktype="1210" name="Golden" premium="yes" **unlocked="no"** enabled="yes" />

it MUST be locked

**Comment by perron5306987** [comment]
> for the golden outfit:
> `{ icons = { "Outfit_Golden_Male_Addon_3.png", "Outfit_Golden_Female_Addon_3.png" }, name = "Full Golden Outfit", price = 870, sexId = {female = 1211, male = 1210}, addon = 3, description = "- only usable by purchasing character\n- colours can be changed using the Outfit dialog\n- includes basic outfit and 2 addons which can be selected individually\n\nFight your bloody battles in the arena and become a darling of the crowd. Once you have made it to the top and everyone is cheering your name, the fashionable outfit of an Arena Champion will show the world what you are made of.", type = GameStore.OfferTypes.OFFER_TYPE_OUTFIT, },`
> in the gamestore.lua and check outfit.xml
> <outfit type="1" looktype="1210" name="Golden" premium="yes" **unlocked="no"** enabled="yes" />
> 
> it MUST be locked

same error

**Comment by lurkgabriel** [comment]
well that's.. weird. did you update to https://github.com/opentibiabr/otservbr-global/pull/1316?
