### ISSUE TITLE
Pack de Errors - Summon (PET)

### ISSUE THREAD

**Issue by Lycanzito** [opentibiabr/otservbr-global-archived#1329]
1- Você apanha de  seu próprio summon.
![image](https://user-images.githubusercontent.com/52710697/84334545-027ec680-ab69-11ea-826d-a71cf13b3c69.png)

2- summon indo parar dentro de água.
![image](https://user-images.githubusercontent.com/52710697/84334603-23dfb280-ab69-11ea-81d3-d37cc371cbef.png)

3- ao relogar, summon não desaparece.

4- todas magias de attack estão com effects / dano /  area, totalmente errados.

![image](https://user-images.githubusercontent.com/52710697/84334463-ce0b0a80-ab68-11ea-9ff6-44f94ca07b48.png)

**Comment by lurkgabriel** [comment]
arrumar segundos colado no final da frase do tempo restante do summon
`timeStr = timeStr .. minutes .. ' minutes and '.. seconds .. ' seconds. '`

**Comment by perron5306987** [comment]
solved? i have the same error

**Comment by lBaah** [comment]
1 - teste isso
https://github.com/lBaah/otservbr-global/commit/08f47be79c69c7dc1497e8008359c63e22b1fedc
2 - é pra refrescar
3 - pelo que sei não desaparecem no global também
4 - você mesmo pode corrigir e enviar: https://github.com/opentibiabr/otservbr-global/blob/develop/data/monster/summons/emberwing.xml#L22

**Comment by matheuspergher** [comment]
> 1 - teste isso
> [lBaah@08f47be](https://github.com/lBaah/otservbr-global/commit/08f47be79c69c7dc1497e8008359c63e22b1fedc)
> 2 - é pra refrescar
> 3 - pelo que sei não desaparecem no global também
> 4 - você mesmo pode corrigir e enviar: https://github.com/opentibiabr/otservbr-global/blob/develop/data/monster/summons/emberwing.xml#L22

Man, sabes como resolver do summon causar damage no player?

**Comment by matheuspergher** [comment]
> 1 - teste isso
> [lBaah@08f47be](https://github.com/lBaah/otservbr-global/commit/08f47be79c69c7dc1497e8008359c63e22b1fedc)
> 2 - é pra refrescar
> 3 - pelo que sei não desaparecem no global também
> 4 - você mesmo pode corrigir e enviar: https://github.com/opentibiabr/otservbr-global/blob/develop/data/monster/summons/emberwing.xml#L22

Testei essa aqui iBaah, mas não funcionou..
