### ISSUE TITLE
[Error - LuaScriptInterface::luaGameLoadMap]

### ISSUE THREAD

**Issue by pedrohfk** [opentibiabr/otservbr-global-archived#1332]
I followed the tutorial through the wiki, I configured my config.lua correctly but not seeing my map in the folder

![image](https://user-images.githubusercontent.com/16357255/84442709-893cad80-ac14-11ea-8191-01ff9f9bfb07.png)

ubuntu-1804-bionic-v20200610
1 vCPUj, 3,75 GB de memória

**Comment by MajestyOTBR** [comment]
https://github.com/opentibiabr/otservbr-global#getting-started

* **WARNING: YOU NEED TO UNZIP THE MAP BEFORE START THE SERVER.**

**Comment by pedrohfk** [comment]
@MajestyOTBR 

I'm trying the Alunia map, and I put it in the RME Map Editor and compile it again and even then he doesn't know.
I already called some people to look at me and they both saw nothing wrong that I am doing.

**Comment by lurkgabriel** [comment]
check config.lua, the map's name should match the name you gave to your otbm file as well as it's spawn and house files

**Comment by dudantas** [comment]
You deleted the worldchange maps? Disable the scripts...
