### ISSUE TITLE
Missing Display Items (Decoration) on Venore Weapon Shop

### ISSUE THREAD

**Issue by LordSamoht** [opentibiabr/otservbr-global-archived#1340]
**Describe the bug:**
Some display items (decorative items) on Venore weapon shop are missing:

Position: 32914, 32119, 6 - Item: axe (id: 2386)
Position: 32916, 32119, 6 - Item: sword (id: 2376)

**To Reproduce:**
1. Go to the Venore Weapon Shop and see the empty shelf behind the NPC

**Expected behavior:**
These tiles should have the specified items on a daily spawn

**Desktop:**
OS: Windows
Version: 8.1

**Comment by majestyotbr** [comment]
Updated map: https://github.com/opentibiabr/otservbr-global/blob/develop/data/world/world.zip
