### ISSUE TITLE
does not have mission dialogues

### ISSUE THREAD

**Issue by perron5306987** [opentibiabr/otservbr-global-archived#1341]
## CAUTION: OUR SERVER IS UPDATED DAILY. MAKE SURE YOU ARE REPORTING SOMETHING ON THE LATEST VERSION OF THE SERVER.

**Describe the bug**
in mission of the new frontier in mission 5 you have to speak to king tibianus, but the script of king tibianus has no dialogues for that mission

**Comment by nickolasdeluca** [comment]
I fixed this issue in this [PR](https://github.com/opentibiabr/otservbr-global/pull/1269).
Can you check if you have the latests commits merged on your repo?

**Comment by perron5306987** [comment]
> I fixed this issue in this [PR](https://github.com/opentibiabr/otservbr-global/pull/1269).
> Can you check if you have the latests commits merged on your repo?

Thank
