### ISSUE TITLE
Sobre houses...

### ISSUE THREAD

**Issue by yehia** [opentibiabr/otservbr-global-archived#1343]
Galera, o servidor não deveria sincronizar as houses.xml com a tabela houses do banco de dados? Nem no Znote e nem o MyAAC mostram as casas do servidor... alguém sabe oq tá acontecendo? Obs:
Já configurei os towns no site...

`'towns' => array(
	1 => 'Dawnport Tutorial',
	2 => 'Dawnport',
	3 => 'Rookgaard',
	4 => 'Island of Destiny',
	5 => 'Ab Dendriel',
	6 => 'Carlin',
	7 => 'Kazordoon',
	8 => 'Thais',
	9 => 'Venore',
	10 => 'Ankrahmun',
	11 => 'Edron',
	12 => 'Farmine',
	13 => 'Darashia',
	14 => 'Liberty Bay',
	15 => 'Port Hope',
	16 => 'Svargrond',
	17 => 'Yalahar',
	18 => 'Gray Beach',
	19 => 'Krailos',
	20 => 'Rathleton',
	21 => 'Roshamuul',
	22 => 'Issavi'		
),`

**Comment by majestyotbr** [comment]
Se configurar certo funciona, eu fiz com o MyAAC e ele mostra as casas no site.
Aqui não é lugar para pedir suporte, você pode entrar no discord do projeto e perguntar lá:
https://discordapp.com/invite/3NxYnyV
