### ISSUE TITLE
Compiling Appveyor

### ISSUE THREAD

**Issue by DamianDEB** [opentibiabr/otservbr-global-archived#1346]
Hi someone know why compilation stuck at
Building package openssl-windows[core]:x64-windows...
Build execution time has reached the maximum allowed time for your plan (60 minutes).
any solutions?
without desktop vs beacuse here i have problem with mysql/mysql.h and boost

**Comment by majestyotbr** [comment]
You can request an increase of build timeout by sending an email to `support@appveyor.com` or using the AppVeyor support center: https://help.appveyor.com/

**Comment by DamianDEB** [comment]
its no problem with timeout 
idk one time you can build this normal next time stuck 
on desktop is problem with boost etc

**Comment by majestyotbr** [comment]
Ok.
