### ISSUE TITLE
client 10

### ISSUE THREAD

**Issue by perron5306987** [opentibiabr/otservbr-global-archived#1348]
## CAUTION: OUR SERVER IS UPDATED DAILY. MAKE SURE YOU ARE REPORTING SOMETHING ON THE LATEST VERSION OF THE SERVER.

**Describe the bug**
i just updated the source and compile and now when i open client 10 it debug me

**Desktop (please complete the following information):**
 - OS: [debian]
 - Version: [9]

**Additional context**
before updating the source and compiling client 10 it worked wonderfully

**Comment by Costallat** [comment]
https://github.com/opentibiabr/otservbr-global/commit/64c330a4825071ef935e78c39513d9871806eb79
