### ISSUE TITLE
Worm priestess corpse cant be opened

### ISSUE THREAD

**Issue by Mortalot** [opentibiabr/otservbr-global-archived#1353]
![worm](https://user-images.githubusercontent.com/66652015/84723710-39335300-af54-11ea-9a54-1792f1801aab.png)

**Comment by gpedro** [comment]
can you test again with a normal player? because the corpseid is right
![image](https://user-images.githubusercontent.com/2898638/85926008-37c62c80-b86a-11ea-9d34-e069881be8a3.png)

**Comment by gpedro** [comment]
unconfirmed.
