### ISSUE TITLE
XP boost and other store items tab missing.

### ISSUE THREAD

**Issue by Mortalot** [opentibiabr/otservbr-global-archived#1358]
![xpboost](https://user-images.githubusercontent.com/66652015/84742758-f044c400-af7e-11ea-8c8f-3587c56377e2.png)

**Comment by Mortalot** [comment]
nothing happens when you click home.
you can click the search loop and xp boost will pop up but there use to be a tab for it.
perhaps you can combine the hirelings tab with the hirelings dresses tab and it'll make room for the xp boost tab to pop up.

**Comment by Mortalot** [comment]
So I combined the hireling dresses into hirelings and i deleted the premium tab to make room for extra and tournament.
Heres a fix: https://pastebin.com/AD9RR7Vh

![storefix](https://user-images.githubusercontent.com/66652015/84976484-fc9f5d00-b0f5-11ea-9f6d-d464efb4a602.png)

**Comment by majestyotbr** [comment]
We have a PR with gamestore updated (with home and subcategories).
