### ISSUE TITLE
Lava id 25331 dont give damage

### ISSUE THREAD

**Issue by tyndy125** [opentibiabr/otservbr-global-archived#1362]
the lava with id 25331, which is walkable, does not cause damage when passing through it.

Can see here:
https://giphy.com/gifs/XcjWxfx1zuCzkZVW2z/html5

**Comment by oualid6496** [comment]
Can you give me the positions that should give damage? And I'll add them.

**Comment by gpedro** [comment]
can you test the PR #1451 ?

--

If you like our project, feel free to pay us a coffee, pizza or something else. Click here check donations methods: https://opentibiabr.github.io/donation
