### ISSUE TITLE
Oberon Lever

### ISSUE THREAD

**Issue by perron5306987** [opentibiabr/otservbr-global-archived#1368]
## CAUTION: OUR SERVER IS UPDATED DAILY. MAKE SURE YOU ARE REPORTING SOMETHING ON THE LATEST VERSION OF THE SERVER.

**Describe the bug**
you cannot use the lever again after 20 hours and if you change it to 1 hour or seconds it doesn't work either

**Comment by oualid6496** [comment]
Did you first kill it while 20hours was configured and then changed it to 1 hour and tried to kill it after 1 hour? Because the first 20 hours would still be effective. Try to change it to 5 minutes and try to kill it with a fresh character.

**Comment by majestyotbr** [comment]
#1384
