### ISSUE TITLE
Oberon Teleport not working

### ISSUE THREAD

**Issue by Szulcek69** [opentibiabr/otservbr-global-archived#137]
08:25 You see a mystic flame.
You feel drawn to the mesmerizing light.
Item ID: 1397, Action ID: 57604
Position: 33297, 31290, 9

Not working

![Przechwytywanie](https://user-images.githubusercontent.com/51335460/59011337-a89c4000-8834-11e9-9fc5-a3c875f0e276.PNG)

Should teleport to: 
{x = 33359, y = 31339, z = 9}

Also the lever teleporting to Oberon isn't working.
08:33 You see a lever.
Item ID: 1946, Action ID: 57603
Position: 33359, 31341, 9

**Comment by dudantas** [comment]
In the true, the library does not have scripts created, I will mark it as an enhancement and soon we will do the scripts for the new quests, before we have to fix several bugs that have been left behind in previous projects.

**Comment by Sargitarium** [comment]
Tested and WORK fine at this time....

**Comment by yatozin** [comment]
timer never ends on the lever fix
