### ISSUE TITLE
Inquisition Issues

### ISSUE THREAD

**Issue by nickolasdeluca** [opentibiabr/otservbr-global-archived#1378]
**Describe the bug**
After doing the inquisition in a party of 5, it is a little rough but almost complete. 

1 - When you "use" the inquisidor manual chest and the witches' chest to get the witches' grimmoire, it turns into a lever.
Inquisidor Manual chest position: X:32316, Y:32260, Z:8
Witche's grimmoire chest position: X:32649, Y:31932, Z:1

2 - At Ushuriel's fight, there are lots of [Eye of the seven](https://tibia.fandom.com/wiki/Eye_of_the_Seven), these shouldn't move, but they are moving.

3 - The reward room door has no action attributed to it. I believe this is a bug because even after receiving all the achievements and getting the full outfit, the reward door doesn't open.
Door position: X:32320, Y:32258, Z:9

**To Reproduce**
1. During [mission 02: Eclipse ](https://tibia.fandom.com/wiki/The_Inquisition_Quest#Mission_2:_Eclipse), talk to Uzon and say Eclipse, he should take you to the top of the mountain, there you need to use a vial at the cauldron and use the chest.
1.1 - When I used the chest, it turned into a lever, I believe this is a recent  bug, because on prior commits this worked well.
1.2 - Same thing happens when getting the inquisidor Manual in the first step of the quest.

2. First boss: Ushuriel, the eyes of the seven should be placed at the walls of the room and shouldn't move.
His position: X:33166, Y:31728, Z:11

3. After you finish all the rooms in this quest and talk to Henricus, you should be able to go downstairs and open the door, but it doesnt open and nothing happens.

**Expected behavior**
All errors mentioned above should be fixed as described.

**Additional context**
All the info you need can be found here: [The Inquisition Quest](https://tibia.fandom.com/wiki/The_Inquisition_Quest).

**Comment by oualid6496** [comment]
2. has been fixed in PR #1374

**Comment by nickolasdeluca** [comment]
Since the Eyes of the seven were fixed in another issue, I'm closing this issue, it appears that my map was corrupted or something.
