### ISSUE TITLE
Falcon Castle minor tweaks needed

### ISSUE THREAD

**Issue by Szulcek69** [opentibiabr/otservbr-global-archived#138]
1) Position: 33311, 31309, 9
This are should be accessible, as well here should spawn 2 falcon knights and 1 falcon palladin.

![falcon1](https://user-images.githubusercontent.com/51335460/59012889-f5821580-8838-11e9-85bf-8ee6906a46b1.PNG)

2) Position: 33321, 31331, 9
Entrance from this side should be closed with red thingies so that mobs can't be lured to the portal from the west side. 

![falcon2](https://user-images.githubusercontent.com/51335460/59013306-f5cee080-8839-11e9-8285-c1ec451fcf46.PNG)

3) Position: 33363, 31343, 7
a) Falcon shouldn't be spawning in here 
b) There should be another door where its highlighted
c)  Couldn't find a way to open the door with blinig light here

![falcon3](https://user-images.githubusercontent.com/51335460/59013569-886f7f80-883a-11e9-85f0-2cb32cccc9d8.PNG)

4) Perceptor Lazare should be spawning at Position: 33375, 31339, 3

5) Could find a way to open doors:
a) 09:15 You see a closed door.
Item ID: 6261, Action ID: 57600
Position: 33376, 31335, 3
b) 09:17 You see a closed door.
Item ID: 6261, Action ID: 57600
Position: 33376, 31349, 4
c) 09:18 You see a closed door.
Item ID: 6261, Action ID: 57600
Position: 33376, 31323, 2

6) Should be another door to the boss at:
09:18 You see an item of type 31443.
Item ID: 31443
Position: 33373, 31320, 2

7) a)Using Paddle here:
09:21 You see a paddle.
Item ID: 3599, Action ID: 57601
Position: 33373, 31309, 7

Should teleport you to:
Position: 33382, 31293, 7

b)While using paddle here:
09:22 You see a paddle.
Item ID: 3600, Action ID: 57601
Position: 33381, 31294, 7

should teleport to:
Position: 33374, 31309, 7

**Comment by dudantas** [comment]
In the true, the library does not have scripts created, I will mark it as an enhancement and soon we will do the scripts for the new quests, before we have to fix several bugs that have been left behind in previous projects.

**Comment by Sargitarium** [comment]
Items 1,2,3,4,5 tested and work correctly....

Item 6, added new DOOR on actiondoors

Item 7 tested and work fine
