### ISSUE TITLE
[ITEM] shrunken head necklace

### ISSUE THREAD

**Issue by xThauma** [opentibiabr/otservbr-global-archived#1382]
It should have 10 speed instead of 20.

https://tibia.fandom.com/wiki/Shrunken_Head_Necklace

**Comment by lucas-caminha** [comment]
xThauma, I saw your post and went to make the change, however when I put the value '10' and reloaded within the game the speed of the necklace was 5. Probably there is a division by 2 somewhere in the code. So I continued with the previous value '20'.

**Comment by xThauma** [comment]
> xThauma, I saw your post and went to make the change, however when I put the value '10' and reloaded within the game the speed of the necklace was 5. Probably there is a division by 2 somewhere in the code. So I continued with the previous value '20'.

Okay, can be closed then.
