### ISSUE TITLE
MOTA - Visual Bugs & Portal not working

### ISSUE THREAD

**Issue by Szulcek69** [opentibiabr/otservbr-global-archived#139]
1) ![mota](https://user-images.githubusercontent.com/51335460/59014570-367c2900-883d-11e9-807d-562c0c70567e.PNG)

2) ![mota2](https://user-images.githubusercontent.com/51335460/59014813-c621d780-883d-11e9-8156-9fc5c3253fbf.PNG)

3) ![mota3](https://user-images.githubusercontent.com/51335460/59014846-de91f200-883d-11e9-8706-033c112ff58c.PNG)

4) ![mota4](https://user-images.githubusercontent.com/51335460/59014996-36c8f400-883e-11e9-8d4c-4c0835bacb0b.PNG)

5) ![mota5](https://user-images.githubusercontent.com/51335460/59014981-303a7c80-883e-11e9-9cec-8bc02bc30087.PNG)

6) ![mota6](https://user-images.githubusercontent.com/51335460/59015035-5102d200-883e-11e9-82d0-6382e31b415d.PNG)

7) ![mota7](https://user-images.githubusercontent.com/51335460/59015073-6677fc00-883e-11e9-8f16-639dd052a9a0.PNG)

8) ![mota8](https://user-images.githubusercontent.com/51335460/59015279-e56d3480-883e-11e9-9a31-bb2e62555202.PNG)

9) This portals aren't working. 
a) 09:27 You see a portal of orange energy.
You can see the other side through it.
Item ID: 27722
Position: 33246, 32106, 8

Should be teleporting to: 
Position: 33246, 32097, 8

b)09:29 You see a portal of orange energy.
Item ID: 27722
Position: 33246, 32098, 8

Should be teleporting to:
Position: 33246, 32107, 8

**Comment by dudantas** [comment]
Thank you. I'll be fixing the problems on the map and I'll be up by the end of the week.
Again, thank you for your cooperation, it is very important for the growth of the project.

**Comment by dudantas** [comment]
In fact one of the tps were not teleporting. I fixed it. Position tp position: Position: 33246, 32098, 8 is right, I made the respawns and teleports based on youtube videos of the global.
Thanks, I will soon upload the map with the correction.
