### ISSUE TITLE
Dawnport bug on the floors to choose the vocation

### ISSUE THREAD

**Issue by neykos** [opentibiabr/otservbr-global-archived#1395]
Em Dawnport tem os pisos onde o player passa para escolher cada vocação, e nem um deles está dando a vocação e os itens necessário para a mesma que foi escolhida.

Localização do piso dos knight
Position: 32064, 31881, 5
Position: 32065, 31881, 5

Localização do piso dos Sorcerer
Position: 32065, 31881, 5
Position: 32056, 31891, 5

Localização do piso dos Druid
Position: 32064, 31900, 5
Position: 32065, 31900, 5

Localização do piso dos Paladin
Position: 32074, 31890, 5
Position: 32074, 31891, 5

Obs: Meu servidor está atualizado, pois baixei ele ontem as 22h da noite.

**Comment by dudantas** [comment]
Aplique este pr e teste novamente : https://github.com/opentibiabr/otservbr-global/pull/1371
