### ISSUE TITLE
Feverish Citizen invasion in venore spawning inside npc booths

### ISSUE THREAD

**Issue by nickolasdeluca** [opentibiabr/otservbr-global-archived#1409]
**Describe the bug**
Feverish citizens can spawn inside npc booths when the invasion is happening in venore.

**To Reproduce**
1. Wait for the invasion trigger.
2. Check the npc booths, some of them will have feverish citizens on them.

**Expected behavior**
I believe these areas should be marked as PZ, so no mobs can spawn within.

**Screenshots**
![image](https://user-images.githubusercontent.com/17858166/85969622-98ef1c80-b99e-11ea-8f4a-ef7b871cd679.png)

**Comment by dudztroyer** [comment]
Actually they are not PZ... Because I can send spells through that area... 
https://i.imgur.com/w2N44y8.jpg

But some of the NPC's do have that system
https://i.imgur.com/FgqdN7X.jpg

**Comment by gpedro** [comment]
the behavior is correct
https://youtu.be/uWIyHYZ-xAc?t=37
