### ISSUE TITLE
Damage of paladins

### ISSUE THREAD

**Issue by perron5306987** [opentibiabr/otservbr-global-archived#1414]
**Describe the bug**
the damage of a paladin using a normal bow, is the same using a bow of destruction or falcon bow

char level 200 with distance 110

with normal bow
15:40 A dragon lord loses 120 hitpoints due to your attack.
15:40 A dragon lord loses 131 hitpoints due to your attack.
15:40 A dragon lord loses 118 hitpoints due to your attack.
15:40 A dragon lord loses 133 hitpoints due to your attack.
15:40 A dragon lord loses 133 hitpoints due to your attack.
second attack
15:40 A dragon lord loses 73 hitpoints due to your attack.
15:40 A dragon lord loses 74 hitpoints due to your attack.
15:40 A dragon lord loses 74 hitpoints due to your attack.
15:40 A dragon lord loses 76 hitpoints due to your attack.
15:40 A dragon lord loses 61 hitpoints due to your attack.

with bow of destruction
15:40 A dragon lord loses 111 hitpoints due to your attack.
15:40 A dragon lord loses 138 hitpoints due to your attack.
15:40 A dragon lord loses 135 hitpoints due to your attack.
15:40 A dragon lord loses 141 hitpoints due to your attack.
second attack
15:40 A dragon lord loses 89 hitpoints due to your attack.
15:40 A dragon lord loses 83 hitpoints due to your attack.
15:40 A dragon lord loses 90 hitpoints due to your attack.
15:40 A dragon lord loses 61 hitpoints due to your attack.

**Comment by oualid6496** [comment]
Well from what you just sent it looks like the bow of destruction gives slightly more damages. But isn't that supposed to be like that? Thought the damage mostly depends on the ammo that you're using.

**Comment by ivansho92** [comment]
I think you could modify slightly in vocations.xml, for example, that's how it worked for me.

from distDamage="1.0"  to   distDamage="1.5"
