### ISSUE TITLE
monsters.xml

### ISSUE THREAD

**Issue by oualid6496** [opentibiabr/otservbr-global-archived#1417]
In monsters.xml this part can be found twice

	<monster name="Ancient Spawn of Morgathla" file="cults_of_tibia/bosses/ancient_spawn_of_morgathla.xml" />
	<monster name="Black Vixen" file="cults_of_tibia/bosses/black_vixen.xml" />
	<monster name="Bloodback" file="cults_of_tibia/bosses/bloodback.xml" />
	<monster name="Darkfang" file="cults_of_tibia/bosses/darkfang.xml" />
	<monster name="Last Planegazer" file="cults_of_tibia/bosses/last_planegazer.xml" />
	<monster name="Reflection Of Mawhawk" file="cults_of_tibia/bosses/reflection_of_mawhawk.xml" />
	<monster name="Reflection Of Obujos" file="cults_of_tibia/bosses/reflection_of_obujos.xml" />
	<monster name="Shadowpelt" file="cults_of_tibia/bosses/shadowpelt.xml" />
	<monster name="Sharpclaw" file="cults_of_tibia/bosses/sharpclaw.xml" />

Also Ancient Spawn of Morgathla should be moved to warzones because it isn't a part of cults of tibia quest.

**Comment by oualid6496** [comment]
Oh wait I see that multiple of these bosses aren't a part of the cults of tibia quest

**Comment by lBaah** [comment]
Can you make a list on those bosses? So I'll put them in their place.

**Comment by oualid6496** [comment]
Ancient Spawn of Morgarthla - (warzones?)
Black Vixen - Grimvale Quest (bosses?)
Bloodback - Grimvale Quest (bosses?)
Darkfang - Grimvale Quest (bosses?)
Last Planegazer - (undead?)
Reflection of Mawhawk - ???
Reflection of Obujos - ???
Shadowpelt - Grimvale Quest (bosses?)
Sharpclaw - Grimvale Quest (bosses?)

Not sure in which monster subfile they should go tho.
