### ISSUE TITLE
Imbuiment "been removed" 

### ISSUE THREAD

**Issue by Lycanzito** [opentibiabr/otservbr-global-archived#1418]
You see a magic sword (Atk:48, Def:35 +3).
Imbuements: (Powerful Strike 0:00h, Powerful Vampirism 0:07h).

You see a magic sword (Atk:48, Def:35 +3).
Imbuements: (Empty Slot, Empty Slot).

When the first Imbuement is removed, the second one, is been removed together;

**Comment by Methemia** [comment]
did you fix it? I have the same problem

**Comment by heberholanda** [comment]
![image](https://user-images.githubusercontent.com/715547/95162117-467e8280-077b-11eb-9817-a8b01a8b753d.png)
It worked perfectly for me, client 12.40.
