### ISSUE TITLE
BUG npc PROMOTION (ALL)

### ISSUE THREAD

**Issue by ruanfurious** [opentibiabr/otservbr-global-archived#1421]
Npc Promotion nao responde ..

**Comment by dudantas** [comment]
> Npc Promotion nao responde ..

Hail queen, promote, yes?

**Comment by ruanfurious** [comment]
> > Npc Promotion nao responde ..
> 
> Hail queen, promote, yes?

Sorry  :P    funcionou ^^ Perfect

Remove post
