### ISSUE TITLE
charms no works

### ISSUE THREAD

**Issue by miguelshta21** [opentibiabr/otservbr-global-archived#1431]
well charms not working i have tried parry and nothing happens

**Comment by lBaah** [comment]
The charms are not scripted yet.

**Comment by miguelshta21** [comment]
> The charms are not scripted yet.

@lBaah i saw in canaryServer they have this charms scripts but i dont know how to move to this ot

**Comment by dudantas** [comment]
> > The charms are not scripted yet.
> 
> @lBaah i saw in canaryServer they have this charms scripts but i dont know how to move to this ot

the canary is totally different from here, in the next few weeks I’ll go up the bestiary and charm by cpp

**Comment by majestyotbr** [comment]
Repeated, #1297
