### ISSUE TITLE
[QUICKLOOT] isContainer

### ISSUE THREAD

**Issue by lucas-caminha** [opentibiabr/otservbr-global-archived#1432]
Hello, I receive this message several times in my distro. I couldn't find a solution. Maybe quickloot.lua is not finding isContainer (). Where can I find this function? 
![isContainer](https://user-images.githubusercontent.com/38120031/86517581-657a1b00-be00-11ea-9ed2-81758f714c29.png)

way: data/modules/scripts/quickloot/quickloot.lua
line 136

if thing:isContainer() then

**

**Comment by dudantas** [comment]
> Hello, I receive this message several times in my distro. I couldn't find a solution. Maybe quickloot.lua is not finding isContainer (). Where can I find this function?
> ![isContainer](https://user-images.githubusercontent.com/38120031/86517581-657a1b00-be00-11ea-9ed2-81758f714c29.png)
> 
> way: data/modules/scripts/quickloot/quickloot.lua
> line 136
> 
> if thing:isContainer() then
> 
> **

Test the quickloot in cpp: https://github.com/opentibiabr/otservbr-global/pull/1400
The quickloot per modules will soon be removed.
