### ISSUE TITLE
Premium account in store

### ISSUE THREAD

**Issue by eduardofacunha** [opentibiabr/otservbr-global-archived#1443]
**Describe the bug**
Premium days compradas no store não atualizam lastday no banco de dados

**To Reproduce**
1. vá para store
2. selecione premiuns
3. compre qualquer uma
4. saia do jogo, digite sua conta, ainda continuará free.

**Expected behavior**
Mostrar na tela do jogo premium account.

**Additional context**
Colocando um valor valido em lastday (account table) a premium aparece.

**Comment by eduardofacunha** [comment]
Eu resolvi mudando os codigos do servidor:
Arquivo = iologindata.cpp
Metodo = IOLoginData::addPremiumDays()

Linha modificada = query << "UPDATE `accounts` SET `premdays` = `premdays` + " << addDays << ", `lastday` = " << time(nullptr) << " WHERE `id` = " << accountId;

E recompilando o servidor.

**Comment by dudantas** [comment]
Você tem certeza? Eu corrigi esse bug.

**Comment by dudantas** [comment]
Tá usando a develop mais atual??

**Comment by eduardofacunha** [comment]
Quando eu baixei os codigos, foi pela default que é a develop, fiz isso há 1 semana atrás, se você disse que corrigiu vou fechar a issue.

**Comment by eduardofacunha** [comment]
Da uma olhada, na branch principal (develop)

https://github.com/opentibiabr/otservbr-global/blob/d78a9b9ef7af6050140e393c2c31faf8dfbaac10/src/iologindata.cpp#L1273

**Comment by dudantas** [comment]
Eu corrigi através da própria store. 
Aqui: https://github.com/opentibiabr/otservbr-global/commit/d9c4b99ab039a190f77dd7737d9703984836c8cd#diff-18db98e4b5bedf01e6b3e1a172dd4438

**Comment by eduardofacunha** [comment]
Puts cara... não acredito que to usando uma versão antiga, pqp...

Obrigado pela atenção

**Comment by dudantas** [comment]
> Puts cara... não acredito que to usando uma versão antiga, pqp...
> 
> Obrigado pela atenção

Mas você chegou a testar para confirmar que funciona? Embora eu tenha testado, mais um teste nunca é demais.

**Comment by eduardofacunha** [comment]
@dudantas Eu estou sem entender cara, serio mesmo, olhei meu historico de downloads, baixei a branch develop dia 29/06/20, tanto que o nome do zip que baixei é otserv-global-develop.zip, baixei outra branch e o nome do arquivo muda (não dei git clone, baixei pelo github mesmo), então em tese meu download deveria ter seu codigo, sendo que seu merge foi antes do meu download(2/06).

Eu testei o codigo que eu fiz e ele funcionou, vou testar o seu.

**Comment by eduardofacunha** [comment]
Agora eu entendi, saca só, eu copiei um codigo inteiro de um PR, sendo que o cara que fez o PR não estava com o codigo atualizado.

https://github.com/opentibiabr/otservbr-global/blob/cfec1ec56404d07ef0bdf0cf5d66e50cb0781c9d/data/modules/scripts/gamestore/init.lua#L1201

Aprendi uma lição hoje, nunca copie um arquivo de PR todo por preguiça de mudar apenas as linhas que precisam kkkk

**Comment by dudantas** [comment]
> Agora eu entendi, saca só, eu copiei um codigo inteiro de um PR, sendo que o cara que fez o PR não estava com o codigo atualizado.
> 
> https://github.com/opentibiabr/otservbr-global/blob/cfec1ec56404d07ef0bdf0cf5d66e50cb0781c9d/data/modules/scripts/gamestore/init.lua#L1201
> 
> Aprendi uma lição hoje, nunca copie um arquivo de PR todo por preguiça de mudar apenas as linhas que precisam kkkk


É que tipo... O pr dele não tá atualizado com a develop, aí vai entrar em conflito e antes de dar merge vamos resolver pra ficar igual. 
PR é sempre bom vc puxar de pouco mesmo, a não ser que seja um PR MUITO grande. kkkk

**Comment by gpedro** [comment]
as vezes correções são feitas durante o merge do PR. o ideal é atualizar o repositório toda semana
