### ISSUE TITLE
PREMIUM DAYS

### ISSUE THREAD

**Issue by ruanfurious** [opentibiabr/otservbr-global-archived#1444]
O player compra coins (vai pro char dele normal as coins)  ai ele vai na Store comprar premium days ate ai > (certinho)  premium days comprada mais quando ele vai olhar o char continua free.

**Comment by vitapng** [comment]
Já foi alterado isso

**Comment by eduardofacunha** [comment]
Cara, verifica se você baixou a branch develop mais recente, esse erro ai foi arrumado dia 2 de junho de 2020 nesse codigo aqui:

https://github.com/opentibiabr/otservbr-global/blob/d78a9b9ef7af6050140e393c2c31faf8dfbaac10/data/modules/scripts/gamestore/init.lua#L1023

**Comment by ruanfurious** [comment]
> Cara, verifica se você baixou a branch develop mais recente, esse erro ai foi arrumado dia 2 de junho de 2020 nesse codigo aqui:
> 
> https://github.com/opentibiabr/otservbr-global/blob/d78a9b9ef7af6050140e393c2c31faf8dfbaac10/data/modules/scripts/gamestore/init.lua#L1023


OBS: verifiquei aqui no meu ta do msm jeito que o code acima.

### function GameStore.processPremiumPurchase(player, offerId)
	db.query("UPDATE `accounts` SET `lastday` = ".. os.time() .." WHERE `id` = " .. player:getAccountId())
	player:addPremiumDays(offerId-3000)

**Comment by eduardofacunha** [comment]
Você tem que deslogar e logar novamente pra aparecer o premium.

Se mesmo assim não aparecer faz como eu fiz numa issue que abri ontem:

Eu resolvi mudando os codigos do servidor:
Arquivo = iologindata.cpp
Metodo = IOLoginData::addPremiumDays()

Linha modificada = query << "UPDATE `accounts` SET `premdays` = `premdays` + " << addDays << ", `lastday` = " << time(nullptr) << " WHERE `id` = " << accountId;

E recompilando o servidor.

_Originally posted by @eduardofacunha in https://github.com/opentibiabr/otservbr-global/issues/1443#issuecomment-656272855_

**Comment by ruanfurious** [comment]
vou tentar fazer isso valeu..

> Você tem que deslogar e logar novamente pra aparecer o premium.
> 
> Se mesmo assim não aparecer faz como eu fiz numa issue que abri ontem:
> 
> Eu resolvi mudando os codigos do servidor:
> Arquivo = iologindata.cpp
> Metodo = IOLoginData::addPremiumDays()
> 
> Linha modificada = query << "UPDATE `accounts` SET `premdays` = `premdays` + " << addDays << ", `lastday` = " << time(nullptr) << " WHERE `id` = " << accountId;
> 
> E recompilando o servidor.
> 
> _Originally posted by @eduardofacunha in [#1443 (comment)](https://github.com/opentibiabr/otservbr-global/issues/1443#issuecomment-656272855)_

olha no meu iologindata esta assim

### void IOLoginData::addPremiumDays(uint32_t accountId, int32_t addDays)
{
  std::ostringstream query;
  query << "UPDATE `accounts` SET `premdays` = `premdays` + " << addDays << " WHERE `id` = " << accountId;
  Database::getInstance().executeQuery(query.str());

so eu trocar essa linha do query por essa acima que vc passou neh

**Comment by eduardofacunha** [comment]
Exatamente

**Comment by ruanfurious** [comment]
> Exatamente

Deu certo amigo, valeu
*Perfect
