### ISSUE TITLE
PVP without activating.

### ISSUE THREAD

**Issue by ivansho92** [opentibiabr/otservbr-global-archived#1445]
in this last branch, if players stay in party, can make damage at members party, if you do some spell of attack, don't care if you opened or closed your hand.
In this example, these two players are in party and make damage with spells.
http://imgfz.com/i/8pVmPLo.png

**Comment by dudantas** [comment]
the server is retro-pvp, this is normal, isn't it?

**Comment by Tazer89** [comment]
> in this last branch, if players stay in party, can make damage at members party, if you do some spell of attack, don't care if you opened or closed your hand.
> In this example, these two players are in party and make damage with spells.
> http://imgfz.com/i/8pVmPLo.png

Enable it shall work i guess? In events/events.xml

```
<event class="Creature" method="onTargetCombat" enabled="0" />
<!-- removeCombatProtection on secure modes protection -->
```

**Comment by ivansho92** [comment]
> > in this last branch, if players stay in party, can make damage at members party, if you do some spell of attack, don't care if you opened or closed your hand.
> > In this example, these two players are in party and make damage with spells.
> > http://imgfz.com/i/8pVmPLo.png
> 
> Enable it shall work i guess? In events/events.xml
> 
> ```
> <event class="Creature" method="onTargetCombat" enabled="0" />
> 
> ```

yeah, fix with that xd

**Comment by dudztroyer** [comment]
Normal behaviour on retro-pvp
