### ISSUE TITLE
Gold pouch visual glitch when using the magic gold converter.

### ISSUE THREAD

**Issue by nickolasdeluca** [opentibiabr/otservbr-global-archived#1448]
**Describe the bug**
After the commits of July 6th, whenever you loot more then 100 gold and the magic converter is turned on, after converting the gold stays visually on your pouch and will only disappear when you loot more gold.

**To Reproduce**
1. Assign the gold to be looted to your gold pouch and have it opened.
2. Loot 50 gold.
3. Loot 100+ gold.
4. Check the gold pouch window, the 100 stack will be there and it doesn't even exist anymore. Sometimes the bug is even worse and it creates two stacks of the same amount of gold, even thou they both don't really exist.
5. Close the pouch and reopen it, the gold will not be there anymore and the converted gold will be there.

6. Also, the converted gold will be thrown in your default backpack, not your gold pouch, which I think it's also a bug. If that could be fixed as well it would be great.

**Expected behavior**
The conversion should happen visually as well, no matter how many gold I loot.

**Screenshots**
This is after I looted the 100+ gold and the magic converter converted the gold.
![gold_pouch_before_reopen](https://user-images.githubusercontent.com/17858166/87232416-3c740000-c395-11ea-8601-d23544bbe248.png)

This is after I reopened the gold pouch, you can see that the gold got properly converted.
As said in step number 6, the converted gold was thrown in my default backpack. Even thou all gold should be sent to my gold pouch.
![gold_pouch_after_reopen](https://user-images.githubusercontent.com/17858166/87232414-3bdb6980-c395-11ea-95e2-416c0a9d0c85.png)

**Additional context**
As I said in the beginning of the issue, this started happening after the commits of July 6th, so it might be worth investigating.

**Comment by attack787** [comment]
Hello, I did some tests and I found a problem with regroup the money in the gold pouch. Initially it seems that money is being cloned, but after closing and reopening the bag, the money is dispersed in the gold pouch.

**Comment by Tazer89** [comment]
Yes there is a bug its confirmed with latest update. Here is video of it.
https://geekbuddys.com/bug.mp4

When you relogging after, all money are back.. lol

**Comment by marcosvf132** [comment]
Can someone try the PR #1617? To check if the problem persist
