### ISSUE TITLE
Rate spawn in config.lua don't works.

### ISSUE THREAD

**Issue by attack787** [opentibiabr/otservbr-global-archived#1454]
**Describe the bug**
When I change the ratespawn in config.lua nothing happens.

**Steps to reproduce the behavior:**
1. First time I change the ratespawn for 10x, and test it, comparing with normal rate.
2. Second time, I change the ratepsawn for 20x, and test it again 
3. The time that respawn born is the same in first and second test comparing with normal rate.

**Expected behavior**
I expected that respawn to be more fast than normal rate.

I'm in doubt if this is a bug or there is another place to make this change.

**Comment by oalbsilva** [comment]
@Attack787  can u test pr #1455 ?
