### ISSUE TITLE
[Bug] - Fabricação de Ground Reed.

### ISSUE THREAD

**Issue by ruanfurious** [opentibiabr/otservbr-global-archived#1458]
Bug Ao fabricar Ground Reed, trigo nao vira o Ground Reed *Estou no sqm Exato para a fabricação* ( As outras tranformações funciona certinho )

Position da ação ->   32298, 31807, 7

Nesta posição clicando a esquerda na maquina de moinho usando esse item (id- 2694 ) para gerar esse item (id-36521)

**Comment by attack787** [comment]
Wrong information about who makes Ground Reed.

In order to get a bunch of reed, you need to cut Reed with a Scythe, a Machete, a Heavy Machete or a Secret Agent Tool. Use it with a Millstone to make Ground Reed.

**Comment by gpedro** [comment]
unconfirmed. on RL only flour returned.
