### ISSUE TITLE
Earth Shrine Feyrist - Wrong entry

### ISSUE THREAD

**Issue by attack787** [opentibiabr/otservbr-global-archived#1460]
**Is your feature request related to a problem? Please describe.**

The entrace for feyrist by Earth Shrine is wrong.

**Describe the solution you'd like**

In **data/scripts/actions/other/gem.lua**

Need to chance destination:
 {x = 33539, y = **32263**, z = 7} 

to destination:
 {x = 33539, y = **32209**, z = 7}

I don't know how to post the changes of scritps here. Sorry

**Comment by gpedro** [comment]
that's right. the pull request #1147 broke it

**Comment by gpedro** [comment]
can you test the PR #1463 ?

--

If you like our project, feel free to pay us a coffee, pizza or something else. Click here check donations methods: https://opentibiabr.github.io/donation
