### ISSUE TITLE
Access to Misguided (Cults of Tibia) - Water vortex without teleport coordinates

### ISSUE THREAD

**Issue by attack787** [opentibiabr/otservbr-global-archived#1465]
**Describe the bug**

Water vortex without teleport coordinates that takes access to Misguided (Cults of Tibia).

**To Reproduce**
to go:
water vortex Position: 32629, 32264, 8    ---> **teleport to**: 32499, 32331, 8.
to back:
water vortex Position:  Position: 32499, 32330, 8   --->  **teleport to**: 32630, 32264, 8.

**Expected behavior**
Access to Misguided (Cults of Tibia)

**Comment by gpedro** [comment]
confirmed.

**Comment by gpedro** [comment]
can you test the PR #1449?

--

If you like our project, feel free to pay us a coffee, pizza or something else. Click here check donations methods: https://opentibiabr.github.io/donation
