### ISSUE TITLE
Access to Boss The Unarmored Voidborn (Cults of Tibia) - Dimensional portal without teleport coordinates.

### ISSUE THREAD

**Issue by attack787** [opentibiabr/otservbr-global-archived#1466]
**Describe the bug**

The access to Boss The Unarmored Voidborn (Cults of Tibia) using dimensional portal dont's works.

**To Reproduce**
to go:
dimensional portal -  Position: 33168, 31930, 12. ---> **teleport** to: 33181, 31837, 15.
to back:
dimensional portal - Position: 33183, 31837, 15 ---> **teleport** to: 33169, 31930, 12.

**Comment by majestyotbr** [comment]
#726
