### ISSUE TITLE
Store Debug Client

### ISSUE THREAD

**Issue by whitecrixu** [opentibiabr/otservbr-global-archived#1468]
Hi After update to 12.20 Tibia Client 12.20 is debug when i I try open store. no any problem in console.

**Comment by majestyotbr** [comment]
We already know about this, the new store will be released soon, but thanks for your report.

**Comment by cys9211** [comment]
When can we expect a new store?

**Comment by majestyotbr** [comment]
When it's ready.

**Comment by whiteprojectcrixu** [comment]
I give code when I back home :) is work on 12.20

**Comment by cys9211** [comment]
Thanks Man

**Comment by cys9211** [comment]
> I give code when I back home :) is work on 12.20

Can u give?

**Comment by whiteprojectcrixu** [comment]
Yes I send code for majesty project but he not update yet. If you wan write for my email. white.project.ots@gmail.com

**Comment by majestyotbr** [comment]
Where did you sent? Why are you mentioning me here? I'm not the only one responsible for the project.

**Comment by whiteprojectcrixu** [comment]
Ok I'm sorry ;) I think this you project.

**Comment by majestyotbr** [comment]
The gamestore.lua used is outdated than the repository. If someone wants a temporary store working, it's better to use from this PR: https://github.com/opentibiabr/otservbr-global/pull/1381/files

**Comment by Meth28** [comment]
> The gamestore.lua used is outdated than the repository. If someone wants a temporary store working, it's better to use from this PR: https://github.com/opentibiabr/otservbr-global/pull/1381/files

unwrap does not work

**Comment by cys9211** [comment]
Category cosmetics no work

**Comment by MajestyOTBR** [comment]
> > The gamestore.lua used is outdated than the repository. If someone wants a temporary store working, it's better to use from this PR: https://github.com/opentibiabr/otservbr-global/pull/1381/files
> 
> unwrap does not work

Look gerotib comment and revert the line of code about wrap/unwrap

> Category cosmetics no work
Configure it.

**Comment by majestyotbr** [comment]
> > The gamestore.lua used is outdated than the repository. If someone wants a temporary store working, it's better to use from this PR: https://github.com/opentibiabr/otservbr-global/pull/1381/files
> 
> unwrap does not work

Look gerotib comment and revert the line of code about wrap/unwrap

> Category cosmetics no work

Configure it.

**Comment by majestyotbr** [comment]
https://github.com/opentibiabr/otservbr-global/commit/ccae88243ef344b56679e8988a2086c6e32bf2a4

**Comment by majestyotbr** [comment]
https://github.com/opentibiabr/otservbr-global/commit/dbf2ab2508a29c87e68ed6f20123e51c8ef2295e

**Comment by majestyotbr** [comment]
https://github.com/opentibiabr/otservbr-global/commit/a6ef1ce0d3b95f8ac111e4a5aab8fab524257ec8

**Comment by majestyotbr** [comment]
Follow updated repo: https://github.com/opentibiabr/otservbr-global/commits/develop
