### ISSUE TITLE
Account not found

### ISSUE THREAD

**Issue by Mortalot** [opentibiabr/otservbr-global-archived#1471]
![accountnotfound](https://user-images.githubusercontent.com/66652015/87474141-9f150800-c5f0-11ea-86a6-22a5d54993a9.png)

updated and suddenly accounts aren't working. they work on un-updated version.

**Comment by majestyotbr** [comment]
Are you using the correct login.php? They were updated to login on protocol 12.20.

GesiorAAC: https://github.com/opentibiabr/gesioraac-tibia12-login/releases/tag/1.1
MyAAC: https://github.com/opentibiabr/myaac-tibia12-login/releases/tag/1.4

Client 12.20: 
https://forums.otserv.com.br/index.php?/forums/topic/167933-otservbr-global-cliente-tibia-12/

**Comment by Mortalot** [comment]
i see. now we have to use our emails to login.

**Comment by majestyotbr** [comment]
Yes.

**Comment by Mortalot** [comment]
is there an updated myaac without the account name?

**Comment by Luizianho** [comment]
How to change email to name for login to game?
