### ISSUE TITLE
Report system (ctrl + z)

### ISSUE THREAD

**Issue by Meth28** [opentibiabr/otservbr-global-archived#1487]
meus jogadores tentaram denunciar usando (Ctrl + Z), mas os reports não aparecem
eu fiz um teste e, na minha conta da ADM, se possível, em todos os meus personagens, mas se for uma nova conta, como jogador, não é possível fazer reports

**Comment by attack787** [comment]
I have the same problem, the reports only work for gods

**Comment by dudantas** [comment]
It's limitation in the source.

**Comment by Meth28** [comment]
players who have a tutor account can make reports
i think that a quick solution would be account tutor to players

**Comment by joseluis2g** [comment]
you can just change this lines
https://github.com/opentibiabr/otservbr-global/blob/develop/src/protocolgame.cpp#L2777-L2782
