### ISSUE TITLE
Hireling: exercise's and player invite (house)

### ISSUE THREAD

**Issue by Meth28** [opentibiabr/otservbr-global-archived#1492]
https://imgur.com/YiRPSyB
quando você compra, com o Hireling você recebe apenas 1 carga

**Comment by Meth28** [comment]
I found another bug, it is not possible to invite all players by adding * to the list

**Comment by majestyotbr** [comment]
According to the wiki, hirelings does not sell exercise weapons.
House fix: https://github.com/opentibiabr/otservbr-global/commit/8eeebe7060e48d365a6c044a43793bda42f9b785
