### ISSUE TITLE
white skull not work

### ISSUE THREAD

**Issue by antonioaraujo664** [opentibiabr/otservbr-global-archived#1504]
https://github.com/opentibiabr/otservbr-global/commit/0dcf45afae3a3889c2af37d8e20920b1f516b116

With this update here, the white skull doesn't work

**Comment by dudantas** [comment]
Ok, vou subir a correção..

**Comment by dudantas** [comment]
Revertido no https://github.com/opentibiabr/otservbr-global/commit/41caf0c68b7021b9b04afd3d996d7f34c3529cda
