### ISSUE TITLE
Docker and docker-compose

### ISSUE THREAD

**Issue by lucascebertin** [opentibiabr/otservbr-global-archived#152]
I have dockerized another otxserver fork a few months ago.

Do you guys would like to have some kind of automation on this repo?

Probably I can send a pull request with this.

**Comment by gpedro** [comment]
LGTM. Feel free to send PR xD. almost users will not use, but it's an interesting tool to use

**Comment by Costallat** [comment]
@lucascebertin 

I would like to see it, I am also working with docker to help building and running the server without needing to change the host OS.
