### ISSUE TITLE
containers cannot be thrown on the floor

### ISSUE THREAD

**Issue by marlon36** [opentibiabr/otservbr-global-archived#1525]
I am using develop branch, and builds 1.0.1124 and console throws this error 

"Lua Script Error: [Event Interface]
data / events / scripts / player.lua: Player @ onMoveItem
data / events / scripts / player.lua: 433: 'for' initial value must be a number
stack traceback:
        [C]: at 0x7ff729bdce10
        data / events / scripts / player.lua: 433: in function <data / events / scripts / player.lua: 329> "

It happens when you want to throw a backpack on the floor or a parcel to the mailbox, try the bags and crates and the same thing happens

**Comment by majestyotbr** [comment]
You are using a build from a pull request. The build that correspond the updated commit with changes in the source of branch develop is 1.0.1117.
https://ci.appveyor.com/project/opentibiabr/otservbr-global/builds/34185280 (Configuration: Release).

**Comment by majestyotbr** [comment]
You can find the builds in:
https://ci.appveyor.com/project/opentibiabr/otservbr-global/history
