### ISSUE TITLE
carpets not working

### ISSUE THREAD

**Issue by perron5306987** [opentibiabr/otservbr-global-archived#1532]
**Describe the bug**
As the title says, some carpets do not extend as they should and are placed in scripts / actions / other / carpets

Carpets id
26366
26089
27085
29388
26363
26369
29390
27088
26367
27084
27087
26368
26376
29354
27090
27089
29352
27091
29357
27086
29350
29387
26088
29359
26087

**Comment by majestyotbr** [comment]
Did you tested inside a house?
![image](https://user-images.githubusercontent.com/32709570/88226864-21ca4280-cc43-11ea-8697-d3b5dc68bd3f.png)

Issue unconfirmed.
