### ISSUE TITLE
Recompensas de Chest invertidas

### ISSUE THREAD

**Issue by LIKEAHYENA** [opentibiabr/otservbr-global-archived#1533]
**Describe the bug**

A recompensa de dois chests estão **invertidas**. Não sei se já foi reportado, mas here we go:

Chest: (32939, 31776, 9)  está dando Orc Powder (item da Explorer Society Quest)
Chest: (32967, 31719, 2) está dando Wolf Tooth Chain (Ceiron's), item do Druid Outfit Quest.

**Comment by majestyotbr** [comment]
#726
