### ISSUE TITLE
own more than 1 house

### ISSUE THREAD

**Issue by Mortalot** [opentibiabr/otservbr-global-archived#1538]
in real tibia you can own up to 3 houses.
if you own more than 1 house in the ot, you can't open any of the store deco. not even in your first house.

**Comment by oualid6496** [comment]
No you can't? Unless this has been updated recently but I doubt that. Every character can only own 1 house. I think you mean that there is a maximum of 3 houses per account on real tibia. On this ot im pretty sure you can have unlimted houses per account but only 1 per character.

**Comment by Mortalot** [comment]
yeah you can buy more than 1 house per character in rl tibia.

**Comment by Geekbuddy** [comment]
Please note that since November 19, 2019 up to three houses per world per account are permitted

https://tibia.fandom.com/wiki/House

Only 1 house for each character.
