### ISSUE TITLE
mirror true asuras

### ISSUE THREAD

**Issue by Mortalot** [opentibiabr/otservbr-global-archived#1540]
![trued](https://user-images.githubusercontent.com/66652015/88345208-7f2dc480-cd13-11ea-9882-4c775f7f1cae.png)

the mirror to get to true asuras is not working. also they have new addons to their outfits.
https://tibia.fandom.com/wiki/True_Dawnfire_Asura

**Comment by EleanorRigby1** [comment]
It works. Check that you are level 250
