### ISSUE TITLE
Demon Helmet TP crashing the server

### ISSUE THREAD

**Issue by FRReinert** [opentibiabr/otservbr-global-archived#1545]
**Describe the bug**
Server crash when using the TP inside the Demon Helmet Room

**To Reproduce**
1. Go to Demon Helmet Room
2. Use the lever to remove the rock and show the exit teleport
3. Enter the teleport

**Expected behavior**
Should take you near of the entry TP

Server
 - OS: Ubuntu Server 20.04 LTS

** I don't have the error log right away, but i'll atach it as soon as possible. anyway, you can follow the steps to reproduce the issue.

**Comment by dudantas** [comment]
You need to inform the positions ..

**Comment by Geekbuddy** [comment]
> You need to inform the positions ..

Its confirmed. When you are finish with the quest and going in to the teleport its crashes the server.

```
02:35 You see a magic forcefield.
Item ID: 1387
Client ID: 1949
Position: 33316, 31574, 15
```
It has the same destination as where it shall spawn. Thats why.

teleport:setDestination({x = 33316, y = 31574, z = 15})
