### ISSUE TITLE
Paw and Fur Tasks - Only one kill needed to end the task.

### ISSUE THREAD

**Issue by FRReinert** [opentibiabr/otservbr-global-archived#1547]
**Describe the bug**
Paw and Fur tasks only need one kill of the hunted monster to complete the mission. 
I tried with Carniphilas and Tarantulas, in both situations, i only had to kill one single monster to complete the task

**To Reproduce**
1. Join Paw and Fur
2. ask for a Task
3. Kill one monster of the task
4. Check your quest log

Client 
- Protocol 12
- Windows 10

Server
- Ubuntu Server 20.04 LTS

**Comment by tyndy125** [comment]
have you tried it with a god account or with a normal account? because in god accounts, even if the player does not have any permission, the system detects that it is a test and automatically generates the rest of the kills.

**Comment by FRReinert** [comment]
i have a GOD in the same account. 
i'll create a new account/player try again and let you know!

**Comment by tyndy125** [comment]
> i have a GOD in the same account.
> i'll create a new account/player try again and let you know!

Do you try that? We need your answer for close the inssue

**Comment by majestyotbr** [comment]
Test with a normal character.
