### ISSUE TITLE
exp stage and skill stage

### ISSUE THREAD

**Issue by Meth28** [opentibiabr/otservbr-global-archived#1567]
https://imgur.com/a/490q2qK
1.-xp bug
My players have reported that sometimes when you are hunting, the experience bugs and you start receiving x1 even if at your level you should receive x400.
2.- skills bug

in this bug there are 2 bugs?
bug 1.- every time you upload the skill, you appear with 1% to the next skill. (for example) you are with 1% to go to skill 50, when you go to 51 you appear with 1% for 52
bug 2.- Some players have told me that when they are skilleando they appear with the whole bar full saying -1000% and no matter how many hours pass, they can't get out of there

**Comment by thatmichaelguy** [comment]
I have experienced the first "bug", but only after reloading libs. It would happen if you use `/reload all` too

**Comment by Geekbuddy** [comment]
This happens with otcv8 client not with normal tibia client so this has nothing with the server to do.

**Comment by majestyotbr** [comment]
Thanks for the answer @thatmichaelguy and @Geekbuddy.
