### ISSUE TITLE
autoloot

### ISSUE THREAD

**Issue by thalesandrei** [opentibiabr/otservbr-global-archived#16]

**Comment by thalesandrei** [comment]
Estou com problema na parte do autoloot

**Comment by dudantas** [comment]
Não há autoloot na source, até amanhã eu subirei na source as funções. Tirei as imagens por conter partes de outros fóruns  e nosso projeto é apoiado pelo otserv.br

#Edit 
Autoloot agora está funcional.

**Comment by htc16** [comment]
Olá, foi colocado autoloot?
