### ISSUE TITLE
Problem with client login

### ISSUE THREAD

**Issue by whiteprojectcrixu** [opentibiabr/otservbr-global-archived#1602]
Hi after update 12.40 when i try login for client i see problem.
![DeepinScreenshot_20200730112618](https://user-images.githubusercontent.com/68076133/88906693-0a4d1400-d258-11ea-94f2-818f0c363540.png)
i download and update accmaker and download client 12.40 official support by otservbr global rl

**Comment by ghost** [comment]
Are you using the `127.0.0.1_client.exe`?
Did you install the `login.php` file on your aac website?

If I'm not mistaken, this error occurs when Tibia client can't connect to your `loginWebService`.

**Comment by cys9211** [comment]
GesiorAAC: https://github.com/opentibiabr/gesioraac-tibia12-login/releases/tag/1.1
MyAAC: https://github.com/opentibiabr/myaac-tibia12-login/releases/tag/1.4

**Comment by gpedro** [comment]
this error looks like a problem on your login.php;

**Comment by whiteprojectcrixu** [comment]
I used  update file from otservbr I'm not new with that. I update all files.

**Comment by ghost** [comment]
Could you please upload in here your `login.php` and your client executable?
This way we can try to figure out what's wrong and help you.

**Comment by whiteprojectcrixu** [comment]
Now I'm not in home I upload later.

**Comment by ghost** [comment]
No problem, as soon as you do we'll be able to help you.

And just to be sure: did you download and replaced/updated all files, right? Not just the server executable.
Because I have the latest server branch on my computer and I don't have these *warnings* and *duplicate unique id* messages you're getting on server console.

**Comment by whiteprojectcrixu** [comment]
This warning and duplicate is from myself. But this is not problem

**Comment by whiteprojectcrixu** [comment]
Login.php
`<?php
require_once('common.php');
require_once('config.php');
require_once('config.local.php');
require_once(SYSTEM . 'functions.php');
require_once(SYSTEM . 'init.php');
require_once(SYSTEM . 'status.php');

# error function
function sendError($msg){
	$ret = [];
	$ret["errorCode"] = 3;
	$ret["errorMessage"] = $msg;
	die(json_encode($ret));
}

$request = file_get_contents('php://input');
$result = json_decode($request);
$action = isset($result->type) ? $result->type : '';

switch ($action) {
	case 'cacheinfo':
		die(json_encode([
			'playersonline' => $status['players'],
			'twitchstreams' => 0,
			'twitchviewer' => 0,
			'gamingyoutubestreams' => 0,
			'gamingyoutubeviewer' => 0
		]));
	break;
	
	case 'eventschedule':
		die(json_encode([
			'eventlist' => []
		]));
	break;

	case 'boostedcreature':
		die(json_encode([
			'boostedcreature' => false,
		]));
	break;

	case 'login':
	
		$port = $config['lua']['gameProtocolPort'];
	
		// default world info
		$world = [
			'id' => 0,
			'name' => $config['lua']['serverName'],
			'externaladdress' => $config['lua']['ip'],
			'externalport' => $port,
			'externaladdressprotected' => $config['lua']['ip'],
			'externalportprotected' => $port,
			'externaladdressunprotected' => $config['lua']['ip'],
			'externalportunprotected' => $port,
			'previewstate' => 0,
			'location' => 'BRA', // BRA, EUR, USA
			'anticheatprotection' => false,
			'pvptype' => array_search($config['lua']['worldType'], ['pvp', 'no-pvp', 'pvp-enforced']),
			'istournamentworld' => false,
			'restrictedstore' => false,
			'currenttournamentphase' => 2
		];

		$characters = [];
		$account = null;
		
		// common columns
		$columns = 'name, level, sex, vocation, looktype, lookhead, lookbody, looklegs, lookfeet, lookaddons, deletion, lastlogin';
		
		$account = new OTS_Account();
		$account->findByEmail($result->email);
		$config_salt_enabled = fieldExist('salt', 'accounts');
		$current_password = encrypt(($config_salt_enabled ? $account->getCustomField('salt') : '') . $result->password);

		if (!$account->isLoaded() || $account->getPassword() != $current_password) {
			sendError('Email or password is not correct.');
		}

		$players = $db->query("select {$columns} from players where account_id = " . $account->getId())->fetchAll();
		foreach ($players as $player) {
			$characters[] = create_char($player);
		}

		$worlds = [$world];
		$playdata = compact('worlds', 'characters');
		$session = [
			'sessionkey' => "$result->email\n$result->password",
			'lastlogintime' => (!$account) ? 0 : $account->getLastLogin(),
			'ispremium' => (!$account) ? true : $account->isPremium(),
			'premiumuntil' => (!$account) ? 0 : (time() + ($account->getPremDays() * 86400)),
			'status' => 'active', // active, frozen or suspended
			'returnernotification' => false,
			'showrewardnews' => true,
			'isreturner' => true,
			'fpstracking' => false,
			'optiontracking' => false,
			'tournamentticketpurchasestate' => 0,
			'emailcoderequest' => false
		];
		die(json_encode(compact('session', 'playdata')));
	break;
	
	default:
		sendError("Unrecognized event {$action}.");
	break;
}

function create_char($player) {
	global $config;
	return [
		'worldid' => 0,
		'name' => $player['name'],
		'ismale' => intval($player['sex']) === 1,
		'tutorial' => false, //intval($player['lastlogin']) === 0,
		'level' => intval($player['level']),
		'vocation' => $config['vocations'][$player['vocation']],
		'outfitid' => intval($player['looktype']),
		'headcolor' => intval($player['lookhead']),
		'torsocolor' => intval($player['lookbody']),
		'legscolor' => intval($player['looklegs']),
		'detailcolor' => intval($player['lookfeet']),
		'addonsflags' => intval($player['lookaddons']),
		'ishidden' => intval($player['deletion']) === 1,
		'istournamentparticipant' => false,
		'remainingdailytournamentplaytime' => 0
	];
}`

**Comment by whiteprojectcrixu** [comment]
login.php
[https://docs.google.com/document/d/1sL2aYouen1dxJI2s101Cz0DNpjsQKqz_yTU2ZJoxFJE/edit?usp=sharing](url)

**Comment by Geekbuddy** [comment]
It works as it should so this problem can be closed.

**Comment by nickolasdeluca** [comment]
You can close your own issue. Or wait till an admin does.

**Comment by Geekbuddy** [comment]
> You can close your own issue. Or wait till an admin does.

Yeah i know but, this issue has been tested of me now and it works without problems. I guess the issues here is only for the project and not for personal issues that can't be handle of them self? Or i may have wrong about it.

**Comment by majestyotbr** [comment]
This is a problem in your side, verify your configurations.

**Comment by whiteprojectcrixu** [comment]
ok thank you i find problem in my login.php
***CLOSED***
