### ISSUE TITLE
Threatened Dreams Quest

### ISSUE THREAD

**Issue by Briluxxx** [opentibiabr/otservbr-global-archived#1606]
https://tibia.fandom.com/wiki/Threatened_Dreams_Quest
reward:
Access to Feyrist, Butterfly Ring, 5 Ancient Coins, 5 Rainbow Quartzes, **Blossom Bag, Shining Sun Catcher, Lit Moon Mirror, Gleaming Starlight Vial and Swan Feather Cloak.**

this quest is missing

**Comment by majestyotbr** [comment]
duplicated.
#726
