### ISSUE TITLE
Attack spells - Damage with arrows + bolts

### ISSUE THREAD

**Issue by matheuspergher** [opentibiabr/otservbr-global-archived#1618]
## CAUTION: OUR SERVER IS UPDATED DAILY. MAKE SURE YOU ARE REPORTING SOMETHING ON THE LATEST VERSION OF THE SERVER.

**Describe the bug**

**To Reproduce**
Note: include any configuration/script required to reproduce.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows] Windows 10 Pro

**Additional context**

Hey guys,

I just notice at my server, when you are using arrows or bolts, the attack spells are not correct, for example, an exori gran with an infernal bolt strip 40, 50 and an exori gran with a normal spear strip 500 +. Make several tests, change or items.xml file with the original, I changed the char, bolt, arrow but could not identify the source of the problem. Also I have replaced the orignal files for spells and vacations, but not great.

Has anyone seen this and know how to solve?

Cheers

**Comment by majestyotbr** [comment]
Why did you closed the issue without a comment?

**Comment by matheuspergher** [comment]
> Why did you closed the issue without a comment?

Sorry, I "solved" the problem. It was related with a lvlup reward, not original from the server. 

Just closed to avoid people spending energy here.

**Comment by majestyotbr** [comment]
Ok, thanks.
