### ISSUE TITLE
Crystal Sword change to Golem Wrench

### ISSUE THREAD

**Issue by cys9211** [opentibiabr/otservbr-global-archived#1619]
You cannot change the Crystal Sword into Golem Wrench in the Telas House

![image](https://user-images.githubusercontent.com/7588103/89270257-625e8e80-d63b-11ea-9a18-b28a5fa221d8.png)

**Comment by cys9211** [comment]
I found a solution #1626 & #1627

**Comment by majestyotbr** [comment]
#726 Quests that need to be developed or revised.

Next time, follow the issue template and explain better the issue to avoid waste time to guess what it is.
