### ISSUE TITLE
XP boost can only be used 1x per day.

### ISSUE THREAD

**Issue by attack787** [opentibiabr/otservbr-global-archived#1625]
The XP boost can only be used 1x per day, contrary to global that can use 5x. After use 1x XP boost shows this message when you try to buy it for second time (The product is currently not available for this character. See the Buy button tooltip for details.)

In global it can be bought in the Store 5 times in a day. The first XP boost is bought for 30 Tibia Coins, the second one for 45 Tibia Coins, the third one for 90 Tibia Coins, the fourth one for 180 Tibia Coins and the fifth one for 360 Tibia Coins.

**Comment by MajestyOTBR** [comment]
![image](https://user-images.githubusercontent.com/32709570/89580287-7c4ecb80-d80b-11ea-8e80-c0fe23b63bf3.png)

**Comment by FakeShinoda** [comment]
It's working. You cannot stack bonusses. So, you need to finish the current bonus to buy another.

**Comment by yatozin** [comment]
its not working can only buy 1 per day
