### ISSUE TITLE
Cliente 10 debug on login

### ISSUE THREAD

**Issue by cocaocla** [opentibiabr/otservbr-global-archived#1655]
hello there is a problem with client 10, there are debugs when trying to log into the game

**Comment by marcosvf132** [comment]
I think this base doesn't work with client 10 anymore.

**Comment by cocaocla** [comment]
hmm, why share this? then

**Comment by marcosvf132** [comment]
12.40 ??

**Comment by MajestyOTBR** [comment]
To use with Object Builder, Item Editor and RME.

**Comment by majestyotbr** [comment]
Because we use the Tibia.dat and Tibia.spr with Object Builder, Item Editor and RME.
