### ISSUE TITLE
Bug with Heal of Gaz'haragoth 

### ISSUE THREAD

**Issue by attack787** [opentibiabr/otservbr-global-archived#1657]
When Gaz'haragoth is spawned by raid or summoned by god this error happens:

```[Warning - Monster::Monster] Unknown event name: GazharagothHeal```

Healing don't works after this.

**Comment by gpedro** [comment]
case sensitive problem. can you try to fix, test and send a PR?
https://github.com/opentibiabr/otservbr-global/blob/649e714cfaa76d5b0a5e5fd3632fb7ea012bb737/data/creaturescripts/creaturescripts.xml#L4

**Comment by attack787** [comment]
Its works. I can't make PR because I need learn how github works. Thanks
