### ISSUE TITLE
vortex not teleporting

### ISSUE THREAD

**Issue by Raphaellb** [opentibiabr/otservbr-global-archived#166]
**Describe the bug**
Cults of Tibia misguided teleport not working

**To Reproduce**
1. Go to 
'08:39 You see a water vortex.
It draws you nearer.
Item ID: 24762
Position: 32629, 32264, 8
2. Click on 'walk on vortex'
nothing happens

**Expected behavior**
should teleport player to 
08:38 You see shallow water.
Item ID: 4625
Position: 32499, 32332, 8

same thing on way back. the following vortex 
08:42 You see a water vortex.
It draws you nearer.
Item ID: 24762
Position: 32499, 32330, 8

should teleport player to 
08:43 You see shallow water.
Item ID: 4620
Position: 32629, 32265, 8

This way the player can continue the Cults of Tibia quest.

**Comment by dudantas** [comment]
Fixed, thanks for your report. 
Issue closed
