### ISSUE TITLE
The Thieves Guild Quest / Bug na missão 4 e 6 

### ISSUE THREAD

**Issue by antonioaraujo664** [opentibiabr/otservbr-global-archived#1663]
**Missão 5.**

![image](https://user-images.githubusercontent.com/16484533/90305360-2bd50f00-de98-11ea-83ce-309f2ccc9d35.png)

Essa porta ta com uma storage desatualizada gravada no mapa 

	ThievesGuild = {
		-- Reserved storage from 515206 - 51409
		Quest = 515206,
		Mission01 = 515207,
		Mission02 = 515208,
		Mission03 = 515209,
		**Mission04 = 51394,**

No caso o correto seria 51394, para poder abrir a porta. Precisa editar o mapa. 

MISSÃO O6

![image](https://user-images.githubusercontent.com/16484533/90305396-a56cfd00-de98-11ea-8ffb-8787c13c59e2.png)

A chave que eu consegui obter pelo NPC Chantalle, deveria me teletransportar para dentro da sala, e depois desaparecer. 
O que acontece é que a porta não abre. Ficando impossuível concluir a missão. 
A tal Action ID gravada na porta é 51394, que liga a storage da missão 4, porém não fez sentido, acho que fizeram uma confusão. 
Se fosse para abrir concluindo a missão 4, seria impossível por esse tipo de porta.  

Ah... todo resto funciona, testei a quest toda. Uma delicia!

**Comment by dudantas** [comment]
Isso está relacionado a reorganização das storages. Fiz isso há uns meses e provavelmente bugou as doors. Vou dar uma olhada, valeu pelo report.
