### ISSUE TITLE
Svargrond Arena Quest BUG

### ISSUE THREAD

**Issue by whitecrixu** [opentibiabr/otservbr-global-archived#1664]
Hi ho i found bug with svargrond arena.
```
13:58 Halvar: Hello competitor! Do you want to fight in the arena or shall I explain the rules first?
13:58 Crixu [1]: fight
13:58 Halvar: You've already completed the arena in all difficulty levels.
13:58 Crixu [1]: mission
13:58 Halvar: Well I would rather call it an Ultimate Challenge than a mission.
13:58 Crixu [1]: Ultimate Challenge
13:58 Halvar: You've already completed the arena in all difficulty levels.
```
![DeepinScreenshot_20200815135521](https://user-images.githubusercontent.com/63555106/90311837-aa18cc00-deff-11ea-8e2f-75d09792d433.png)
![DeepinScreenshot_20200815135531](https://user-images.githubusercontent.com/63555106/90311838-ab49f900-deff-11ea-8ac7-19c5b08b7bb6.png)

**Comment by majestyotbr** [comment]
About NPC Halvar of Svargrond Arena, was reported in #1610. About the images, make sure you are using updated repository.
Next time, use the issue template.
