### ISSUE TITLE
Bug in prey.

### ISSUE THREAD

**Issue by ivansho92** [opentibiabr/otservbr-global-archived#1668]
you can use prey card, works fine, but if you're offline or using a bed, when you get online again, loose the prey time and therefore the player his money

**Comment by attack787** [comment]
This don'ts happens here. I get prey and I put the char sleeping for 9 hours and prey continues at same time. Can you be more specific with the error? When you go to report use templete issue.

![image](https://user-images.githubusercontent.com/47985212/90663527-2bce6980-e220-11ea-8485-bcc891fcbe66.png)

**Comment by FakeShinoda** [comment]
Ivasho and your bugs...
