### ISSUE TITLE
error compilando

### ISSUE THREAD

**Issue by vancinis** [opentibiabr/otservbr-global-archived#1673]
## CAUTION: OUR SERVER IS UPDATED DAILY. MAKE SURE YOU ARE REPORTING SOMETHING ON THE LATEST VERSION OF THE SERVER.

**Describe the bug**
problemas al compilar servidor en ubuntu 20.04 

**To Reproduce**
realice todos los pasos necesarios para compilar el servidor, como lo dice la wiki.

**Expected behavior**

**Screenshots**
<img width="838" alt="2020-08-17_21h39_26" src="https://user-images.githubusercontent.com/33733355/90460647-501c3000-e0d2-11ea-829b-cdf677dbdc6d.png">

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version: 20.04

**Comment by Costallat** [comment]
![1597719408](https://user-images.githubusercontent.com/1304176/90465246-5a93f500-e0e5-11ea-9e0d-5c4830e0b106.png)

**Comment by majestyotbr** [comment]
https://github.com/opentibiabr/otservbr-global/wiki/Compiling-on-Ubuntu-16.04,-18.04,-20.04
