### ISSUE TITLE
Server is locking when player logout

### ISSUE THREAD

**Issue by attack787** [opentibiabr/otservbr-global-archived#1682]
**Describe the bug**
Server is locking when player logout. If player makers spam logging in/logging out this locking the server. 
**To Reproduce**
1. You need two player to test this bug
2. First player start login/logout making spam
3. Second player test  locking

Note:  The problem is when player makes logout, this makes locking server. I download today the base of last commit to make this test.

**Expected behavior**
Server doesn't  locking when players leave the server

**Desktop (please complete the following information):**
 Windows 10

**Comment by enzerah** [comment]
what u mean by "locking" ?

**Comment by attack787** [comment]
crashing (little freezing for milliseconds). if more players do this together it increases the time of freezing.

**Comment by attack787** [comment]
Note: fixed bug.

Crashes happened because of Xampp, changing the program I solved the problem.
