### ISSUE TITLE
Exercise Training 'stopaction'

### ISSUE THREAD

**Issue by dracoalv** [opentibiabr/otservbr-global-archived#1694]
**Describe the bug**
char doesnt stop action training when move or cast any spell.

**To Reproduce**
1. Start training with exercise item.
2. Cast spells or any action like move and back to position sqm. 

**Expected behavior**
must be stop training when make any action (except conversations).
he only stop when the training hit its realized by another sqm.

**Video link on Youtube demonstration**
https://youtu.be/Emtxp1-Esk0

**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu]
 - Version: [e.g. 16.04]

**Comment by majestyotbr** [comment]
https://github.com/opentibiabr/otservbr-global/blob/develop/data/scripts/actions/other/exercise_training.lua

Tested, it's ok now.
