### ISSUE TITLE
Player@onStorageUpdate

### ISSUE THREAD

**Issue by Briluxxx** [opentibiabr/otservbr-global-archived#1695]
Lua Script Error: [Event Interface]
data/events/scripts/player.lua:Player@onStorageUpdate
data/lib/core/quests.lua:5436: attempt to compare number with nil

Lua Script Error: [Event Interface]
data/events/scripts/player.lua:Player@onStorageUpdate
data/lib/core/quests.lua:5436: attempt to compare number with nil

**Comment by dudantas** [comment]
Use the issue template. An issue with no explanation of how to reproduce it for later correction is useless ...

It is probably a bug generated by you only, are you trying to add storages in the login to free access?

Remember, we don't guess, we need clues to investigate any errors.
