### ISSUE TITLE
Scarlett Etzel

### ISSUE THREAD

**Issue by dracoalv** [opentibiabr/otservbr-global-archived#1696]
Scarlett Etzel Mechanics dot not work correctly.
1 - When use avalanche cause hit avalanche + 7500.
2 - Mirror's stay where u left it later u freeze and hit scarlett..

**Describe the solution you'd like**
1 - Hitpoint's damage should be 7500 only.
2 - Mirror should be rotate randomly after action of freezing the boss

**Comment by dudantas** [comment]
Added to #726
