### ISSUE TITLE
Inconsistencies in "Killing in the Name of..." quest implementation

### ISSUE THREAD

**Issue by Rezn1** [opentibiabr/otservbr-global-archived#1706]
**data/lib/core/quests.lua** and **data/lib/quests/killing_in_the_name_of.lua** differs in the way they handle _Killing in the Name of..._ quest. 

**killing_in_the_name_of.lua** defines the following values: 
```QUESTSTORAGE_BASE = 1500
JOIN_STOR = 100157
KILLSSTORAGE_BASE = 65000
REPEATSTORAGE_BASE = 48950
POINTSSTORAGE = 2500
```
It's a simple convention. The quest state (open or finished) is stored in `QUESTSTORAGE_BASE + taskId`, kill count in `KILLSSTORAGE_BASE + taskId` and number of repeats in `REPEATSTORAGE_BASE + taskId`. The taskId is quest's index in the `tasks` table.

**quests.lua** mostly ignores that.
The issue with that can be seen in the following missions:

- _Edron City - Elite Hunting: Trolls_ stored in `Quests[14][36]` have `storageid = 1501` and description takes kill count from `player:getStorageValue(1501)` (should be 65001)
- _Paw and Fur: Necromancers and Priestess_ in  `Quests[14][39]` have `storageid = 65001` (should be 1550) and description kill count `player:getStorageValue(65001)` (should be 65050)
- _Edron City - Elite Hunting: Goblins_ (`Quests[14][37]`) - `storageid = 1502`, `player:getStorageValue(1502)` (65002)
- _Paw and Fur: Minotaurs_ (`Quests[14][38]`) - `storageid = 65002` (1549), `player:getStorageValue(65002)` (65049)

The other mission all have correct descriptions, but all their storageid are set to their kill count storage.

The fix for minotaurs and necromancers tasks is obvious, what I'm trying to highlight here is issue with what a quest storageid should be. 

`QUESTSTORAGE_BASE` looks like a proper choice, it stores the quest status. The problem is it doesn't work with current quest tracker. 
The tracker updates on update of player storage value if its id is equal to quests storageid. It requires some workaround like adding killcountid value that **quest.lua**: function Player.updateStorage would check or adding a pointless update to `QUESTSTORAGE_BASE` in **data\creaturescripts\scripts\quests\killing_in_the_name_of\kill.lua**: function onKill.

Or just set storageid to `KILLSSTORAGE_BASE + taskId` and ignore that in other cases it stores the quest's state.

**Comment by marcosvf132** [comment]
Due to a huge amount of issues, we are moving all bugs related to quest to one single ISSUE, for future issues related to the quest, please consider reporting it on that specific ISSUE, thanks.
 - Ref: #726
