### ISSUE TITLE
Stow items depo box to Stash

### ISSUE THREAD

**Issue by yatozin** [opentibiabr/otservbr-global-archived#1708]
Cannot stow all items from depot box

Should be able to click on depot box and select "stow all items in this container"
![image](https://user-images.githubusercontent.com/55179288/91650979-dbd28b00-eada-11ea-9f1d-af40fca22d3b.png)

What we have at the moment 
![image](https://user-images.githubusercontent.com/55179288/91650994-002e6780-eadb-11ea-95af-09fcad35157e.png)

Missing option to Stow all items in container and dragging depo box onto stash items also dont transfer to stash

Adding: you should also be able to imbue with items in stash currently must have item on you.

**Comment by marcosvf132** [comment]
The menu option on depot/inbox is available and is working like a charm here.
![image](https://user-images.githubusercontent.com/66353315/91651196-2236d400-ea60-11ea-89c0-9948f84baba6.png)

But indeed the depot/inbox drag&drop dont work.

Also the imbue shrine integration is a missing feature, will work on that too.

**Comment by yatozin** [comment]
> 
> 
> The menu option on depot/inbox is available and is working like a charm here.
> ![image](https://user-images.githubusercontent.com/66353315/91651196-2236d400-ea60-11ea-89c0-9948f84baba6.png)
> 
> But indeed the depot/inbox drag&drop dont work.
> 
> Also the imbue shrine integration is a missing feature, will work on that too.

Nevermind it seems god characters it doesnt work

**Comment by marcosvf132** [comment]
WIth /ghost on this option wont show to you. The opposite can happen too, if you step on depot tile, activate /ghost and leave, this menu option will stay even leaving depot. With regular players this wont happen.
