### ISSUE TITLE
Exercise Weapons (Knight+Paladin)

### ISSUE THREAD

**Issue by matheuspergher** [opentibiabr/otservbr-global-archived#1715]
## CAUTION: OUR SERVER IS UPDATED DAILY. MAKE SURE YOU ARE REPORTING SOMETHING ON THE LATEST VERSION OF THE SERVER.

**Describe the bug**

**To Reproduce**
Note: include any configuration/script required to reproduce.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Version: [e.g. 10]

**Additional context**

Hey guys. 

I've noticed that when you're using an exercise weapond and you are knight or paladin, your gain on skills are not that equivalent as mages. Is there any way to change this value? Skills are incrising very slowlly when you compare with mages.. .

Thank you.

**Comment by enzerah** [comment]
check rates in lua.

**Comment by matheuspergher** [comment]
> check rates in lua.

Which one?

**Comment by enzerah** [comment]
rateMagic
rateSkill

**Comment by matheuspergher** [comment]
> rateMagic
> rateSkill

Actually that's not what I need. but anyway. thank you for you help. 

I'll close this issue, for those who are looking for improve the speed training on exercise weapons, you can change here:

data\actions\scripts\others - > exercise_training.lua

                            if skills[itemid].id == SKILL_MAGLEVEL then
                                if not bonusDummy then
                                    player:addManaSpent(math.ceil(500*magicRate))
                                else
                                    player:addManaSpent(math.ceil(500*magicRate)*1.1) -- 10%
                                end
                            else
                                if not bonusDummy then
                                    player:addSkillTries(skills[itemid].id, (1*skillRate)*2.6)
                                else
                                    player:addSkillTries(skills[itemid].id, (1*skillRate)*2.6) -- 10%
                                end
                            end

Change the numbers after *, like 2.8, 3.0 etc. 

Cheers
