### ISSUE TITLE
Player causing damage in player when party

### ISSUE THREAD

**Issue by matheuspergher** [opentibiabr/otservbr-global-archived#1717]
## CAUTION: OUR SERVER IS UPDATED DAILY. MAKE SURE YOU ARE REPORTING SOMETHING ON THE LATEST VERSION OF THE SERVER.

**Describe the bug**

**To Reproduce**
Note: include any configuration/script required to reproduce.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Version: [e.g. 10]

**Additional context**

Hi there.

When players are on party, one can attack the next other, causing damages. 

In the normal party, player cannot attack another player.

Thx

**Comment by dracoalv** [comment]
i belive it is retro pvp by default

**Comment by matheuspergher** [comment]
> i belive it is retro pvp by default

Do you know if there's any way to change that?

Thank you.

**Comment by dracoalv** [comment]
havent been done yet expert_pvp and open_pvp.

**Comment by matheuspergher** [comment]
> havent been done yet expert_pvp and open_pvp.

Thank you.

**Comment by RDaruish** [comment]
There is still no expert or open pvp but I use this system on my ot and it works perfectly, the players will not take damage from those in the party


**Data > Events > Events.xml**

```xml
change from 
<event class="Creature" method="onTargetCombat" enabled="0" />

for
<event class="Creature" method="onTargetCombat" enabled="1" />
```
**Data > Events > Scripts > creature.lua**

```lua
function Creature:onTargetCombat(target)
	if not self then
		return true
	end

	if self:isPlayer() and target:isPlayer() then
		local party = self:getParty()
		if party then
			local targetParty = target:getParty()
			if targetParty and targetParty == party then
				return RETURNVALUE_YOUMAYNOTATTACKTHISPLAYER
			end
		end
	end
	return true
end
```

**Comment by dudantas** [comment]
> There is still no expert or open pvp but I use this system on my ot and it works perfectly, the players will not take damage from those in the party
> 
> **Data > Events > Events.xml**
> 
> ```
> change from 
> <event class="Creature" method="onTargetCombat" enabled="0" />
> 
> for
> <event class="Creature" method="onTargetCombat" enabled="1" />
> ```
> 
> **Data > Events > Scripts > creature.lua**
> 
> ```lua
> function Creature:onTargetCombat(target)
> 	if not self then
> 		return true
> 	end
> 
> 	if self:isPlayer() and target:isPlayer() then
> 		local party = self:getParty()
> 		if party then
> 			local targetParty = target:getParty()
> 			if targetParty and targetParty == party then
> 				return RETURNVALUE_YOUMAYNOTATTACKTHISPLAYER
> 			end
> 		end
> 	end
> 	return true
> end
> ```

That is the answer
Just change to 1
Is that the server default is retro-pvp (there is no party protection)

Thanks for the response
