### ISSUE TITLE
ctrl + shift click floor to teleport

### ISSUE THREAD

**Issue by Mortalot** [opentibiabr/otservbr-global-archived#1720]
you can already ctrl + shift click on the map to teleport but it would be cool to be able to ctrl + shift click the floor to teleport.

**Comment by dudantas** [comment]
If you want to make the code and send it as a request, feel free
Any contribution is welcome
However, I would like to understand ... How do you imagine doing that?

**Comment by ghost** [comment]
Well, it IS technically possible to do it, but I think it is easier to use some script from OTLand where you can "use with..." an existing item (or making a new one for GMs maybe) to teleport to a SQM.

**Comment by majestyotbr** [comment]
https://otland.net/threads/tfs-1-3-tp-wand-for-admins-updated.267323/
https://otland.net/threads/1-3-teleport-where-you-look.267325/
