### ISSUE TITLE
New lions

### ISSUE THREAD

**Issue by Mortalot** [opentibiabr/otservbr-global-archived#1728]
![lions rope spot](https://user-images.githubusercontent.com/66652015/92336462-fa9ec780-f06e-11ea-95a8-ddb1cd948371.png)

![lions prey](https://user-images.githubusercontent.com/66652015/92336465-fd012180-f06e-11ea-9a83-705001722645.png)

**Comment by LIKEAHYENA** [comment]
It's connected to the Werehyaenas cave, which does not exist atm, that's why. I'll be uploading it soon-ish after I'm done.

**Comment by Mortalot** [comment]
thank you :)
