### ISSUE TITLE
XP boost only works once a day

### ISSUE THREAD

**Issue by Mortalot** [opentibiabr/otservbr-global-archived#1738]
![xpboosts](https://user-images.githubusercontent.com/66652015/92463305-a2b0af80-f199-11ea-9a63-63296628d798.png)

**Comment by matheuspergher** [comment]
Same issue here =/

**Comment by ivansho92** [comment]
If you want to delete this lines from your init.lua and unlock the amount, you could buy as many as you want in one day, in the end it is convenient for you if you want your players to spend TC.


if (player:getExpBoostStamina()>0) then
     disabled = 1
     disabledReason = "You can't buy XP Boost while you still have one active."
end
remove this in your init.lua
and you can buy more XP Boost (stack time)

**Comment by matheuspergher** [comment]
> If you want to delete this lines from your init.lua and unlock the amount, you could buy as many as you want in one day, in the end it is convenient for you if you want your players to spend TC.
> 
> if (player:getExpBoostStamina()>0) then
> disabled = 1
> disabledReason = "You can't buy XP Boost while you still have one active."
> end
> remove this in your init.lua
> and you can buy more XP Boost (stack time)

I couldn`t find that code... there`s only:

function GameStore.processExpBoostPuchase(player)
	local currentExpBoostTime = player:getExpBoostStamina()

	player:setStoreXpBoost(50)
	player:setExpBoostStamina(currentExpBoostTime + 3600)

	if (player:getStorageValue(51052) == -1 or player:getStorageValue(51052) == 6) then
		player:setStorageValue(51052, 1)
	end

	player:setStorageValue(51052, player:getStorageValue(51052) + 1)
	player:setStorageValue(51053, os.time()) -- last bought
end
