### ISSUE TITLE
Not getting mana leech/life leech/crit chance

### ISSUE THREAD

**Issue by Szulcek69** [opentibiabr/otservbr-global-archived#174]
Even tough I imbued my items with mana leech, life leech and crit chance I'm not getting that. Neither the % are shown in the status bar, nor a I seeing and effect ingame.

**Comment by Szulcek69** [comment]
I've now checked, and it doesn't apply imbuing bonuses when you imbue item while you are wearing it. You have to unequip and equip for the bonus to apply.

**Comment by dudantas** [comment]
Oooooooh
Thanks for the report

@gpedro look this

**Comment by ghost** [comment]
@Szulcek69 can you test it again with latest changes?

**Comment by LukSrT** [comment]
@Szulcek69 Does the bug persist?
