### ISSUE TITLE
Yana doesn't say nothing when you say trade.

### ISSUE THREAD

**Issue by Mortalot** [opentibiabr/otservbr-global-archived#1743]
![trade](https://user-images.githubusercontent.com/66652015/92654762-514e1080-f2be-11ea-9b6a-cc347dee0eb6.png)

**Comment by dracoalv** [comment]
u have to say 'strike, vampirism or void' to exchange your token in imbuiments..

**Comment by majestyotbr** [comment]
Yana does not have trade option.

**Comment by Mortalot** [comment]
in real tibia, if you say trade.. she says this.
17:18 Yana: I have creature products for the imbuements strike, vampirism and void. Make your choice, please!
player's do not know they have to say creature products.

**Comment by majestyotbr** [comment]
Look the blue words.

**Comment by majestyotbr** [comment]
Feel free to help and fix the issues that you find in the server.

**Comment by Mortalot** [comment]
so how do i contribute what i fix?

**Comment by majestyotbr** [comment]
https://github.com/opentibiabr/otservbr-global/wiki/How-To-Create-a-Pull-Request
