### ISSUE TITLE
Yana: in real tibia you can say trade and she says the following.

### ISSUE THREAD

**Issue by Mortalot** [opentibiabr/otservbr-global-archived#1744]
17:18 Yana: I have creature products for the imbuements strike, vampirism and void. Make your choice, please!

in the ot, you can not say trade. you have to say creature products and players do not know this.

**Comment by majestyotbr** [comment]
Already commented in the other issue. Feel free to help and fix the issues that you find in the server.

**Comment by Mortalot** [comment]
how do i upload the files i fix?

**Comment by majestyotbr** [comment]
https://github.com/opentibiabr/otservbr-global/wiki/How-To-Create-a-Pull-Request
