### ISSUE TITLE
Equip hotkey

### ISSUE THREAD

**Issue by xThauma** [opentibiabr/otservbr-global-archived#1745]
You can't equip 2h weapon if you are using 1h+shield.
On real tibia the 1h and shield would go to the backpack and 2h would be equipped.

**Comment by marcosvf132** [comment]
I cant reproduce it, which items are you trying to equip/dequip?
![weapon](https://user-images.githubusercontent.com/66353315/92657874-f02d3980-f2cb-11ea-9055-19342264a5d3.gif)
Do your server contain the commit #1707 ?

**Comment by xThauma** [comment]
> I cant reproduce it, which items are you trying to equip/dequip?
> ![weapon](https://user-images.githubusercontent.com/66353315/92657874-f02d3980-f2cb-11ea-9055-19342264a5d3.gif)

1. Equip weapon and shield, 
2. Put 18 items and 2h weapon in the backpack. You have now 1 slot left in the backpack.
3. Equip the 2h weapon, 1h will go to the backpack and 2h will not switch with the shield. You will get a message "both hands needs to be free"
On real tibia the shield would switch with the weapon. Here it tries to put the shield into the backpack instead of changing it with the weapon.

**Comment by marcosvf132** [comment]
The problem is not on the hotkey, you can't even do it by hand, if you have 0 free slots first you need to remove the item and then move the new one to the specific slot.

**Comment by xThauma** [comment]
> The problem is not on the hotkey, you can't even do it by hand, if you have 0 free slots first you need to remove the item and then move the new one to the specific slot.

Yea. Changing the Items should be changed then if we want to be on par with real tibia.

**Comment by gpedro** [comment]
i cannot reproduce too.
