### ISSUE TITLE
Yana, this is what it should look like.

### ISSUE THREAD

**Issue by Mortalot** [opentibiabr/otservbr-global-archived#1747]
![trade](https://user-images.githubusercontent.com/66652015/92657780-62e5e700-f2c3-11ea-8943-3023f63ec3d5.png)
what it should look like

**Comment by Mortalot** [comment]
![trade2](https://user-images.githubusercontent.com/66652015/92657903-9c1e5700-f2c3-11ea-866b-fdc417862cda.png)
what it currently looks like

**Comment by enzerah** [comment]
have you tried the word "worth" ?

**Comment by Mortalot** [comment]
u can say creature products and it works but trade needs to give you the same response. i don't need help when reporting an issue, i'm just putting it out there so it can be perma fixed.

**Comment by majestyotbr** [comment]
I said twice, feel free to contribute and help sending a pull request with the fix.

**Comment by majestyotbr** [comment]
And when create issue here, use the Bug Report issue template.

**Comment by majestyotbr** [comment]
All NPCs needs a revision.
