### ISSUE TITLE
Flower Bouquet crashing the game

### ISSUE THREAD

**Issue by Szulcek69** [opentibiabr/otservbr-global-archived#175]
Flower Bouquet that is dropped by Vampire Bride is crashing the game. Either when you loot it or when you drop on the ground. Crashes the game for whoever gets that item on his/hers screen.

**Comment by dudantas** [comment]
![image](https://user-images.githubusercontent.com/8551443/60209959-251daf80-9832-11e9-80e0-4a31e7af5026.png)

This is the 10x client

**Comment by dudantas** [comment]
![image](https://user-images.githubusercontent.com/8551443/60210112-762da380-9832-11e9-83b6-78c8c868b642.png)


here is normal

**Comment by dudantas** [comment]
Use the new client of the repository

**Comment by gpedro** [comment]
@Szulcek69 can you test using a newer client?
https://forums.otserv.com.br/index.php?/forums/topic/168668-otservbr-global-cliente%C2%A0tibia-1144-sprites-até-12158706/

**Comment by dudantas** [comment]
unconfirmed, I tested it and it all looks ok, closing
