### ISSUE TITLE
Carnivora's Rocks

### ISSUE THREAD

**Issue by cys9211** [opentibiabr/otservbr-global-archived#1755]
From level 250 you should be able to enter, but you can't. It's also impossible to talk to NPC Andrew Lyze

```
You see a closed door.
Item ID: 22821, Action ID: 1250
Client ID: 20450
Position: 32761, 32630, 7

```
![image](https://user-images.githubusercontent.com/7588103/93474397-947c3500-f8f7-11ea-91cf-5c934f3a22e7.png)

**Comment by ivansho92** [comment]
I suggest you delete the door from the RME since it does not imply having a quest as such but a single "mission" and you're done or just a door with level restriction, more easy.
