### ISSUE TITLE
Training Machine - manadrain attack

### ISSUE THREAD

**Issue by matheuspergher** [opentibiabr/otservbr-global-archived#1756]
## CAUTION: OUR SERVER IS UPDATED DAILY. MAKE SURE YOU ARE REPORTING SOMETHING ON THE LATEST VERSION OF THE SERVER.

**Describe the bug**

**To Reproduce**
Note: include any configuration/script required to reproduce.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Version: [e.g. 10]

**Additional context**

Hey guys. 

I've created a new attack for training machines, so when the player are there being attacked her mana will be recovered. But, when I use "manadrain", the server shows us as 

![image](https://user-images.githubusercontent.com/26007416/93691680-0e94ff80-fb2c-11ea-985a-0dbc0d770b99.png)

monster.attacks = {
	{name = "melee", attack = 130, effect = CONST_ME_DRAWBLOOD, interval = 2*1000, minDamage = -1, maxDamage = -2};
	{name = "manadrain", effect = manadrain, interval = 2*1000, chance="90", range="7", min="10", max="30"}
}

Does anybody know how is the right name for "manadrain"?

**Comment by majestyotbr** [comment]
Example:
```
monster.attacks = {
	{name ="combat", interval = 2000, chance = 100, minDamage = 0, maxDamage = -210, effect = CONST_ME_DRAWBLOOD},
	{name ="combat", interval = 2000, chance = 10, minDamage = -260, maxDamage = -450, type = COMBAT_ICE, length = 10, spread = 3, effect = CONST_ME_ICETORNADO, target = false},
	{name ="combat", interval = 2000, chance = 20, minDamage = -150, maxDamage = -280, type = COMBAT_DROWN, effect = CONST_ME_BUBBLES, target = true},
	{name ="combat", interval = 2000, chance = 15, minDamage = -80, maxDamage = -140, type = COMBAT_LIFEDRAIN, range = 7, effect = CONST_ME_SMALLPLANTS, target = false},
	{name ="combat", interval = 2000, chance = 10, minDamage = -60, maxDamage = -140, type = COMBAT_MANADRAIN, range = 7, effect = CONST_ME_SMALLPLANTS, target = false},
	{name ="combat", interval = 2000, chance = 10, range = 5, target = false}
}
```

**Comment by matheuspergher** [comment]
Sensationl MajestyOTBR.

Thank you so much.
