### ISSUE TITLE
Hirelings Tab Broke

### ISSUE THREAD

**Issue by Bloodimarez** [opentibiabr/otservbr-global-archived#1768]
![hirelingstab](https://user-images.githubusercontent.com/71848382/94190502-32cd4500-fe7a-11ea-98f9-5c03a7bdd65d.png)

**Comment by majestyotbr** [comment]
I did a clean install today and it's working fine.

Unconfirmed.

**Comment by dracoalv** [comment]
probably u forget to compil or wrong repo
works fine here too 
![image](https://user-images.githubusercontent.com/70287096/94191407-d707b980-fe83-11ea-8e5d-2fedeeb22b06.png)

**Comment by Bloodimarez** [comment]
downloaded again and it works.
