### ISSUE TITLE
Exori Gran ok?

### ISSUE THREAD

**Issue by Bloodimarez** [opentibiabr/otservbr-global-archived#1775]
new
```
	local min = (level / 5) + (skill + 2 * attack) * 1.1
	local max = (level / 5) + (skill + 2 * attack) * 3

```
old
```
function onGetFormulaValues(player, skill, attack, factor)
	local skillTotal = skill * attack
	local levelTotal = player:getLevel() / 5
	return -(((skillTotal * 0.12) + 12) + (levelTotal)), -(((skillTotal * 0.15) + 27) + (levelTotal))
end
```

**Comment by morenao97** [comment]
https://tibia.fandom.com/wiki/Formulae

Just Ctrl+f and search fierce berserk.

**Comment by oalbsilva** [comment]
![image](https://user-images.githubusercontent.com/7233083/94351246-289f7800-002d-11eb-9f2f-d53671ba9207.png)
****

Formulae is a  Deprecated page. 
It is not reliable and should not be used!!!

**Comment by morenao97** [comment]
deprecated is different from incorrect. There have been no announcements of changes in damage to Tibia in recent times

**Comment by Bloodimarez** [comment]
the person that edited the spells used the wiki formulas. apparently exori gran is hitting less than exori min

**Comment by morenao97** [comment]
Knight level 100, skill 70, weapon 50 atk
Exori Gran = min:207 max:530 med: 369
Exori Min = min: 191 max: 345 med: 268

I can't understand what you are saying.

**Comment by morenao97** [comment]
in the old formula, the average  dmg is 512.
Do you really believe that they would leave a knight doing an average of 512 damage with lvl 100+ skill 70? LuL

**Comment by Bloodimarez** [comment]
ok cool so its fine.
