### ISSUE TITLE
Food items that the script needs to be created

### ISSUE THREAD

**Issue by dudantas** [opentibiabr/otservbr-global-archived#179]
**item id=35172**

> Notes
It grants +7 Shielding skill for one hour when eaten. After consuming one, you have to wait 10 minutes to consume another Hireling dish.

> It can be bought from Hirelings with the Cook skill for 15,000 gold, but the dish received is random it's average price is actually 90,000 gold. This item has the properties of Store products, which means it can only be stored inside Your Store Inbox and Depot Boxes and cannot be thrown on the ground, traded or used by other players.

**item id=35173**

> It grants +7 Distance skill for one hour when eaten. After consuming one, you have to wait 10 minutes to consume another Hireling dish.

> It can be bought from Hirelings with the Cook skill for 15,000 gold, but the dish received is random it's average price is actually 90,000 gold. This item has the properties of Store products, which means it can only be stored inside Your Store Inbox and Depot Boxes and cannot be thrown on the ground, traded or used by other players.

**item id=35174**

> It grants +3 Magic Level for one hour when eaten. After consuming one, you have to wait 10 minutes to consume another Hireling dish.

> It can be bought from Hirelings with the Cook skill for 15,000 gold, but the dish received is random it's average price is actually 90,000 gold. This item has the properties of Store products, which means it can only be stored inside Your Store Inbox and Depot Boxes and cannot be thrown on the ground, traded or used by other players.

**item id=35175**

> It grants +3 on all Melee skills for one hour when eaten. After consuming one, you have to wait 10 minutes to consume another Hireling dish.

> It can be bought from Hirelings with the Cook skill for 15,000 gold, but the dish received is random it's average price is actually 90,000 gold. This item has the properties of Store products, which means it can only be stored inside Your Store Inbox and Depot Boxes and cannot be thrown on the ground, traded or used by other players.

**item id=35176**

> It grants +80 Speed boost for one hour. After consuming one, you have to wait 10 minutes to consume another Hireling dish.

> It can be bought from Hirelings with the Cook skill for 15,000 gold, but the dish received is random it's average price is actually 90,000 gold. This item has the properties of Store products, which means it can only be stored inside Your Store Inbox and Depot Boxes and cannot be thrown on the ground, traded or used by other players.

**item id=35177**

> It grants +30 Fishing skill for one hour when eaten. After consuming one, you have to wait 10 minutes to consume another Hireling dish.

> It can be bought from Hirelings with the Cook skill for 15,000 gold, but the dish received is random it's average price is actually 90,000 gold. This item has the properties of Store products, which means it can only be stored inside Your Store Inbox and Depot Boxes and cannot be thrown on the ground, traded or used by other players.

**item id=35178**

> It restores 30% of the character's maximum Health when used. After consuming one, you have to wait 10 minutes to consume another Hireling dish.

> It can be bought from Hirelings with the Cook skill for 15,000 gold, but the dish received is random it's average price is actually 90,000 gold. This item has the properties of Store products, which means it can only be stored inside Your Store Inbox and Depot Boxes and cannot be thrown on the ground, traded or used by other players.

**item id=35179**

> It restores 30% of the character's maximum Mana when used. After consuming one, you have to wait 10 minutes to consume another Hireling dish.

> It can be bought from Hirelings with the Cook skill for 15,000 gold, but the dish received is random it's average price is actually 90,000 gold. This item has the properties of Store products, which means it can only be stored inside Your Store Inbox and Depot Boxes and cannot be thrown on the ground, traded or used by other players.

**item id=35180**

> It does not have any effect when eaten. After consuming one, you have to wait 10 minutes to consume another Hireling dish.

> It can be bought from Hirelings with the Cook skill for 15,000 gold, but the dish received is random it's average price is actually 90,000 gold. This item has the properties of Store products, which means it can only be stored inside Your Store Inbox and Depot Boxes and cannot be thrown on the ground, traded or used by other players.

**Comment by Aerwix** [comment]
We should consider too this items.
["31719"] = https://tibia.fandom.com/wiki/Blueberry_Cupcake
["31720"] = https://tibia.fandom.com/wiki/Strawberry_Cupcake 
["31721"] =https://tibia.fandom.com/wiki/Lemon_Cupcake

**Comment by ghost** [comment]
we are also missing several special foods from jean pierre aswell https://otland.net/threads/hot-cuisine-dishes-for-tfs-1-0.206545/

**Comment by ghost** [comment]
I guess this issue can be closed after #370 get merged
