### ISSUE TITLE
Tibia Client 10.zip

### ISSUE THREAD

**Issue by cys9211** [opentibiabr/otservbr-global-archived#1803]
Tibia Client 10.zip Debug!

![image](https://user-images.githubusercontent.com/7588103/94914687-c4a50580-04ab-11eb-9b12-1f7626d7fc8d.png)

**Comment by majestyotbr** [comment]
This base doesn't work with client 10 anymore. We use the Tibia.dat and Tibia.spr with Object Builder, Item Editor and RME.

**Comment by cys9211** [comment]
Okey, thanks! <3
