### ISSUE TITLE
Hirelings lose outfits and names

### ISSUE THREAD

**Issue by cys9211** [opentibiabr/otservbr-global-archived#1806]
Hirelings lose outfits and names within hours of starting the server

![image](https://user-images.githubusercontent.com/7588103/94959925-50418500-04f2-11eb-8ec2-f88a8a40fb14.png)
![image](https://user-images.githubusercontent.com/7588103/94959964-5f283780-04f2-11eb-8dea-96d7ea7cd308.png)

When the lamp is reopened, everything returns to normal
![image](https://user-images.githubusercontent.com/7588103/94960040-79621580-04f2-11eb-98ad-b2033892e635.png)

**Comment by majestyotbr** [comment]
When create issue here, use the issue template. Are you using updated repository? Do you use server save?

**Comment by cys9211** [comment]
Yes, i use actually, and have server save options

- Server Save
-- NOTE: serverSaveNotifyDuration in minutes
serverSaveNotifyMessage = true
serverSaveNotifyDuration = 5
serverSaveCleanMap = true
serverSaveClose = false
serverSaveShutdown = false

**Comment by Vitaapng** [comment]
After servesave here its ok!!
After close and start server too!
ITS all ok!
![image](https://user-images.githubusercontent.com/67878708/95522275-a8b4ce80-0999-11eb-82e5-1eed0a7767d6.png)

download again the files..
