### ISSUE TITLE
monsters attacking from range

### ISSUE THREAD

**Issue by yatozin** [opentibiabr/otservbr-global-archived#1807]
**Describe the bug**
some monsters are still attacking from range when they should be melee

**To Reproduce**
1. Go to 'Old Fortress'
2. Vile Granmaster , Visios Squire , Renegade knight dont come melee range to attack

**Expected behavior**
Should come to melee range to attack

**Comment by jairocarvalho** [comment]
Yes, go to cults carlin cemetery, monsters are attacking from range with black hit effect.

Vile Granmaster too and others. On Gray Island, Waspoids and other insects too.

**Comment by jairocarvalho** [comment]
> Yes, go to cults carlin cemetery, monsters are attacking from range with black hit effect.
> 
> Vile Granmaster too and others. On Gray Island, Waspoids and other insects too.

Solution!

on: data/scripts/monsters/humans/vile_grandmaster.lua

remove `{name ="melee", interval = 2000, chance = 15, target = false},`

and set `targetDistance = 1, `

work for me!

now repply to others =X

**Comment by dudantas** [comment]
> > Yes, go to cults carlin cemetery, monsters are attacking from range with black hit effect.
> > Vile Granmaster too and others. On Gray Island, Waspoids and other insects too.
> 
> Solution!
> 
> on: data/scripts/monsters/humans/vile_grandmaster.lua
> 
> remove `{name ="melee", interval = 2000, chance = 15, target = false},`
> 
> and set `targetDistance = 1, `
> 
> work for me!
> 
> now repply to others =X

We are already working on the fix. There was a problem with the converter.

**Comment by debone** [comment]
Where is the converter work being done? Do you need help? There are couple of other things missing.

On the topic: One of the symptons of the problem is that none of the ranged attacks have their animation working, so it looks like monsters are always attacking meele from range. A clear example of that are hunters. Apparently having an arrow flying across the screen is really important :P
