### ISSUE TITLE
In Shop bought Blessing!

### ISSUE THREAD

**Issue by cys9211** [opentibiabr/otservbr-global-archived#1813]
When you buy five blessings, you get one
![image](https://user-images.githubusercontent.com/7588103/95026837-730b9f00-0694-11eb-8ab8-6dbbe398dd2b.png)
![image](https://user-images.githubusercontent.com/7588103/95026848-80c12480-0694-11eb-9eca-225758a86934.png)

**Comment by majestyotbr** [comment]
Duplicated, #1814
