### ISSUE TITLE
Amazon shield

### ISSUE THREAD

**Issue by ivansho92** [opentibiabr/otservbr-global-archived#1817]
Every Orc Warlord has been droped "amazon shield" same with all orc warlord existing on the map.
![4](https://user-images.githubusercontent.com/54079212/95037255-01315680-0690-11eb-8f82-813298830566.png)

**Comment by dudantas** [comment]
Are you sure about this? Yeah, I looked at the code and there is no such loot in the orc warlord

**Comment by dudantas** [comment]
Ok, I have already identified the problem

**Comment by ivansho92** [comment]
could it be in raids?

**Comment by dudantas** [comment]
I went up the correction. You can test it? @ivansho92

**Comment by ivansho92** [comment]
ill testing, thank you!

**Comment by dudantas** [comment]
Okay! :)

If you like our project, feel free to pay us a coffee, pizza or something else. Click here and check donations methods: https://opentibiabr.github.io/donation
