### ISSUE TITLE
Summons need fix

### ISSUE THREAD

**Issue by sudoslut** [opentibiabr/otservbr-global-archived#1819]
## CAUTION: OUR SERVER IS UPDATED DAILY. MAKE SURE YOU ARE REPORTING SOMETHING ON THE LATEST VERSION OF THE SERVER.

**Describe the bug**
Thundergiant, Grovebeast, Skullfrost, Emberwing 
They do not work correctly and disappear when attacked 

**To Reproduce**
Summon Thundergiant, Grovebeast, Skullfrost, Emberwing and try to hunt

**Expected behavior**
they need to follow and attack and not vanish

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Version: [e.g. 10]

**Additional context**

**Comment by majestyotbr** [comment]
Duplicated, #1789
