### ISSUE TITLE
Formula Training

### ISSUE THREAD

**Issue by dracoalv** [opentibiabr/otservbr-global-archived#1835]
**Describe the bug**
Exercise, Offline and Online Training Formula.

**To Reproduce**
1. do 30 hits with your weapon in a Training Machine
2. do 30 hits with exercise item.
3. the skills up are the same..

![image](https://user-images.githubusercontent.com/70287096/95345011-ad419000-0890-11eb-8b37-8ae2591a510a.png)

**Expected behavior**
I make a test and following tibia-stats we can see
![image](https://user-images.githubusercontent.com/70287096/95345286-f2fe5880-0890-11eb-8e33-f9337a26eb97.png)

and following intibia we have:
![image](https://user-images.githubusercontent.com/70287096/95345433-1923f880-0891-11eb-9737-f70e53fe2cea.png)

concluding: offline training is a half of online training and exercise training is 524% better with online training.

**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu]
 - Version: [e.g. 18.04]

**Comment by morenao97** [comment]
I've make the tests on Global, server Xandebra, a knight with 15 Skill Axe, for each attack he gain 1.25% of current skill, with a exercise weapon, he gain 8.75% (7x).

https://i.imgur.com/pSVEy1L.mp4
