### ISSUE TITLE
Unregister creature event run always

### ISSUE THREAD

**Issue by carlosrbta** [opentibiabr/otservbr-global-archived#1836]
**Describe the bug**
I'm creating a `creaturescripts` with event type `logout` and than without register in player when player logout the event are runing

**Code**
In `data/creaturescripts/creaturescripts.xml`
```
<?xml version="1.0" encoding="UTF-8"?>
<creaturescripts>
  <event type="logout" name="Test" script="test.lua" />
</creaturescripts>
```

In `data/creaturescripts/scripts/test.lua`
```
function onLogout(player)
    print('onLogout', player)
    return true
end
```

**Note: I dont register this event in anypoint in code and dont register in player.registerEvent()

**Comment by gpedro** [comment]
unconfirmed. the use of the XML definitions is not recommended.
try to use revscriptsys instead.

```lua
-- scripts/creaturescripts/test_logout.lua
local playerLogout = CreatureEvent("TestLogout")

function playerLogout.onLogout(player)
    print('onLogout', player:getName())
	return true
end

playerLogout:register()
```

**Comment by IgorCFG** [comment]
The `creaturescripts` is meant to be called by any **player** that makes event X. 
I don't think you need to register for that event to be called.

**Comment by dex-89** [comment]
Old version file (xml). We use revsripts now
