### ISSUE TITLE
Poison damage 

### ISSUE THREAD

**Issue by yatozin** [opentibiabr/otservbr-global-archived#1865]
**Describe the bug**
All monsters with poison damage doing to high damage

**To Reproduce**
1. Fight monsters with poison attacks damage is to high

**Expected behavior**

**Comment by Darcksody** [comment]
Poison Arrow have 91 attack set To 23

poisonArrow:attack(91)

**Comment by yatozin** [comment]
poison arrow fix  is not the fix for this
