### ISSUE TITLE
Server Crashing

### ISSUE THREAD

**Issue by yatozin** [opentibiabr/otservbr-global-archived#1869]
**Describe the bug**
Server crash, sometimes on startup (rare), mostly after 10 - 30 minutes online

no errors server just closes

**To Reproduce**
1. Start the server and wait about 30 minutes

**Expected behavior**
server should not close/crash

**Desktop (please complete the following information):**
 - OS: [ Windows] and Ubuntu 20.04

**Comment by MajestyOTBR** [comment]
I did a test with updated repository in Windows and Ubuntu 20.04, the server didn't closed or crashed. Issue not confirmed here.

Try to update your build.

**Comment by MajestyOTBR** [comment]
I did a test with updated repository in Windows 10 and Ubuntu 20.04, the server didn't closed or crashed. Issue not confirmed here.

Try to update your build.

**Comment by debone** [comment]
@yatozin Would you mind sharing the logs from your server?

**Comment by yatozin** [comment]
> I did a test with updated repository in Windows 10 and Ubuntu 20.04, the server didn't closed or crashed. Issue not confirmed here.
> 
> Try to update your build.

i did the test with fresh download i would test for upto an hour it closed every time :s

**Comment by cys9211** [comment]
I also downloaded a fresh project just now and everything works as it should

**Comment by yatozin** [comment]
> I also downloaded a fresh project just now and everything works as it should

did you test for atleast 1 hour?

**Comment by MajestyOTBR** [comment]
Here, the server completed 1 hour and 30 minutes online without problems.

**Comment by gpedro** [comment]
open manually via cmd/powershell and check which message is displayed

**Comment by yatozin** [comment]
![image](https://user-images.githubusercontent.com/55179288/95792083-3a785f00-0d3f-11eb-96fa-4aa7b1972b29.png)
nothing shows in console when it closes i dont know if this is helpful. i have even redownloaded a new fresh copy again and fresh compile and it still crashes so i have no idea whats the problem :s

**Comment by debone** [comment]
Does Yasir show in the console?

**Comment by yatozin** [comment]
> Does Yasir show in the console?

no i just did another test from cmd and the server closes with no message as to why

**Comment by yatozin** [comment]
i removed #1800 and the crash has stopped take that as you will

**Comment by xThauma** [comment]
Yup, this is crashing the server. RemoveItem causes it.

**Comment by SaiyansKing** [comment]
> i removed #1800 and the crash has stopped take that as you will

I find it funny that this code even got approved on main tfs repository after seeing how many "programmers" reviewed it, it has about 3 undefined behaviors that can result in a crash like how it happens for you or simply corrupt some part of memory.

And the funniest part is calling it "Optimized" when it actually make removeItem slower by another complexity of O(n) while this function is already slow enough, it only make the clean looks faster by mitigating complexity somewhere else instead of optimizing it.

**Comment by heberholanda** [comment]
It was for this reason that I trusted the code. =\

**Comment by majestyotbr** [comment]
> It was for this reason that I trusted the code. =\

Mistakes happens ¯\_(ツ)_/¯. We learn with the errors to not repeat again and we move on.

**Comment by majestyotbr** [comment]
After the discussion, we decided to revert the code from PR 1800. It's the best way to avoid other problems in the future. Thanks.
