### ISSUE TITLE
/reload command

### ISSUE THREAD

**Issue by cys9211** [opentibiabr/otservbr-global-archived#1874]
scripts/talkactions/god/reload.lua 

The problem is, while we want reload scripts, it's not the reload scripts/movements
You cannot add new script lines at will, restart the server. Only then will they work.

**Comment by matheuspergher** [comment]
> scripts/talkactions/god/reload.lua
> 
> The problem is, while we want reload scripts, it's not the reload scripts/movements
> You cannot add new script lines at will, restart the server. Only then will they work.

Hey cys9211
Here it works using the comamand /reload scripts.

**Comment by cys9211** [comment]
You don't understand, all folders is reloand, only folder one folder, movements No reload

**Comment by ivansho92** [comment]
> You don't understand, all folders is reloand, only folder one folder, movements No reload

no man, its true, do something, change something in your movements, for example, change some level required in a armor, /reload scritps, and the changes not applys, just when restart your server.

**Comment by majestyotbr** [comment]
The datapack is being converted to revscriptsys, so use /reload scripts. The script will be reviewed.

**Comment by cys9211** [comment]
Folder movements too?

W dniu pt., 16.10.2020 o 13:32 Majesty <notifications@github.com>
napisał(a):

**Comment by cys9211** [comment]
Folder movements too?

**Comment by majestyotbr** [comment]
Folder actions, creaturescripts, globalevents, monsters, npc (?), movements, spells (to-do), talkactions, weapons.

**Comment by majestyotbr** [comment]
The datapack will work only with revscriptsys: https://github.com/opentibiabr/otservbr-global/tree/develop/data/scripts
