### ISSUE TITLE
Field runes causing pz lock in party

### ISSUE THREAD

**Issue by yatozin** [opentibiabr/otservbr-global-archived#1875]
## CAUTION: OUR SERVER IS UPDATED DAILY. MAKE SURE YOU ARE REPORTING SOMETHING ON THE LATEST VERSION OF THE SERVER.

**Describe the bug**
Field runes are causeing players in a party to get pz locked

**To Reproduce**
1. Join a party throw down a field rune and have party member walk into it

**Expected behavior**
should not get pz lock when in a party

**Comment by marcosvf132** [comment]
Our pvp default type is 'retro-pvp', so throwing a field rune is always making the user get pzlocked. if you don't wan't this in your server try changing the world type.

**Comment by yatozin** [comment]
> Our pvp default type is 'retro-pvp', so throwing a field rune is always making the user get pzlocked. if you don't wan't this in your server try changing the world type.

not ment to if you are in a party even in retro pvp
