### ISSUE TITLE
onRecvbyte and onExtendedOpcode not working with revscripts?

### ISSUE THREAD

**Issue by BR4W0** [opentibiabr/otservbr-global-archived#1886]
I'm trying to send opcodes from OTC with no success. Sending it works, but receiving it does not.
After a while trying to fix via client side I noticed that it was a problem in otservbr source. I've tested with many other TFS sources and they all worked fine. When I tried to debug it by printing from inside these functions I noticed that none of them were working (the ones inside data/scripts). I believe if they go back to .xml they would work, as with another simular bug posted here few hours ago.

**Comment by mattyx14** [comment]
otc are revoked for use from otclientv8 from

**Comment by BR4W0** [comment]
I'm sorry, you mean this source is not compatible with OTC? Everything else works fine, and the functions I mentioned are there they just don't seem to work.

**Comment by majestyotbr** [comment]
Now we have a OTClient 12.x compatible with the server:
https://github.com/opentibiabr/otclient
