### ISSUE TITLE
Missing VCRUNTIME140_1.dll

### ISSUE THREAD

**Issue by Davenorthern** [opentibiabr/otservbr-global-archived#1897]
Heya!

Trying to start up the server but getting an error where a dll file is missing. Ive downloaded all the files provided. Any thoughts?

![image](https://user-images.githubusercontent.com/52839094/96500223-d2e67600-124e-11eb-93d1-11098f9208ef.png)

**Comment by majestyotbr** [comment]
**Microsoft Visual C++ 2015-2019 Redistributable:**
**32-bit download:** https://aka.ms/vs/16/release/vc_redist.x86.exe
**64-bit download:** https://aka.ms/vs/16/release/vc_redist.x64.exe

**Comment by Davenorthern** [comment]
<3
