### ISSUE TITLE
Trouble logging in

### ISSUE THREAD

**Issue by Davenorthern** [opentibiabr/otservbr-global-archived#1900]
Heya, noob here again. 

Server is running, and I manage to enter username and password and get to the character list in the client. When I try to log into the character, it says account or password incorrect. Even though ive already logged in. How to work around?
![account not found](https://user-images.githubusercontent.com/52839094/96753101-a9a12380-13cf-11eb-932c-0e87aa9494ed.jpg)

Thanks alot :)

**Comment by majestyotbr** [comment]
The login works with email/password.

GesiorAAC:
https://github.com/opentibiabr/gesioraac-tibia12-login/releases/tag/1.3

MyAAC:
https://github.com/opentibiabr/myaac-tibia12-login/releases/tag/1.6
