### ISSUE TITLE
Prey Loot

### ISSUE THREAD

**Issue by brunomaidana97** [opentibiabr/otservbr-global-archived#1902]
## CAUTION: OUR SERVER IS UPDATED DAILY. MAKE SURE YOU ARE REPORTING SOMETHING ON THE LATEST VERSION OF THE SERVER.

**Describe the bug**

The improved loot prey is not working.

**To Reproduce**
1. Select someone creature in prey and select full bonus improved loot. (all stars)

example:
![image](https://user-images.githubusercontent.com/64701283/96822727-23053a00-1401-11eb-998d-9d21bd3010bd.png)

2. Now, create a lot the creature you chose and kill them all.

Note: include any configuration/script required to reproduce.

Script found in scripts/creaturescripts/others/prey_loot.lua

**Expected behavior**

appear You get extra loot due your active prey at least some dead creatures, but dont work.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Version: [e.g. 10]

**Additional context**

**Comment by heberholanda** [comment]
In: **scripts/creaturescripts/others/prey_loot.lua**

Change:
target:registerEvent('bonusPreyLootDeath')

To:
target:registerEvent('**BonusPreyLootDeath**')
