### ISSUE TITLE
The Postman (Mission 02 - Fix Mailbox)

### ISSUE THREAD

**Issue by Darcksody** [opentibiabr/otservbr-global-archived#1908]
## CAUTION: OUR SERVER IS UPDATED DAILY. MAKE SURE YOU ARE REPORTING SOMETHING ON THE LATEST VERSION OF THE SERVER.

**Describe the bug**
The Postman Quest bad Storage lowercase in actions (Storage.postman.Mission02)

**To Reproduce**
Note: First you need to have 2nd mission of The Postman quest "Mission 02 - Fix Mailbox"

1. Go to 'Position: 32013, 31562, 4' Folda Mailbox
2. Generate Crowbar (id:2416) and use in mailbox
3. See error

**Fix:** In _/data/actions/lib/actions.lua_ change
Storage.postman.Mission02 to Storage.Postman.Mission02

Lines file (807 and 808).

**Comment by debone** [comment]
Thanks for the detailed report on this issue @Darcksody ! It looks like an easy fix, would you mind opening a PR for that one please?

**Comment by Darcksody** [comment]
Can u show me how make pr?

**Comment by debone** [comment]
Sure! You can try to follow the steps on this one [How to contribute to a github repository](https://medium.com/javascript-in-plain-english/how-to-contribute-to-a-github-repository-project-78f777623f18) (You will skip the step with `contributors.md` as we don't have such file).

Alternatively, if you are more of a video learner, you can definitely find something on YouTube.

Don't be afraid of making mistakes, this is your first time :)
