### ISSUE TITLE
In service of yalahar, gets stuck on mission 3: Death to the Deathbringer

### ISSUE THREAD

**Issue by Davenorthern** [opentibiabr/otservbr-global-archived#1910]
Heya

Mission 3, In service of yalahar. player:setStorageValue(Storage.InServiceofYalahar.NotesPalimuth, 1) does not kick in when you read the notes, so the quest stalls.

Same thing with player:setStorageValue(Storage.InServiceofYalahar.NotesAzerus)

**Comment by debone** [comment]
Thanks for reporting this issue @Davenorthern ! Have you tried fixing it? Seems like an easy one, and we could benefit from more contributions :)

**Comment by Davenorthern** [comment]
No problem :) I'll try!

**Comment by marcosvf132** [comment]
Due to a huge amount of issues, we are moving all bugs related to quest to one single ISSUE, for future issues related to the quest, please consider reporting it on that specific ISSUE, thanks.
 - Ref: #726
