### ISSUE TITLE
Poison Arrow wrong Attack(91)

### ISSUE THREAD

**Issue by Darcksody** [opentibiabr/otservbr-global-archived#1911]
## CAUTION: OUR SERVER IS UPDATED DAILY. MAKE SURE YOU ARE REPORTING SOMETHING ON THE LATEST VERSION OF THE SERVER.

**Describe the bug**
Poison arrow has 91 of Attack

**To Reproduce**
1. Generate Poison arrow
2. Use with paladin with bow
3. Attack monster like Cyclops
4. See error (Maybe you kill cyclop by one hit) high damage!

**Expected behavior**
Poison arrow normaly have 23 attack.

Source: **data\scripts\weapons\scripts\**poison_arrow.lua

Change: 
poisonArrow:attack(91) to poisonArrow:attack(23)

**Comment by Darcksody** [comment]
Critical bug! To community some players are taking advantage of the bug.

**Comment by debone** [comment]
Thanks for your report @Darcksody ! Would you mind opening a pull request with the fix? We could benefit from more contributions :)

**Comment by Darcksody** [comment]
I dont know how make PR :'v

**Comment by debone** [comment]
I sent you instructions on the other issue
