### ISSUE TITLE
Seacrest Grounds.

### ISSUE THREAD

**Issue by ivansho92** [opentibiabr/otservbr-global-archived#1914]
the whole map is in the wrong way, the teleports do not work and actions are missing therefore quest twenty miles beneat do not works.
in Scripts apparently is ok, but in entrance just work with deep galea.
	if headItem and isInArray({5461, 12541, 15408}, headItem.itemid) then

i dont know well this area, but are incomplete, i have players that knows very well and them report about this area.

**Comment by debone** [comment]
Thank you for the report @ivansho92 ! We are keeping track of the missing quests on the issue #726, including this one. I will close this one as duplicated.
