### ISSUE TITLE
Haunted Cellar map.

### ISSUE THREAD

**Issue by ivansho92** [opentibiabr/otservbr-global-archived#1915]
Haunted cellar map have details like this...
![1](https://user-images.githubusercontent.com/54079212/97261504-9255a200-17e4-11eb-9f04-42c0579940b7.png)
at the entrance there should be no respawn and less of the blues untill the door of this picture.  V

![4](https://user-images.githubusercontent.com/54079212/97261962-8ae2c880-17e5-11eb-8cd7-f298a15b18f9.png)

and finally the final floor is quite empty more than for a few arachnophobics.

![3](https://user-images.githubusercontent.com/54079212/97261712-03955500-17e5-11eb-9fce-da2caeadcd00.png)

**Comment by dudantas** [comment]
@ivansho92 Put the positions, or you won't be able to do anything ...

**Comment by ivansho92** [comment]
sorry for that missing information, you can start from Position: 32697, 32246, 8

**Comment by dudantas** [comment]
> 32697, 32246, 8

Thanks

**Comment by dudantas** [comment]
Really, the respawns were all wrong ... I'm already correcting.

**Comment by ivansho92** [comment]
Yes like i say before at Pedro in liberty bay have little details in an house, still not in home to send you the pictures to compare
