### ISSUE TITLE
profesion ID formules?

### ISSUE THREAD

**Issue by ivansho92** [opentibiabr/otservbr-global-archived#1916]
How can I solve that the players abuse this bug?
for example, they select magicians as a vocation, they raise +15 magic level and before leaving they switch to knight or paladin and leave with a considerably high ml, compared to players who have been playing for more time.
Lately i was having players with only one day of creation and obtaining a high level of magic because at the last moment they are deciding to change into paladin or knight.

**Comment by debone** [comment]
Thank you for the issue @ivansho92. This is working as intended and we ask you to bring support questions into Discord. 

If you think our default vocations setup could be improved, please don't hesitate in opening a pull request with a proposal.

**Comment by debone** [comment]
And once more, please stick to the issue templates we provide.
