### ISSUE TITLE
Training Enter bug!

### ISSUE THREAD

**Issue by cys9211** [opentibiabr/otservbr-global-archived#1945]
On training machine enter bug

https://im6.ezgif.com/tmp/ezgif-6-785f2b6611fb.gif

**Comment by majestyotbr** [comment]
![test](https://user-images.githubusercontent.com/32709570/98572362-4d297980-2294-11eb-9efd-ddfc27359035.gif)

Unconfirmed.

**Comment by marcosvf132** [comment]
Cant even see your gif, check if your character is on ghostmode (god char), this can bug the trainer in some cases

**Comment by cys9211** [comment]
this error pops up only when they are occupied 20 places

Up to the 20th place works okay, only after it exactly in the location you can see on the gif

**Comment by debone** [comment]
@cys9211 Use this issue as reminder to use the issue template when creating a new one then. Up to this point you had not shared such information, which seems crucial to reproduce the issue :)

**Comment by majestyotbr** [comment]
> this error pops up only when they are occupied 20 places
> 
> Up to the 20th place works okay, only after it exactly in the location you can see on the gif

You didn't explained that and didn't used the issue template. Next time, create the issue following the issue template and explain better the issue/bug.

**Comment by cys9211** [comment]
https://gfycat.com/pl/nextsnivelingkusimanse

1018, 1061, 7 

In this place is Bug

**Comment by debone** [comment]
Can you test it with a normal player? The training action is expected to handle 77 slots. It's very odd to have the 21st break, even more when the position reported on the video represents the 4th place.
Also, are you sure the coordinates are not (1018, 1161, 7) as in your video?

**Comment by cys9211** [comment]
the same for a regular player


Even if I take this place myself, it still directs other characters like here

![ezgif-2-23c5824e92cf](https://user-images.githubusercontent.com/7588103/98591886-32292a80-22d1-11eb-80cd-be43ad4521cf.gif)

**Comment by debone** [comment]
Sorry @cys9211 , I cannot reproduce this issue with the latest commit of the develop branch. Please verify if you don't have any modifications on the map or the training scripts.

**Comment by cys9211** [comment]
> Sorry @cys9211 , I cannot reproduce this issue with the latest commit of the develop branch. Please verify if you don't have any modifications on the map or the training scripts.

Have actially scripts and map :/

**Comment by cys9211** [comment]
Okay, i found the bug on \otservbr-global-develop\data\world\custom\otservbr-custom.otbm
![image](https://user-images.githubusercontent.com/7588103/98651021-faa29880-2339-11eb-84ac-3eb355aff6b2.png)
The appropriate distance is 12 sqm, and the map is set to 11, adds a changed map and added number of places, works checked.

	LINK TO MAP! 
`https://mega.nz/file/cEMlHCpQ#_zOx3rKKOZoBdCBsnsZ0L-WYicOmmJZ0ZkXt8Sv2aKQ`

Script : otservbr-global-develop\data\scripts\custom\movement_trainer_entrance.lua
Need to change from 11 to 54
```
-- Number of lines
	lines= 11  
```

**Comment by debone** [comment]
Thanks for digging this up @cys9211
