### ISSUE TITLE
BUG: Scepter does not work on scorn of the emperor

### ISSUE THREAD

**Issue by Davenorthern** [opentibiabr/otservbr-global-archived#1949]
In the quest, wrath of the emperor, mission "message of freedom". The scepter does not register the dead body of the boss, resulting in the quest stalling. 

#### How to Reproduce?
Kill the scorn of the emperor miniboss, use scepter on the dead body (this is the third boss out of four, and needs to be done in a specific order). 

> Give us all details to reproduce the behavior:
Use teleport behind the sleeping dragon under the lizard city, proceed though the quest mission until the third miniboss. 

#### Logs or errors
None. 

#### Expected behavior
Use scepter on dead boss, register it as the third kill, adds to quest log as 3/4 completed and proceed to the next teleport.

**Comment by Davenorthern** [comment]
Ive tried to find any inconsistencies in the code, nothing differs in the quest files from the other minibosses. hm. Might not look in the right places through.

**Comment by yatozin** [comment]
I tested it on a fresh install and my live and it worked fine. :s

**Comment by marcosvf132** [comment]
Due to a huge amount of issues, we are moving all bugs related to quest to one single ISSUE, for future issues related to the quest, please consider reporting it on that specific ISSUE, thanks.
 - Ref: #726
