### ISSUE TITLE
Potions and imbuing

### ISSUE THREAD

**Issue by DamianDEB** [opentibiabr/otservbr-global-archived#195]
Hi somebody know how fix it 
if you have example 300potion and using it on hotkey only show how many you have on 1 stack

small question how safe disable a quest imbuing (storage) without any problem 

and about exhaust its possible find another ways to cut time for open/close door beacuse 1000
ms its really slow in config information do not touch wpe pro crash distro possible

best regards 
and thanks you for great open src project

**Comment by granoob** [comment]
> Hi somebody know how fix it
> if you have example 300potion and using it on hotkey only show how many you have on 1 stack
> 
> small question how safe disable a quest imbuing (storage) without any problem
> 
> and about exhaust its possible find another ways to cut time for open/close door beacuse 1000
> ms its really slow in config information do not touch wpe pro crash distro possible
> 
> best regards
> and thanks you for great open src project

in the pull request I have already had the solution of the pots

**Comment by DamianDEB** [comment]
Thanks you Granoob for solution pot problem :) work perfect

**Comment by dudantas** [comment]
Thanks for @granoob 

Merged pull, close issue.

https://github.com/opentibiabr/OTServBR-Global/commit/b40a667d610c498ac91308a898c7e0847a817621

**Comment by dudantas** [comment]
The actions in: https://github.com/opentibiabr/OTServBR-Global/commit/2a8f2634ab7ca154c7b8173f26f17cb17937df33
