### ISSUE TITLE
MAP: 

### ISSUE THREAD

**Issue by shumagoraa** [opentibiabr/otservbr-global-archived#1952]
movement: killing of the name... boss. não estava funcionando.

no script "boss" em movements estava assim:
__________________________________
boss:type("stepin")

for index, value in pairs(bosses) do
	boss:uid(index)
end

boss:uid(3260, 3261, 3262)
boss:aid(3244)
boss:register()
__________________________________

então removi as linhas e deu certo:

__________________________________
boss:type("stepin")

for index, value in pairs(bosses) do
	boss:uid(index)
end
boss:register()
___________________________________

acredito que varios outros movements e actions não estão funcionando devido a alguns detalhes que possam ter passado despercebidos depois que moveu para pasta scripts.

**Comment by Darcksody** [comment]
the problem is with boss:aid(3244)

**Comment by Darcksody** [comment]
just remove

**Comment by marcosvf132** [comment]
Due to a huge amount of issues, we are moving all bugs related to quest to one single ISSUE, for future issues related to the quest, please consider reporting it on that specific ISSUE, thanks.
 - Ref: #726
