### ISSUE TITLE
BUG: Ancient scarabs poisoning storm problem

### ISSUE THREAD

**Issue by Davenorthern** [opentibiabr/otservbr-global-archived#1953]
#### Describe the bug
Small problem with Ancient scarabs. Attack skill poisoning storm does all the damage in one hit, instead of debuffing, hitting 22-26 dmg per turn. 

#### How to Reproduce?
Say hello to an ancient scarab, use character with no more than 440hp. Get one-shot. :D 

#### Logs or errors
{name ="combat", type = COMBAT_EARTHDAMAGE, interval = 2000, chance = 30, minDamage = -440, maxDamage = -520, effect = CONST_ME_POISONAREA, target = false}

#### Expected behavior
Ancient scarab uses poisoning storm skill, adds debuff that ticks 22-26 hp per turn. 

#### Screenshots
> If applicable, add screenshots to help explain your problem.
![as](https://user-images.githubusercontent.com/52839094/98815892-1edca300-2428-11eb-80fb-8e2b823aa886.png)

**Comment by gerotib** [comment]
It was fixed in #1920

**Comment by dudantas** [comment]
Ok @gerotib, thanks
