### ISSUE TITLE
BUG:  Monsters still attacking from range when should be melee range 

### ISSUE THREAD

**Issue by yatozin** [opentibiabr/otservbr-global-archived#1968]
#### Describe the bug
> Monsters still attacking from range when should be melee range 

Hero cave, old fortress, sea serpent, death portal etc

**Comment by ivansho92** [comment]
thats is a shit easy to fix, if you know what monster should attack literally melee just change this in thats scripts...
	
        targetDistance = 0,
to:

	targetDistance = 1,

thats all bro, just you need to do that one by one...

**Comment by heberholanda** [comment]
Thanks brow

**Comment by ivansho92** [comment]
> Thanks brow

happy to contribute a little bit (:

**Comment by yatozin** [comment]
> > Thanks brow
> 
> happy to contribute a little bit (:

wow right over the top lol
