### ISSUE TITLE
BUG: Boss disappear after 3 min

### ISSUE THREAD

**Issue by IvanMir014** [opentibiabr/otservbr-global-archived#1969]
#### Describe the bug
> The Duke of the Depths or The Count of the Core, when you enter to kill them, after 3 min the boss disapear.

#### How to Reproduce?
>Just go and try to kill these bosses.

#### Logs or errors
>No errors shown.

#### Expected behavior
>The boss wait the tibia rl time to disapear.

#### Environment
- Tibia Version (12.52):

**Comment by IgorCFG** [comment]
@IvanMir014 is always 3 minutes?

**Comment by HeberPcL** [comment]
The setup kicks you after **5 minutes**. What is the correct time?

**Comment by IvanMir014** [comment]
Yes, always.
