### ISSUE TITLE
BUG: EXP Multiplier is not working correctly

### ISSUE THREAD

**Issue by yatozin** [opentibiabr/otservbr-global-archived#1981]
#### Describe the bug
> Players are getting more exp than they should

#### How to Reproduce?
> Kill monsters

> Give us all details to reproduce the behavior:
> 1. Kill monsters calculate exp

#### Screenshots
![SPOILER_1x_exp](https://user-images.githubusercontent.com/55179288/99227675-6e6c0600-2850-11eb-9dd2-f64633788260.jpg)

This Image is 1x exp + Stamina bonus + store exp boost and is more than double the exp it should be

**Comment by marcosvf132** [comment]
Check data/xml/events.xml to see if the exp bonus is activated.

**Comment by yatozin** [comment]
> Check data/xml/events.xml to see if the exp bonus is activated.

`<?xml version="1.0" encoding="UTF-8"?>
<events>
	<event name="Otservbr example 1" startdate="11/03/2020" enddate="11/30/2020" >
		<ingame exprate="250" lootrate="200" spawnrate="100" skillrate="200" />
		<description description="Otserver br example 1 description double exp and a half, double loot !chance!, regular spawn and double skill" />
		<colors colordark="#235c00" colorlight="#2d7400" />
		<details displaypriority="6" isseasonal="0" specialevent="0" />
	</event>
	<event name="Otservbr example 2" startdate="10/2/2020" enddate="11/7/2020" >
		<ingame exprate="50" lootrate="300" spawnrate="150" skillrate="100" />
		<description description="Otserver br example 2 description 50% less exp, triple loot !chance!, 50% faster spawn and regular skill" />
		<colors colordark="#735D10" colorlight="#8B6D05" />
		<details displaypriority="6" isseasonal="0" specialevent="0" />
	</event>
</events>`  So that date means its activates?

**Comment by marcosvf132** [comment]
Until 11/30/2020 the exprate is 2.5x. just change the date or the bonus. "100" is the regular rate.
