### ISSUE TITLE
BUG: Ancient Tombs boss room exit tps

### ISSUE THREAD

**Issue by yatozin** [opentibiabr/otservbr-global-archived#1988]
#### Describe the bug
> The Tps in all Pharos rooms dont work 

#### How to Reproduce?
> goto ankrahmun tombs into the boss rooms Mahrdis etc and try to exit

#### Logs or errors
> Please include any errors or logs that are relevant

#### Expected behavior
> if you have the item of the boss it should tp you somewere

#### Screenshots

![image](https://user-images.githubusercontent.com/55179288/99434036-327d9180-2973-11eb-869c-7a87642a69fd.png)

**Comment by dex-89** [comment]
Confirmed. I'll fix it. But I was thinking about testing the entire quest. Carrots working properly?

**Comment by marcosvf132** [comment]
Due to a huge amount of issues, we are moving all bugs related to quest to one single ISSUE, for future issues related to the quest, please consider reporting it on that specific ISSUE, thanks.
 - Ref: #726
