### ISSUE TITLE
Lever to Urmahlullu the Weakened

### ISSUE THREAD

**Issue by IvanMir014** [opentibiabr/otservbr-global-archived#1994]
Lever to Urmahlullu the Weakened don't do nothing.

22:49 You see a lever.
Item ID: 9825, Unique ID: 9545
Client ID: 8911
Position: 33917, 31626, 8

Code don't use this unique id, anywhere.

**Comment by ivansho92** [comment]
well, do you have 2 easy options now, you can change just the id in data/scripts/actions/quest/killmaresh/leverboss.lua

in last line:

leverboss:uid(33001)
leverboss:register()

TO:

leverboss:uid(9545)
leverboss:register()

and this works fine or you can change the id from RME.

**Comment by dex-89** [comment]
> well, do you have 2 easy options now, you can change just the id in data/scripts/actions/quest/killmaresh/leverboss.lua
> 
> in last line:
> 
> leverboss:uid(33001)
> leverboss:register()
> 
> TO:
> 
> leverboss:uid(9545)
> leverboss:register()
> 
> and this works fine or you can change the id from RME.

can you make pull request?

**Comment by ivansho92** [comment]
> > well, do you have 2 easy options now, you can change just the id in data/scripts/actions/quest/killmaresh/leverboss.lua
> > in last line:
> > leverboss:uid(33001)
> > leverboss:register()
> > TO:
> > leverboss:uid(9545)
> > leverboss:register()
> > and this works fine or you can change the id from RME.
> 
> can you make pull request?

let me try to fix the event in Urmahlullu first.

**Comment by ivansho92** [comment]
https://github.com/opentibiabr/otservbr-global/commit/e8440e6104f149d9405e2ce84c0bce6b5edf5251
i was trying to do a fork but i got lost hahahaha

**Comment by dex-89** [comment]
Fixed in #2000
