### ISSUE TITLE
BUG: WOTE doesn't work

### ISSUE THREAD

**Issue by gynho** [opentibiabr/otservbr-global-archived#2010]
#### Describe the bug
> The WOTE quest is not working, the NPC's Zizzle and Sleeping Dragon does not respond and the scepter does not work on the bosses, I tested it by adding the storages in the player as a Majesty post teaches.

#### How to reproduce?
> Add the storages on the characters and go to the quest, it will not be possible to complete it.

> Provide all details to reproduce the behavior:
> 1. The quest is in farmine
> 2. Try talking to zizzle or sleeping dragon
> 3. Try to proceed with the quest
> 4. See the error

#### Logs or errors
> Nothing to declare

#### Expected behavior
> I hoped the character could pass through to proceed to the completion of the quest.

#### Screenshots
> Not applicable.

#### Environment
- OS (e.g. Windows): lunix ubuntu 20.04
- OTServ version (for example, commit): three days ago
- Tibia version (e.g. 12.52): 12.5

#### Additional context
> Not applicable.

**Comment by dudantas** [comment]
> ## READ BEFORE PROCEEDING: OUR SERVER IS UPDATED DAILY. IF POSSIBLE, BE SURE TO UPDATE TO THE LATEST VERSION BEFORE REPORTING.
> #### Describe the bug
> > The WOTE quest is not working, the NPC's Zizzle and Sleeping Dragon does not respond and the scepter does not work on the bosses, I tested it by adding the storages in the player as a Majesty post teaches.
> 
> #### How to reproduce?
> > Add the storages on the characters and go to the quest, it will not be possible to complete it.
> 
> > Provide all details to reproduce the behavior:
> > 
> > 1. The quest is in farmine
> > 2. Try talking to zizzle or sleeping dragon
> > 3. Try to proceed with the quest
> > 4. See the error
> 
> #### Logs or errors
> > Nothing to declare
> 
> #### Expected behavior
> > I hoped the character could pass through to proceed to the completion of the quest.
> 
> #### Screenshots
> > Not applicable.
> 
> #### Environment
> * OS (e.g. Windows): lunix ubuntu 20.04
> * OTServ version (for example, commit): three days ago
> * Tibia version (e.g. 12.52): 12.5
> 
> #### Additional context
> > Not applicable.

Did you test doing the entire quest? The last time I tested the quest it was normal. You probably forgot some storage ...

**Comment by yatozin** [comment]
works for me
