### ISSUE TITLE
BUG:  Monsters do not go over the fire/electric/poison fields  until be attacked

### ISSUE THREAD

**Issue by ghost** [opentibiabr/otservbr-global-archived#2015]
#### Describe the bug
> The vast majority of monsters do not go over the fire / electric / poison field until attacked, making it easy to complete quests without attacking any monsters by running

#### How to Reproduce?
> Go in some resp, trap yourself with a rune of poison, fire, electric field and don't attack any monsters around, they will stay away

#### Logs or errors
> 

#### Expected behavior
> Make monsters pass over these fields without being targeted

#### Screenshots
![bugfire](https://user-images.githubusercontent.com/74992552/100365924-e075e500-2fde-11eb-94c9-da7b665a3436.jpg)
![bugelectric](https://user-images.githubusercontent.com/74992552/100365928-e23fa880-2fde-11eb-83fc-f2c25b751aac.jpg)
![bugpoison](https://user-images.githubusercontent.com/74992552/100365929-e2d83f00-2fde-11eb-83cc-89fc1df4f3c6.jpg)

#### Environment
- Ubuntu 20.04 
- OTServBR-Global
- 12.51 

#### Additional context
>

**Comment by gerotib** [comment]
Thats because before change to revscript system monsters that havent had any "canwalkon" flag specified would run through fields, but in monster converter it is set to "false" by default if not specified. It needs to be either fixed in this converter or file by file manually.

**Comment by amoxicilinaaa** [comment]
all monsters corrected follow the tibia wiki for monsters to pass in their respective fields.
[Download](https://www.mediafire.com/file/rkmnvt69i7hplt2/monster.rar/file)
[Scan](https://www.virustotal.com/gui/file/5c433984e397f8aa7a3d9df0d4773a4f689d0324d188e206244fb1166d9d6999/detection)
