### ISSUE TITLE
Itens não estão dando Magic Level

### ISSUE THREAD

**Issue by zarkank** [opentibiabr/otservbr-global-archived#203]

**Comment by gpedro** [comment]
@zarkank consegue nos dizer alguns itens para testarmos?

**Comment by zarkank** [comment]
Eu estava testando no cliente 12 e todos os itens que testei que dão ML não estava funcionando
So que testei agora no cliente 10 e la ta mostrando normalmente

**Comment by douglera22** [comment]
Algo que notei referente a isso, no cliente 12 ele da sim o ML, porem não atualiza quando equipa o item, se você equipar um item que da ML, você precisa deslogar e logar novamente, ai ele aplica o ML dos itens.

**Comment by dudantas** [comment]
hum
deixa eu ver se entendi... dá o ml mas não mostra na descrição do item ?

**Comment by zarkank** [comment]
Fala @eduardodantas95 
Era só um bug visual memso, perdão.
Se você relogar no cliente 12 o bonus aparece
