### ISSUE TITLE
MAP: missing uniques or actions.

### ISSUE THREAD

**Issue by ivansho92** [opentibiabr/otservbr-global-archived#2032]
#### What are the coordinates of the place where the issue with the map was found?
- X: 32911
- Y: 32339
- Z: 15

#### What kind of issue you found (respawns missing, details, large areas...)?
- actions or unique missing, this happen in all shrines,  too in scarlet etzel, missing actions or uniques

#### Screenshots
![1](https://user-images.githubusercontent.com/54079212/100558334-a07b6000-3273-11eb-8f48-f4c7eedea81d.png)
![2](https://user-images.githubusercontent.com/54079212/100558339-a7a26e00-3273-11eb-9bd6-c6c69829e6f9.png)

#### What was expected to be in place?
we need the actions or uniques to make the portals work, example in fire shrine works with small ruby but obviously can't work.

#### Environment
- OS (e.g. Windows): 
- OTServ Version (e.g. commit): 
12.51

#### Additional context
> so far they are the only ones I have found without actions or uniques

**Comment by marcosvf132** [comment]
The actionids are not on the map anymore, did you tried checking this ingame? All action/uniqueids are being loaded through .lua table

**Comment by ivansho92** [comment]
of course, that's why I'm doing the report, in game not works

**Comment by ivansho92** [comment]
> The actionids are not on the map anymore, did you tried checking this ingame? All action/uniqueids are being loaded through .lua table

![2](https://user-images.githubusercontent.com/54079212/100558726-277d0800-3275-11eb-9244-33ab02690d7d.png)

same with every shrine, not works, no errors in console, nothing in game like example "sorry, not possible" or something like that.

**Comment by ivansho92** [comment]
New report about dawnport, new characters can choice a vocation cus if they go through the portal nothing happens. (Portals without actions or uniques)

**Comment by oualid6496** [comment]
Shrines fixed in commit: c7907c5d7e70bc23e97807d2815236c11b018196

**Comment by dudantas** [comment]
Already fixed.
