### ISSUE TITLE
BUG: new system quest

### ISSUE THREAD

**Issue by brunomaidana97** [opentibiabr/otservbr-global-archived#2036]
#### Describe the bug
> 
![image](https://user-images.githubusercontent.com/64701283/100682062-f8899380-3353-11eb-9a5f-cb721498676b.png)

#### How to Reproduce?
> Use chests that give quest keys.

example of some test positions:

32411, 32155, 15

32813, 31964, 7

#### Environment
- OS Windows
- OTServ Version (last commit):

**Comment by dudantas** [comment]
This is because you did not pull the commit correctly, take the startup folder from the repository and place it on your server.

**Comment by brunomaidana97** [comment]
yes, it was my mistake, now everything is ok.
