### ISSUE TITLE
BUG:  When the time changes in Tibia, it gets a crash when placing NPCs

### ISSUE THREAD

**Issue by cys9211** [opentibiabr/otservbr-global-archived#2041]
## 
> NPC Ghostly Wolf added!
> NPC Talila added!
> NPC Valindara removed!

#### Describe the bug
> On remove and place NPC

#### How to Reproduce?
> 
Ghastly removed it, added the two below, and Crash

> Give us all details to reproduce the behavior:
> Ghastly removed it, added the two below, and Crash

#### Environment
- OS (e.g. Windows): Windows 10
- OTServ Version (e.g. commit): 1.0
- Tibia Version (e.g. 12.52): 12.52

**Comment by dex-89** [comment]
Confirmed. I try fix it
