### ISSUE TITLE
BUG: The Ancient Tombs Quest

### ISSUE THREAD

**Issue by travisani** [opentibiabr/otservbr-global-archived#2050]
#### Describe the bug
> Teleport while finish the bosses doesn't work

#### How to Reproduce?
> Just when player try to go out from boss.

#### Logs or errors
> No errors on console and screen.

#### Expected behavior
> A clear and concise description of what you expected to happen.

#### Screenshots
> If applicable, add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/13306169/101291214-dd040a00-37e5-11eb-9fbd-18839c0d4605.png)

#### Environment
Linux Versions

**Comment by marcosvf132** [comment]
Due to a huge amount of issues, we are moving all bugs related to quest to one single ISSUE, for future issues related to the quest, please consider reporting it on that specific ISSUE, thanks.
 - Ref: #726
