### ISSUE TITLE
BUG: Treiner offline

### ISSUE THREAD

**Issue by mrleao** [opentibiabr/otservbr-global-archived#2055]
#### Describe the bug
> O rate de skill inicial não diminui no treino offline, por exemplo meu rate tá 150x ml até o ml 30, certo? mas ai um Rp ml 0 deixa treino off e sai com ml 80, e só então ele vai pro segundo estágio de ml rate

#### How to Reproduce?
> bastar por rate alto inicial de magic level e deixa treinando offline por algum tempo. 

> Give us all details to reproduce the behavior:
> estatua de treino offline

#### Environment
- OTServ Version 12.51
- Tibia Version 12.51

**Comment by travisani** [comment]
I've tested, but no bugs.. Update yours repository.
