### ISSUE TITLE
Yalahar quest room bugado, aparecem varias waves, porém o boss não aparece.

### ISSUE THREAD

**Issue by mrleao** [opentibiabr/otservbr-global-archived#2056]
Yalahar quest room bugado, aparecem varias waves, porém o boss não aparece.

Vá até a room da yalahar quest e comece a matar os monstros, logo perceberá que a quest não tem fim.

- OTServ Version (12.51): 
- Tibia Version (12.51):

**Comment by brunomaidana97** [comment]
Ao puxar o globo, o script cria um azerus imortal, leva 3 minutos para ele ficar mortal, o que esta de acordo com o global. O problema é os summon, como ja foi reportado, os summon de criaturas esta bugado (spam de summons).

**Comment by mrleao** [comment]
Obrigado pela resposta, mas ao puxar o globo ele não cria o Azerus, ele tá criando as waves..  

![image](https://user-images.githubusercontent.com/24782663/101515572-40fd0e80-395d-11eb-9799-8ffacabdd2fc.png)

**Comment by dex-89** [comment]
Wait a few seconds... Azerus appears. It was tested.

**Comment by mrleao** [comment]
> Espere alguns segundos ... Azerus aparece. Foi testado.

Não apareceu pra mim, qual versão você tá usando?

**Comment by mrleao** [comment]
matei todas as waves e nada..
![image](https://user-images.githubusercontent.com/24782663/101520191-dfd83980-3962-11eb-80fb-526a31cb56b4.png)

**Comment by brunomaidana97** [comment]
https://streamable.com/gbs6jj

Esta funcionando normal. Atualize seu repositório.

**Comment by dex-89** [comment]
#1974

**Comment by mrleao** [comment]
Ahhh tem que ficar em um sqm especifico, não é assim no global

**Comment by brunomaidana97** [comment]
> Ahhh tem que ficar em um sqm especifico, não é assim no global

estranho, aqui funciona exatamente igual global.

**Comment by majestyotbr** [comment]
https://github.com/opentibiabr/otservbr-global/commit/2329c031bb19b41efea360a64be55867e06a5b06
