### ISSUE TITLE
BUG DA ESCADA LIVRARIA DE ENERGY 

### ISSUE THREAD

**Issue by Bragarg** [opentibiabr/otservbr-global-archived#2057]
#### What are the coordinates of the place where the issue with the map was found?
- X:32479
- Y:32479
- Z:12
#### Screenshots

![1](https://user-images.githubusercontent.com/75695293/101529012-bd4c1d80-396e-11eb-919e-1e2cdfa640eb.png)
![2](https://user-images.githubusercontent.com/75695293/101529026-c4732b80-396e-11eb-92b2-dd560301ca96.png)

#### Environment
OTServ Version (12.51):
Tibia Version (12.51):

**Comment by travisani** [comment]
Não confere.

**Comment by DeCarvalhoJr** [comment]
Stair Position
3249 32780 12
![image](https://user-images.githubusercontent.com/13871000/101562510-52b6d400-39a6-11eb-90fc-9cd0878a8367.png)

Up floor position
3249 32780 11
![image](https://user-images.githubusercontent.com/13871000/101562624-84c83600-39a6-11eb-821f-8de6b83b9ba5.png)

This is the only upstair in this place and the floor right above its 'empty'
Im using the last global map from develop repo and did use remere to find the place.

Based on tibiawiki we should find a little room here
![image](https://user-images.githubusercontent.com/13871000/101563415-f3f25a00-39a7-11eb-983e-1ad7a02b0f4c.png)

**Comment by dex-89** [comment]
@TheAncientDragon Can you send the link to the map from the screenshot?

**Comment by DeCarvalhoJr** [comment]
> @TheAncientDragon Can you send the link to the map from the screenshot?

Hey, well, just go to tibiawiki search info about the library and use the map to find the coordinates.
I just have my phone rn and it's kinda hard to browse there..

**Comment by dex-89** [comment]
Fixed.
![image](https://user-images.githubusercontent.com/67392692/106639095-e2cb6100-6584-11eb-8a42-f6133445c8b8.png)
