### ISSUE TITLE
BUG: Familiars wont walk over fields

### ISSUE THREAD

**Issue by DeCarvalhoJr** [opentibiabr/otservbr-global-archived#2058]
#### Describe the bug
After being summoned the familiar wont walk over fire/poison/energy field

#### How to Reproduce?
Summon a familiar and shot fire/poison/energy wall/bomb

#### Logs or errors
no errors shown

#### Expected behavior
Familiar should walk over it w/o problem.

#### Screenshots
![ezgif-2-68403e63eb05_1](https://user-images.githubusercontent.com/13871000/101554608-ba185800-3995-11eb-8ca5-86a7b190b215.gif)
Sorry for the low quality but wasnt able to make it lesser than 10mb :s , anyway, you're still able to get the thing

#### Environment
- OS (e.g. Windows): Debian 10
- OTServ Version (e.g. commit): Develop
- Tibia Version (e.g. 12.52): 12.51

**Comment by travisani** [comment]
This is problem at yours scripts, it's not a bug.

**Comment by dex-89** [comment]
Confirmed. But pvp and non-pvp fire bombs are different (PVP Mode). No-pvp = no damage
