### ISSUE TITLE
The New Frontier Quest

### ISSUE THREAD

**Issue by LaKinney** [opentibiabr/otservbr-global-archived#2060]
Nas portas para a segunda alavanca em Farmine, nas coordenadas z=14, apenas a porta da direita abre após você começar a Quest com Ongulf. Em \data\startup\tables\door_quest.lua as seguintes linhas estão repetidas: 
{x = 33061, y = 31529, z = 12},
{x = 33062, y = 31529, z = 12},
Basta trocar o valor z para 14 um cada uma das linhas repetidas.

Também as vinhas que você precisa subir na missão 03 não estão funcionando. Em \data\scripts\actions\quests\the_new_frontier\vine.lua é só substituir
theNewFrontierVine:id(3153,3154)
por
theNewFrontierVine:id(10761, 10762)

**Comment by patrickqcf** [comment]
Substitui 
`theNewFrontierVine:id(3153,3154)`
por
`theNewFrontierVine:uid(3153,3154)`

Assim você vincula os uniqueID das vines com o script lua, e deixa o itemID daquele sprite livre pra poder ser utilizado em outro lugar.
Ao vincular o item ID como o proposto, em qualquer lugar que você reutilizar essa vine, ao dar use você será teleportado para zao.

**Comment by marcosvf132** [comment]
Due to a huge amount of issues, we are moving all bugs related to quest to one single ISSUE, for future issues related to the quest, please consider reporting it on that specific ISSUE, thanks.
 - Ref: #726
