### ISSUE TITLE
Children of the Revolution Quest

### ISSUE THREAD

**Issue by LaKinney** [opentibiabr/otservbr-global-archived#2061]
Na missão 04, após usar o óleo nas alavancas, as mesmas não se movem pra dar continuidade a Quest, o problema é resolvido adicionando um arquivo .lua em \data\scripts\actions\quests\children_of_the_revolution\

[mission04_levers.txt](https://github.com/opentibiabr/otservbr-global/files/5665685/mission04_levers.txt)

**Comment by marcosvf132** [comment]
Due to a huge amount of issues, we are moving all bugs related to quest to one single ISSUE, for future issues related to the quest, please consider reporting it on that specific ISSUE, thanks.
 - Ref: #726
