### ISSUE TITLE
BUG:  Crash Distro

### ISSUE THREAD

**Issue by Nicrox** [opentibiabr/otservbr-global-archived#2073]
https://i.imgur.com/7U08W01.jpg

Thread 2 "otbr" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff6a09700 (LWP 499030)]
0x0000000100000001 in ?? ()
(gdb) bt full
#0  0x0000000100000001 in ?? ()
No symbol table info available.
#1  0x00005555557c6ebe in Game::checkDecay() ()
No symbol table info available.
#2  0x000055555567cd03 in Dispatcher::threadMain() ()
No symbol table info available.
#3  0x00007ffff70e2d84 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
No symbol table info available.
#4  0x00007ffff71f6609 in start_thread (arg=<optimized out>) at pthread_create.c:477
        ret = <optimized out>
        pd = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140737331107584, 438456973233355735, 140737488346366, 140737488346367, 140737488346368,
                140737331105664, -438437913741624361, -438440752003941417}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {
              prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = 0
#5  0x00007ffff7eef293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
No locals.

(gdb) thread 1
[Switching to thread 1 (Thread 0x7ffff6a0d780 (LWP 499026))]
#0  0x00007ffff7eef5ce in epoll_wait (epfd=4, events=0x7fffffffd640, maxevents=128, timeout=-1) at ../sysdeps/unix/sysv/linux/epoll_wait.c:30
30      ../sysdeps/unix/sysv/linux/epoll_wait.c: No such file or directory.

**Comment by travisani** [comment]
This is problem in your distro, try to upgrade and recompile.

**Comment by Nicrox** [comment]
> This is problem in your distro, try to upgrade and recompile.

bump
distro is the same as github

**Comment by bosmak** [comment]
@Nicrox I believe you're running the Linux client, right?

I have similar issues with this one (some that don't happen on the Windows client.)

My client closes after login, and I can see the following logs from the crashed client.
```
[ 2020-12-23 22:54:38,564 ] Asset loading complete
[ 2020-12-23 22:55:22,274 ] Request connection to gameserver  "tcp://<redacted>:7172"  (unprotected:  "tcp://ot.bsmk.xyz:7172" )  requested (Charakter "GOD" )
[ 2020-12-23 22:55:22,274 ] Request connection to gameserver  "tcp://<redacted>:7172" "OTServBR-Global"
[ 2020-12-23 22:55:22,279 ] Connected to gameserver  "tcp://<redacted>:7172" "OTServBR-Global"
terminate called after throwing an instance of 'tibia::protocol::TUnknownGameserverException'
  what():  Unknown Gameserver Message: 0
```

Attaching the gdb to it, I see the following stack.
```
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
        set = {__val = {0, 140725182626296, 0, 0, 1065353216, 0, 0, 0, 3212836864, 0, 0, 0, 0, 0, 
            3138431948, 0}}
        pid = <optimized out>
        tid = <optimized out>
        ret = <optimized out>
#1  0x00007fbb310f8859 in __GI_abort () at abort.c:79
        save_stage = 1
        act = {__sigaction_handler = {sa_handler = 0x7fbb312bf5c0 <_IO_2_1_stderr_>, 
            sa_sigaction = 0x7fbb312bf5c0 <_IO_2_1_stderr_>}, sa_mask = {__val = {140441960576448, 1, 
              140441960576579, 3432, 140441959164625, 29, 10, 140441960576448, 140441916227840, 
              10458128, 0, 140441964201280, 140441959165971, 10, 140441960576448, 140441916227840}}, 
          sa_flags = 827315876, sa_restorer = 0x7fbb312bf780 <stderr>}
        sigs = {__val = {32, 0 <repeats 15 times>}}
#2  0x00007fbb314f2951 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
No symbol table info available.
#3  0x00007fbb314fe47c in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
No symbol table info available.
#4  0x00007fbb314fe4e7 in std::terminate() () from /lib/x86_64-linux-gnu/libstdc++.so.6
No symbol table info available.
#5  0x00007fbb314fe799 in __cxa_throw () from /lib/x86_64-linux-gnu/libstdc++.so.6
No symbol table info available.
#6  0x0000000000992fd5 in ?? ()
No symbol table info available.
#7  0x000000000093b382 in ?? ()
No symbol table info available.
```

I think that this may be related since we can't remove the BattlEye from the modified client (since we can't find the same bits to disable on the Windows client, it may be possible I just don't have the know-how.).

I could also observe that when logging into the Global servers, the BattlEye initializes and computes after the game server connection GUID.

```
[ 2020-12-23 23:06:57,100 ] Asset loading complete
[ 2020-12-23 23:07:12,732 ] BattlEye: "Initialized (v1.246)"
[ 2020-12-23 23:07:12,771 ] Request connection to gameserver  "tcp://protected-ip-sa-v4.tibia.com:7171"  (unprotected:  "tcp://tibia-pool-br.ciproxy.com:7171" )  requested (Charakter "<redacted>" )
[ 2020-12-23 23:07:12,771 ] Request connection to gameserver  "tcp://protected-ip-sa-v4.tibia.com:7171" "Dibra"
[ 2020-12-23 23:07:12,781 ] Connected to gameserver  "tcp://protected-ip-sa-v4.tibia.com:7171" "Dibra"
[ 2020-12-23 23:07:13,214 ] Request connection to gameserver  "tcp://tibia-pool-br.ciproxy.com:7171" "Dibra"
[ 2020-12-23 23:07:13,302 ] Backup connection to gameserver  "tcp://tibia-pool-br.ciproxy.com:7171" "Dibra" established
[ 2020-12-23 23:07:15,671 ] BattlEye: "Server computed GUID: 46f8d01ffaeeee2f747085dc749a9f21"
```

**Comment by bosmak** [comment]
I had debugged this with @gpedro on the discord, It is related to the custom bytes for the client, forcing my otserver to set the client as the MacOS one allowed me to log in (sometimes it will crash most of the time) but as soon as I connect to the game it starts waiting on the game server, but it was able to log in (sometimes)

I believe that this issue is pretty hard to fix since it will need to add the custom bytes needed for the Linux client (that seems to never be implemented)
