### ISSUE TITLE
BUG: Ferumbras' Ascendant Quest Final

### ISSUE THREAD

**Issue by cys9211** [opentibiabr/otservbr-global-archived#2075]
#### Describe the bug
> Last mission and Ferumbras and summons

#### Logs or errors
> [Warning - Monster::Monster] Unknown event name: RiftInvaderDeath
    [Warning - Monster::Monster] Unknown event name: RiftInvaderDeath
#### Screenshots
> 
![image](https://user-images.githubusercontent.com/7588103/102196581-6390a980-3ec0-11eb-8ded-63510cc35a6c.png)

#### Environment
- OS (e.g. Windows): Windows 10
- OTServ Version (e.g. commit): 1.0
- Tibia Version (e.g. 12.52): 12.51

**Comment by gpedro** [comment]
unconfirmed.
can you check if you have this file? `data\scripts\creaturescripts\quests\ferumbras_ascendant\rift_invader_death.lua`

**Comment by dudantas** [comment]
He probably used the reload scripts command, it breaks events
