### ISSUE TITLE
Duvida

### ISSUE THREAD

**Issue by gustavotfs** [opentibiabr/otservbr-global-archived#2076]
Existe algum meio para retirar as missões das quest ou acessos fácil?  deixar livre acesso exemplo, yalahar tem que fazer quest pra entrar

**Comment by majestyotbr** [comment]
https://forums.otserv.com.br/index.php?/forums/topic/169565-otservbr-global-liberar-acessos-a-quests-e-cidades/

Para outras quests você estuda o quests.lua:
https://github.com/opentibiabr/otservbr-global/blob/develop/data/lib/core/quests.lua

Obs: o issue tracker não é fórum de suporte, você pode acessar nosso discord:
https://discordapp.com/invite/3NxYnyV
