### ISSUE TITLE
FEATURE: heart_of_destruction

### ISSUE THREAD

**Issue by travisani** [opentibiabr/otservbr-global-archived#2078]
Lua Script Error: [Scripts Interface]
/home/global/data/scripts/creaturescripts/quests/heart_of_destruction/charger_spawn.lua:callback
luaAddEvent(). callback parameter should be a function.
stack traceback:
        [C]: in function 'addEvent'
        ...urescripts/quests/heart_of_destruction/charger_spawn.lua:23: in function <...urescripts/quests/heart_of_destruction/charger_spawn.lua:8>

**Comment by travisani** [comment]
Also are missing all storages from this quest.

**Comment by marcosvf132** [comment]
Due to a huge amount of issues, we are moving all bugs related to quest to one single ISSUE, for future issues related to the quest, please consider reporting it on that specific ISSUE, thanks.
 - Ref: #726
