### ISSUE TITLE
FEATURE: ferumbras_ascendant - shulgrax lever

### ISSUE THREAD

**Issue by travisani** [opentibiabr/otservbr-global-archived#2079]
Lua Script Error: [Scripts Interface]
/home/global/data/scripts/actions/quests/ferumbras_ascendant/shulgrax_lever.lua:callback
data/lib/core/game.lua:118: table index is nil
stack traceback:
        [C]: in function '__newindex'
        data/lib/core/game.lua:118: in function 'setStorageValue'
        ...ts/actions/quests/ferumbras_ascendant/shulgrax_lever.lua:40: in function <...ts/actions/quests/ferumbras_ascendant/shulgrax_lever.lua:15>

**Comment by marcosvf132** [comment]
Due to a huge amount of issues, we are moving all bugs related to quest to one single ISSUE, for future issues related to the quest, please consider reporting it on that specific ISSUE, thanks.
 - Ref: #726
