### ISSUE TITLE
BUG: skill limit for dawnport characters

### ISSUE THREAD

**Issue by DeCarvalhoJr** [opentibiabr/otservbr-global-archived#2093]
#### Describe the bug
The limit system from server, that should limit dawnport's players from level up skills, isnt working.
You're able to set a limit eg 20/20 (base skills/ml) and yet the player is able to level up it more than that.

#### How to Reproduce?
Configure the file properly `data/lib/others/dawnport_lib.lua` starting at line 197 for sorcerer vocation.
Create a dawnport character, if you did change the limit for only one vocation, select that vocation and keep training your skills, axe/sword/etc to see you going higher than the limit previously set.

#### Logs or errors
No errors

#### Expected behavior
The player shouldnt be able to rise his/er skills above the limit set

#### Environment
- OS (e.g. Windows): Debian 10
- OTServ Version (e.g. commit): develop
- Tibia Version (e.g. 12.52): 12.51

**Comment by ElTeixe** [comment]
Is this an official tibia limit or just for open tibia customization?

**Comment by dex-89** [comment]
http://tibiacommunity.com/skill-limit-in-dawnport-or-bug
https://www.tibiawiki.com.br/Dawnport

To test: https://otland.net/threads/convert-skills-ml-when-change-vocation-dawnport.270731/

**Comment by DeCarvalhoJr** [comment]
> http://tibiacommunity.com/skill-limit-in-dawnport-or-bug
> https://www.tibiawiki.com.br/Dawnport
> 
> To test: https://otland.net/threads/convert-skills-ml-when-change-vocation-dawnport.270731/

This one is working for 0.4 (at least was) the one you linked isnt working 

https://otland.net/threads/convert-skills-ml-when-change-vocation-dawnport.265155/page-2

**Comment by ElTeixe** [comment]
@dex-89, @TheAncientDragon Thanks guys I'll check that for issue #2092.

This one #2093  is about skills limit. And from what we previously discussed on discord, only apply to magic level, however I opened to be customized for the skills too.

**Comment by amoxicilinaaa** [comment]
eu consegui limitar o avanço de skills no vocations.xml nesta área: 
I managed to limit the advancement of skills in vocations.xml in this area:

		<skill id="0" multiplier="1.5" />
		<skill id="1" multiplier="2.0" />
		<skill id="2" multiplier="2.0" />
		<skill id="3" multiplier="2.0" />
		<skill id="4" multiplier="2.0" />
		<skill id="5" multiplier="1.5" />
		<skill id="6" multiplier="1.1" />
