### ISSUE TITLE
MAP: loadLuaMapAction Error Startup Server

### ISSUE THREAD

**Issue by LeoTKBR** [opentibiabr/otservbr-global-archived#2097]
![Sem título](https://user-images.githubusercontent.com/41605307/102731352-5c312c00-4316-11eb-904c-4ec1983b0f0d.png)

**Comment by ElTeixe** [comment]
Currently there is an issue due missing item id on the map. To temporaly fix it, go to: [data/startup/tables/item.lua](https://github.com/opentibiabr/otservbr-global/blob/develop/data/startup/tables/item.lua#L50) and on line 50 and change **1495** to **false**.
