### ISSUE TITLE
monsters making drift

### ISSUE THREAD

**Issue by sonoxGit** [opentibiabr/otservbr-global-archived#212]
os ratos estão fazendo moonwalk

**Comment by gpedro** [comment]
xDDD it's my fault. i already solved on my machine. tonight i will push the fix.

**Comment by gpedro** [comment]
can you check PR #214?

@sonoxGit

**Comment by dudantas** [comment]
fix on: https://github.com/opentibiabr/OTServBR-Global/commit/2d2d0bf38e8b1274538e7c2950f3eee0fa063dbe
