### ISSUE TITLE
BUG: Imbuiments

### ISSUE THREAD

**Issue by travisani** [opentibiabr/otservbr-global-archived#2136]
I tested and i've checked the imbuiment only effects one monster when use area runes like avalanche rune. Then the life and mana gain is much less than it should normally to be.

**Comment by brunomaidana97** [comment]
I'll take mana leech as an example, you have 16% (max/weapon + helmet), for each creature that takes damage, that mana leech % decreases a little for the creature and increases the mana received. Imagine if you won 16% of each creature hit, you wouldn't need to use potions at hunt.


here is an example, not tested, but an example of how it would work.

1 mob hit: 100% leech - total mana returned: 100

2 mobs hit: 80% leech - total mana returned: 160

3 mobs hit: 66% leech - total mana returned: 200

4 mobs hit: 60% leech - total mana returned: 240

5 mobs hit: 52% leech - total mana returned: 260

6 mobs hit: 46,66% leech - total mana returned: 280

you can test, with a fixed damage and increase the creatures ... 1, 2, 3 ...

**Comment by hyresu** [comment]
The actual math behind the leech is 100% for the first monster and 10% for the rest, the thing is this mana or hp return is divided in total monsters hit, example:
8% leech
1 monster hit by 1000 dmg = 80 mana
2 monster hit by 1000 dmg = 80 + 8 = 88 (it will say 44 for each one)
3 monster hit by 1000 dmg = 80 + 8 + 8 = 96 (it will say 32 for each one)
But actually the leech does increase, not at a 100% but at 10% per extra monster hit

**Comment by travisani** [comment]
While i've tested area spells like exevo mas san and avalanche runes, doesnt make effects to heal mana life.

**Comment by brunomaidana97** [comment]
> While i've tested area spells like exevo mas san and avalanche runes, doesnt make effects to heal mana life.

19:53 You were restored for 20 mana.
19:53 Training Dummy loses 255 hitpoints due to your attack.
19:53 You were restored for 20 mana.
19:53 Training Dummy loses 251 hitpoints due to your attack.
19:53 You were restored for 21 mana.
19:53 Training Dummy loses 260 hitpoints due to your attack.

here it works, with spells and runes.

**Comment by mrhultin** [comment]
With a fresh base it works as intended, 100%. You may confuse it to other servers which have been lazy and implemented leech as it was in the first parts of the test server for them, that is to say they were bonkers and 8% really did mean 8%.
