### ISSUE TITLE
raw watermelon tourmaline

### ISSUE THREAD

**Issue by Santejious** [opentibiabr/otservbr-global-archived#2141]
#### Describe the wrong or missing content
Ao usar a obsidian nice no item raw watermelon tourmaline(Item ID: 38613), não funciona ( https://www.tibiawiki.com.br/wiki/Raw_Watermelon_Tourmaline )

#### Describe the correct content
> deveria transformar em umdesses dois itens

#### Links
> If applicable, add links to help references of how the content

#### Screenshots
> If applicable, add screenshots to help explain the content

#### Additional context
> Add any other context about the problem here

**Comment by majestyotbr** [comment]
You don't need to open other issue for the same thing, you can just edit the issue. I saw that you explained better in #2155 so i close this issue.
