### ISSUE TITLE
Store Bug

### ISSUE THREAD

**Issue by denniscm** [opentibiabr/otservbr-global-archived#215]
Ao comprar a montaria "Cinderhoof" na Store, você compra uma Premium de 90 dias. Acredito que o ID da Premium Account de 90 dias está igual ao da montaria "Cinderhoof".

**Comment by FakeShinoda** [comment]
Its just a ward (y)

**Comment by majestyotbr** [comment]
https://github.com/opentibiabr/otservbr-global/commit/fd1878c3d48867148e8523985296b2cde9f07b2f
