### ISSUE TITLE
BUG: Server crash related to stash container

### ISSUE THREAD

**Issue by gerotib** [opentibiabr/otservbr-global-archived#2159]
I am not using 100% clear base of this project but im pretty confident that my changes didnt affect that. Unfortunately I can't reproduce this crash and test on clear base.

Its very rare, it happened only twice during two months on test and main server played by 10-60 playes. We tried to reproduce this in many ways but nothing worked.

It happens when you try to stow an item, but I dont know if the way you do it even matters (drag or click stow on item)

[Heres crashlog](https://pastebin.com/Fkfx3g8Z).

**Comment by gpedro** [comment]
can you check if #2217 solves your problem?

**Comment by Juanzin93** [comment]
aconteceu aqui comigo tbm agora, e ja tou com esse fix @gpedro
