### ISSUE TITLE
FEATURE: Cult Of Misguised - Outlawcamp / Bug Mechanic Boss

### ISSUE THREAD

**Issue by LeoTKBR** [opentibiabr/otservbr-global-archived#2169]
The server closes when it will throw the boss in the water

https://user-images.githubusercontent.com/41605307/103161830-765f8400-47c6-11eb-94a6-06a7691b439c.mp4

**Comment by travisani** [comment]
Confirmed.

**Comment by oualid6496** [comment]
my pr will solve the crash, however the whole quest needs to be revised to be working again and there already is an issue for that opened

**Comment by Bipbop69** [comment]
`local function bossTransformBack(creatureid, itemid)
	local creature = Creature(creatureid)
	if not creature then
		return false
	end
	local vidaAtual = creature:getHealth()
	local position = creature:getPosition()
	if Tile(position):getItemCountById(itemid) > 0 then
		addEvent(bossTransformBack, 4*1000, creature:getId(), itemid)
		return false
	end
	local bossTransformBack = Game.createMonster("the sinister hermit dirty", position, true, true)
	if bossTransformBack then
		bossTransformBack:registerEvent("spawnBoss")
		creature:remove()
		local subtrair = bossTransformBack:getHealth() - vidaAtual
		bossTransformBack:addHealth(-subtrair)
	end
return true
end

local geyser = MoveEvent()

function geyser.onStepIn(creature, item, position, fromPosition)
if not creature:isMonster() then
	return true
end

local monstro1 = "The Sinister Hermit"


	if creature:getType():getName():lower() == monstro1:lower() and creature:getOutfit().lookBody == 63 then
		local vidaAtual = creature:getHealth()
		local position = creature:getPosition()
		local bossTransform = Game.createMonster("the sinister hermit", position, true, true)
		if bossTransform then
			creature:remove()
			item:remove()
			local subtrair = bossTransform:getHealth() - vidaAtual
			bossTransform:addHealth(-subtrair)
			bossTransform:registerEvent("spawnBoss")
			addEvent(bossTransformBack, 4*1000, bossTransform:getId(), item:getId())
			return false
		end
	end
	return true
end

geyser:type("stepin")
geyser:id(28869)
geyser:register()
`

fixed

**Comment by marcosvf132** [comment]
Due to a huge amount of issues, we are moving all bugs related to quest to one single ISSUE, for future issues related to the quest, please consider reporting it on that specific ISSUE, thanks.
 - Ref: #726
