### ISSUE TITLE
FEATURE: Killing_in_the_name_of/Boss.lua BUG

### ISSUE THREAD

**Issue by LeoTKBR** [opentibiabr/otservbr-global-archived#2175]
![Sem tídsadastulo](https://user-images.githubusercontent.com/41605307/103177181-e4ec2280-4856-11eb-80c2-eb6c6ebbfc74.png)

**Comment by travisani** [comment]
Confirmed.

**Comment by marcosvf132** [comment]
Due to a huge amount of issues, we are moving all bugs related to quest to one single ISSUE, for future issues related to the quest, please consider reporting it on that specific ISSUE, thanks.
 - Ref: #726
