### ISSUE TITLE
problem login client 12.60

### ISSUE THREAD

**Issue by cocaocla** [opentibiabr/otservbr-global-archived#2177]
when I try to log in to the server I get such an error

![image](https://user-images.githubusercontent.com/57010926/103177961-14168a00-487f-11eb-9bbc-2dfa0e2ed4f0.png)

does not download anything from the client server,
ubuntu system 16.04

**Comment by marcosvf132** [comment]
The problem is not on the base, you misconfigured something because its working with no problem atm.
You can try to find help on the discord. Here are only for the issues on the repository!

**Comment by cocaocla** [comment]
how could i configure something wrong?

**Comment by cocaocla** [comment]
![image](https://user-images.githubusercontent.com/57010926/103178045-cf3f2300-487f-11eb-9009-6cb79b205337.png)
everything is fine and ip also changed in client and not working. then how can everything work fine?

**Comment by cocaocla** [comment]
![image](https://user-images.githubusercontent.com/57010926/103178078-10373780-4880-11eb-9c04-5b27992900a0.png)

**Comment by marcosvf132** [comment]
You mistyped something or forget to change some lines. Try updating your myacc/gesior login/ws_login too

GesiorAAC:
https://github.com/opentibiabr/gesioraac-tibia12-login/releases/tag/1.5

MyAAC:
https://github.com/opentibiabr/myaac-tibia12-login/releases/tag/1.8

**Comment by cocaocla** [comment]
changing the login also did not do anything, after checking the files and data provided are correct, know I do not know why it does not work
