### ISSUE TITLE
FEATURE: Roshamuul Prision / Boss Prince Drazzak Incomplete

### ISSUE THREAD

**Issue by LeoTKBR** [opentibiabr/otservbr-global-archived#2178]
When pulling the lever the boss is not born, but even though it is created by the god it still does not have the mechanics

**Comment by oualid6496** [comment]
Can't reproduce this, golden key is working and Prince Drazzak gets spawned.

**Comment by marcosvf132** [comment]
Due to a huge amount of issues, we are moving all bugs related to quest to one single ISSUE, for future issues related to the quest, please consider reporting it on that specific ISSUE, thanks.
 - Ref: #726
