### ISSUE TITLE
FEATURE: Demon Helmet Bug Wall

### ISSUE THREAD

**Issue by LeoTKBR** [opentibiabr/otservbr-global-archived#2180]
![Sem tídsadastulo](https://user-images.githubusercontent.com/41605307/103181607-ad46a000-4881-11eb-9d08-d0da972492c8.png)

**Comment by amoxicilinaaa** [comment]
O que você faz na quest para aparecer esse erro ? Mande screens para uma explicação melhor talvez eu possa ajudar neste problema. 

What do you do in the search for this error to appear? Send screens for a better explanation. Maybe I can help with this problem.

**Comment by LeoTKBR** [comment]
> O que você faz na quest para aparecer esse erro ? Mande screens para uma explicação melhor talvez eu possa ajudar neste problema.
>
Eu sinceramente não sei estava tentando fazer etc.... e gerou esse erro não sei como reproduzir

**Comment by dudantas** [comment]
@LeoTK4, você precisa dar mais detalhes. Quando eu fiz a quest, testei e estava tudo ok. Dá problema ao abrir as walls? Vai de boa? Sem saber como executar, não dá pra corrigir.
