### ISSUE TITLE
BUG: New Magic Shield

### ISSUE THREAD

**Issue by XmasGame** [opentibiabr/otservbr-global-archived#2185]
Testing the new vocations ajusts, I found that when I spell utamo vita, I can only regenerate the purple bar with another utamo vita spell, not with the corresponding potions.
And when when I put utamo vita with the new potions, that's when the potions work and it regenerates the entire purple bar

**Comment by daanyx** [comment]
@hyresu

**Comment by hyresu** [comment]
Confirmed bug, thank you, I'm as well adding the new icon for the mage magic shield
