### ISSUE TITLE
FEATURE: Não mostra cooldown potions na barra hotkey 

### ISSUE THREAD

**Issue by amoxicilinaaa** [opentibiabr/otservbr-global-archived#2194]
habilitei o exhaust dos potions ele funcionando perfeitamente o único problema e que ele não mostra na barra das hotkey o seu tempo de cooldown.

Gostaria da Solução para aparecer o cooldown na barra de hotkeys.

__________________________________________________________________________________________________________________________________
I enabled the escape of potions he perfectly perfectly the only problem and that he does not show his cooldown time on the hotkey bar.

I would like the solution to appear the cooling on the hotkey bar

**Comment by henriquesameshima** [comment]
@MajestyOTBR global Tibia does not have this function, I suggest closing this.
