### ISSUE TITLE
CONTENT: NPCs não estão vendendo diamond arrow e spectrol bolt

### ISSUE THREAD

**Issue by Santejious** [opentibiabr/otservbr-global-archived#2195]
#### Describe the wrong or missing content
> NPCs não estão vendendo diamond arrow e spectrol bolt

#### Describe the correct content
> Eles devem vender agora

#### Links
> https://www.tibiawiki.com.br/wiki/Diamond_Arrow

#### Screenshots
> If applicable, add screenshots to help explain the content

#### Additional context
> Add any other context about the problem here

**Comment by hyresu** [comment]
This is getting added in #2117 , but it's on test phase, test it if you can and give us feedback!
