### ISSUE TITLE
CONTENT: Walker missing

### ISSUE THREAD

**Issue by Santejious** [opentibiabr/otservbr-global-archived#2196]
#### Describe the wrong or missing content
> Deveria ter um walker nessa hunt, conforme link abaix(na hunt do glooth factory)

#### Describe the correct content
> Deve ser adicionado 3 walker no mapa

#### Links
> https://www.tibiawiki.com.br/wiki/Walker

#### Screenshots
> If applicable, add screenshots to help explain the content

#### Additional context
> Add any other context about the problem here

**Comment by gpedro** [comment]
Positions:

33520,31980,12
33467,31982,12
33582,32005,12
