### ISSUE TITLE
FEATURE: Grave Danger Quest

### ISSUE THREAD

**Issue by Santejious** [opentibiabr/otservbr-global-archived#2197]
#### Describe your feature request
> A quest está incompleta, falta NPCs(Jack Springer, exemplo), as alavancas para os bosses não estão funcionando e o mapa também está fora.

#### Describe the solution you'd like
> A clear and concise description of what you expected to happen.

#### Describe alternatives you've considered
> A clear and concise description of any alternative solutions or features you've considered.

#### Links
> https://www.tibiawiki.com.br/wiki/Grave_Danger_Quest ; https://www.tibiawiki.com.br/wiki/Jack_Springer

#### Screenshots
> If applicable, add screenshots to help explain your feature request

#### Additional context
> Add any other context about the problem here.

**Comment by marcosvf132** [comment]
Due to a huge amount of issues, we are moving all bugs related to quest to one single ISSUE, for future issues related to the quest, please consider reporting it on that specific ISSUE, thanks.
 - Ref: #726
