### ISSUE TITLE
FEATURE: Scarlett armor

### ISSUE THREAD

**Issue by Santejious** [opentibiabr/otservbr-global-archived#2198]
#### Describe your feature request
> Ao usar a runa desintegrate(2310) da para excluir a armadura da scarlett. Ou seja, tem que ir lá na mão add a armadura e a action para que não tenha esse bug.

#### Describe the solution you'd like
> Adicionar um script na runa para não pode remover o id do armor

#### Describe alternatives you've considered
> A clear and concise description of any alternative solutions or features you've considered.

#### Links
> If applicable, add links to help explain how this feature works.

#### Screenshots
> If applicable, add screenshots to help explain your feature request

#### Additional context
> Add any other context about the problem here.

**Comment by Underewarrr** [comment]
I think that item should be created on use lever to enter, and destroy on step ou...

**Comment by gpedro** [comment]
can you check if #2222 resolves your problem?

**Comment by Santejious** [comment]
All working perfectly!

**Comment by majestyotbr** [comment]
https://github.com/opentibiabr/otservbr-global/commit/83173846b02c90231f5a334578b3f0cf35e56b48
