### ISSUE TITLE
Souleater

### ISSUE THREAD

**Issue by coney4** [opentibiabr/otservbr-global-archived#220]
When you kill souleater on client 12 it closes client and you cannot login. I tested it with client 10 and it works. I think problem is with this items/corpses on client 12

```
<item id="12631" article="a" name="dissolved souleater">
		<attribute key="containerSize" value="20" />
		<attribute key="decayTo" value="12632" />
		<attribute key="duration" value="10" />
		<attribute key="corpseType" value="undead" />
	</item>
	<item id="12632" article="a" name="dissolved souleater">
		<attribute key="containerSize" value="20" />
		<attribute key="decayTo" value="12633" />
		<attribute key="duration" value="300" />
		<attribute key="corpseType" value="undead" />
	</item>
	<item id="12633" article="a" name="dissolved souleater">
		<attribute key="decayTo" value="12634" />
		<attribute key="duration" value="300" />
		<attribute key="corpseType" value="undead" />
	</item>

```
When i created them in game (client 12) it created them but client crashed, but on client 10 is everything ok.
Maybe there is some problem with item id in client.

PS: The last stage of corpse works on both clients

```
<item id="12634" article="a" name="dissolved souleater">
		<attribute key="decayTo" value="0" />
		<attribute key="duration" value="60" />
		<attribute key="corpseType" value="undead" />
	</item>
```

**Comment by Raphaellb** [comment]
I have the same problem with the forgotten knowledge boss Lloyd. the corps is crashing client 12.

9:50 You see a dead lloyd (Vol:20).
Item ID: 27595
Decays to: 0
Position: 32797, 32829, 14

It works fine on client 11.49

**Comment by ghost** [comment]
I can confirm this aswell, maybe has something to do with items.otb, I remember that something changed when they added those "animated" corpses years ago too

**Comment by majestyotbr** [comment]
#265
