### ISSUE TITLE
BUG: Store: Dummys and Decoration

### ISSUE THREAD

**Issue by gynho** [opentibiabr/otservbr-global-archived#2201]
No home decor item is opening after being purchased in the store, playing in the house and given use.

The most important would be the training Dummys but they don't work ...

After purchase at the store you receive the decoration kit item
(You see a decoration kit.
You bought this item in the Store.
Unwrap it in your own house to create a <exercise dummy>.
Item ID: 26054
Client ID: 23398)

This should allow to be opened after being on the floor of the house but nothing happens!

This happened with the items in the "Houses" category of the "Decorations", "Furniture" and "Upgrades" subcategories.

**Comment by travisani** [comment]
It's working fine for me, are u using the updated files from items.xml/otb?

**Comment by gynho** [comment]
> It's working fine for me, are u using the updated files from items.xml/otb?

items.xml now warns about duplicated items (#2174) that?

**Comment by Underewarrr** [comment]
When you downloaded the server? 
Works fine for me.
I believe the actual code only can't open (Unwrap) if have 2 houses in same Character.

**Comment by gynho** [comment]
> When you downloaded the server?
> Works fine for me.
> I believe the actual code only can't open (Unwrap) if have 2 houses in same Character.

I downloaded it when it updated to 12.6 and didn't change anything, it should work

**Comment by hyresu** [comment]
Does your character have 2 houses or more?

**Comment by Underewarrr** [comment]
How are you trying to open that? Certify you are owner of the house and be a player with level to buy the house.

**Comment by gynho** [comment]
> Does your character have 2 houses or more?

I only have one house

> How are you trying to open that? Certify you are owner of the house and be a player with level to buy the house.

the player who owned the house bought it, put it on the floor and used it and nothing happened.  now i'm not at the computer but as soon as i arrive i will test again.  earlier I tried and it didn't work.

**Comment by gynho** [comment]
I just tried, level 390 character owner of the house, bought the dummy demon, put it on the floor of the house and gave it use and the message that appears is: You cannot use this object.

After that nothing happens, not even in the distro any information appears. I am using the updated servidro and without any changes in these items

**Comment by gynho** [comment]
Attention: The mistake was mine, the piece that is between the screen and the chair.

It does not open with use, but with the right button and selecting the option "Unwrap".

Thank you for all the help provided <3
