### ISSUE TITLE
Off: access to commit/push

### ISSUE THREAD

**Issue by luucassoares** [opentibiabr/otservbr-global-archived#222]
Hi people. 

Im trying to solve some issues on my free time to help you all. I fixed the issue #206 that i have opened myself. I have created a branch, fix/yasirAndHanna but im unable to commit and push to origin (the branch isnt being created here in git) so that I can open a PR for people to test.

here is the log

`lucassoares@MAC-MC1SPO-V001 OTServBR-Global (fix/YasirAndHanna) $     git push --set-upstream origin fix/YasirAndHanna
Username for 'https://github.com': luucassoares
Password for 'https://luucassoares@github.com': 
remote: Permission to opentibiabr/OTServBR-Global.git denied to luucassoares.
fatal: unable to access 'https://github.com/opentibiabr/OTServBR-Global.git/': The requested URL returned error: 403
`

thanks in advance

**Comment by gpedro** [comment]
read this:
https://github.com/opentibiabr/OTServBR-Global/wiki/How-To-Create-a-Pull-Request

ps: you are trying push to us instead your fork. you can change the origin on `.git/config` to your fork and push again. After pushed, you are allowed to send PR from your fork.

**Comment by luucassoares** [comment]
didnt know i had to fork the project to do it.

soon i will be sending the PR.. before i will look in issues to see if there is anything else that makes sense to fix in this pr

thanks
