### ISSUE TITLE
BUG: Scarlet Script

### ISSUE THREAD

**Issue by travisani** [opentibiabr/otservbr-global-archived#2223]
Lua Script Error: [Main Interface] 
in a timer event called from: 
(Unknown scriptfile)
luaDoTargetCombatHealth(). Creature not found
stack traceback:
	[C]: in function 'doTargetCombatHealth'
	...rescripts/quests/grave_danger/cobra_bastion/scarlett.lua:35: in function <...rescripts/quests/grave_danger/cobra_bastion/scarlett.lua:27>

**Comment by gpedro** [comment]
@travisani are you on discord?

**Comment by travisani** [comment]
Not now, i'm testing bosses from these scripts just for fun, and reporting bugs.

**Comment by gpedro** [comment]
send me your discord username, please.

**Comment by travisani** [comment]
Travisani

**Comment by gpedro** [comment]
or join our channel.

https://discordapp.com/invite/3NxYnyV

**Comment by travisani** [comment]
ok
