### ISSUE TITLE
Error on Server load

### ISSUE THREAD

**Issue by yatozin** [opentibiabr/otservbr-global-archived#2228]
Error in console when starting server
>> Wrong item id found
> Action id: 14900, item id: 22821

**Comment by majestyotbr** [comment]
Unconfirmed.

**Comment by dudantas** [comment]
![image](https://user-images.githubusercontent.com/8551443/103468639-ed9e9600-4d39-11eb-9db0-1e18ddc24a74.png)
Update your repository map and test again. If the error persists, let me know.

**Comment by yatozin** [comment]
my mistake all ok
