### ISSUE TITLE
MAP: i cant find ghost npc in POH from The Dream Courts Quest

### ISSUE THREAD

**Issue by krisu91** [opentibiabr/otservbr-global-archived#2229]
#### What are the coordinates of the place where the issue with the map was found?
- X:
- Y:
- Z:

#### What kind of issue you found (respawns missing, details, large areas...)?
- 

#### Screenshots
> Please include screenshots or recordings of the place in the map

#### What was expected to be in place?
> A clear and concise description of what you expected to see on the place you described.

#### Environment
- OS (e.g. Windows): 
- OTServ Version (e.g. commit): 
- Tibia Version (e.g. 12.52): 

#### Additional context
> Add any other context about the problem here.

**Comment by Costallat** [comment]
@krisu91 please, provide more details, position, image, etc, this helps when checking things, like without position I will need to walk to check the place, if you give those information I can teleport there. 

Keep in mind that there are people that doesn't play the game on global and doesn't know those new stuffs

**Comment by dex-89** [comment]
He think probably about:
**Stricken Soul**
https://www.tibiaroyal.com/en/guide/quest/277/the-dream-courts-quest/spoiler#toc_5
