### ISSUE TITLE
Mapclick bug

### ISSUE THREAD

**Issue by Nilokz** [opentibiabr/otservbr-global-archived#223]
Quando "bugamos" o mapa clicando com o direito, o char corre muito! acaba bugando a velocidade de uma forma anormal.

**Comment by ghost** [comment]
só no client 12 né? aqui tbm está assim

**Comment by Eternal-Scripts** [comment]
Isso tem até no Global, se não me engano.

**Comment by ghost** [comment]
acabei de testar e no client 10 tbm está assim

**Comment by ghost** [comment]
testei nos 2 clients e não consigo mais encontrar esse bug, e vc? @Nilokz

**Comment by Nilokz** [comment]
também notei que sumiu! Pode ter relação com a correção do speed dos monstros?

**Comment by granoob** [comment]
foi sim quando refiz a formula mantive as outra corretas
