### ISSUE TITLE
BUG: Foreshock / Aftershock errors

### ISSUE THREAD

**Issue by oualid6496** [opentibiabr/otservbr-global-archived#2239]
#### Describe the bug
When attacking Foreshock, Foreshock disappears at 80% health and Aftershock doesn't spawn.

#### How to Reproduce?
Summon Foreshock, and start attacking it until it's at least less then 80% health.

#### Logs or errors
I didn't include the error because it seems the whole script is messed up, there are multiple errors when you fix one another one appears.

#### Expected behavior
After Foreshock gets 80% Aftershock has to spawn and has to be lowered until 80% so that Aftershock spawns again (every 20% they'll switch until they're dead and Realityquake spawns.

#### Environment
- OS: Windows 10
- OTServ Version: Latest
- Tibia Version: 12.60

**Comment by marcosvf132** [comment]
Due to a huge amount of issues, we are moving all bugs related to quest to one single ISSUE, for future issues related to the quest, please consider reporting it on that specific ISSUE, thanks.
 - Ref: #726
