### ISSUE TITLE
BUG: Daily reward

### ISSUE THREAD

**Issue by Risk-CPU** [opentibiabr/otservbr-global-archived#2242]
I cannot collect second day daily raward on otserv br global, anyone else have this issue?

Windows
Latest
tibia 12.60

**Comment by dex-89** [comment]
Server save. No restart. 'data/scripts/globalevents/others/server_save.lua' and work

**Comment by Darcksody** [comment]
If you dont restart server... boosted creature not change

**Comment by majestyotbr** [comment]
> Server save. No restart. 'data/scripts/globalevents/others/server_save.lua' and work
