### ISSUE TITLE
BUG: can’t save a player with logout

### ISSUE THREAD

**Issue by cys92114fun1260** [opentibiabr/otservbr-global-archived#2253]
Version 12.60
System : Linux Mint 20 

[Error - mysql_real_query] Query: UPDATE `players` SET `level` = 1008,`group_id` = 1,`vocation` = 7,`health` = 10185,`healthmax` = 10185,`experience` = 16994100504,`lookbody` = 132,`lookfeet` = 79,`lookhead` = 114,`looklegs` = 95,`looktype` = 684,`lookaddons` = 3,`lookmountbody` = 0,`lookm
Message: Out of range value for column 'manaspent' at row 1

**Comment by dex-89** [comment]
@cys92114fun1260 can you test #2254

**Comment by cys9211** [comment]
After adding the patch everything works as it should.

Good job! @dex-89
