### ISSUE TITLE
BUG: Magic shield - max value

### ISSUE THREAD

**Issue by dex-89** [opentibiabr/otservbr-global-archived#2259]
#### Describe the bug
Magic shield (utamo vita): max magic shield = max mana?

#### How to Reproduce?
Global 340MS: E.g.: max mana **10050**, max magic shield **3696**

#### Environment
- OTServ Version (e.g. commit):  current [Vocation Adjustments 12.6]

@hyresu

**Comment by hyresu** [comment]
Not a bug, it is working as intended
