### ISSUE TITLE
BUG: the writing is erased on letters

### ISSUE THREAD

**Issue by CarlosAlexanderGonzalezGarcia** [opentibiabr/otservbr-global-archived#2263]
the players receive the empty  letters

**Comment by marcosvf132** [comment]
This bug was fixed on 'Fix sending letters #2255', do you have this commit on your server? Or even with this changes, the bug continues?

**Comment by CarlosAlexanderGonzalezGarcia** [comment]
@marcosvf132 marcosvf132Before today's corrections, it was only necessary to correct game.cpp from line 2205 ...
@hyresu corrected it
in #2255 Update game.cpp

But now I find it somewhat confusing to be able to add what is missing.

**Comment by gerotib** [comment]
First commit in game.cpp worked but change in mailbox.cpp that got merged didnt.

**Comment by majestyotbr** [comment]
@CarlosAlexanderGonzalez can you test #2265?
