### ISSUE TITLE
BUG: Client crashes when walking into the ice where you "fake die/cleanse yourself" during Cults of Tibia Quest (Barkless)

### ISSUE THREAD

**Issue by oualid6496** [opentibiabr/otservbr-global-archived#2270]
#### Describe the bug
> When you walk through the fence at the barkless missions, after going through the tar, sulphur and ice trial you will have to walk into a small room with a fence in front of it. When you walk in there you usually fake die and get teleported to the temple. Now it does that also but it also crashes the client.

#### How to Reproduce?
> Follow the Cults of Tibia Quest (Barkless mission) after doing the tar / sulphur / ice trial.

> 1. Just follow the quest like it says on the wiki.
> 2. You do have to do the Barkless part all the way up to the tar / sulphur / ice party (must be completed).

#### Logs or errors
> client crashed it didnt give any error after just personal stuff no error code or something.

#### Expected behavior
> Client shouldn't crash

#### Environment
- OS: Windows 10
- OTServ Version: Latest
- Tibia Version: Latest

**Comment by marcosvf132** [comment]
Due to a huge amount of issues, we are moving all bugs related to quest to one single ISSUE, for future issues related to the quest, please consider reporting it on that specific ISSUE, thanks.
 - Ref: #726
