### ISSUE TITLE
BUG: value timeToDecreaseFrags in config.lua

### ISSUE THREAD

**Issue by CarlosAlexanderGonzalezGarcia** [opentibiabr/otservbr-global-archived#2283]
this formula is correct for

timeToDecreaseFrags = 24 * 60 * 60 * 1000 == 86,400,000ms == 1 day
 
??

on config.lua appears like this
timeToDecreaseFrags = 1 * 24 * 60 * 60  == 86,400ms ==86+seg

**Comment by dex-89** [comment]
Add a title in future issues. It will be easier for us to determine what the error is related to
