### ISSUE TITLE
Ferumbras' Ascension Quest/ Edit: all levers and kills

### ISSUE THREAD

**Issue by riesjuh666** [opentibiabr/otservbr-global-archived#2290]
#### Got an Error when i pull this lever
This problem is in the Verminor - Plagirath's Seal of the Ferumbras' Ascension Quest.
When you want to go to the boss room you have to pull this lever 
![image](https://user-images.githubusercontent.com/14964639/104836368-c43f4780-58ad-11eb-87f1-097c66e344aa.png)

af pulling you wil get teleported to the boss, (its works) but it give's me a error in console
![image](https://user-images.githubusercontent.com/14964639/104835856-bb4c7700-58a9-11eb-9941-d10d65bbec4c.png)

#### How to Reproduce?
> find the scholar Mazarius (just tp to him ^^) in darashia northeastern part of town and start the mission, you need 30 demonic essences for this quest! once you have it you can enter the portal to the north,
then follow this path :
![image](https://user-images.githubusercontent.com/14964639/104835909-21d19500-58aa-11eb-8dbe-b8c1804b0b7b.png)
and then go to number 1:
![image](https://user-images.githubusercontent.com/14964639/104835920-2bf39380-58aa-11eb-81cf-ba4d6b2af07d.png)
after that follow these lines:
![image](https://user-images.githubusercontent.com/14964639/104835951-5cd3c880-58aa-11eb-8b5a-6d6afef2ca5e.png)
you have to use a lever there to go to a mini boss, that lever works fine!
after killing the mini boss a teleport will be made on the south side of the room, enter it and follow this line:
![image](https://user-images.githubusercontent.com/14964639/104835979-868cef80-58aa-11eb-87cc-bb83d26c2200.png)
enter the teleport and there will be another room with a lever, that lever give me the error.

#### Logs or errors
Lua Script Error: [Scripts Interface]
data\scripts\actions\quests\ferumbras_ascendant\plagirath_lever.lua:callback
data/lib/core/game.lua:118: table index is nil
stack traceback:
        [C]: in function '__newindex'
        data/lib/core/game.lua:118: in function 'setStorageValue'
        ...s\actions\quests\ferumbras_ascendant\plagirath_lever.lua:40: in function <...s\actions\quests\ferumbras_ascendant\plagirath_lever.lua:15>

#### Expected behavior
Not getting a error/messege in console

#### Screenshots
/\

#### Environment
- OS (e.g. Windows): Windows 10
- OTServ Version (e.g. commit): nieuwest version
- Tibia Version (e.g. 12.52): 12.6

#### plagirath_lever.lua
local config = {
	centerRoom = Position(33172, 31501, 13),
	BossPosition = Position(33172, 31501, 13),
	playerPositions = {
		Position(33229, 31500, 13),
		Position(33229, 31501, 13),
		Position(33229, 31502, 13),
		Position(33229, 31503, 13),
		Position(33229, 31504, 13)
	},
	newPosition = Position(33173, 31504, 13)
}

local ferumbrasAscendantPlagirathLever = Action()
function ferumbrasAscendantPlagirathLever.onUse(player, item, fromPosition, target, toPosition, isHotkey)
	if item.itemid == 9825 then
		if player:getPosition() ~= Position(33229, 31500, 13) then
			item:transform(9826)
			return true
		end
	end
	if item.itemid == 9825 then
		local specs, spec = Game.getSpectators(config.centerRoom, false, false, 15, 15, 15, 15)
		for i = 1, #specs do
			spec = specs[i]
			if spec:isPlayer() then
				player:sendTextMessage(MESSAGE_EVENT_ADVANCE, "Someone is fighting with Plagirath.")
				return true
			end
		end
		Game.createMonster("Plagirath", config.BossPosition, true, true)
		for y = 31500, 31504 do
			local playerTile = Tile(Position(33229, y, 13)):getTopCreature()
			if playerTile and playerTile:isPlayer() then
				playerTile:getPosition():sendMagicEffect(CONST_ME_POFF)
				playerTile:teleportTo(config.newPosition)
				playerTile:getPosition():sendMagicEffect(CONST_ME_TELEPORT)
			end
		end
		Game.setStorageValue(GlobalStorage.FerumbrasAscendant.PlagirathTimer, 1)
		addEvent(clearForgotten, 30 * 60 * 1000, Position(33159, 31491, 13), Position(33185, 31513, 13), Position(33319, 32318, 13), GlobalStorage.FerumbrasAscendant.PlagirathTimer ,1)
		item:transform(9826)
	elseif item.itemid == 9826 then
		item:transform(9825)
	end
	return true
end

ferumbrasAscendantPlagirathLever:uid(1022)
ferumbrasAscendantPlagirathLever:register()`

**Comment by riesjuh666** [comment]
Same thing happens by the second boss: Bazir - Zamulosh's Seal

same quest second boss
![image](https://user-images.githubusercontent.com/14964639/104836289-35322f80-58ad-11eb-9823-e72d05dd1f55.png)

also boss lever:
![image](https://user-images.githubusercontent.com/14964639/104836326-79bdcb00-58ad-11eb-8ace-f27104958cab.png)



Way to second boss:
![image](https://user-images.githubusercontent.com/14964639/104837032-4df11400-58b2-11eb-9c2a-50f57474e0a8.png)
![image](https://user-images.githubusercontent.com/14964639/104837036-52b5c800-58b2-11eb-8375-1f7f8c66a6a8.png)
![image](https://user-images.githubusercontent.com/14964639/104837039-59443f80-58b2-11eb-81c4-fdd2680a9907.png)
![image](https://user-images.githubusercontent.com/14964639/104837042-5cd7c680-58b2-11eb-855c-3454c62789e4.png)


Script: zamulosh_lever.lua

local config = {
	centerRoom = Position(33643, 32756, 11),
	BossPosition = Position(33643, 32756, 11),
	newPosition = Position(33644, 32760, 11),
	zamuloshSummons = {
		Position(33642, 32756, 11),
		Position(33642, 32756, 11),
		Position(33642, 32756, 11),
		Position(33644, 32756, 11),
		Position(33644, 32756, 11),
		Position(33644, 32756, 11)
	}
}

local ferumbrasAscendantZamulosh = Action()
function ferumbrasAscendantZamulosh.onUse(player, item, fromPosition, target, toPosition, isHotkey)
	if item.itemid == 9825 then
		if player:getPosition() ~= Position(33680, 32741, 11) then
			item:transform(9826)
			return true
		end
	end
	if item.itemid == 9825 then
		local specs, spec = Game.getSpectators(config.centerRoom, false, false, 15, 15, 15, 15)
		for i = 1, #specs do
			spec = specs[i]
			if spec:isPlayer() then
				player:sendTextMessage(MESSAGE_EVENT_ADVANCE, "Someone is fighting with Zamulosh.")
				return true
			end
		end
		Game.createMonster("Zamulosh", config.BossPosition, true, true)
		for d = 1, #config.zamuloshSummons do
			Game.createMonster('Zamulosh3', config.zamuloshSummons[d], true, true)
		end
		for y = 32741, 32745 do
			local playerTile = Tile(Position(33680, y, 11)):getTopCreature()
			if playerTile and playerTile:isPlayer() then
				playerTile:getPosition():sendMagicEffect(CONST_ME_POFF)
				playerTile:teleportTo(config.newPosition)
				playerTile:getPosition():sendMagicEffect(CONST_ME_TELEPORT)
			end
		end
		Game.setStorageValue(GlobalStorage.FerumbrasAscendant.ZamuloshTimer, 1)
		addEvent(clearForgotten, 30 * 60 * 1000, Position(33634, 32749, 11), Position(33654, 32765, 11), Position(33319, 32318, 13), GlobalStorage.FerumbrasAscendant.ZamuloshTimer)
		item:transform(9826)
	elseif item.itemid == 9826 then
		item:transform(9825)
	end
	return true
end

ferumbrasAscendantZamulosh:uid(1026)
ferumbrasAscendantZamulosh:register()

**Comment by marcosvf132** [comment]
Due to a huge amount of issues, we are moving all bugs related to quest to one single ISSUE, for future issues related to the quest, please consider reporting it on that specific ISSUE, thanks.
 - Ref: #726
