### ISSUE TITLE
BUG: Mana bug when choosing 'rookgaard' at npc Inigo.

### ISSUE THREAD

**Issue by marcosvf132** [opentibiabr/otservbr-global-archived#2299]
#### How to Reproduce?
Go to NPC Inigo and say "hi - rookgaard - yes - yes" and your mana will be bugged

#### Possible fix
at `data/lib/others/dawnport_lib.lua` at line 185 (On function rookgaardSetStats(player)) the math is not working properly, its returning negative value when the character have less then level 5. This math need to be changed.

#### Additional context
This issue have a possible fix on the PR #2297, if the PR is not merged i will create a new PR to fix this one, that's why this issue exists.

**Comment by ElTeixe** [comment]
If the PR is rejected, you can check how I did it reading vocations stats instead of fixed maths if you wish.

https://github.com/opentibiabr/otservbr-global/blob/2f2a98e399b75610b447943932ab38aff66e474a/data/lib/others/dawnport_lib.lua#L100
