### ISSUE TITLE
God & Players Outfit Crash Console BUG: 

### ISSUE THREAD

**Issue by kungen32** [opentibiabr/otservbr-global-archived#2304]
#### Describe the bug
When any player or God try change the outfit the game crashes, it's randomly i try each outfit deleting but nothing

#### How to Reproduce?
> Changing outfits

#### Expected behavior
> A clear and concise description of what you expected to happen.

#### Screenshots
> If applicable, add screenshots to help explain your problem.

#### Environment
- Os 10 windows home, otserv global 12.51 ( 1260 )

**Comment by MajestyOTBR** [comment]
Already fixed: https://github.com/opentibiabr/otservbr-global/commits/develop

**Comment by majestyotbr** [comment]
Already fixed: https://github.com/opentibiabr/otservbr-global/commit/7c8b92aefd6ea069cc82568dac6871354b5dcdb2
