### ISSUE TITLE
BUG:  PORTA DA POI ESTÁ BUGADA

### ISSUE THREAD

**Issue by CaduMoraes** [opentibiabr/otservbr-global-archived#2312]
A PORTA PARA PEGAR ACESSO FÁCIL APÓS PUXAR AS ALAVANCAS DE VOCAÇÕES ESTÁ BUGADA.

**Comment by dex-89** [comment]
Could you say something more? Position? Location?

**Comment by CaduMoraes** [comment]
THIS DOOR: 32825, 32332, 11

![Sem título](https://user-images.githubusercontent.com/77340104/105778861-fc005c00-5f4b-11eb-9162-b38caa4f92d6.png)

**Comment by majestyotbr** [comment]
https://github.com/opentibiabr/otservbr-global/commit/6a0bcb0fef764b24a3a0e428368c1370fdab08d0
