### ISSUE TITLE
BUG: Cults of Tibia \ sand_entrance.lua:3

### ISSUE THREAD

**Issue by kungen32** [opentibiabr/otservbr-global-archived#2313]
#### Describe the bug
> Cults of tibia \ sand_entrance.lua:3 Error Script
The same as for lion_rock.lua:207 Error Script

#### How to Reproduce?
> Lion rock: Oramond fountain click on it
> Cults of tibia, i dont know was a player do it 

#### Logs or errors
Console:
> Cults of tibia \ sand_entrance.lua:3 Error Script
The same as for lion_rock.lua:207 Error Script

When i try Ctrl+C i forget they shutdown server.............

#### Environment
Windows 10, znote acc

**Comment by marcosvf132** [comment]
Due to a huge amount of issues, we are moving all bugs related to quest to one single ISSUE, for future issues related to the quest, please consider reporting it on that specific ISSUE, thanks.
 - Ref: #726
