### ISSUE TITLE
MAP: 

### ISSUE THREAD

**Issue by kungen32** [opentibiabr/otservbr-global-archived#2315]
## READ BEFORE PROCEEDING: OUR SERVER IS UPDATED DAILY. IF POSSIBLE MAKE SURE TO UPDATE TO THE LATEST VERSION BEFORE REPORTING.

I Have downloaded the version 30 minuts ago.

#### What are the coordinates of the place where the issue with the map was found?
- X: 32332
- Y: 32094
- Z: 7

#### What kind of issue you found (respawns missing, details, large areas...)?
- You can enter on Energy Gate leading to the Astral Shaper Boss Dungeon , but you can't return back from the Energy portal.

#### What was expected to be in place?
> Add the ActionID for come back to thais temple ( i dont know how do it, remeres map editor to new and system hard to understand )

#### Environment
- OS (e.g. Windows): 10 home
- OTServ Version (e.g. commit):  Version 26.01.2021 - 09:17 GMT+1
- Tibia Version (e.g. 12.52): 12.61

**Comment by dex-89** [comment]
Thank you for your issue
