### ISSUE TITLE
BUG: GM Outfits crash on new 12.61 Version

### ISSUE THREAD

**Issue by kungen32** [opentibiabr/otservbr-global-archived#2316]
#### Describe the bug
> Changing outfit on GM on 12.61 ( downloaded today and compiled ) Make crash server, it was fixed on 12.60 and again appears in this version 12.61

#### How to Reproduce?
> Change GM Outfit, ghost mode or not.

**Comment by dex-89** [comment]
Unconfirmed.

https://user-images.githubusercontent.com/67392692/105888522-5e6d6100-600d-11eb-87e4-c64403f8295e.mp4

**Comment by kungen32** [comment]
I have downloaded version, compiled, and used on localhost, it's crash each time.. I didnt know what, the 12.60 is working aswell, so no problem for this, maybe database so making crash ?

**Comment by dex-89** [comment]
> I have downloaded version, compiled, and used on localhost, it's crash each time.. I didnt know what, the 12.60 is working aswell, so no problem for this, maybe database so making crash ?

Try to clean the database ... something is wrong with your server.
