### ISSUE TITLE
BUG: Server freeze (100% CPU) when typing space into bestiary monster search

### ISSUE THREAD

**Issue by gerotib** [opentibiabr/otservbr-global-archived#2319]
Basically what title says. It happened twice on my test server but now I have found a way to reproduce this issue. I don't know if typing space is the only way, other characters I tried were fine. 

How to reproduce: Open cyclopedia -> bestiary window, type space into search window, and then click search.
[Video showing the issue](https://gfycat.com/velvetybetterblueandgoldmackaw)

Perf top command showing 100% of cpu usage (server does not crash, just freezes until manually killed)
![ApplicationFrameHost_ep3zP6ErPG](https://user-images.githubusercontent.com/29408915/105931837-32250500-604c-11eb-903d-58153f300cf7.png)

Theres also another kinda related issue with bestiary search, it always shows only one creature instead of each one containing the word you typed. For example if you search for orc, it will show only one of orcs instead of each known one.

Related to both issues: if you type space in real tibia it will show each of known creature that contain space in their name.

**Comment by Bipbop69** [comment]
tested and confirmed

**Comment by methx** [comment]
confirmed

**Comment by marcosvf132** [comment]
Thank you for reporting it, this is a critical error. Can you guys test the PR #2320 ?
