### ISSUE TITLE
BUG: Bosses Forgotten Knowledge Quest

### ISSUE THREAD

**Issue by CaduMoraes** [opentibiabr/otservbr-global-archived#2327]
Alguns bosses estão com bug, abaixo a listagem e o que ocorre:

Dragonking Zyrtarch: Não é possível acessar seu teleport (Fire Teleport)
![image](https://user-images.githubusercontent.com/77340104/107119172-96be3c00-6864-11eb-9c91-4425cc8db163.png)

The Last Lore Keeper: É possível acessar seu portal, porém não tem como voltar, não está funcionando.
![image](https://user-images.githubusercontent.com/77340104/107119167-8908b680-6864-11eb-9baa-a7d211bdccb6.png)

**Comment by dex-89** [comment]
`The Last Lore Keeper: É possível acessar seu portal, porém não tem como voltar, não está funcionando.`
Fixed in #2295

**Comment by CaduMoraes** [comment]
I tested this dimensional portal yesterday and it is still not working 

> `The Last Lore Keeper: É possível acessar seu portal, porém não tem como voltar, não está funcionando.`
> Fixed in #2295

**Comment by dex-89** [comment]
#2295 isn't merged yet. Did you download the map from this PR?

**Comment by RodrigoSilva93** [comment]
> Dragonking Zyrtarch: Não é possível acessar seu teleport (Fire Teleport)

The fire teleport will be available after you talk with Ivallisse. There's a quest going on, but no questlog to track them. Check her .lua file

**Comment by dex-89** [comment]
> > Dragonking Zyrtarch: Não é possível acessar seu teleport (Fire Teleport)
> 
> The fire teleport will be available after you talk with Ivallisse. There's a quest going on, but no questlog to track them. Check her .lua file

NPC Invallisse is wrong. Its to rework.

**Comment by marcosvf132** [comment]
Due to a huge amount of issues, we are moving all bugs related to quest to one single ISSUE, for future issues related to the quest, please consider reporting it on that specific ISSUE, thanks.
 - Ref: #726
