### ISSUE TITLE
BUG: Falcon Bastion Doors Locked

### ISSUE THREAD

**Issue by CaduMoraes** [opentibiabr/otservbr-global-archived#2328]
Algumas portas na Falcon Bastion está trancada e nao existe chave para abri-la, impossibilitando o acesso a diferentes salas.
![image](https://user-images.githubusercontent.com/77340104/107119082-054eca00-6864-11eb-9353-33024156733d.png)
![image](https://user-images.githubusercontent.com/77340104/107119095-113a8c00-6864-11eb-923d-d6b82e0795c6.png)
![image](https://user-images.githubusercontent.com/77340104/107119116-2ca59700-6864-11eb-8a44-df73852983ec.png)

**Comment by marcosvf132** [comment]
Due to a huge amount of issues, we are moving all bugs related to quest to one single ISSUE, for future issues related to the quest, please consider reporting it on that specific ISSUE, thanks.
 - Ref: #726
