### ISSUE TITLE
BUG: Protocol 12.61

### ISSUE THREAD

**Issue by runn3t** [opentibiabr/otservbr-global-archived#2337]
Currently I'm doing a few tests with tibia code and i encountered a problem that i suppose nots my fault which i will explain now. I was using the protocol 12.60 but sometimes i pull the new release from develop branch as i did today. When i've got the last update of the repository and the last client downloaded from [https://forums.otserv.com.br/](url) with the procotol 12.61 i tried to login in the client as always and i recieved a message more or less like this "Login failed. Tibia might currently be under maintenance". After some tests i couldn't enter the game again and this was weird thats why i decided to checkout to a older branch which date is 26 Dec 2020 (1fe5e244e4961e80b074ca37de68e4fd18504cc3) and all still working correctly. Idk if im doing something wrong but these are the facts that i bring! I sniffed network communication with wireshark and the http flow looks good but obviously the server doesn't send the first packet to the client and this one could not response. If all what im telling about can help in something ill be glad! 

PD: my enviroment is a linux VM with ubuntu 20.04 lts. Feel free to ask me for more information, regards!

**Comment by dex-89** [comment]
You got something wrong, I don't know what changes you've made, but basically everything works for Linux. I use linux myself and I have no problem logging in. You probably don't have a fully up-to-date repository.

**Comment by runn3t** [comment]
> You got something wrong, I don't know what changes you've made, but basically everything works for Linux. I use linux myself and I have no problem logging in. You probably don't have a fully up-to-date repository.

Maybe, ill try things later but is weird that with the before protocol (12.60) all works perfect and with the 12.61 update not becouse is just one month time difference between both. I have fully up-to-date repository becouse i downloaded the source code again surprised by what was happening but maybe other things are wrong. I'll be investigating on the error when i have time to do it, thanks for all. Regards!

**Comment by hyresu** [comment]
Did you edit the client.exe again? As well, you might try checking if apache has any kind of error log

**Comment by runn3t** [comment]
> Did you edit the client.exe again? As well, you might try checking if apache has any kind of error log

Yes i changed the ip with the program HxD. I didnt check the log files of MyAAC, maybe i can find something there but should not be a http protocol problem becouse with 12.60 all works fine. I'll look at the logs just in case. Other thing, Idk if with this new protocol the login.php plugin for MyAAC changed, maybe the error was there becouse the server in principle has nothing to do if the character list is not shown.

**Comment by Tazer89** [comment]
I have tested with clean build in linux. Did not get this problems.

**Comment by runn3t** [comment]
Okey guys, i was working in the instalation of my new enviroment (im on holidays and i was bored) which is based on WSL2 with a Debian 10 distrubution. After a lot of head pains with the installation i got all running successfully and then i tested again with the protocol 12.61 and now all work correctly. I suppose that the fail was occasioned becouse i changed a lot of things in my old operating system but i have no idea what was the exactly problem. Now i have proofed that was my fault but the issue will still be a mistery. Thanks to all and regards!

PD: all working fine https://ibb.co/2SfzJcz
