### ISSUE TITLE
BUG: Charms not work

### ISSUE THREAD

**Issue by Zapotoczny** [opentibiabr/otservbr-global-archived#2338]
I have the latest version of the engine, but the charm is not working corrently.
Only the effects don't work, e.g. when I have poison on a crystal wolf, I don't attack with poison :) etc

I have exactly as in this topic https://github.com/opentibiabr/otservbr-global/commit/54f9d777ec57b6ac5cec6eeecf62553e077b8f97

When I do as in this topic https://github.com/opentibiabr/otservbr-global/issues/1297, the some charms work but when someone does not have the charm, errors pop up in the command line.
**Like**
_Lua Script Error: [Event Interface]
data/events/scripts/player.lua:Player@onCombat
data/events/scripts/player.lua:984: attempt to call field 'getCharmFromTarget' (a nil value)
stack traceback:
        [C]: in function 'getCharmFromTarget'
        data/events/scripts/player.lua:984: in function <data/events/scripts/player.lua:953>_

**Comment by marcosvf132** [comment]
What? player.lua doesnt even have 984 lines. The topic you just mentioned is an ISSUE, it does not contain anything that is useful now. The current repository have the charm working on the src and not on lua. Just use the new version of the repository without this line and the charms should work properly.
