### ISSUE TITLE
BUG: Quest Canivete Rosa e Vermelho - Secret Service Quest

### ISSUE THREAD

**Issue by CaduMoraes** [opentibiabr/otservbr-global-archived#2344]
A quest destes canivetes estão com bug, sendo:

Missão 01: Borrowed Knowledge: não é possível acessar o baú
![image](https://user-images.githubusercontent.com/77340104/107119589-7348c080-6867-11eb-9c03-4dcb98b3b4ed.png)

Canivete rosa: Missão 03: Rust In Peace não está funcionando a parte de jogar inseto na porta.

![image](https://user-images.githubusercontent.com/77340104/107119374-e5b8a100-6865-11eb-96e2-5a22ba641918.png)

Canivete vermelho: Missão 06: A Little Bribe Won't Hurt a porta da witch tower está trancada, e não existe chave para esta porta, a mesma é livre no global.
![image](https://user-images.githubusercontent.com/77340104/107119279-5ca16a00-6865-11eb-82cc-7a1f2cdb0a3c.png)

**Comment by marcosvf132** [comment]
Due to a huge amount of issues, we are moving all bugs related to quest to one single ISSUE, for future issues related to the quest, please consider reporting it on that specific ISSUE, thanks.
 - Ref: #726
