### ISSUE TITLE
BUG: Deep Desert - Skeletons door

### ISSUE THREAD

**Issue by CaduMoraes** [opentibiabr/otservbr-global-archived#2345]
Não é possível passar pela porta selada da Deep Desert onde tem mais respawn de Skeletons Elite.
Mesmo fazendo a missão, diz ainda que a porta está selada.

![unknown](https://user-images.githubusercontent.com/77340104/107033759-8474cd00-6794-11eb-8209-655a07e90273.png)

**Comment by marcosvf132** [comment]
Due to a huge amount of issues, we are moving all bugs related to quest to one single ISSUE, for future issues related to the quest, please consider reporting it on that specific ISSUE, thanks.
 - Ref: #726
