### ISSUE TITLE
BUG: Hangable items can't be hanged on certain walls

### ISSUE THREAD

**Issue by oualid6496** [opentibiabr/otservbr-global-archived#2349]
#### Describe the bug
> Hangable items can't be put on certain walls (19385 & 19409)

#### How to Reproduce?
> Try to hang anything on one of those walls, I've tested it with a trophy and mirror.

> Give us all details to reproduce the behavior:
> 1. create the wall mentioned before
> 2. try to hang a dragon trophy on it

#### Expected behavior
> Stuff should be hangable on these walls

#### Environment
- OS: Windows
- OTServ Versio: Latest
- Tibia Version: 12.61

**Comment by dex-89** [comment]
All works ok. Unconfirmed.
