### ISSUE TITLE
CONTENT: Diamond arrows elemental damage

### ISSUE THREAD

**Issue by karimadnan** [opentibiabr/otservbr-global-archived#2363]
Imbuing a bow with an element, does not affect diamond arrow damage since it's scripted in lua.

**Comment by cys9211** [comment]
ID diamond arrow? 
Maybe you use Old Diamond Arrow
Correct ID - 40746
Old ID - 29057

**Comment by hyresu** [comment]
![image](https://user-images.githubusercontent.com/61813040/107096305-38a04300-67e9-11eb-9269-41287309a683.png)

It is working as intended, if you want them to work with element, add this line
`combat:setOrigin(ORIGIN_RANGED)`

below
`combat:setArea(area)`

in data/scripts/weapons/scripts/diamond_arrow.lua

**Comment by karimadnan** [comment]
> ![image](https://user-images.githubusercontent.com/61813040/107096305-38a04300-67e9-11eb-9269-41287309a683.png)
> 
> It is working as intended, if you want them to work with element, add this line
> `combat:setOrigin(ORIGIN_RANGED)`
> 
> below
> `combat:setArea(area)`
> 
> in data/scripts/weapons/scripts/diamond_arrow.lua

that didn't work :/

**Comment by hyresu** [comment]
> > ![image](https://user-images.githubusercontent.com/61813040/107096305-38a04300-67e9-11eb-9269-41287309a683.png)
> > It is working as intended, if you want them to work with element, add this line
> > `combat:setOrigin(ORIGIN_RANGED)`
> > below
> > `combat:setArea(area)`
> > in data/scripts/weapons/scripts/diamond_arrow.lua
> 
> that didn't work :/

Change this in events/scripts/player.lua

`if isInArray({ITEM_OLD_DIAMOND_ARROW, ITEM_DIAMOND_ARROW}, item:getId()) then
			return primaryDamage, primaryType, secondaryDamage, secondaryType
		else
			item = self:getSlotItem(CONST_SLOT_LEFT)
		end`

to
`item = self:getSlotItem(CONST_SLOT_LEFT)`
