### ISSUE TITLE
BUG: Acesso ao boss Necropharus

### ISSUE THREAD

**Issue by CaduMoraes** [opentibiabr/otservbr-global-archived#2368]
Teleport de acesso ao boss Necropharus não está funcionando conforme imagem
![image](https://user-images.githubusercontent.com/77340104/107130228-3356fd00-68aa-11eb-85aa-d960f8198137.png)

**Comment by hyresu** [comment]
Did you updated with this pr? #2362

**Comment by hyresu** [comment]
As I'm not getting reply, I will close this, feel free to reopen the issue if the bug persists.
