### ISSUE TITLE
BUG: Diamond arrow

### ISSUE THREAD

**Issue by Badeburu** [opentibiabr/otservbr-global-archived#2386]
#### Diamond arrow have 2 ids.
> The id 29057, the diamond arrow have 3 problems: infinite, single target and decay time.
>The id 40736 is correctly and functionally.

#### Hireling don't sell
> The hireling don't sell the diamond arrow.

**Comment by hyresu** [comment]
That's right the hireling should sell diamond arrow, however the id 29057 is the old diamond arrow and the 40736 is the new one
