### ISSUE TITLE
Inclusion of items in items.xml

### ISSUE THREAD

**Issue by daanyx** [opentibiabr/otservbr-global-archived#2406]
To fully update the NPC (Yasir) some items need to be added to items.xml.
I am updating the main NPC's.

Mouldy Powder
Pirate Coin
Pirat's Tail
Ratmiral's Hat
Shark Fins
Small Treasure Chest
Tiara
Cheesy Membership Card
Golden Cheese Wedge
Golden Dustbin
Golden Skull
Tentacle of Tentugly
Tentugly's Eye
Tentugly's Jaws
Grappling Hook

https://tibiopedia.pl/npcs/Yasir

**Comment by thovanderlaann** [comment]
@daanyx those are already added to items.xml and yasir

**Comment by daanyx** [comment]
Sory!
