### ISSUE TITLE
BUG: Team assembler/finder

### ISSUE THREAD

**Issue by thovanderlaann** [opentibiabr/otservbr-global-archived#2415]
#### Describe the bug
> Other people can't find the created team with the team assembler function.
> When you create a search you see it but other people don't

#### How to Reproduce?
> 1. Create a search for whatever you want,
> 2. Check it out with an other character, you wont see it in the list.

#### Expected behavior
> Other people should see your request

#### Environment
- OS: Windows
- OTServ Version: Latest
- Tibia Version: 12.62

**Comment by marcosvf132** [comment]
Unconfirmed, i can see it with two different characters. Are you sure your search filter is right?? 
![image](https://user-images.githubusercontent.com/66353315/107866636-ae438900-6e51-11eb-8ded-fcc22cdaf55b.png)

**Comment by thovanderlaann** [comment]
Yea it was indeed out of the scope. Works fine, closed.
