### ISSUE TITLE
BUG: Forgotten Knowledge Quest bosses

### ISSUE THREAD

**Issue by thovanderlaann** [opentibiabr/otservbr-global-archived#2416]
#### Describe the bug
> The death area spell of Lady Tenebris goes to fast and doesn't give you the chance to run. Lady Tenebris also shouldn't move when this spell is being used but she does. Also it happens very often within a minute time, on real tibia it should be way less like once every 45 seconds / minute?
#### How to Reproduce?
> 1. Start the fight with Lady Tenebris and see.
#### Expected behavior
> Lady Tenebris shouldn't be able to move when casting the death area spell until she actually casts it.
> Lady Tenebris death area spells shouldn't occur that often.
> The time between the message and the death area spell is now 1 or 2 seconds? Should be more to give players the chance to run.

#### Describe the bug
> The Thorn Knight should be healed when dealing death damage at all 3 phases but it doesn't.
#### How to Reproduce?
> 1. Shoot a sd on any of the phases
#### Expected behavior
> Any of the phases should be healed.

#### Environment
- OS: Windows
- OTServ Version: Latest 
- Tibia Version: 12.62

**Comment by marcosvf132** [comment]
Due to a huge amount of issues, we are moving all bugs related to quest to one single ISSUE, for future issues related to the quest, please consider reporting it on that specific ISSUE, thanks.
 - Ref: #726
