### ISSUE TITLE
BUG: Not getting kicked when facing prison bosses (keys)

### ISSUE THREAD

**Issue by thovanderlaann** [opentibiabr/otservbr-global-archived#2419]
#### Describe the bug
> When you challenge one of the prison bosses with the copper, bronze, silver and maybe also the golden(not tested) prison keys. You don't get kicked out and the room doesn't get cleaned after X time. An error pops up in the console when the room should be cleared.

#### How to Reproduce?
> Go to pos 33603, 32394, 11 and use a copper prison key (ID: 22605) on the copper lock pedestal. 
![image](https://user-images.githubusercontent.com/79021269/107863698-98849280-6e56-11eb-9519-41db96032227.png)
> You will get teleported in and the boss will spawn.
> After 15 minutes you won't be kicked, the room won't be cleared and an error will be shown in the console.
PS: Of course you don't have to wait 15 minutes but just edit the script to wait 10 seconds or something just to test it.
PS: For some reason it uses the clearBossRoom function from the killing in the name of... boss script but even when that one and the one in the script it self get removed, so it only uses the one in lib\core\functions.lua, it still will throw the same error as seen in de screenshot below.

#### Logs or errors
![image](https://user-images.githubusercontent.com/79021269/107863624-1a27f080-6e56-11eb-8a66-899b8199bacb.png)

#### Expected behavior
> Room should be cleared and player kicked after the time (15 minutes) has past.

#### Environment
- OS: Windows
- OTServ Version: Latest
- Tibia Version: 12.62

**Comment by marcosvf132** [comment]
Due to a huge amount of issues, we are moving all bugs related to quest to one single ISSUE, for future issues related to the quest, please consider reporting it on that specific ISSUE, thanks.
 - Ref: #726

**Comment by thovanderlaann** [comment]
The problem is with the function that's being used for a lot of things not just quests. The prison bosses are also not part of a quest so this rlly shouldn't be moved to the quest issue.

**Comment by gccris** [comment]
you just need to write **local** before your function **clearBossRoom**. It should fix it. This function is being rewrite on killing in the name of quest.
