### ISSUE TITLE
FEATURE: Recalculate status @ login

### ISSUE THREAD

**Issue by Rechdan** [opentibiabr/otservbr-global-archived#2426]
### Description

A function where the character's stats is calculated and updated upon login, so in the event of some value has changed by the server administrator all the characters are affected by it.

#### Motivation

So the characters always stay up-to-date with the server configuration, even if they change.

**Comment by henriquesameshima** [comment]
@Rechdan Could you explain more and give some examples?

**Comment by Rechdan** [comment]
@henriquesameshima sure, just before I raised this issue I decided to change the `cap` that the vocations get by level, but this does not update the characters that are already created, so a character of level 20 would still have the `cap` of before this update. So my idea here is to update the character when it logs in to match the settings of the server, even when its correct.

**Comment by ElTeixe** [comment]
> @henriquesameshima sure, just before I raised this issue I decided to change the `cap` that the vocations get by level, but this does not update the characters that are already created, so a character of level 20 would still have the `cap` of before this update. So my idea here is to update the character when it logs in to match the settings of the server, even when its correct.

If Im understanding you right you can achieve that.

Adjust the stats hp/mana/capacity gain on vocations.xml.

Add somewhere this function:

```
function Player.updateStats(self)
	-- Base stats for level 1
	local stats = {health = 150, mana = 55, capacity = 40000}
	-- No vocation
	if self:getVocation():getId() == VOCATION.ID.NONE then
		local level = self:getLevel() - 1
		stats.health = stats.health + (level * self:getVocation():getHealthGain())
		stats.mana = stats.mana + (level * self:getVocation():getManaGain())
		stats.capacity = stats.capacity + (level * self:getVocation():getCapacityGain())
	-- Main vocations
	else
		local baseLevel = self:getLevel() - 1
		local baseVocation = Vocation(VOCATION.ID.NONE)
		local level = 0
		if self:getLevel() > 8 then
			baseLevel = 7
			level = self:getLevel() - 8
		end
		stats.health = stats.health + (baseLevel * baseVocation:getHealthGain()) + (level * self:getVocation():getHealthGain())
		stats.mana = stats.mana + (baseLevel * baseVocation:getManaGain()) + (level * self:getVocation():getManaGain())
		stats.capacity = stats.capacity + (baseLevel * baseVocation:getCapacityGain()) + (level * self:getVocation():getCapacityGain())
	end
	self:setMaxHealth(stats.health)
	self:addHealth(stats.health)
	self:setMaxMana(stats.mana)
	self:addMana(stats.mana)
	self:setCapacity(stats.capacity)
	return true
end
```

Call it in on a existing or new `onLogin` event like: [/data/scripts/creaturescripts/others/login.lua](https://github.com/opentibiabr/otservbr-global/blob/develop/data/scripts/creaturescripts/others/login.lua#L23)

Like this: 
```
local playerLogin = CreatureEvent("PlayerLogin")

function playerLogin.onLogin(player)
	player:updateStats()
end
```

I havent tested the function to be honest: just a fast edit of function player:changeVocation: https://github.com/opentibiabr/otservbr-global/blob/develop/data/lib/others/dawnport_lib.lua#L21 but for sure what you ask for is possible.

**Comment by Rechdan** [comment]
@ElTeixe thank you! I'll test it and confirm if it worked

**Comment by Rechdan** [comment]
@ElTeixe amazing script, I made a few changes in it but yours works 100%!

Here's what I came up with:
```lua
function Player.updatePlayerBaseStats(self)
	local level = self:getLevel()

	local rookVoc = Vocation(VOCATION.ID.NONE)
	local playerVoc = self:getVocation()

	local rookLevel = level
	if rookLevel > 8 then
		rookLevel = 8
	end

	local mainLevel = level - 8

	local health = stats.health + (rookLevel * rookVoc:getHealthGain())
	local mana = stats.mana + (rookLevel * rookVoc:getManaGain())
	local capacity = stats.capacity + (rookLevel * rookVoc:getCapacityGain())

	if mainLevel > 0 then
		health = health + (mainLevel * playerVoc:getHealthGain())
		mana = mana + (mainLevel * playerVoc:getManaGain())
		capacity = capacity + (mainLevel * playerVoc:getCapacityGain())
	end

	self:setMaxHealth(health)
	self:setMaxMana(mana)
	self:setCapacity(capacity)

	self:addHealth(health)
	self:addMana(mana)
end
```

With this one I could even update the HP/MP recovery amount

Thanks again mate!

**Comment by ElTeixe** [comment]
@Rechdan  Good to know!

**Comment by Rechdan** [comment]
I'll close the issue, but a functionality like this would be really nice to have built in the server, thanks!
