### ISSUE TITLE
BUG: build (make)

### ISSUE THREAD

**Issue by gustavotfs** [opentibiabr/otservbr-global-archived#2428]
estou com esse problema, não sei se eu fiz alguma coisa errada ou deixei de fazer algo.
antes eu compilava certinho, mas após ter feito a atualização (baixado tudo de novo daqui) tentei recompilar e aparece essa mensagem (ubuntu 16)

`-- MySQL Include dir: /usr/include/mysql  library dir: /usr/lib/x86_64-linux-gnu
-- MySQL client libraries: /usr/lib/x86_64-linux-gnu/libmysqlclient.so;-ldl
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   system
--   filesystem
--   iostreams
--   date_time
--   regex
CMake Error at CMakeLists.txt:68 (find_package):
  By not providing "Findjsoncpp.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "jsoncpp", but
  CMake did not find one.

  Could not find a package configuration file provided by "jsoncpp" with any
  of the following names:

    jsoncppConfig.cmake
    jsoncpp-config.cmake

  Add the installation prefix of "jsoncpp" to CMAKE_PREFIX_PATH or set
  "jsoncpp_DIR" to a directory containing one of the above files.  If
  "jsoncpp" provides a separate development package or SDK, be sure it has
  been installed.

-- Configuring incomplete, errors occurred!
See also "/home/source/build/CMakeFiles/CMakeOutput.log".
See also "/home/source/build/CMakeFiles/CMakeError.log".
`
O que eu preciso instalar para resolver?

**Comment by majestyotbr** [comment]
`ca-certificates libcurl4-openssl-dev libjsoncpp-dev`
https://github.com/opentibiabr/otservbr-global/wiki/Compiling-on-Ubuntu

**Comment by gustavotfs** [comment]
verdade eu estava procurando e acabei usando isso
sudo apt-get update && sudo apt-get install cmake build-essential ca-certificates libcurl4-openssl-dev libjsoncpp-dev liblua5.2-dev libmysqlclient-dev libboost-system-dev libboost-iostreams-dev libboost-filesystem-dev libpugixml-dev libcrypto++-dev libspdlog-dev libluajit-5.1-dev libboost-date-time-dev
dai resolveu
obrigado e desculpa
