### ISSUE TITLE
Compilado de Erros/Bugs/Coisas Faltando/Etc:

### ISSUE THREAD

**Issue by Lycanzito** [opentibiabr/otservbr-global-archived#243]
Compilado de Erros/Bugs/Coisas Faltando/Etc:

1- Experience Gain Rate, 1 = 100%, 10 = 1000% ( Só assim para funcionar a Boost Experience da Store)
2- Coins não Atualizam no Market
3- Ao Abrir "History" você toma um bom e velho Debug
4- Vocação na lista aparecendo com numero
5- Mesmo com a informação de "free premium" ,aparece a info de free account
6- 2 monstros iguais na prey system ou até mais de 2 (funcionando/ sem os efeitos da prey)
8- Cast System Sem funcionar ( Versão 12)

Algumas imagens para ilustrar os "errors" do 1 ao 6

https://imgur.com/a/04cK1HB

**Comment by Lycanzito** [comment]
Alguém para comentar? Algum desenvolvedor?

**Comment by gpedro** [comment]
1 - não entendi.
2 e 3 - ainda estamos trabalhamos para corrigir o market. existem algumas alterações que estão sendo estudadas. (#209 e #251)
4 e 5 - Isso é problema do seu login.php
6 - O Prey System foi refeito e foi adicionado hoje (#234)
7 - isso já foi reportado em #4 
8 - Precisa ser refeito também, não funciona por que muita coisa mudou, porém, pode ser seu login.php também/

**Comment by Lycanzito** [comment]
o 7,  foi concluido! boa =), vou remover da lista

@gpedro o numero 1, que eu me refiro, é a experiencia que aparece na barra de skills, para ser igual o Tibia global, 10x de experiência, seria 1000%, e não, 10% como é atualmente.

**Comment by Lycanzito** [comment]
@gpedro @mattyx14 Depois da ultima atualização do exeta res, os monstros não estão dropando loot.

**Comment by mattyx14** [comment]
try gpedro now moment no have pc

**Comment by ghost** [comment]
> @gpedro @mattyx14 Depois da ultima atualização do exeta res, os monstros não estão dropando loot.

![2019-07-17 14_54_18-Window](https://user-images.githubusercontent.com/4684880/61401088-0eee9680-a8a8-11e9-8074-df0c85b73ca1.jpg)
tão sim

**Comment by Lycanzito** [comment]
> > @gpedro @mattyx14 Depois da ultima atualização do exeta res, os monstros não estão dropando loot.
> 
> ![2019-07-17 14_54_18-Window](https://user-images.githubusercontent.com/4684880/61401088-0eee9680-a8a8-11e9-8074-df0c85b73ca1.jpg)
> tão sim

NO DROP LOOT #281

da uma olhada

**Comment by gpedro** [comment]
@Lycanzito can you check if all issues are solved?
