### ISSUE TITLE
FEATURE: Autoloot option on config.lua

### ISSUE THREAD

**Issue by leonardoelias300** [opentibiabr/otservbr-global-archived#2432]
Option to enable an autoloot system when the player kill a monster, using the QuickLoot whitelist/ignore list already implemented or a function doPlayerQuickLoot to call from a script using the onKill method, replacing the need to click on the dead corpse.

**Comment by oualid6496** [comment]
@leonardoelias300 Is that the same as real tibia? Haven't played it in a long time but I don't think it is. If it indeed isn't then that's more a suggested feature then missing content.

**Comment by leonardoelias300** [comment]
_

> > @leonardoelias300 Is that the same as real tibia? Haven't played it in a long time but I don't think it is. If it indeed isn't then that's more a suggested feature then missing content.

_
I haven't played the real tibia in a long time too, only OT. I changed the title but idk how to change the tag.
I'm trying to figure out how to do it without changing the source code but haven't got success yet. A call function **doPlayerQuickLoot** to call the void **Game::internalQuickLootCorpse** would come in handy. Its a content on most OT servers but I really don't know if its present on real tibia since the engine is kinda diffrent.
At this time, the player needs to press [ Alt ] + [ Mouse Click ] on dead corpse to send a opCode to server to activate the QuickLoot.

**Comment by henriquesameshima** [comment]
Tibia Global doesn't have this automatic quick loot function. It would be a feature that could be implemented.

**Comment by hyresu** [comment]
This was added before and removed as well because it isn't a global feature, this is custom and if you want to add it use this link

https://forums.otserv.com.br/index.php?/forums/topic/169047-tfs-13-autoloot-modal-window/
