### ISSUE TITLE
BUG: dead monster

### ISSUE THREAD

**Issue by Bipbop69** [opentibiabr/otservbr-global-archived#2439]
Paladin  Apparition
Sruid Apparition
Sorcerer Apparition
Knight Apparition

it is not possible to use auto loot on this monsters

**Comment by oualid6496** [comment]
confirmed

**Comment by ElTeixe** [comment]
I wonder how you got noticed about this if they are not currently on the map. Do you have some of the Soul War areas maps?

**Comment by oualid6496** [comment]
Nope, you can spawn them. But im using a custom map. There is this new thais area that already has been added (for a part) which im using.

**Comment by ElTeixe** [comment]
> Nope, you can spawn them. But im using a custom map. There is this new thais area that already has been added (for a part) which im using.

Well I was referring to the OP (@joao-blip), my fault. I know you can spawn them lol. Anyway thanks for explain your use of them.
