### ISSUE TITLE
Crash ao dar /reload creaturescripts

### ISSUE THREAD

**Issue by LukSrT** [opentibiabr/otservbr-global-archived#244]
**Describe the bug**
Ao dar reload creaturescripts, o servidor crasha sem nenhuma explicação
gdb: https://pastebin.com/vDQBaagN

**Comment by LukSrT** [comment]
Apagando tds os onThink aparece esse erro:
https://pastebin.com/K4QjZcX8

**Comment by granoob** [comment]
estranho que não tenho isso acontecendo ainda mais quem sabe...

**Comment by LukSrT** [comment]
Basicamente só clonei o repositório e segui essa etapa:
Primeiro exemplo:
Loguei duas contas no servidor
Uma deixei parada e a outra eu dei /reload creaturescripts e logo em seguida o servidor caiu

Segundo exemplo:
Apaguei todos os onthinks, loguei no servidor, dei reload e em seguida ataquei um monstro.

**Comment by granoob** [comment]
umm.., eu vir relatos sobre isso com pessoas usando linus debian, ja que uso ubuntu comigo nao acontece ainda

**Comment by Costallat** [comment]
Checked here with Ubuntu 18.04 and I was able to reproduce it, sometimes it works, sometimes it crash on the first run, and sometimes it crash on the second run, it looks that it is trying to use a pointer that was not initialised or it is being changed. There is one PR on TFS that is mentioning a problem in the reload system.

**Comment by EvilHero90** [comment]
This PR will solve the problem
https://github.com/otland/forgottenserver/pull/2634
