### ISSUE TITLE
Bug closed door

### ISSUE THREAD

**Issue by juansanchesz** [opentibiabr/otservbr-global-archived#2440]
in lib/tables/door.lua it's:

	{ lockedDoor = 3535, closedDoor = 3336, openDoor = 3537 },

the correct would be:

	{ lockedDoor = 3535, closedDoor = 3536, openDoor = 3537 },

**Comment by beats-dh** [comment]
I took a while to see this 5! Kk

**Comment by dex-89** [comment]
You haven't updated the repository. This has been corrected.
