### ISSUE TITLE
Plain, Valueable and Ornate weapons.

### ISSUE THREAD

**Issue by kungen32** [opentibiabr/otservbr-global-archived#2455]
Hello,

Plain, valuable and ornate items, sword, axe, chopper, mace, are working with modify, critical, damage, adding correctly stats and imbuements.
Rod, wand , crossbow and bow, can change only Attak and def, but adding anything death or what ever you want, this not add on character the changes, for example add on item 29242 critical chance 30%, then add it on unscriptted weapons, this doesnt work.
Happens on rod , wand bow and crossbow from Valueable, plain and ornate, from Mayhem, Remedy and Carving.
Also, give's and error trying modify, all items become's an ' You see an Item type ID Item '.

**Comment by dudantas** [comment]
What are you talking about?

Explain how to test the bug... You said several things that made no sense to me.

**Comment by kungen32** [comment]
Yes, i was looking for this weapons, has not more obtainables in versions 12X, server is running ultra fine eh, no problem with this.

Item id: 29242, you can add on all weapons, shields, amulets, all what is equipement, a critical chance, on this we are ok right ?
So in some of Ornate, Valuables Mayhem/Carving and Remedy, if you add attibute key="criticalhitchance" value="30"  for example i dont remember the line of critical now, doesnt work. Was trying to add new items, and finally i add some unobtainables items like listed in wiki as a fansite items, and this one like shields and hats giving correctly this stat, but some of Valuables Mayhem Bow / ornate mayhem bow, if you try to add this stats, YES they show it, but they are not adding on player stats and is not working, i dont know if really is a bug or not ( i have also added on unscripted_weapons also ) and is still not working, i know no one is looking for this old weapons, but graphically still very beautiful and cannot use it giving more stats than , attack and defense, not more, adding magic level, not working ( bows & crossbows ) , wands cannot be changed with an element attack, ( the only working till now, was Knight weapons ).
We are 4 people working on this ot, i am sorry about my english is bad, im french, and all 4 have tested modify each item in game and this items was the only one cannot change stats.

**Comment by hyresu** [comment]
> Yes, i was looking for this weapons, has not more obtainables in versions 12X, server is running ultra fine eh, no problem with this.
> 
> Item id: 29242, you can add on all weapons, shields, amulets, all what is equipement, a critical chance, on this we are ok right ?
> So in some of Ornate, Valuables Mayhem/Carving and Remedy, if you add attibute key="criticalhitchance" value="30" for example i dont remember the line of critical now, doesnt work. Was trying to add new items, and finally i add some unobtainables items like listed in wiki as a fansite items, and this one like shields and hats giving correctly this stat, but some of Valuables Mayhem Bow / ornate mayhem bow, if you try to add this stats, YES they show it, but they are not adding on player stats and is not working, i dont know if really is a bug or not ( i have also added on unscripted_weapons also ) and is still not working, i know no one is looking for this old weapons, but graphically still very beautiful and cannot use it giving more stats than , attack and defense, not more, adding magic level, not working ( bows & crossbows ) , wands cannot be changed with an element attack, ( the only working till now, was Knight weapons ).
> We are 4 people working on this ot, i am sorry about my english is bad, im french, and all 4 have tested modify each item in game and this items was the only one cannot change stats.

Try adding them to unscripted_equipment.lua

**Comment by kungen32** [comment]
Is what i say, i add it on Unscripted and restart server, but doesnt working, for this i reported here ( i have downloaded 3 Days ago the version of otservbr )

**Comment by hyresu** [comment]
> Is what i say, i add it on Unscripted and restart server, but doesnt working, for this i reported here ( i have downloaded 3 Days ago the version of otservbr )

There are 2 files
unscripted_weapons.lua on data/scripts/weapons
and
unscripted_equipments.lua on data/scripts/movements/equipment

You said you added them to unscripted_weapons.lua, but I said unscripted_equipments.lua, try there too please.

**Comment by kungen32** [comment]
They are all added in Unscripted_equipements, for this i dont tell about this script, this one has Equip and Deequip, is seems to be ok, but is not working when you add critical damage, life leech, maxhitpoints, maxmana, skill, is not working too.

**Comment by VyroNeoz** [comment]
> They are all added in Unscripted_equipements, for this i dont tell about this script, this one has Equip and Deequip, is seems to be ok, but is not working when you add critical damage, life leech, maxhitpoints, maxmana, skill, is not working too.

![imagen_2021-03-01_150534](https://user-images.githubusercontent.com/60127859/109558884-926df300-7a9f-11eb-98ee-c430e9b5c086.png)

It works if you do all the thing he said hyresu about:
unscripted_weapons.lua on data/scripts/weapons
and unscripted_equipments.lua on data/scripts/movements/equipment
this is my example in items.xml 

`<item id="29242" article="an" name="ornate mayhem crossbow">
		<attribute key="weight" value="4000" />
		<attribute key="slotType" value="two-handed" />
		<attribute key="loottype" value="distance" />
		<attribute key="range" value="5"/>
		<attribute key="hitChance" value="10"/>
		<attribute key="attack" value="6"/>
		<attribute key="skilllifechance" value="100" />
		<attribute key="skilllifeamount" value="5" />
		<attribute key="skillDist" value="1" />
		<attribute key="weaponType" value="distance"/>
		<attribute key="ammoType" value="bolt"/>
		<attribute key="imbuingSlots" value="3" />
	</item>`
and with imbuiments also works.

i dont know how to add maxhp, max mana.

**Comment by kungen32** [comment]
![Notworking](https://user-images.githubusercontent.com/77188623/109675175-d7655880-7b77-11eb-83a6-4be2472513c5.png)

I Tried with others , restarting server 200 Times, im going try again re download the server.... maybe 3 days ago not works i dont know really.

You can with, maxHitPoints,  maxManaPoints

**Comment by kungen32** [comment]
After Download it again, now yes is working, but before was not working.
