### ISSUE TITLE
BUG: Monsters Resistance

### ISSUE THREAD

**Issue by kungen32** [opentibiabr/otservbr-global-archived#2458]
Hello, 

After check with some differents vocations, about some damages doing on some monsters, i see a lot of monster has resistances are not same as i know for some of them, and same as wiki ( maybe wiki is not updated ) , but i take one i know was Grimeleech, and i know they take a normal damage in ice, but this one has a before type = combat_icedamage, percent = 65 , it means 65% Resis of Ice, im right ? Is, taken 100% damage from ice, should be 0 if no ?
I this case, have see a lot of monsters with resistances are not same , demon, vexclawn.. each time is 5-50 difference in some of them, well there is to much for write it.
It's just to inform.
There is pastebin of correct grimeleech

Pastebin of lua: https://pastebin.com/9QA5HcJB

**Comment by phacUFPE** [comment]
can you list the monsters that need elements revision ?
