### ISSUE TITLE
BUG: Going up and down stairs/levels

### ISSUE THREAD

**Issue by Yatoziin** [opentibiabr/otservbr-global-archived#2459]
#### Describe the bug
> Players are experiencing very high ping increase/ lag when going up and down level/stairs

#### How to Reproduce?
>Go up and down stairs

#### Logs or errors
>none

#### Environment
- OS (Ubuntu 20.04): 
- Tibia Version (e.g. 12.61):

**Comment by travisani** [comment]
Are you using Real Files, Real Map? do any changes? Check if u do any new bugged script.
It's ok for me on test, try to recompile with your correct system configs.
