### ISSUE TITLE
CONTENT: SOUL WAR QUEST

### ISSUE THREAD

**Issue by jairocarvalho** [opentibiabr/otservbr-global-archived#2460]
I would like to know if you have plans to add the soul war quest, or how many updates we are after this update of the soul war quest, my project is being defined, and these answers can help me make some decisions, thank you in advance.

**Comment by UReddington** [comment]
Soul war quest maps and content are being added by the same community, likely it wouldn't be added unless someone else has the initiative to do it.

Also keep on mind that this is a community runned project, there isn't a "planned" schedule more than be up to date with the cipsoft protocol.

**Comment by travisani** [comment]
Let us time, and we will do... have a lot leechers here, try to help too.

**Comment by Badeburu** [comment]
I will wait all mechanics... all maps you found in web foruns... only i cant found ebb and flow

**Comment by majestyotbr** [comment]
Added to #726.
