### ISSUE TITLE
BUG: Server crash after a lot of monsters target you.

### ISSUE THREAD

**Issue by gccris** [opentibiabr/otservbr-global-archived#2461]
#### Describe the bug
> I'm receving a server exception whenever i try to get down from a floor and a lot of monsters try to focus you.

#### How to Reproduce?
> Summon several monsters on a floor below (for example, floor 8), using a normal character, go down the ladder and the error will show up.
Error shows up on function Monster::doAttacking of monster.cpp file.

> Give us all details to reproduce the behavior:
> 1. Create 30+ rats (or any monster) on floor 8 (or any floor)
> 2. Using a normal character(not a god), go down on stairs/ladder
> 3. All monsters will target you and server will crash
> 4. See error :
Exception thrown at 0x00007FF612CCD0A0 in otservbr-global-x64.exe: 0xC0000005: Access violation executing location 0x00007FF612CCD0A0.

#### Logs or errors
> Exception thrown at 0x00007FF612CCD0A0 in otservbr-global-x64.exe: 0xC0000005: Access violation executing location 0x00007FF612CCD0A0.
![image](https://user-images.githubusercontent.com/9938654/109888451-48813a80-7c62-11eb-9afb-0606a15834b7.png)

#### Expected behavior
> All monsters target you correctly.

#### Screenshots
> If applicable, add screenshots to help explain your problem.

#### Environment
- OS : Windows 
- OTServ Version (e.g. commit): last commit.
- Tibia Version (e.g. 12.61): 

#### Additional context
> Add any other context about the problem here.

**Comment by henriquesameshima** [comment]
It doesn't happen here. Did you change anything in the sources? Would you know if it is in a specific place?

![rat](https://user-images.githubusercontent.com/9365346/109896254-5f7a5980-7c6f-11eb-8f23-2783fe5cc755.gif)

**Comment by Bipbop69** [comment]
tested with the screen full of monsters I had no problems

**Comment by kungen32** [comment]
Tested full animations, Infernal Demons, Brachiodemons also, there is no bug about this, but, if you have downloaded a version without compiling it, yes you get some of this errors.

**Comment by travisani** [comment]
Probably your system make crashes because video graphics fault try to do this with new graphcs settings again.

**Comment by travisani** [comment]
![image](https://user-images.githubusercontent.com/13306169/110383178-b0f16280-803a-11eb-95ce-5503cebf6e48.png)

**Comment by gccris** [comment]
idk what happened, but this error stopped. Maybe it was something related to bad memory position, some weird thing on my machine. After multiples restarts and re builds on source, everythings seems to work fine. I will close it and if happens again, reaise more details and tag to this.
