### ISSUE TITLE
BUG: Imbuements not working properly

### ISSUE THREAD

**Issue by rusaskii** [opentibiabr/otservbr-global-archived#2463]
#### Describe the bug
Leech imbues only affect 1 monster.  You make exori on full box and you will receive mana from one monster. 

#### How to Reproduce?
Imbue any weapon or helmet with mana leech. 
Make area damage on monsters.

**Comment by lichak232** [comment]
Hello,
mana leech on real tibia, gain you mana from one monster not more. -- sorry but my english is easy.

**Comment by rusaskii** [comment]
You are right, I got confused.
