### ISSUE TITLE
BUG: Free Quest INQU

### ISSUE THREAD

**Issue by cys9211** [opentibiabr/otservbr-global-archived#2465]
#### Describe the bug

You cannot complete The Inquisition Quest using the "freequests" function.
You can buy vial of water from NPC Henricus, but after taking the last step on the magic wall, you cannot talk to the NPC about completing the mission.
![Zrzut ekranu z 2021-03-06 11-37-28](https://user-images.githubusercontent.com/7588103/110204182-25c57080-7e72-11eb-8560-94c0430508b3.png)
![Zrzut ekranu z 2021-03-06 11-37-41](https://user-images.githubusercontent.com/7588103/110204184-26f69d80-7e72-11eb-89f5-1e1765f69b92.png)
![Zrzut ekranu z 2021-03-06 11-38-04](https://user-images.githubusercontent.com/7588103/110204185-28c06100-7e72-11eb-964c-29a81d07dfdd.png)
![Zrzut ekranu z 2021-03-06 11-38-17](https://user-images.githubusercontent.com/7588103/110204190-2b22bb00-7e72-11eb-9080-675ff133a28b.png)
![Zrzut ekranu z 2021-03-06 11-39-09](https://user-images.githubusercontent.com/7588103/110204192-2d851500-7e72-11eb-923f-f57d7557abd3.png)
![Zrzut ekranu z 2021-03-06 11-39-31](https://user-images.githubusercontent.com/7588103/110204199-2fe76f00-7e72-11eb-850a-0b133464b8d7.png)
![Zrzut ekranu z 2021-03-06 11-39-48](https://user-images.githubusercontent.com/7588103/110204202-3249c900-7e72-11eb-9d60-5be23f9973dd.png)

**Comment by dex-89** [comment]
This is not a bug. Free missions are a custom item from us for you. It will not be improved. We will try to improve the missions according to the Tibia rules.
