### ISSUE TITLE
MONSTERS ADD

### ISSUE THREAD

**Issue by le0z3r4** [opentibiabr/otservbr-global-archived#2477]
How do I add new monsters if there is no monsters.xml file?

**Comment by UReddington** [comment]
Using revscripts, that's lua

**Comment by le0z3r4** [comment]
I already got to copy the file .moon and just change the name of the creature, even so I can't add in the game. Do I have to add it to any other file?

**Comment by le0z3r4** [comment]
I already got to copy the file .lua and just change the name of the creature, even so I can't add in the game. Do I have to add it to any other file?
