### ISSUE TITLE
BUG: Offline Training cause connection lost

### ISSUE THREAD

**Issue by ghost** [opentibiabr/otservbr-global-archived#2492]
#### Describe the bug
> When using offline training in bed or skill trainer, client experiences loss of connection before returning to the character selection screen.

#### Screenshots
> 
![image](https://user-images.githubusercontent.com/81339085/112408419-82d87780-8cf6-11eb-8f73-4292f3bd5007.png)

![image](https://user-images.githubusercontent.com/81339085/112408437-8c61df80-8cf6-11eb-89f5-2d40e0267acc.png)

#### Environment
- OS: Windows 10
- OTServ Version: 19/03/2021
- Tibia Version: 12.64

**Comment by givera12** [comment]
it's not only offline training, every logout show this communicat... please fix

**Comment by dudantas** [comment]
> it's not only offline training, every logout show this communicat... please fix

This is not true. It is only in offline training.

**Comment by Juanzin420** [comment]
please revise, the change caused reconnecting throw character list (Ctrl+G) to bug and never reconnect to game
steps:
1- login on char,
2- ctrol+G to another char
3- ctrol+G to the char u first login
4- see error(never connecting)
