### ISSUE TITLE
BUG: Cannot find some monsters on prey list

### ISSUE THREAD

**Issue by Owaeka** [opentibiabr/otservbr-global-archived#2493]
#### Describe the bug
> I have used 5 prey wildcards in order to select Plaguesmit, but the monster is not in the list

#### How to Reproduce?
> Just use 5 prey wildcards and search for plaguesmith

#### Expected behavior
> The monster should be in the list just like the others

#### Screenshots
> 
![prey_monster](https://user-images.githubusercontent.com/6351237/112697524-7a06b380-8e66-11eb-90fc-49037c6a86fa.png)

#### Environment
- OS server at ubuntu 18.04
- OTServ Version #2478
- Tibia Version 12.64

**Comment by kungen32** [comment]
Hello,
This is the proof you never try to modify a little bit the game...
You can add by youself all Monsters and Bosses in Prey.
Go in Prey_system file, open Assets & Prey in a notepad
Search plaguesmith in your database folder, you will find ' Race ID ' 314
Check ctrl+f 314 if is in assets.lua, if not add it, where you want "314" 
The go in Prey.lua , you will see ' Tier Bronze / Tier Silver / Tier Gold '
This works with level, if you want to see only Plaguesmith in higher levels, add the name , "Plaguesmith" in Gold Tier , 
If you want see it in all levels, add it in each tier.
Save , make a /reload modules in game.

**Comment by Owaeka** [comment]
I didn't know about the assets.lua file
thanks!

**Comment by kungen32** [comment]
You can modify all, then if is something in ' look ' of Preys, this you can change background etc, editing tibia client 12x
![6 png e3f289010ee02b753c075dc4807fa75a](https://user-images.githubusercontent.com/77188623/112751388-113a4b00-8fce-11eb-8758-2c69ef9883bb.png)
![nouveauclient1 thumb png e760030d36c71776f47eb516b690cdaf](https://user-images.githubusercontent.com/77188623/112751391-139ca500-8fce-11eb-9ad1-a31e5b3973b7.png)

**Comment by Eufuriaa** [comment]
What about were Werehyaena, Werehyaena Shaman? coz i add it to asset.lua and it dosent work
