### ISSUE TITLE
BUG: market deport

### ISSUE THREAD

**Issue by Bipbop69** [opentibiabr/otservbr-global-archived#2505]
the market in some cities is not opening 

Bounac,,Issavi,Feyrist

**Comment by adrianomengue** [comment]
That's because these are not cities yet. (On our base).

**Comment by Bipbop69** [comment]
would you have to create the town on the editor map?
created for the forehead but not activated
can you tell where this verification is in the src?

**Comment by dex-89** [comment]
#2399 it was fixed, but not merged yet

**Comment by Bipbop69** [comment]
> #2399 it was fixed, but not merged yet

I looked on the map and in the code I didn't find the change related to the market

**Comment by dex-89** [comment]
> > #2399 it was fixed, but not merged yet
> 
> I looked on the map and in the code I didn't find the change related to the market

It was added to global map `.otbm` file
