### ISSUE TITLE
Lost Soul creatures and usuper archer [Monster-LUA]

### ISSUE THREAD

**Issue by Lucasvdo** [opentibiabr/otservbr-global-archived#2514]
Follow the 'Lua' files of the Lost Soul creatures and the Archer usuper

[_new.zip](https://github.com/opentibiabr/otservbr-global/files/6261782/_new.zip)

**Comment by adrianomengue** [comment]
Lucas, please create a new PULL REQUEST, also, Usurper's monsters are already created in this PR #2334

**Comment by majestyotbr** [comment]
Lost Soul monsters and Usurper Archer are already in the datapack.
