### ISSUE TITLE
BUG: INQUISITOR QUEST players dont get the holy water

### ISSUE THREAD

**Issue by easy2host** [opentibiabr/otservbr-global-archived#2516]
#### Describe the bug
> Players cant get the holy water (special flask) item id 7494 from Henricus, so they cant finish the inquisitor quest

Latest Tibia Version 12.64 downloaded today compiled on ubuntu 20.04

**Comment by adrianomengue** [comment]
What message the player was supposed to say to get the holy water? Does it need some part of the quest already done?

**Comment by easy2host** [comment]
the thing is, i cant start the quest at all. you tell hi then inquisitor
then after word join, nothing happens. the quest will not start

**Comment by easy2host** [comment]
minato nakamize-sama

**Comment by adrianomengue** [comment]
Ok, I'll take a look today to see how it can be fixed. I guess it's not a big deal.

**Comment by adrianomengue** [comment]
![image](https://user-images.githubusercontent.com/19974082/114112198-48540a80-98b2-11eb-850c-af61f30af084.png)

Hi - Inquisitor - Join - Yes

**Comment by majestyotbr** [comment]
Hi - Inquisitor - Join - Yes
