### ISSUE TITLE
When you change floor/screen fastly makes character lost it outfit and instantly becomes invisible

### ISSUE THREAD

**Issue by Feliipe93** [opentibiabr/otservbr-global-archived#252]
**Describe the bug**
When player change from floor  using stairs,teleports or whatever, the player instantly gets invisible, this happens on tibia 10 11 and 12

**To Reproduce**
use an stairs, sewer graters , upside or down it doesnt matters
Note: include any configuration/script required to reproduce.

**Expected behavior**
do not change outfit while youre performing the action of stair or use something to change floor

**Comment by westwol** [comment]
This only happens on a god character, and it works as inteed.
