### ISSUE TITLE
BUG: Store Carpet

### ISSUE THREAD

**Issue by Bipbop69** [opentibiabr/otservbr-global-archived#2554]
even placing the quantity of 5 items the player when purchasing receives only 1 item

**Comment by kungen32** [comment]
Keep it to 1, not on 5 and lose 30 Seconds more.

**Comment by Bipbop69** [comment]
> Keep it to 1, not on 5 and lose 30 Seconds more.

so it will be the same as the global 

![image](https://user-images.githubusercontent.com/64280614/116622827-aefd9e80-a91b-11eb-8f8a-2fdda66cd9e7.png)

**Comment by majestyotbr** [comment]
For purchases in house category, the gamestore need to be edited to accept count > 1 and edit decoration kit to come in a parcel for example.
