### ISSUE TITLE
BUG: compile cmake 

### ISSUE THREAD

**Issue by Zapotoczny** [opentibiabr/otservbr-global-archived#2564]
-- Disabled: ccache
-- Enabled: ipo
-- Enabled: openmp
-- Disabled: DEBUG LOG
CMake Error at src/CMakeLists.txt:88 (find_package):
  Could not find a package configuration file provided by "cryptopp" with any
  of the following names:

    cryptoppConfig.cmake
    cryptopp-config.cmake

  Add the installation prefix of "cryptopp" to CMAKE_PREFIX_PATH or set
  "cryptopp_DIR" to a directory containing one of the above files.  If
  "cryptopp" provides a separate development package or SDK, be sure it has
  been installed.

**Comment by majestyotbr** [comment]
https://github.com/opentibiabr/otservbr-global/wiki/Compiling-on-Ubuntu-or-Debian-GNU-Linux
