### ISSUE TITLE
BUG: Crash server stash items

### ISSUE THREAD

**Issue by lichak232** [opentibiabr/otservbr-global-archived#2578]
Hello my dear,
I found a problem that crash the server. When we go to the depo and quickly click "stow all items this type" server is crashed.
Earlier and later when I added: https://github.com/opentibiabr/otservbr-global/pull/2359 problem still exists.
I'm sorry, but my english is easy.

**Comment by givera12** [comment]
it's fixed here:

https://github.com/opentibiabr/otservbr-global/pull/2448
