### ISSUE TITLE
Monsters drop no loot

### ISSUE THREAD

**Issue by Davenorthern** [opentibiabr/otservbr-global-archived#258]
**Describe the bug**
None of the monsters drop any loot. The bodies are empty and there are no server messages such as "loot of a minotaur: nothing."

**To Reproduce**
Note: include any configuration/script required to reproduce.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Version: [e.g. 10]
Windows 10.

**Additional context**

**Comment by majestyotbr** [comment]
If you are god, disable notgenerateloot flag on data/xml/groups.xml.
