### ISSUE TITLE
BUG:  exana vita

### ISSUE THREAD

**Issue by bashcode** [opentibiabr/otservbr-global-archived#2583]
#### Describe the bug
> when use exana vita spell, appear error (Warning!, never give your password to anybody or tell anybody which email address is asigned to your tibia account" 

#### How to Reproduce?
> using exana vita spell

#### Screenshots
![error](https://user-images.githubusercontent.com/8944176/118308479-fc504300-b4b9-11eb-848b-a8393e0567a7.png)

**Comment by Aerwix** [comment]
Hahahaha, make sure any of your accounts/password have one of this words on ur database. All good on my distro 👍 

![ezgif com-gif-maker](https://user-images.githubusercontent.com/26527255/118313830-f017b600-b4b8-11eb-84dd-c2239b355c90.gif)
