### ISSUE TITLE
FEATURE: Backpacks

### ISSUE THREAD

**Issue by Bipbop69** [opentibiabr/otservbr-global-archived#2585]
Backpack is not saving your spot
example below 
![image](https://user-images.githubusercontent.com/64280614/118338648-10616800-b4ed-11eb-8d2e-74b9ba97a577.png)

now after relogging 
![image](https://user-images.githubusercontent.com/64280614/118338716-371f9e80-b4ed-11eb-8497-2b1025010a4d.png)

**Comment by majestyotbr** [comment]
Already reported in #2450
