### ISSUE TITLE
BUG: Game store, Cant buy blessings

### ISSUE THREAD

**Issue by Mattehj** [opentibiabr/otservbr-global-archived#2597]
#### Describe the bug
> I cant buy blessing for coins, It says you already have all blessings, I don't have any blessing..
It could buy bless like idk 5 times for coins, Then this happened, so it worked before
#### How to Reproduce?
> Idk what it reproduce means, But if i google it, it say its something sexual :S

> Give us all details to reproduce the behavior:
> 1. Walk to city '...'
> 2. Click on item '....'
> 3. Drag it to backpack '....'
> 4. See error

#### Logs or errors
> Please include any errors or logs that are relevant

#### Expected behavior
> I should be able to buy blessings for coins

#### Screenshots
> If applicable, add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/84507314/119179955-e02b4380-ba6f-11eb-8642-90fb34f425f4.png)

#### Environment
- OS (e.g. Windows): 
- OTServ Version (e.g. commit): 
- Tibia Version (e.g. 12.52): 

#### Additional context
> Add any other context about the problem here.

**Comment by majestyotbr** [comment]
![image](https://user-images.githubusercontent.com/32709570/120900384-e17d7400-c60a-11eb-80c7-a15b1c0c15c2.png)
![image](https://user-images.githubusercontent.com/32709570/120900354-bbf06a80-c60a-11eb-8355-0084cf5bf2e1.png)
