### ISSUE TITLE
BUG: PREY CRASH

### ISSUE THREAD

**Issue by michu940107** [opentibiabr/otservbr-global-archived#2599]
WHEN U REROLL PREY IT CRASHED THE SERVER

**Comment by rusaskii** [comment]
More information.. 
How to Reproduce?

Im rerolling and it's working fine. Maybe some specific monster?

**Comment by dan4ndrade** [comment]
@michu940107 

I tested in current version and dont have problems...

![image](https://user-images.githubusercontent.com/19895470/120545370-f2d53f00-c3c4-11eb-9eb1-14146a9f9932.png)
