### ISSUE TITLE
BUG: Cant acces gnomebase alpha

### ISSUE THREAD

**Issue by Mattehj** [opentibiabr/otservbr-global-archived#2601]
#### Describe the bug
I cant access gnomebase alpha. (Where the warzones 1,2,3 are) It says that my my rank is to low, but it is 1440

#### How to Reproduce?
> If you cannot reproduce an issue by redoing the same steps, we also will not be able :)

> Give us all details to reproduce the behavior:
> 1. Walk to city '...'
> 2. Click on item '....'
> 3. Drag it to backpack '....'
> 4. See error

#### Logs or errors
> Please include any errors or logs that are relevant
No errors.

#### Expected behavior
> A clear and concise description of what you expected to happen.

#### Screenshots
> If applicable, add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/84507314/119269447-0e3b8f80-bbf8-11eb-8deb-051abc3abc4e.png)
![image](https://user-images.githubusercontent.com/84507314/119269926-6b384500-bbfa-11eb-80e7-bcac84342dd0.png)

#### Environment
- OS (e.g. Windows): 
- OTServ Version (e.g. commit): 
- Tibia Version (e.g. 12.52): 

#### Additional context
> Add any other context about the problem here.

**Comment by dan4ndrade** [comment]
Hello @Mattehj.

In current version, i tested all the steps of quest and I didn't find any bug.

![image](https://user-images.githubusercontent.com/19895470/120542190-32019100-c3c1-11eb-824d-d5578325eb9b.png)

![image](https://user-images.githubusercontent.com/19895470/120542241-3fb71680-c3c1-11eb-94b4-fb696ac1bdfd.png)

How u improved your renown points?

Searching in the scripts, i found validations on rank in the crystal keepers and changing minor tokens on Gnomally.

**Comment by dan4ndrade** [comment]
![image](https://user-images.githubusercontent.com/19895470/120542743-db488700-c3c1-11eb-90be-e2d2c3709082.png)

**Comment by Mattehj** [comment]
Hello @danilommandrade 
I havent done the quest, because its added in freequests by default. But I cant talk to any npc or go anywhere cause it say to low rank,
