### ISSUE TITLE
BUG: Mana leech on multiple monsters is not working

### ISSUE THREAD

**Issue by Annbelmont** [opentibiabr/otservbr-global-archived#2604]
#### Describe the bug
> Imbuiment mana leech is not working properly when you attack multiple monsters, it on absorbs/leeches 
as if you were attacking only 1 creature  and not mutiple and does not apply the original formula: 

#### How to Reproduce?
> add mana leech imbuiment to any bow and attack a group of monsters with a diamond arrow
you will only manaleech 1 creature and not multiple creatures.

> Give us all details to reproduce the behavior:
tested with a pally bow and arrow (powerful void)
1.- hit 4 frazzlemaw with diamond arrow
2.- hit 1 frazzlemaw  with crystalline arrow

#### Logs or errors
15:17 You were restored for 4 mana.
15:17 A frazzlemaw loses 167 hitpoints due to your attack.
15:17 You were restored for 4 mana.
15:17 A frazzlemaw loses 167 hitpoints due to your attack.
15:17 You were restored for 4 mana.
15:17 A frazzlemaw loses 159 hitpoints due to your attack.
15:17 You were restored for 4 mana.
(Diamond arrow) total for  16 mana leeched

15:20 You were restored for 13 mana.
15:20 A frazzlemaw loses 168 hitpoints due to your attack.
(crystalline arrow) 13 mana leeched

#### Expected behavior
1.- restore 13 mana per creature with the diamond arrow

#### Environment
- OS win 10
- OTServ Version: 12/10
- Tibia Version tested on client 10 and 12

#### Additional context
> me and a friend were discussing this "probable" issue since it makes manaleech barely noticeable
-Are we applying the formula wrong?
-Is there a way to change this?
-Same thing happens with area spells /runes
-I did not modify the original 8% of the powerful void imbue

**Comment by lichak232** [comment]
It's not a bug!
This same on real Tibia.
