### ISSUE TITLE
BUG: Client Debug (100 players online, crash about 10x-20x every day)

### ISSUE THREAD

**Issue by givera12** [opentibiabr/otservbr-global-archived#2605]
Describe the bug:

> When players are on exp place, and killing mosnters sometime (not every time) when they make slant, when the walk on slant, thast they have crash tibia and this error log like on screenshot

#### Screenshots
>
![aasd](https://user-images.githubusercontent.com/81332938/119538907-dcf3c880-bd8b-11eb-85f7-27107f8303d3.png)

#### Environment

Tibia ver 12.64

**Comment by lgrossi** [comment]
Sorry, templates are there to be used. No one will magically figure out what is going on with no information in the issue.
Please either re-open it with more information or do not create meaningless issues.

Thank you.

**Comment by Juanzin93** [comment]
ok so im facing the same issue, and i might be able to give some insight.. from what i noticed it happens individually by players, there can be 5 players in a room, but only 1 gets debug, i know for a fact that the players that got debug had exp boost active and prey active, so these 2 are what im looking at. just need to figure out which byte needs to be changed x.x and if the problem is actually with one of these 2

**Comment by Juanzin93** [comment]
ive been looking on the version updates and came across this 

https://github.com/opentibiabr/otservbr-global/pull/2302/files?file-filters%5B%5D=.cpp&file-filters%5B%5D=.dist&file-filters%5B%5D=.h&file-filters%5B%5D=.otb

uint16_t version = g_config.getNumber(ConfigManager::CLIENT_VERSION);	uint32_t clientVersion = 0;	
uint32_t version = g_config.getNumber(ConfigManager::CLIENT_VERSION);	int32_t clientVersion = 0;
any idea why it was changed from uint32 to int32? could that be causing it?

**Comment by xThauma** [comment]
> ive been looking on the version updates and came across this
> 
> https://github.com/opentibiabr/otservbr-global/pull/2302/files?file-filters%5B%5D=.cpp&file-filters%5B%5D=.dist&file-filters%5B%5D=.h&file-filters%5B%5D=.otb
> 
> uint16_t version = g_config.getNumber(ConfigManager::CLIENT_VERSION); uint32_t clientVersion = 0; uint32_t version = g_config.getNumber(ConfigManager::CLIENT_VERSION); int32_t clientVersion = 0;
> any idea why it was changed from uint32 to int32? could that be causing it?

Did you find the answer?
