### ISSUE TITLE
BUG: When looking at an item by trade on the npc, it does not show the charges

### ISSUE THREAD

**Issue by lucaszrocha** [opentibiabr/otservbr-global-archived#2606]
When looking at an item by trade on the npc, it does not show the charges.
this happens with any item that has charges, and on any npc. There is no error in the console

![image](https://user-images.githubusercontent.com/46580821/120095572-10708300-c0fd-11eb-84cd-40214ac2a122.png)

**Comment by ArturKnopik** [comment]
This can be fixed in ProtocolGame but does not fix the issue of non-standard charge items.
I use default charge value from item
https://github.com/opentibiabr/otservbr-global/blob/8427233cacf98d6c733be2ed91951e368eb5c05a/src/server/network/protocol/protocolgame.cpp#L1404
someone maby find better place to fix, i fix this here

**Comment by dex-89** [comment]
> This can be fixed in ProtocolGame but does not fix the issue of non-standard charge items.
> I use default charge value from item
> https://github.com/opentibiabr/otservbr-global/blob/8427233cacf98d6c733be2ed91951e368eb5c05a/src/server/network/protocol/protocolgame.cpp#L1404
> 
> 
> someone maby find better place to fix, i fix this here

https://github.com/opentibiabr/otservbr-global/blob/develop/data/events/scripts/player.lua#L121

**Comment by ArturKnopik** [comment]
@ dex-89 unfortunately, in shop, this event does not work (never called), event Player: onLookInShop (itemType, count) can fix this problem but if npc offer custom charge item (for example: protection amulet with 1k charge) we don't know value of custom charges, we can us only default values from xml file

maybe this will fix this issue
https://github.com/opentibiabr/otservbr-global/blob/8427233cacf98d6c733be2ed91951e368eb5c05a/src/items/item.cpp#L2062
replace this line to to this 

```cpp
if (subType == 0){
	s << " that has " << it.charges << " charge" << (subType != 1 ? "s" : "") << " left";
} else{
	s << " that has " << subType << " charge" << (subType != 1 ? "s" : "") << " left";
}
```

**Comment by lucaszrocha** [comment]
@ArturKnopik OMG MAN, IT WORKED PERFECTLY!!!! THANKS <3

![image](https://user-images.githubusercontent.com/46580821/120872280-99ac0d80-c574-11eb-91d5-ac8d8905a3f5.png)

**Comment by MajestyOTBR** [comment]
Who let close the issue? The issue tracker is not a support forum to solve problems and close the issue.

**Comment by majestyotbr** [comment]
@ArturKnopik Create a pull request with the fix.

**Comment by lucaszrocha** [comment]
> Who let close the issue? The issue tracker is not a support forum to solve problems and close the issue.

Sorry, this is the first time I work with github, I thought it was by closing the inssues that you would see that the problem was solved. I really apologize, I didn't know I needed to do something else

**Comment by MajestyOTBR** [comment]
> Sorry, this is the first time I work with github, I thought it was by closing the inssues that you would see that the problem was solved. I really apologize, I didn't know I needed to do something else

Ok. The issue can be solved and closed with linked pull request.
