### ISSUE TITLE
BUG: Familiars atking players, and you can atk them

### ISSUE THREAD

**Issue by Mattehj** [opentibiabr/otservbr-global-archived#2607]
#### Describe the bug
> A clear and concise description of what the bug is. If I hunt with a guy who have his summon, The summon is atking me with spells

#### How to Reproduce?
> I dontk now what this mean

> Give us all details to reproduce the behavior:
> 1. Walk to city '...'
> 2. Click on item '....'
> 3. Drag it to backpack '....'
> 4. See error

#### Logs or errors
> Please include any errors or logs that are relevant

#### Expected behavior
> A clear and concise description of what you expected to happen. 
That summons only atking monsters, at least when u have ur pvp off!

#### Screenshots
> If applicable, add screenshots to help explain your problem.

#### Environment
- OS (e.g. Windows): 
- OTServ Version (e.g. commit): 
- Tibia Version (e.g. 12.52): 

#### Additional context
> Add any other context about the problem here.

**Comment by ArturKnopik** [comment]
![image](https://user-images.githubusercontent.com/17506599/120899403-d983fb00-c62f-11eb-8672-c4d9a2738828.png)
Did you modify anything in src/data?

**Comment by Mattehj** [comment]
> ![image](https://user-images.githubusercontent.com/17506599/120899403-d983fb00-c62f-11eb-8672-c4d9a2738828.png)
> Did you modify anything in src/data?
No!
That is ur own summon, I'm talking about other players summons.

**Comment by ArturKnopik** [comment]
most likely it depends on the type of world, as you can see in the video below, summons can be attacked and they can attack others
https://youtu.be/U-L5yRXeShA?t=471
look on left down knight familiar he attack, druid familiar take dmg in same situation

**Comment by Mattehj** [comment]
Yea, But on normal pvp if u dont have pvp option enable, ur summons should not atk other players, Basicly now you can kill other players without getting skull
