### ISSUE TITLE
MAP: Hunt sem teto

### ISSUE THREAD

**Issue by tataboy67** [opentibiabr/otservbr-global-archived#2608]
Position:
x: 33390
y: 32723
z: 8
![foto](https://user-images.githubusercontent.com/34138503/120726831-6e131f80-c4af-11eb-8948-04ba303ab78e.PNG)

Teto descoberto.
Ao acessar essa posição, você verá que esse local, não possui "teto".

Área corrigida:
[ajusteMap.zip](https://github.com/opentibiabr/otservbr-global/files/6598047/ajusteMap.zip)

**Comment by majestyotbr** [comment]
It's normal here.
![unknown](https://user-images.githubusercontent.com/32709570/121206282-b7b48f00-c84e-11eb-8355-7f8796c67698.png)
