### ISSUE TITLE
MAP:  An map issue in Buster Spectre cave (Darashia)

### ISSUE THREAD

**Issue by travisani** [opentibiabr/otservbr-global-archived#2616]
33103, 32324, 8

![image](https://user-images.githubusercontent.com/13306169/121167794-a5275f00-c828-11eb-84d9-d55a2e6cf0a0.png)

**Comment by MajestyOTBR** [comment]
Can you post how the area should be? Use the issue template correctly or will be closed if not contain more infos. Thanks.

**Comment by majestyotbr** [comment]
Can you post how the area should be? Use the issue template correctly or will be closed if not have more infos. Thanks.
