### ISSUE TITLE
CONTENT: Can't add diamond arrow to actionbar (equip)

### ISSUE THREAD

**Issue by Zapotoczny** [opentibiabr/otservbr-global-archived#2625]
Normal arrow i can but diamond no
![image](https://user-images.githubusercontent.com/63909484/121513042-b3bd7400-c9ea-11eb-8de5-ef2776c3cc4a.png)

**Comment by majestyotbr** [comment]
Use the correct issue template and put more infos, which id of the diamond arrow you tried to equip. 
Issues that not follow the issue template will be closed.
