### ISSUE TITLE
FIX red skull and black skull time

### ISSUE THREAD

**Issue by lichak232** [opentibiabr/otservbr-global-archived#2629]
Remove ms from time
src/player.cpp
`	if (getSkull() != SKULL_BLACK) {
		if (dayKills >= 2 * g_config.getNumber(ConfigManager::DAY_KILLS_TO_RED) || weekKills >= 2 * g_config.getNumber(ConfigManager::WEEK_KILLS_TO_RED) || monthKills >= 2 * g_config.getNumber(ConfigManager::MONTH_KILLS_TO_RED)) {
			setSkull(SKULL_BLACK);
			//start black skull time
			skullTicks = static_cast<int64_t>(g_config.getNumber(ConfigManager::BLACK_SKULL_DURATION)) * 24 * 60 * 60 * 1000;
		} else if (dayKills >= g_config.getNumber(ConfigManager::DAY_KILLS_TO_RED) || weekKills >= g_config.getNumber(ConfigManager::WEEK_KILLS_TO_RED) || monthKills >= g_config.getNumber(ConfigManager::MONTH_KILLS_TO_RED)) {
			setSkull(SKULL_RED);
			//reset red skull time
			skullTicks = static_cast<int64_t>(g_config.getNumber(ConfigManager::RED_SKULL_DURATION)) * 24 * 60 * 60 * 1000;
		}
	}`

change to:
`	if (getSkull() != SKULL_BLACK) {
		if (dayKills >= 2 * g_config.getNumber(ConfigManager::DAY_KILLS_TO_RED) || weekKills >= 2 * g_config.getNumber(ConfigManager::WEEK_KILLS_TO_RED) || monthKills >= 2 * g_config.getNumber(ConfigManager::MONTH_KILLS_TO_RED)) {
			setSkull(SKULL_BLACK);
			//start black skull time
			skullTicks = static_cast<int64_t>(g_config.getNumber(ConfigManager::BLACK_SKULL_DURATION)) * 24 * 60 * 60;
		} else if (dayKills >= g_config.getNumber(ConfigManager::DAY_KILLS_TO_RED) || weekKills >= g_config.getNumber(ConfigManager::WEEK_KILLS_TO_RED) || monthKills >= g_config.getNumber(ConfigManager::MONTH_KILLS_TO_RED)) {
			setSkull(SKULL_RED);
			//reset red skull time
			skullTicks = static_cast<int64_t>(g_config.getNumber(ConfigManager::RED_SKULL_DURATION)) * 24 * 60 * 60;
		}
	}`

**Comment by beats-dh** [comment]
What is the current problem?

**Comment by lichak232** [comment]
He adds to database player>skulltime from config.lua(my its: redSkullDuration = 3) * 24 * 60 * 60 * 1000 = red skull duration 8 years. When remove from src/player.cpp in skull time value 1000. works fine.
sorry but my english is easy.

**Comment by beats-dh** [comment]
> He adds to database player>skulltime from config.lua(my its: redSkullDuration = 3) * 24 * 60 * 60 * 1000 = red skull duration 8 years. When remove from src/player.cpp in skull time value 1000. works fine.
> sorry but my english is easy.

You can comment on the project's Discord in PT I'm online
