### ISSUE TITLE
BUG: Teleport Trashing

### ISSUE THREAD

**Issue by travisani** [opentibiabr/otservbr-global-archived#2637]

**Comment by travisani** [comment]
![image](https://user-images.githubusercontent.com/13306169/121817997-eff70b80-cc5a-11eb-9409-c47372d606dd.png)
![image](https://user-images.githubusercontent.com/13306169/121818010-04d39f00-cc5b-11eb-9abd-f6c39dc1d5c4.png)

**Comment by majestyotbr** [comment]
Where is the issue? Why did you removed?

**Comment by travisani** [comment]
I didn't express it correctly or error, I'm fixing the bug and will post the solution.

**Comment by majestyotbr** [comment]
Ok.
