### ISSUE TITLE
BUG: item imbued

### ISSUE THREAD

**Issue by Bipbop69** [opentibiabr/otservbr-global-archived#2649]
when the item is imbued
using two for example when 1 ends the second even if it has a longer time it is reset

**Comment by xThauma** [comment]
Yea, this bug exists. If you want to fix replace void Game::checkImbuements() with this: https://pastebin.com/s7k23GCT

**Comment by beats-dh** [comment]
@Bipbop69 You have to create an issue following the model and be clear when explaining the problem.
@xThauma If you solve the problem "I don't even know what it is" you open a PR with the solution.

**Comment by Bipbop69** [comment]
> Yea, this bug exists. If you want to fix replace void Game::checkImbuements() with this: https://pastebin.com/s7k23GCT

fixed
