### ISSUE TITLE
BUG: Crash em store

### ISSUE THREAD

**Issue by ifwednesday** [opentibiabr/otservbr-global-archived#2650]
#### Describe the bug
>  Vários players estão derrubando o server e conseguindo rollback apenas abrindo e fechando a store rapidamente. 
#### How to Reproduce?
>​tentei reproduzir sozinho com ACC do god mas sem sucesso apenas reparei que o player fica com exasted e o server lento

#### Logs or errors
> Não foi gerado logs

#### Environment
- OS (windows, Ubuntu 20.04): 
- OTServ Version (branch 10-12): 
- Tibia Version (12.64):

**Comment by travisani** [comment]
modules.xml
<module type="recvbyte" byte="250" delay="600" script="gamestore/gamestore.lua"/>

aumente o delay.

**Comment by beats-dh** [comment]
> modules.xml
> aumente o delay.

I thought about it too.
Pensei nisso também
