### ISSUE TITLE
BUG: rainbow amulet are with wrong sprite

### ISSUE THREAD

**Issue by Schiffers** [opentibiabr/otservbr-global-archived#2685]
actual:
![image](https://user-images.githubusercontent.com/10325310/126919836-d01ee6b7-e07d-4c5b-a7a7-d410104ecc4f.png)
correct:
![image](https://user-images.githubusercontent.com/10325310/126919868-e349696c-086f-468d-95fc-6597d6838c59.png)
just check it in game....
I try change it in assets with assets editor but no works....
should be an itemEditor issue.

**Comment by beats-dh** [comment]
id?

**Comment by Schiffers** [comment]
@Beats-Dh 
Id 36391 If i'm not wrong

**Comment by Schiffers** [comment]
CLOSING THIS BECAUSE I FIND THE ERROR....
there is 2 "rainbow"
1 - rainbow amulet --- thsi is with the sprite of enchanted pendulet ... it shouldn't exist..
2 - rainbow necklace with correct sprite ID 35150 .... its ok with this item, should just check if the bosses drop it instead rainbow amulet...
