### ISSUE TITLE
BUG: some Monsters don't exists in bestiary

### ISSUE THREAD

**Issue by Schiffers** [opentibiabr/otservbr-global-archived#2687]
Some Monsters as Tainted Soul are not in bestiary ...
Idk How check the Race number from the client...

Also, some Monsters as infernal demons and anothers Monsters of Soul war doesn't appear on Monsters list in prey window

**Comment by amoxicilinaaa** [comment]
> 
> 
> Some Monsters as Tainted Soul are not in bestiary ...
> Idk How check the Race number from the client...
> 
> Also, some Monsters as infernal demons and anothers Monsters of Soul war doesn't appear on Monsters list in prey window


and for the simple fact that it is not in the monsters folder. make a list of missing creatures that I can add them to the monster mass and thus contribute to you and the super project, OTBR.

**Comment by Schiffers** [comment]
@amoxicilinaaa I've checked some monsters ...
then, only tainted soul isn't in the bestiary from that I checked, I'll made a pr to fix
https://github.com/opentibiabr/otservbr-global/pull/2739
