### ISSUE TITLE
[Bug]: Docker - cannot locate config.lua and vocations.xml file

### ISSUE THREAD

**Issue by powroseba** [opentibiabr/otservbr-global-archived#2694]
### What happened?

I executed a docker-compose and start up a containers. Everything work properly but when i need to config website i need to pass server path. Docker containers cannot share directories between each other so in my point of view there is no possible solution to pass proper server path to give website possibility to locate **config.lua**. I have tried probably all possible path to server like _(/bin/otbr, /tmp/otserver/, /otbr)_ and i all website cannot locate **config.lua**. I copied the config from server container and paste it into the volume of website. But there is another problem, in 7 step of website config vocations.xml file in necessary. So in my point of view configuration of docker is not proper or you dont pass any information in README what should be the valid path of server which will pleased website config.

### How to Reproduce?

Just normally run docker-compose up, go to localhost:8080 and in step of server path try to process this step further

### Relevant log output

```shell
Cannot locate config.lua file
```

### Version

12.x (Default)

### What OS are you seeing the problem on?

Linux

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Costallat** [comment]
> Docker containers cannot share directories between each other 

Fake, you can share using volumes

> I copied the config from server container and paste it into the volume of website

Did you try to copy the config.lua.dist to config.lua and make the same changes as the server containers does? The website is not part of this project, so it needs some manual steps, and the path is /tmp/otserver as you can see on the docker-compose file

**Comment by powroseba** [comment]
Okay so why you does not configure proper volume to share config.lua ?
Anyway, i try to copy config.lua and it work but in 7 step there is vocations.xml file required, i cannot find where is path configuration for this in php files. So for now i stuck in step where configuration of website require access to vocations.xml which is in server files. Do you know how to get around it ?

**Comment by Costallat** [comment]
> Okay so why you does not configure proper volume to share config.lua ?

Why you can't do that? It's open source you can improve things and open a PR with those changes.

> Anyway, i try to copy config.lua and it work but in 7 step there is vocations.xml file required, i cannot find where is path configuration for this in php files.

This repository handles with the server not the website, if they changed something it can breaks things here, as we don't need the website to work, we can only track what we changed, if you see that they changed and broke something feel free to also fix that and open a PR with the changes, 

You can use the search on their repository to see where they keep those settings, on the server the path is:

https://github.com/opentibiabr/otservbr-global/blob/develop/data/XML/vocations.xml

**Comment by powroseba** [comment]
Okay after copying file website work properly. Sorry I thought that all server ready to use is the purpouse of this repository but you have totally right that this repo is focused only on server. Sorry for problem issie to close.
