### ISSUE TITLE
[Bug]: You are already logged in. 

### ISSUE THREAD

**Issue by cys9211** [opentibiabr/otservbr-global-archived#2705]
### What happened?

When we exit the game "exit" or debug the client, we can't log in until the kick. 

![image](https://user-images.githubusercontent.com/7588103/129788723-8521929b-2f43-446f-bc16-2e8e0e55a875.png)

### How to Reproduce?

Login

### Version

12.x (Default)

### What OS are you seeing the problem on?

Linux

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dex-89** [comment]
config.lua: `replaceKickOnLogin` you have `true` or `false`?

**Comment by cys9211** [comment]
Have "false"

**Comment by cys9211** [comment]
Ahhh thanks
Closed
