### ISSUE TITLE
two bugs  poi and triangle tower

### ISSUE THREAD

**Issue by Feliipe93** [opentibiabr/otservbr-global-archived#272]
i found few errors
poi burning gates doesnt block the path to players, so theres no need to  pull lever in order to advance in the quest
seccond bug
and the gate of the triangle tower doesnt push monsters 1 sqm back when its closed

**Comment by FakeShinoda** [comment]
this is just a ward (y)

**Comment by Sargitarium** [comment]
Fixed on #633 and TESTED today.... WORK fine.....
