### ISSUE TITLE
[Bug serious ]: npc

### ISSUE THREAD

**Issue by Bipbop69** [opentibiabr/otservbr-global-archived#2735]
### What happened?

take the npc to some place where you can fall into it done so put it to talk to him in talk with this server will fall 

### How to Reproduce?

![image](https://user-images.githubusercontent.com/64280614/132931109-feed36b9-c22d-4bc6-8ff0-0f58483760da.png)

### Version

12.x (Default)

### What OS are you seeing the problem on?

Ubuntu 18.04

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Bipbop69** [comment]
`
void Game::playerNpcGreet(uint32_t playerId, uint32_t npcId)
{
	Player* player = getPlayerByID(playerId);
	if (!player) {
		return;
	}

	Creature* creature = getCreatureByID(npcId);
	if (!creature) {
		return;
	}

	Npc* npc = creature->getNpc();
	if(npc) {
		SpectatorHashSet spectators;
		spectators.insert(npc);
		map.getSpectators(spectators, player->getPosition(), true, true);
		internalCreatureSay(player, TALKTYPE_SAY, "Hi", false, &spectators);
		spectators.clear();
		spectators.insert(npc);
		if (npc->getSpeechBubble() == SPEECHBUBBLE_TRADE) {
			internalCreatureSay(player, TALKTYPE_PRIVATE_PN, "Trade", false, &spectators);
		} else {
			internalCreatureSay(player, TALKTYPE_PRIVATE_PN, "Sail", false, &spectators);
        }

		return;
	}
}
`



apparently the bug is in this function

**Comment by Schiffers** [comment]
Confirmed... I'm trying resolve, but I get crash in the client instead the server XD
