### ISSUE TITLE
Bug wyrms zone crash client

### ISSUE THREAD

**Issue by IvanMir014** [opentibiabr/otservbr-global-archived#278]
**Describe the bug**
When you go to wyrms zone on liberty bay the client 12 crashes and people die.

**To Reproduce**
1. Go to wyrms zone to liberty bay and client crash and people die.

On client 12.

**Expected behavior**
Zone working as expected.

**Screenshots**
![wrym issue](https://user-images.githubusercontent.com/33207582/61406688-a372ec00-a8dc-11e9-8650-86edc35a1019.jpeg)

**Comment by ghost** [comment]
confirmed, its because the animated corpse of energy elemental
related #220

**Comment by majestyotbr** [comment]
#265
