### ISSUE TITLE
Tibia client 12 crashes with new prey system

### ISSUE THREAD

**Issue by IvanMir014** [opentibiabr/otservbr-global-archived#279]
**Describe the bug**
I updated to the last version of develop, recompile and run the server. On open client 12 crashes.

**To Reproduce**
1. Update the repo to the last version, included the database changes.
2. Recompile and run the tfs.
3. Open client 12 and try to connect, list of characters working properly, but when I enter on character, the client crashes.

**Expected behavior**
Working as expected.

**Desktop (please complete the following information):**
 - OS: windows 10
 - Version: 12

**Comment by ghost** [comment]
![2019-07-17 18_41_06-Window](https://user-images.githubusercontent.com/4684880/61413656-77e30800-a8c2-11e9-82aa-1ee7201d4190.jpg)
its working fine here, try again with the client from [this link](https://github.com/opentibiabr/tools)

**Comment by westwol** [comment]
Close the server truncate prey_slots table, open the server and test it, it should work. Also make sure you are running latest source code.
