### ISSUE TITLE
NO DROP LOOT

### ISSUE THREAD

**Issue by Lycanzito** [opentibiabr/otservbr-global-archived#281]
Ao matar qualquer criatura, não está dropando nenhum loot.

![image](https://user-images.githubusercontent.com/52710697/61416129-0d819600-a8c9-11e9-8b37-297fd32b0041.png)

![image](https://user-images.githubusercontent.com/52710697/61416221-5fc2b700-a8c9-11e9-804c-cb819bbf82c6.png)

Nem Server log.. nada. 
O Ganho de experiência, continua normal.

**Comment by LukSrT** [comment]
Veja isso:
https://github.com/opentibiabr/OTServBR-Global/blob/develop/data/XML/groups.xml#L85
Se tiver "1", mude para "0"

**Comment by dudantas** [comment]
God não pode dropar loot por padrão.

Se quiser mudar vá em groups.xml

**Comment by Lycanzito** [comment]
> Veja isso:
> https://github.com/opentibiabr/OTServBR-Global/blob/develop/data/XML/groups.xml#L85
> Se tiver "1", mude para "0"

Tá normal lá meu querido.. Foi Testado em player também..

Esse erro surgiu, depois que eu alterei a src, após a implementação do Exeta res,

**Comment by Lycanzito** [comment]
> God não pode dropar loot por padrão.
> 
> Se quiser mudar vá em groups.xml

![image](https://user-images.githubusercontent.com/52710697/61416624-bc72a180-a8ca-11e9-8b3a-ff0f8ca480c4.png)

**Comment by ghost** [comment]
vc deve ter feito alguma alteração em algum lugar e não percebeu, pois o código alterado no exeta res não tem ABSOLUTAMENTE nada a ver com loot drop, lembre-se de reportar apenas se vc conseguir reproduzir o "bug" em uma versão não modificada baixada aqui do github

**Comment by Lycanzito** [comment]
> vc deve ter feito alguma alteração em algum lugar e não percebeu, pois o código alterado no exeta res não tem ABSOLUTAMENTE nada a ver com loot drop, lembre-se de reportar apenas se vc conseguir reproduzir o "bug" em uma versão não modificada baixada aqui do github

Existe alguma hipótese, de ser algo da pack? e não da sourcer?

**Comment by ghost** [comment]
> > vc deve ter feito alguma alteração em algum lugar e não percebeu, pois o código alterado no exeta res não tem ABSOLUTAMENTE nada a ver com loot drop, lembre-se de reportar apenas se vc conseguir reproduzir o "bug" em uma versão não modificada baixada aqui do github
> 
> Existe alguma hipótese, de ser algo da pack? e não da sourcer?

sim, algum creatureevent ou algo na pasta events/scripts/monster.lua

**Comment by Lycanzito** [comment]
> > > vc deve ter feito alguma alteração em algum lugar e não percebeu, pois o código alterado no exeta res não tem ABSOLUTAMENTE nada a ver com loot drop, lembre-se de reportar apenas se vc conseguir reproduzir o "bug" em uma versão não modificada baixada aqui do github
> > 
> > 
> > Existe alguma hipótese, de ser algo da pack? e não da sourcer?
> 
> sim, algum creatureevent ou algo na pasta events/scripts/monster.lua

irei investigar, obrigado. :)
