### ISSUE TITLE
Summons without their respective skulls

### ISSUE THREAD

**Issue by ghost** [opentibiabr/otservbr-global-archived#285]
**Describe the bug**
Summons have no skulls when you summon them

**To Reproduce**
1. Summon anything with either utevo res or /summon command
2. See error

**Expected behavior**
![2019-07-17 20_34_37-Window](https://user-images.githubusercontent.com/4684880/61418862-643f9d80-a8d2-11e9-89f3-15c30ae7114c.jpg)
green skull for yourself and red for other around you

**What happens instead**
![2019-07-17 20_38_34-Window](https://user-images.githubusercontent.com/4684880/61419043-f3e54c00-a8d2-11e9-819a-f949adb87213.jpg)

**Desktop (please complete the following information):**
N/A

**Comment by gerotib** [comment]
These "skulls" arrives the next time that monster shows on your screen (if you walk away and lose him out of game window). So theres probably missing some function that add them at the moment of creating summon.

**Comment by oualid6496** [comment]
Has this been fixed or is this issue only on client 12? Because I just summoned something on client 10 and it comes with its respective skulls.

**Comment by gerotib** [comment]
Im pretty sure this also doesnt work on client 11, so theres probably missing something that make it works on 11/12 client.
