### ISSUE TITLE
Monsters dont drop loot without any notification

### ISSUE THREAD

**Issue by kiper166** [opentibiabr/otservbr-global-archived#292]
**Describe the bug**
monsters dont drop the loot.

**To Reproduce**
1. Go anywhere
2. Click on any monster that drops loot
3. kill it
4. nothing happens, empty corpse
Note: include any configuration/script required to reproduce.
Datapack with exe client from here https://ci.appveyor.com/project/opentibiabr/otservbr-global/build/job/jaxo04bc49ebqlay/artifacts

**Expected behavior**
As above.

**Screenshots**
No need.

**Desktop (please complete the following information):**
 - OS: windows 10 x64

**Additional context**
No solution worked, adding 	<flag notgenerateloot="0" /> to a god or player.

**Comment by majestyotbr** [comment]
I used datapack latest version and exe from appveyor, tested with a normal character, the issue isn't confirmed. The monsters drops loot.
If you are god, disable notgenerateloot flag on data/xml/groups.xml.
