### ISSUE TITLE
Alguns bugs pt2

### ISSUE THREAD

**Issue by ghost** [opentibiabr/otservbr-global-archived#295]
- [ ] trocar as portas daqui {x = 32801, y = 31220, z = 7} e a do lado para portas de quest q podem ser acessadas após começar a Mission 03: Death to the Deathbringer
- [ ] esta porta em {x = 32822, y = 31745, z = 10} só pode ser aberta após completar warzone 1, 2 e 3 pelo menos 1 vez (openGoldenFruits)
- [ ] não lembro se tem uma porta aqui {x = 33313, y = 31849, z = 9}, porém após limpar 100 fungos das paredes, apenas os jogadores que limparam 100+ podem ficar la dentro (podem sair e entrar livremente) e quando limpam toda a cave, começa as várias waves de iron, golden e diamond servants e por fim o mad mage (conferir td no tibia wiki)
- [ ] falta action ID nessa porta {x = 33211, y = 31634, z = 13} pra ser aberta somente com a chave pega na parchment room
- [ ] trocar a porta daqui {x = 32990, y = 31547, z = 4} por uma porta de quest q só pode passar nela após entregar a Mission 10: New Horizons da the new frontier quest
- [ ] {x = 32953, y = 31485, z = 6} a entrada e saida do castelo é pra ser mystic flame e não magic forcefield, e os jogadores só podem entrar após a Mission 06: A Black History da quest blood brothers
- [ ] as portas no vengoth castle deve ser portas de quest e liberadas conforme as missões da quest citada anteriormente

**Comment by Sargitarium** [comment]
Items 1,2,3,4,5 fixed on #633 TESTED NOW

Item 6 removed magicforcefield, but the QUEST need FIX....

Item 7 making quest scripts...
