### ISSUE TITLE
Live Leech / Mana leech - Imbuements not fixed like Real tibia / Critical System Deal random damage

### ISSUE THREAD

**Issue by omarcopires** [opentibiabr/otservbr-global-archived#3]
**For a moment the server its ok but have some issues, here you can check some bugs:**

* Imbuement live leech: To reproduce ->
* If you have live leech 25% on your Axe, and 25% on your Armor the live leech its ok but have bug.
* When you use this two items on Elite kninght for example and you try to hunt at level 600+ on Roshamuul/Ferumbras you can get easy a lot of HP and Mana every attack getting your character Like a GOD:

Formula Actual status OTX (notfixed):

* Damage (1000xmonster)x8Monsters= 8000 Damage -> 8000/50%=4000 HP x Turn -> you get all from all monsters receibe damage.

Formula Actual status RL (Fixed): If you do a lot of damage in area like 8 monsters you only get from one monster/Target (1 monster)

* Formula 8x1000 = 8000/8(Number of monsters receibe damage)=1000/50%=500 -> 500 Hp max if you have 100% Chance.

Same with Mana leech, if you are Wizard and you deal damage 400 x 10 monsters you get a lot of mana.

---

Critical

When you deal critical damage on some creatures, the system its ok have a random posobilty to get dat special attribute to the damage, but the critical just need added to the all monsters receibe damage and not random from damage taken by your attack:

Actual status: Exori gran, 8 monsters receibe damage

* 1 turn: 1/8 only get critical damage boosted
* 2 turn: 3/8 only get critical damage boosted
* 3 turn: 0/8 get 0 damage boosted
* 4 turn: 2/8 only get critical damage boosted
* 5 turn: 0/8 get 0 damage boosted
* 6 turn: 1/8 only get critical damage boosted
* 7 turn: 0/8 get 0 damage boosted
* 8 turn: 8/8 only get critical damage boosted
* 9 turn: 7/8 only get critical damage boosted
* 10 turn: 0/8 get 0 damage boosted
* We know the chance is only 10 %
* 10 times test

Real tibia status: Exori gran, 8 monsters receibe damage

* 1 turn: 8/8 only get critical damage boosted
* 2 turn: 0/8 get 0 damage boosted
* 3 turn: 0/8 get 0 damage boosted
* 4 turn: 8/8 only get critical damage boosted
* 5 turn: 0/8 get 0 damage boosted
* 6 turn: 0/8 get 0 damage boosted
* 7 turn: 0/8 get 0 damage boosted
* 8 turn: 8/8 only get critical damage boosted
* 9 turn: 0/8 get 0 damage boosted
* 10 turn: 0/8 get 0 damage boosted
* 10 times test

**Comment by LukSrT** [comment]
@marcomoa Tested with the latest version?

**Comment by liontts** [comment]
The problem does not exist or has been fixed.
