### ISSUE TITLE
changegold/knight training/autoloot

### ISSUE THREAD

**Issue by mervin89go** [opentibiabr/otservbr-global-archived#305]
Oi Galera, teno algunas duvidas.. 

1- Autoloot, nao esta agragando
2- Knight traning elos nao cargan en el ot e nao existe en el map editor
3- changegold platinum crystals nao esta funcionando.
4- como posso desactivar missao pra quest? todas piden accesos e missiones :(.

sou novo mais gusto de aprender e leer pra ajudar.

Saludos e obrigado

**Comment by ghost** [comment]
2-data\world\worldchanges\additionals
3- https://otland.net/threads/new-ot-project-otservbr-global-10x-outdated-with-sprites-12-15.264701/page-4#post-2564984

if you have any support related question, please use [our thread](https://otland.net/threads/new-ot-project-otservbr-global-10x-outdated-with-sprites-12-15.264701/), use here only for bug reporting

**Comment by mervin89go** [comment]
thank you very much friend. I can ask you one last question and I close the subject. How do I operate knight training? I have the \ world \ worldchanges \ additionals route but I don't know how to make it work .. what should I add? @EPuncker
