### ISSUE TITLE
Yalahar final mission

### ISSUE THREAD

**Issue by mervin89go** [opentibiabr/otservbr-global-archived#307]
Yalahar quest's final mission is not working by killing the boss and slashing in the sqm does nothing. With the GOD account, remove the door and check the chest: The chest is empty.

**Comment by Raphaellb** [comment]
![image](https://user-images.githubusercontent.com/42285366/62100036-0dd14800-b25e-11e9-91b8-10ffee745fc1.png)

I tested this whole quest from start to finish, and the quest is 100%. this is working by downloading and using the latest version of this pack. Please close issue as invalid.
