### ISSUE TITLE
Pits of inferno, end of the maze lever

### ISSUE THREAD

**Issue by Davenorthern** [opentibiabr/otservbr-global-archived#315]
**Describe the bug**
The room with 3 hellfire fighters and magic throwers in the end of the maze. The lever that removes the stone which blocks the path to the ladder is not working. It does switch, nor remove the stone.

**Comment by FakeShinoda** [comment]
Tested and it's working

**Comment by htc16** [comment]
Pessoal, tenho um pessoal que joga meu server e eles disseram que tem esse bug na pits, a alavanca movida não deu efeito algum. Mals reviver o tópico.

**Comment by gpedro** [comment]
@Heitortadeu poderia fornecer mais detalhes?

**Comment by htc16** [comment]
![unknown-6](https://user-images.githubusercontent.com/58153179/78455233-72f1fe80-7673-11ea-9b17-becb74309c8a.png)

O bug está na alavanca n3, que foi onde o pessoal não passou...

**Comment by htc16** [comment]
Se precisar de mais detalhes eu vejo pergunto aqui, só me reportaram e disse que essa alavanca não deu efeito algum..
