### ISSUE TITLE
Double click closes modal window on client 12

### ISSUE THREAD

**Issue by edilsonbim** [opentibiabr/otservbr-global-archived#319]
** Double click closes modal window on client 12 **

**Reproduce**
1. Open any modal window
2. Double-click a selected option.
3. She refuses and closes the window.

**Expected behavior**
The chosen option should be confirmed.

** Desktop: **
- OS: Windows
- Version: 10

**Comment by majestyotbr** [comment]
Probably it was the autoloot, it was removed from the server.
