### ISSUE TITLE
Prey system never changes the stars

### ISSUE THREAD

**Issue by IvanMir014** [opentibiabr/otservbr-global-archived#328]
**Describe the bug**
This is a issue with prey system, prey system never changes the stars.

**Comment by westwol** [comment]
This is intentional, if you want to receive a new bonus (type and rank) you have to use a bonus reroll (prey wildcard on client 12+). You won't get a new bonus rank or type if you just buy a new monster list.

**Comment by Lycanzito** [comment]
> This is intentional, if you want to receive a new bonus (type and rank) you have to use a bonus reroll (prey wildcard on client 12+). You won't get a new bonus rank or type if you just buy a new monster list.

Actually, they didnt made the Bonuses yet, or am I wrong?

**Comment by westwol** [comment]
Bonuses are working, feel free to test em

**Comment by Lycanzito** [comment]
> Bonuses are working, feel free to test em

![image](https://user-images.githubusercontent.com/52710697/62013059-31b06300-b164-11e9-906f-17b748585b18.png)

also , You know how to setthe card bonus reroll, without getting it from store?

**Comment by westwol** [comment]
`player:setPreyBonusRerolls(5)` or set them on the database while the player is logged out.

**Comment by Lycanzito** [comment]
> `player:setPreyBonusRerolls(5)` or set them on the database while the player is logged out.

Tested the bonuses, they are working! :)
Only having problems with this creature,

also..

When I roll the creatures from this Gamemaster
The games crash also the website

![image](https://user-images.githubusercontent.com/52710697/62013175-548f4700-b165-11e9-888a-dbe3ade31562.png)

Problably a problem on the database?

**Comment by westwol** [comment]
It's rare, unless you are not using latest commit.

**Comment by Lycanzito** [comment]
> It's rare, unless you are not using latest commit.

Well.. I think that im using the lastest commit.. 

![image](https://user-images.githubusercontent.com/52710697/62013194-a33ce100-b165-11e9-81b0-ff5501cecfe9.png)

**Comment by westwol** [comment]
Please try to record a video on how to does that happen, cause when I ran my tests on client 12 everything worked as inteed. Let me know if that also happens on client 10.

**Comment by Lycanzito** [comment]
> Please try to record a video on how to does that happen, cause when I ran my tests on client 12 everything worked as inteed. Let me know if that also happens on client 10.
Im using the client 12
also the time from the monsters are not getting restored when use the card

![image](https://user-images.githubusercontent.com/52710697/62013233-0af32c00-b166-11e9-836f-2d982a4fd61e.png)

also, please can you send me the lastest commint? Im not a gooduser with github ! xD

**Comment by westwol** [comment]
It seems like you are not using the latest commit as repeated monsters was fixed a commits ago.

You can grab it from here:
https://github.com/opentibiabr/OTServBR-Global/archive/develop.zip

**Comment by Lycanzito** [comment]
> It seems like you are not using the latest commit as repeated monsters was fixed a commits ago.
> 
> You can grab it from here:
> https://github.com/opentibiabr/OTServBR-Global/archive/develop.zip

But which files had changes?

**Comment by westwol** [comment]
Unless you can reproduce the bug using a clean copy of OTServBR-Global, I'm afraid I can't help you.

**Comment by IvanMir014** [comment]
My players says, that the daily reward gives this option to roll again the bonus, but daily reward it's not working, Another option to get this roll again is when the bonus finish but the bonus never finish :/

**Comment by westwol** [comment]
Unrelated.

**Comment by IvanMir014** [comment]
ok, I don't understand. Sorry.

**Comment by ghost** [comment]
> My players says, that the daily reward gives this option to roll again the bonus, but daily reward it's not working, Another option to get this roll again is when the bonus finish but the bonus never finish :/

aqui é sobre o prey system e não sobre daily reward

**Comment by IvanMir014** [comment]
Prey but I think daily reward it's not working too.

**Comment by majestyotbr** [comment]
Before create a issue, make sure you are using latest version. 
When create a issue, use the issue template and describe the problem without mixing things.
