### ISSUE TITLE
VS 17 warnings after last imbui changes

### ISSUE THREAD

**Issue by ghost** [opentibiabr/otservbr-global-archived#339]
no changes on source
![image](https://user-images.githubusercontent.com/4684880/62375165-076bf600-b514-11e9-8461-f9448bdd8ff4.png)

windows 10 64bits, release/x64 visual studio 17 with vcpackage

**Comment by LukSrT** [comment]
Hmm ok
Vou compilar no windows e já upo os fixs

**Comment by gpedro** [comment]
resolvido em #343 ?

**Comment by ghost** [comment]
> resolvido em #343 ?

ainda não, ele disse que não sabe como resolver os que sobraram: 
![image](https://user-images.githubusercontent.com/4684880/62375165-076bf600-b514-11e9-8461-f9448bdd8ff4.png)
