### ISSUE TITLE
Gold borders on equipment

### ISSUE THREAD

**Issue by coney4** [opentibiabr/otservbr-global-archived#34]
![image](https://user-images.githubusercontent.com/4528737/58715776-d82bf200-83c7-11e9-86c1-3285cd791cc3.png)

I tried to logout or log as normal player but borders are still there.

**Comment by gpedro** [comment]
@coney4 are you talking about golden borders on equipment slot at top-right?

**Comment by coney4** [comment]
yes

**Comment by gpedro** [comment]
@coney4 the golden borders represent a blessing status. if golden, you are protected by blessing.

... I can be wrong, but you are free to say anything if I say any shit.

**Comment by coney4** [comment]
yes, you are right i tested it without blessings borders disappeared
