### ISSUE TITLE
[Items] Store tapestry can be wrapped inside the wall

### ISSUE THREAD

**Issue by oualid6496** [opentibiabr/otservbr-global-archived#340]
When you buy a tapestry in the store and place it on the wall you can wrap it again and then you'll have a decoration kit inside a wall.

**Comment by ghost** [comment]
I don't think that the tapestries hanged sprite should be wrappable at all, to prevent this issue

**Comment by oualid6496** [comment]
exactlly but it has the same item id as the one that you can pickup so im not sure how to change this

**Comment by ghost** [comment]
true, my bad, the wrappable system need a review

**Comment by rilex037** [comment]
So is it like a toggle? Is there no lua function to get sprite frame from item?

**Comment by oualid6496** [comment]
Not that I know of I have no clue to where this is being handled

**Comment by dudantas** [comment]
This is handled in items.xml
