### ISSUE TITLE
Problem with area spells, don't use + 45 energy damage

### ISSUE THREAD

**Issue by IvanMir014** [opentibiabr/otservbr-global-archived#349]
**Describe the bug**
When you use exori, or exori gran, or exori min (all damage in area), the enery damage it's not applied (of course using gnome sword etc).

**To Reproduce**
1. Attack the monster with physical damage. (Working properly with gnome sword for example)
2. Use Exori spell.
3. Energy damage not applied.

**Expected behavior**
Physical damage and energy damage.

Extra info: with imbuement weapons it's working properly, It's not working just for default energy damage. (all types of special damange).

**Screenshots**
Exori with magic sword (working properly)
![magic sword](https://user-images.githubusercontent.com/33207582/62401341-1dfd6600-b583-11e9-8c84-55c30a27cdd6.gif)
Exori with gnome sword without energy and worng damage.
![gnome_sword](https://user-images.githubusercontent.com/33207582/62401368-33729000-b583-11e9-98a3-7d289062f212.gif)

Server updated.

**Comment by oualid6496** [comment]
Is exori supposed to do elemental damage depending on the weapon that you're wearing?

**Comment by IvanMir014** [comment]
Not, but the energy damage and the physical damage should sum in area spells. If not, it no have sense, with magic sword have more damage with area spells than the gnome sword.

**Comment by IvanMir014** [comment]
This happen since the rebuild imbuement system update.
