### ISSUE TITLE
You can't move this item, too heavy.

### ISSUE THREAD

**Issue by IvanMir014** [opentibiabr/otservbr-global-archived#350]
**Describe the bug**
When you try to get a backpack with a lot of items, inside another backpack with more backpack, and you try to move the backpacks order or you drop to the floor and try to get again, with 100000 cap, mesage error You can't move this item, too heavy (the cap don't care).

**To Reproduce**
1. Get a backpack with a lot of items.
2. Drop it to the floor.
3. Try to get it.

**Expected behavior**
You can get it if you have cap.

**Comment by ghost** [comment]
not a bug, its intended:

https://github.com/opentibiabr/OTServBR-Global/blob/develop/data/events/scripts/player.lua#L545

**Comment by IvanMir014** [comment]
Ok, sorry.
