### ISSUE TITLE
Task System (storages)

### ISSUE THREAD

**Issue by Nilokz** [opentibiabr/otservbr-global-archived#351]
The storages from:
/data/lib/miscellaneous/killingInTheNameOfQuest.lua 

are different from the storages declared on:
data/movements/scripts/quests/killinginthenameof/boss.lua

so, when some player finish the tasks, he can't pass throught the teleport because the storage are wrong.

**Comment by Raphaellb** [comment]
I reported this in issue #144. it was closed then, but not properly fixed.
