### ISSUE TITLE
dwacatra door wrong action ID

### ISSUE THREAD

**Issue by rilex037** [opentibiabr/otservbr-global-archived#353]
I believe this action:

`<action actionid="1098" script="quests/explorer society/dwacatradoor.lua" />`

doesn't correspond to the map:

> 02:14 You see a closed door.
> Item ID: 5105, Action ID: 3802
> Position: 32598, 31933, 15

Family brooch is not obtainable for the NPC Uzgod for The Explorer Society Quest

**Comment by oualid6496** [comment]
Im pretty sure that this is working as intended action id refers to key 3802 which is needed to open that door. Check tibia.wiki this is working fine.

**Comment by rilex037** [comment]
Except it doesn't, i have that key, and door wouldn't open
![image](https://user-images.githubusercontent.com/44920715/62438004-dbd05200-b745-11e9-8d3d-7f48bc7ad2e5.png)

in rl tibia door opens when you  have started quest which i have:
![image](https://user-images.githubusercontent.com/44920715/62438071-16d28580-b746-11e9-89cb-b16a33d60e98.png)


but should be more clear, I was referring to the second door inside the hole

**Comment by oualid6496** [comment]
How did you get the key? Through the quest or just by making it? Can you try to give the key action id 3802 and see if it works? You can use /attr aid, 3802

**Comment by rilex037** [comment]
through the quest inside a chest,  also making it now, it doesn't match, its because those are quest doors, and inside doors.lua  it only checks for player storage; pls read my original post, when i change action id from 1098 to 3802 in actions.xml line 159  it works as it should; there may be other similar problems in the line of quest so I may do pull request once i investigate all

**Comment by oualid6496** [comment]
Yea the key is for the entrance of dwacatra the door that you're talking about should indeed be accesible when you've started the mission. I'll check it out later today

**Comment by ghost** [comment]
![2019-08-06 14_00_41-Window](https://user-images.githubusercontent.com/4684880/62560032-96e61180-b852-11e9-9513-8d90a30f99ba.jpg)
the key is to those doors
