### ISSUE TITLE
Client crashing on oramond factory raids (mechanical creatures).

### ISSUE THREAD

**Issue by FenyksGod** [opentibiabr/otservbr-global-archived#362]
**Describe the bug**
When you gather multiple monsters in this specific factory raid (south mechanical creatures) and kill them at the same time your client crashes every single time.

**To Reproduce**
- Go to the oramond factory raids
- Enter the mechanical creatures (x: 33552 y:31971 z:13)
- Gather monsters around you
- Kill them at the same time

**Comment by ghost** [comment]
can you test killing a souleater and see if your client crash too?

**Comment by FenyksGod** [comment]
It does.

**Comment by ghost** [comment]
then you need to update your sources, this issue has been fixed for some weeks already
