### ISSUE TITLE
Crash BUG I using the new SRC

### ISSUE THREAD

**Issue by ghost** [opentibiabr/otservbr-global-archived#363]
Thread 2 (Thread 0x7ffff25f8700 (LWP 899)):
#0  __memmove_avx_unaligned_erms () at ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:364
No locals.
#1  0x00007ffff652c52b in std::basic_streambuf<char, std::char_traits<char> >::xsputn(char const*, long) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
No symbol table info available.
#2  0x00007ffff651d58e in std::basic_ostream<char, std::char_traits<char> >& std::__ostream_insert<char, std::char_traits<char> >(std::basic_ostream<char, std::char_traits<char> >&, char const*, long) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
No symbol table info available.
#3  0x0000555555668fae in Player::getDescription[abi:cxx11](int) const ()
No symbol table info available.
#4  0x000055555563bcd4 in LuaScriptInterface::luaCreatureGetDescription(lua_State*) ()
No symbol table info available.
#5  0x00007ffff75acc75 in ?? () from /usr/lib/x86_64-linux-gnu/liblua5.2.so.0
No symbol table info available.
#6  0x00007ffff75b8825 in ?? () from /usr/lib/x86_64-linux-gnu/liblua5.2.so.0
No symbol table info available.
#7  0x00007ffff75acf9e in ?? () from /usr/lib/x86_64-linux-gnu/liblua5.2.so.0
No symbol table info available.
#8  0x00007ffff75ac5cf in ?? () from /usr/lib/x86_64-linux-gnu/liblua5.2.so.0
No symbol table info available.
#9  0x00007ffff75ad201 in ?? () from /usr/lib/x86_64-linux-gnu/liblua5.2.so.0
No symbol table info available.
#10 0x00007ffff75a90a1 in lua_pcallk () from /usr/lib/x86_64-linux-gnu/liblua5.2.so.0
No symbol table info available.
#11 0x00005555557602f8 in LuaScriptInterface::protectedCall(lua_State*, int, int) ()
No symbol table info available.
#12 0x00005555557604f0 in LuaScriptInterface::callVoidFunction(int) ()
No symbol table info available.
#13 0x0000555555720c7b in Events::eventPlayerOnLook(Player*, Position const&, Thing*, unsigned char, int) ()
No symbol table info available.
#14 0x000055555570af44 in Game::playerLookAt(unsigned int, Position const&, unsigned char) ()
No symbol table info available.
#15 0x00005555556c880e in Dispatcher::threadMain() ()
No symbol table info available.
#16 0x00007ffff64c9e6f in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
No symbol table info available.
#17 0x00007ffff67994a4 in start_thread (arg=0x7ffff25f8700) at pthread_create.c:456
        __res = <optimized out>
        pd = 0x7ffff25f8700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140737259734784, 2619948130629725256, 140737488348190, 140737488348191, 140737251344384, 3, -2619959946109637560, -2619969071663797176}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
        pagesize_m1 = <optimized out>
        sp = <optimized out>
        freesize = <optimized out>
        __PRETTY_FUNCTION__ = "start_thread"
#18 0x00007ffff5c3ed0f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97
No locals.

Thread 1 (Thread 0x7ffff7fe65c0 (LWP 895)):
#0  0x00007ffff5c3f303 in epoll_wait () at ../sysdeps/unix/syscall-template.S:84
No locals.
#1  0x0000555555698582 in boost::asio::detail::epoll_reactor::run(bool, boost::asio::detail::op_queue<boost::asio::detail::task_io_service_operation>&) ()
No symbol table info available.
#2  0x00005555556d7b87 in ServiceManager::run() ()
No symbol table info available.
#3  0x00005555555de65d in main ()
No symbol table info available.
$1 = 0

**Comment by westwol** [comment]
This bug hasn't even been solved on official TFS 1.3 repository, feel free to report it on the official repo.

**Comment by ghost** [comment]
seems like you are not using our source them, we are not OTX/ tfs 1.2

https://otland.net/threads/crash-gdb-help-please.265612/

**Comment by westwol** [comment]
I love the fact that **OTServ-BR-Global** is an open-source project but this is the kind of people I don't like, they just take resources to make profit out of them without contributing/supporting the project. At least he failed on the attempt to make us fix his own project.

**Comment by ghost** [comment]
Sorry, I thought OTBR was based on tfs.

https://github.com/otland/forgottenserver/issues/2561
