### ISSUE TITLE
A lot of issues with bosses

### ISSUE THREAD

**Issue by IvanMir014** [opentibiabr/otservbr-global-archived#364]
**Describe the bug**
Most part of bosses have the same issue, always, you are not the owner, like Ferumbras.

**Comment by Raphaellb** [comment]
you are probably using GM or GOD, use player.

**Comment by IvanMir014** [comment]
I’m using a player.

**Comment by thatmichaelguy** [comment]
This is confirmed.
When a raid xml file spawns a boss (e.g. ferumbras.xml), the onSpawn event is not called.
A workaround is to remove the spawn from the .xml file and instead call a script ferumbras.lua which spawns the monster and sets it as a reward boss.
/raids/libertybay/Ferumbras.xml
```
<?xml version="1.0" encoding="utf-8"?>
<raid>
  <announce delay="1000" type="Event" message="The seals on Ferumbras old cidatel are glowing. Prepare for HIS return mortals." />
  <announce delay="60000" type="Event" message="Ferumbras return is at hand. The Edron Academy calls for Heroes to fight that evil." />
  <announce delay="120000" type="Event" message="Ferumbras has returned to his citadel once more. Stop him before its too late." />
  <script delay="100000" script="Ferumbras.lua" />
</raid>
```
/raids/scripts/Ferumbras.lua
```
function onRaid()
 local monster = Game.createMonster("Ferumbras", Position(32124, 32687, 4), false, true)
 monster:setReward(true)
end
```

This solution was provided by Keek in Discord.
Changing ~95 bosses to this method would be a tedious task, it would be better if raids would call the onSpawn event.
```
function Monster:onSpawn(position)
	if self:getType():isRewardBoss() then
		self:setReward(true)
	end
```

**Comment by ghost** [comment]
I guess we need to revert this commit? https://github.com/opentibiabr/OTServBR-Global/pull/293

**Comment by dudantas** [comment]
@IvanMir014  which operating system are you using?

**Comment by IvanMir014** [comment]
Debian
