### ISSUE TITLE
Bug nos items com slot de imbuement

### ISSUE THREAD

**Issue by dudantas** [opentibiabr/otservbr-global-archived#368]
Quando o item está com a flag <attribute key="imbuingSlots" value="1" /> ativada, ao dar look no item da erro no console e o look não aparece

![image](https://user-images.githubusercontent.com/8551443/62591374-c5410c80-b8a5-11e9-81b5-21893ae0e796.png)

**Comment by dudantas** [comment]
@LucasCPrazeres

**Comment by LukSrT** [comment]
@eduardodantas95 verificou se ta usando a base atualizada?

**Comment by dudantas** [comment]
It's corrected!
