### ISSUE TITLE
Exercise Training bug

### ISSUE THREAD

**Issue by coney4** [opentibiabr/otservbr-global-archived#37]
When you logout while you are training on dummy (with exercise weapon) it shows error and if you login you cannot train it says You are already using this item.
I suggest block logout player during training or on player login reset player storage (Storage.Exercisedummy.exaust) to 0

Lua Script Error: [Main Interface]
in a timer event called from:
(Unknown scriptfile)
data/actions/scripts/others/exercise_training.lua:145: attempt to index local 'player' (a nil value)
stack traceback:
        [C]: in function '__index'
        data/actions/scripts/others/exercise_training.lua:145: in function <data/actions/scripts/others/exercise_training.lua:30>

**Comment by dudantas** [comment]
Hello, Good morning, thanks for your report

**Comment by dudantas** [comment]
#fix on https://github.com/opentibiabr/OTServBR-Global/commit/6a371b8097ea425ead451e7fa0fabe3438759f5b
