### ISSUE TITLE
Looting of Crazed Summer Rearguards

### ISSUE THREAD

**Issue by Davenorthern** [opentibiabr/otservbr-global-archived#372]
**Describe the bug**
When trying to open a dead crazed summer rearguard, the client shuts down and logs the player out.

**To Reproduce**
Go to the court of summer.
Kill a crazed rearguard.
Open the corpse. 

**Expected behavior**
The body should open and display the loot. 

![Screenshot (3)](https://user-images.githubusercontent.com/52839094/62738686-319d4680-ba33-11e9-912b-7d3aa6ebb3a3.png)

**Comment by FakeShinoda** [comment]
Which client version are you using ?
Client 11 and 12 i checked and its fine

**Comment by Davenorthern** [comment]
Im using client 11.
Wierd, i'll try again tomorrow 😃

Den 9 aug. 2019 12:00 fm skrev Rick <notifications@github.com>:

Which client version are you using ?
Client 11 and 12 i checked and its fine

**Comment by oualid6496** [comment]
Yea your client crashes because there is nothing in items.xml of that body so when you open it your client crashes. I can add it later when the team is done with the summer update.

**Comment by oualid6496** [comment]
You can add this in items.xml as a temporary fix I'm not sure what the name of the body is or the container size but it will be added later.
```
	<item id="34712" article="a" name="elf remains">
		<attribute key="decayTo" value="0" />
		<attribute key="duration" value="300" />
		<attribute key="corpseType" value="blood" />
	</item>
	<item id="34713" article="a" name="elf remains">
		<attribute key="containerSize" value="20" />
		<attribute key="decayTo" value="34712" />
		<attribute key="duration" value="300" />
		<attribute key="corpseType" value="blood" />
	</item>
	<item id="34714" article="a" name="elf remains">
		<attribute key="containerSize" value="20" />
		<attribute key="decayTo" value="34713" />
		<attribute key="duration" value="300" />
		<attribute key="corpseType" value="blood" />
	</item>
	<item id="34715" article="a" name="elf remains">
		<attribute key="containerSize" value="20" />
		<attribute key="decayTo" value="34714" />
		<attribute key="duration" value="300" />
		<attribute key="corpseType" value="blood" />
	</item>
	<item id="34716" article="a" name="elf remains">
		<attribute key="decayTo" value="0" />
		<attribute key="duration" value="300" />
		<attribute key="corpseType" value="blood" />
	</item>
	<item id="34717" article="a" name="elf remains">
		<attribute key="containerSize" value="20" />
		<attribute key="decayTo" value="34716" />
		<attribute key="duration" value="300" />
		<attribute key="corpseType" value="blood" />
	</item>
	<item id="34718" article="a" name="elf remains">
		<attribute key="containerSize" value="20" />
		<attribute key="decayTo" value="34717" />
		<attribute key="duration" value="300" />
		<attribute key="corpseType" value="blood" />
	</item>
	<item id="34719" article="a" name="elf remains">
		<attribute key="containerSize" value="20" />
		<attribute key="decayTo" value="34718" />
		<attribute key="duration" value="300" />
		<attribute key="corpseType" value="blood" />
	</item>```

**Comment by Davenorthern** [comment]
Awesome, you're a fricken legend mate


Den 9 aug. 2019 9:49 fm skrev Oualid6496 <notifications@github.com>:

You can add this in items.xml as a temporary fix I'm not sure what the name of the body is or the container size but it will be added later.
<item id="34712" article="a" name="elf remains"> <attribute key="decayTo" value="0" /> <attribute key="duration" value="300" /> <attribute key="corpseType" value="blood" /> </item> <item id="34713" article="a" name="elf remains"> <attribute key="containerSize" value="20" /> <attribute key="decayTo" value="34712" /> <attribute key="duration" value="300" /> <attribute key="corpseType" value="blood" /> </item> <item id="34714" article="a" name="elf remains"> <attribute key="containerSize" value="20" /> <attribute key="decayTo" value="34713" /> <attribute key="duration" value="300" /> <attribute key="corpseType" value="blood" /> </item> <item id="34715" article="a" name="elf remains"> <attribute key="containerSize" value="20" /> <attribute key="decayTo" value="34714" /> <attribute key="duration" value="300" /> <attribute key="corpseType" value="blood" /> </item> <item id="34716" article="a" name="elf remains"> <attribute key="decayTo" value="0" /> <attribute key="duration" value="300" /> <attribute key="corpseType" value="blood" /> </item> <item id="34717" article="a" name="elf remains"> <attribute key="containerSize" value="20" /> <attribute key="decayTo" value="34716" /> <attribute key="duration" value="300" /> <attribute key="corpseType" value="blood" /> </item> <item id="34718" article="a" name="elf remains"> <attribute key="containerSize" value="20" /> <attribute key="decayTo" value="34717" /> <attribute key="duration" value="300" /> <attribute key="corpseType" value="blood" /> </item> <item id="34719" article="a" name="elf remains"> <attribute key="containerSize" value="20" /> <attribute key="decayTo" value="34718" /> <attribute key="duration" value="300" /> <attribute key="corpseType" value="blood" /> </item>

**Comment by ghost** [comment]
no debug here but I'll add the corpse by @oualid6496 , I suggest you to use client 12, always use the latest client when testing new content, maybe the client 11 doesn't have some item sprite

**Comment by oualid6496** [comment]
No don't that was just a temporary fix for Davenorthern the name of the body and containersize are probably not right also these are just the bodys of the summer elfs the same problem is with the ice elfs. I did reproduce this bug on client 10.

**Comment by ghost** [comment]
> No don't that was just a temporary fix for Davenorthern the name of the body and containersize are probably not right also these are just the bodys of the summer elfs the same problem is with the ice elfs. I did reproduce this bug on client 10.

seems like the .spr file from client 10 didn't have the sprites then :P that is how they should look like as off latest tibia 12 assets converted to spr file:
![2019-08-17 13_47_12-Window](https://user-images.githubusercontent.com/4684880/63214945-9b81b400-c0f5-11e9-82f1-39900937c31d.jpg)

can you provide bodies items.xml for ice elf as well? even if its only temporary :P better than nothing

**Comment by oualid6496** [comment]
hmm okay well then for the ice elfs it would be

	<item id="34760" article="a" name="elf remains">
		<attribute key="containerSize" value="20" />
		<attribute key="decayTo" value="34762" />
		<attribute key="duration" value="300" />
		<attribute key="corpseType" value="blood" />
	</item>
	<item id="34761" article="a" name="elf remains">
		<attribute key="containerSize" value="20" />
		<attribute key="decayTo" value="34765" />
		<attribute key="duration" value="300" />
		<attribute key="corpseType" value="blood" />
	</item>
	<item id="34762" article="a" name="elf remains">
		<attribute key="containerSize" value="20" />
		<attribute key="decayTo" value="34763" />
		<attribute key="duration" value="300" />
		<attribute key="corpseType" value="blood" />
	</item>
	<item id="34763" article="a" name="elf remains">
		<attribute key="containerSize" value="20" />
		<attribute key="decayTo" value="34764" />
		<attribute key="duration" value="300" />
		<attribute key="corpseType" value="blood" />
	</item>
	<item id="34764" article="a" name="elf remains">
		<attribute key="decayTo" value="0" />
		<attribute key="duration" value="300" />
		<attribute key="corpseType" value="blood" />
	</item>
	<item id="34765" article="a" name="elf remains">
		<attribute key="containerSize" value="20" />
		<attribute key="decayTo" value="34766" />
		<attribute key="duration" value="300" />
		<attribute key="corpseType" value="blood" />
	</item>
	<item id="34766" article="a" name="elf remains">
		<attribute key="containerSize" value="20" />
		<attribute key="decayTo" value="34767" />
		<attribute key="duration" value="300" />
		<attribute key="corpseType" value="blood" />
	</item>
	<item id="34767" article="a" name="elf remains">
		<attribute key="decayTo" value="0" />
		<attribute key="duration" value="300" />
		<attribute key="corpseType" value="blood" />
	</item>

**Comment by oualid6496** [comment]
Btw saw at the summer elfs part all the way down ''' that shouldn't be there

**Comment by ghost** [comment]
thanks, also I've created a new thread with updated clients on otland, just waiting for it to be approved, so people can use them and stop getting debugs

**Comment by ghost** [comment]
my updated client thread was not accepted on otland, we need to wait the good will of developers now to have an updated .spr and asset files for the tools repository then...

**Comment by gpedro** [comment]
The @MajestyOTBR already update the client last night.

**Comment by majestyotbr** [comment]
I'll upload and update clients 10 and 12 on [tools](https://github.com/opentibiabr/tools) repository.

**Comment by majestyotbr** [comment]
Updated clients 10 and 12 on [tools](https://github.com/opentibiabr/tools) repository.
