### ISSUE TITLE
XP Gain Rate not showing Stamina XP %

### ISSUE THREAD

**Issue by cacovi** [opentibiabr/otservbr-global-archived#379]
O percentual de experiência não aparece como deveria, já que indica apenas a experiência base, quando deve indicar também o bônus% de Stamina.

Neste momento, parece assim.

![fail](https://user-images.githubusercontent.com/52906969/62802614-4838b180-bab6-11e9-9fe4-04943c1386b8.png)

Deveria se parecer com isto.
![good](https://user-images.githubusercontent.com/52906969/62802679-74543280-bab6-11e9-851e-c22776c1177c.png)

**Comment by thatmichaelguy** [comment]
I will add this feature tomorrow.
