### ISSUE TITLE
Imbuements on movements fail

### ISSUE THREAD

**Issue by granoob** [opentibiabr/otservbr-global-archived#38]
**Describe the bug**
Depois de analisar a pedido de um issue verifiquei que o imbuiments funciona normal
porem a quando encantado o item quando se equipa os bônus não aparece.

**To Reproduce**
1. Go to 'imbuements shine'
2. Click on 'encante o item'
4. See error: ao equipar o item o jogador não recebe o bonus

**Additional context**
Estou analisando mais a fundo, mais pelo que percebi esta ligado ao movements a função parou de atuar

**Comment by dudantas** [comment]
Obrigado pelo report. Ao que percebi o problema é na source, irei analisar e retorno uma resposta e solução
