### ISSUE TITLE
Killing in the name of

### ISSUE THREAD

**Issue by Raphaellb** [opentibiabr/otservbr-global-archived#403]
fazzrah boss exit teleport needs to teleport player to this position 33308, 31184, 7.

change teleport too in following teleport 
23:07 You see a magic forcefield.
Item ID: 1387
Position: 32989, 31177, 7

**Comment by Raphaellb** [comment]
change teleportTo in following teleport
14:46 You see a wooden railing.
Item ID: 5255
Position: 31942, 31046, 2

to teleport to this location to access boss leviathan.  31927, 31068, 10.

**Comment by Raphaellb** [comment]
Leviathan boss exit portal should teleport player to this position 32351, 31122, 6

change teleport too in flowing teleport
14:52 You see a magic forcefield.
You can see the other side through it.
Item ID: 1387
Position: 31916, 31071, 10

**Comment by ghost** [comment]
> change teleportTo in following teleport
> 14:46 You see a wooden railing.
> Item ID: 5255
> Position: 31942, 31046, 2
> 
> to teleport to this location to access boss leviathan. 31927, 31068, 10.

the teleport should be in {x = 31938, y = 31042, z = 6} (a move event script) that teleports to {x = 31938, y = 31041, z = 8} as seem [here](https://youtu.be/JB9V88viP74?t=89)

**Comment by ghost** [comment]
for the moment I'll leave it as magic forcefield until someone create the scripts

**Comment by Raphaellb** [comment]
got it, sorry about that. I saw a different video, and it seemed to have edited straight into that last room

**Comment by Raphaellb** [comment]
all done, these were all the bugs I found.
