### ISSUE TITLE
[Outfits] Crash When I open Outfits

### ISSUE THREAD

**Issue by JaziJazz** [opentibiabr/otservbr-global-archived#406]
Eu baixo o servidor e compilo ele normalmente, efetuo a criação do site e entro no servidor sem nenhuma espécie de erro de console, porém quando eu acesso a conta padrão administrativa 'GOD/god' e acesso as outfits o cliente fecha automaticamente. 

Então eu crio uma conta administrativa e ocorre o mesmo erro, eu tento alterar as outfits pelo /looktype porém o cliente também fecha automaticamente, eu só chego a uma conclusão plausível, o cliente não possui o looktype configurado no XML e então ele crasha. 

Alguém possui um cliente funcional? Lembrando que eu já estou utilizando os arquivos mais atualizados, download direto do git... Isso é normal? É só comigo que crasha?

**Comment by oualid6496** [comment]
I think it's because of the new summer update outfits and mount of which you don't have the sprites yet in your client. Try to revert outfits.xml and mounts.xml of pr #342 and tell me if it worked

**Comment by ghost** [comment]
seu client ta desatualizado

**Comment by JaziJazz** [comment]
Obrigado pela ajuda pessoal! Em especial ao oualid6496, essa #342 me ajudou a encontrar a solução. 

A quem passar pelo mesmo erro que eu, acesse a data/XML e abra outfits.xml e mounts.xml

Removam essas linhas: 
mount id="144" clientid="1191" name="Gryphon" speed="20" premium="yes" 
outfit type="0" looktype="1244" name="Tomb Assassin" premium="yes" unlocked="no" enabled="yes" 
outfit type="1" looktype="1244" name="Tomb Assassin" premium="yes" unlocked="no" enabled="yes" 

**Eu também pensei que fosse um cliente desatualizado porém eu estou utilizando os assets da versão mais recente do Tibia e o erro persistia.** 

Obrigado pela ajuda pessoal.
