### ISSUE TITLE
Erro na nova hunt dos Elfos

### ISSUE THREAD

**Issue by Sargitarium** [opentibiabr/otservbr-global-archived#409]
**Describe the bug**
Erro no mapa na localização 32725, 31528, 8, há um SMALL HOLE 385 que não permite o char descer, onde o correto seria SMALL HOLE 383.

**To Reproduce**
1. Go to '32725, 31528, 8'
2. Walk on 'small hole'
3. you don't go down

**Screenshots**
Imagem do local do ERRO no MAPA
https://imagizer.imageshack.com/img921/9517/F49VzU.png

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: [10]

**Comment by ghost** [comment]
vou arrumar isso ja ja
