### ISSUE TITLE
GS Task Bug

### ISSUE THREAD

**Issue by RDaruish** [opentibiabr/otservbr-global-archived#410]
Fiz a task da GS peguei o achievement quando fui entrar no tp para matar o boss, não deu certo, ai fui procurar um script para tentar mexer e não achei também

**Comment by ghost** [comment]
@Raphaellb

**Comment by Raphaellb** [comment]
Acabei de termina e fazer todas as tasks da Grizzly adams,e matei todos os bosses. nao tive problema com a old widow q seria a boss das GS.  manda a posicao do TP por favor? 

o script dos bosses estao aqui.
data/movements/script/killinginthenameof/boss.lua

**Comment by RDaruish** [comment]
Aqui a pos do tp

12:54 You see a magic forcefield.
You can see the other side through it.
Item ID: 1387, Unique ID: 3240
Position: 32814, 32280, 8

**Comment by Raphaellb** [comment]
Esse e o TP para ir matar a old widow a boss das Giant spiders da task do Grizzly Adams. killing in the name of. eu fiz todas essas tasks nas ultimas duas semanas e esta tudo funcionando. olha suas storages ai.
