### ISSUE TITLE
Prey System

### ISSUE THREAD

**Issue by HttpsBR** [opentibiabr/otservbr-global-archived#412]
Então, crio a conta e logo pela primeira vez e quando vou pega o free reroll pela primeira vez o bônus vem 0% as três abas independente do bônus.

**Comment by lBaah** [comment]
Hello. https://github.com/opentibiabr/OTServBR-Global/commit/c81da8b059f4250aee4ee4c67ccee0b3fab38335 fixed this issue.

**Comment by cellss** [comment]
![prey_system_2019-09-20 16-24-12](https://user-images.githubusercontent.com/38795963/65353374-556fb280-dbc3-11e9-9ab7-090106ecae08.png)
It happened today after I compiled on Linux...

Even if I buy list reroll nothing changes... two slots 0/10 and the third 9/10
