### ISSUE TITLE
ERRO ?

### ISSUE THREAD

**Issue by HttpsBR** [opentibiabr/otservbr-global-archived#414]
Lua Script Error: [Event Interface]
data/events/scripts/player.lua:Player@onGainExperience
data/events/scripts/player.lua:721: attempt to index field '?' (a nil value)
stack traceback:
        [C]: in function '__index'
        data/events/scripts/player.lua:721: in function 'preyTimeLeft'
        data/events/scripts/player.lua:778: in function <data/events/scripts/player.lua:749>

**Comment by majestyotbr** [comment]
Quando criar issue aqui, utilize o template e coloque mais informações.
