### ISSUE TITLE
Mensagem de loot

### ISSUE THREAD

**Issue by SelectorK** [opentibiabr/otservbr-global-archived#420]
as mensagens de loot dropados não estão indo para o channel "Loot"

**Comment by ghost** [comment]
its a known issue, going to be fixed soon

**Comment by lmiguelm26** [comment]
fix ??

**Comment by miezaF** [comment]
This work is in progress to colored loot messages

**Comment by gpedro** [comment]
fiz o teste no 12.x e está funcionando corretamente. poderia me informar mais detalhes?

**Comment by SelectorK** [comment]
as mensagens de loot estão indo para aba "Server Log" e não para a aba "Loot"

**Comment by dudantas** [comment]
qual cliente tá usando ?

**Comment by SelectorK** [comment]
12

**Comment by dudantas** [comment]
ok,quero saber qual o cliente, o do repositório, de onde ?

**Comment by SelectorK** [comment]
foi o do guilhermesidney

**Comment by dudantas** [comment]
o do guilhermesidney não é o oficial do projeto, baixe 
e teste https://github.com/opentibiabr/tools/tree/master/Tibia%20Client%2012/Tibia%2012

**Comment by SelectorK** [comment]
ainda continuam as mensagens no Server Log

**Comment by gpedro** [comment]
verifique se você esta no canal de loot certo. veja também: #479

**Comment by SelectorK** [comment]
deu certo,obrigado!
