### ISSUE TITLE
Seller npc

### ISSUE THREAD

**Issue by HttpsBR** [opentibiabr/otservbr-global-archived#421]
Quando eu vendo uma quantidade acima de 32 items o client fecha as vezes.

Sistema operacional: win7 
Pack que eu uso tem 15 dias que eu baixei 
Client eu uso o do repositório.

**Comment by mrhultin** [comment]
You will need to provide more info. Operating system, client, how old a commit are you running?  This issue is real, but  info helps narrowing it down and fixing it.

**Comment by ghost** [comment]
yeah, please provide step-by-step on how to reproduce the issue, and also which client are you using

**Comment by miezaF** [comment]
Não precisa fornecer informações, é um bug conhecido e peguei ele hoje pra corririgir.
Ao vender diversos itens não agrupaveis o client envia 1 unico pacote, e o servidor interpreta como multiplos, isso faz com que o CLIENT trave, certo?

**Comment by gpedro** [comment]
duplicated #518
#518 is better described
