### ISSUE TITLE
First Dragon Quest

### ISSUE THREAD

**Issue by Raphaellb** [opentibiabr/otservbr-global-archived#427]
- [x] 1 - after starting the quest, and killing dragons for the Power Boss (Tazhadur). I am getting an error on quest log:

> `Lua Script Error: [Event Interface]`
> data/events/scripts/player.lua:Player@onRequestQuestLine
> data/lib/core/quests.lua:3163: bad argument #2 to 'format' (no value)
> stack traceback:
>         [C]: in ?
>         [C]: in function 'format'
>         data/lib/core/quests.lua:3163: in function 'value'
>         data/lib/core/quests.lua:3387: in function <data/lib/core/quests.lua:3385>
>         (...tail calls...)
>         data/lib/core/quests.lua:3617: in function 'sendQuestLine'
>         data/events/scripts/player.lua:833: in function `<data/events/scripts/player.lua:832>`

- [x] 2 - All movement teleports into the bosses Zorvorax/Gelidrazah the Frozen/Kalyassa/Tazhadur are open to all players after starting the quest, and receiving start storages 10195.
The movement script in movement/quests/first dragon/entranceTeleports.lua is not checking for the specific bosses storages before allowing player into boss fight. Because of this all the player needs to do is start the quest with tamoril, and they are allowed to kill all bosses.

- [x] 3 - Life Boss Zorvorax secrets. player is getting questlog update on the ab'dendriel part by stepping on this position:
> `You see grass.
> Item ID: 9050
> Position: 32691, 31724, 7.
- The correct location is
> 00:00 You see grass.
> Item ID: 9043
> Position: 32697, 31718, 7`

- [x] 4 - Final lever not working: 

> 21:22 You see a lever.

> Item ID: 9826, Action ID: 24888
> Position: 33583, 30992, 14

**Comment by Raphaellb** [comment]
All movement teleports into the bosses Zorvorax/Gelidrazah the Frozen/Kalyassa/Tazhadur are open to all players after starting the quest, and receiving start storages 10195 = 1. the movement script in movement/quests/first dragon/entranceTeleports.lua is not checking for the specific bosses storages before allowing player into boss fight. because of this all the player needs to do is start the quest with tamoril, and they are allowed to kill all bosses.

**Comment by Raphaellb** [comment]
Life Boss Zorvorax secrets. player is getting questlog update on the ab'dendriel part by stepping on this position 00:00 You see grass.
Item ID: 9050
Position: 32691, 31724, 7.
the correct location is 
00:00 You see grass.
Item ID: 9043
Position: 32697, 31718, 7

**Comment by ghost** [comment]
any changes in map are needed? :)

**Comment by Raphaellb** [comment]
final lever not working.

21:22 You see a lever.
Item ID: 9826, Action ID: 24888
Position: 33583, 30992, 14

**Comment by dudantas** [comment]
Tasklist 2 is unconfirmed. I'm tested and it's is ok.
