### ISSUE TITLE
[Quest] The Scatterbrained Sorcerer 

### ISSUE THREAD

**Issue by omarcopires** [opentibiabr/otservbr-global-archived#43]
O script do NPC Eclesius não está completo. Não importa o seu level, não dá para iniciar a quest. Ele sempre vai dizer "Who are you? What do you want? You seem too experienced to become my assistant. Please leave."

Source: http://tibia.wikia.com/wiki/The_Scatterbrained_Sorcerer_Quest

**Comment by dudantas** [comment]
No script for NPC

**Comment by dudantas** [comment]
Moving alls issues of the quests for one unique issue!
