### ISSUE TITLE
Monstertype revscriptsys needs update

### ISSUE THREAD

**Issue by ghost** [opentibiabr/otservbr-global-archived#434]
Seems like we are missing this commit:

https://github.com/otland/forgottenserver/commit/11120043d831684d3625498b4284c8452a0c673c

and update #example.lua and move it to data/monster/lua

**Comment by ghost** [comment]
@gpedro

**Comment by gpedro** [comment]
@Costallat can you cherry-pick these changes?

**Comment by Costallat** [comment]
I will try here

**Comment by Costallat** [comment]
Done #439
