### ISSUE TITLE
NPC Chrak sem dialogo

### ISSUE THREAD

**Issue by 7762489** [opentibiabr/otservbr-global-archived#448]
Fale com o NPC Chrak (aquiMap (Colour).gif) para entrar na arena. Diga mission, battle e yes.

Nao Responde A nenhum Dialogo 

https://www.tibiawiki.com.br/The_New_Frontier_Quest

Missão 09: Combate Mortal

**Comment by Raphaellb** [comment]
abre o /npc/scripts/chrak.lua. o script esta la. eu ja completei esse quest, e esta 100%. olha as suas storages. prescisa de Storage.TheNewFrontier.Questline == 24 pra battle, and Storage.TheNewFrontier.Questline == 26 pra mission, mas esta funcionando.

**Comment by 7762489** [comment]
teria como fazer ela sem fazer as outras missao ja ir direto na arena

**Comment by Raphaellb** [comment]
Isso e coisa custom, e nao issue. e so adicionar storages certas nos players. fecha esse issue por favor.
