### ISSUE TITLE
[Quest] Pilgrimage of Ashes 

### ISSUE THREAD

**Issue by omarcopires** [opentibiabr/otservbr-global-archived#46]
Nenhum NPC guia(ex:Aneus, Gnomad, Guide Elena etc...) consegue iniciar a quest.

source: http://tibia.wikia.com/wiki/Pilgrimage_of_Ashes_Quest

**Comment by dudantas** [comment]
No script for NPC

**Comment by dudantas** [comment]
Moving alls issues of the quests for one unique issue!
