### ISSUE TITLE
Double respawn

### ISSUE THREAD

**Issue by newacc12** [opentibiabr/otservbr-global-archived#461]
**Describe the bug**
The feature to respawn monsters with players on the screen is not working correctly. Depending on the situation it can respawn new monsters even if the existing creature is still alive (double respawn).

**To Reproduce**
1. Go to the black knight quest (32874, 31947, 11) with a regular character.
2. Kill the beholders and scorpions only. Keep the black knight alive.
3. Stay on the SQM like in the screenshot below (32869, 31951, 11).
4. Wait until the new black knight respawn.

**Expected behavior**
Monsters don't respawn before they die.

**Screenshots**
![image](https://user-images.githubusercontent.com/20234557/63556288-cf9c1100-c509-11e9-9af9-2908ca16e9f6.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 16.04

**Additional context**
You can find additional information about this problem here: https://github.com/otland/forgottenserver/issues/2517 . I have posted this on the TFS forum last year as a question. On the original post I commented about a possible solution but I don't know if there would be any side effects to the respawn system. The TFS repository doesn't have this problem because it doesn't have this feature on its sources (or didn't at the time I posted).

**Comment by majestyotbr** [comment]
https://github.com/opentibiabr/otservbr-global/commit/82fc51d1975124c1ac537151784af68a3c259890
https://github.com/opentibiabr/otservbr-global/commit/ebe63ef8c4d6a227af1a7f6859c5a5f0b3b96b5c
