### ISSUE TITLE
[Question] - Project Goal

### ISSUE THREAD

**Issue by newacc12** [opentibiabr/otservbr-global-archived#463]
Hello everyone,

I would like to know the goal of this project regarding the functionalities. Are we trying to re-create a global tibia like experience? 

The reason I am asking is because there are quests that don't required missions to be done first (e.g. djinn war). Should we be changing those?

Thanks.

**Comment by majestyotbr** [comment]
Yes.

**Comment by newacc12** [comment]
Thanks!
