### ISSUE TITLE
Rashid can't sell demonbone amulet

### ISSUE THREAD

**Issue by IvanMir014** [opentibiabr/otservbr-global-archived#465]
**Describe the bug**
You can see demonbone amulet but when you click nothing happens.

**Comment by Sargitarium** [comment]
Não sei por qual motivo ocorre esse ERRO, mesmo estando configurado corretamente RASHID não compra o DEMONDONE com ID 14333, a solução foi mudar o loot dos monstros abaixo relacionados para o ID 2136, e mudar no RASHID para essa mesma ID...
Falcon Knight, Hellfire Fighter, Hellflayer, Hellgorak, Juggernaut, Morguthis, Preceptor Lazare, Prince Drazzak, Shulgrax, Spectre.

**Comment by gpedro** [comment]
@Sargitarium vc pode mandar um PR disso?

**Comment by dudantas** [comment]
o id certo é o 2136 mesmo 
o 14333 deve ser outro item com a mesma sprite
