### ISSUE TITLE
GameStore

### ISSUE THREAD

**Issue by Tazer89** [opentibiabr/otservbr-global-archived#468]
GameStore when try to buy items don't work.

Error shown:

Gamestore: Purchase failed due to an unhandled script error.
        Stacktrace: data/modules/scripts/gamestore/init.lua:1105: attempt to com           pare number with nil

**Comment by cys9211** [comment]
I have the same bug..

**Comment by oualid6496** [comment]
And prey rerolls no error given tho but you're not getting bonus rerolls

**Comment by gpedro** [comment]
it's just typo. fixed in 7143b3c
