### ISSUE TITLE
Server Name

### ISSUE THREAD

**Issue by genrider** [opentibiabr/otservbr-global-archived#470]
If it is in confing.lua serverName = "Open-TibiaBR" then you can log in to the server, but if you change to anything else you cannot log in.

![Bez nazwy](https://user-images.githubusercontent.com/5441478/63647291-1c0c6a00-c71f-11e9-9103-3238f223ecf8.png)

**Comment by Tazer89** [comment]
It has nothing to the server to do. You have to change it inside your web config or login.php file. It has to have exact same name as the server.
