### ISSUE TITLE
Segmentation fault (core dumped) Server restarts :O

### ISSUE THREAD

**Issue by IvanMir014** [opentibiabr/otservbr-global-archived#481]
**Describe the bug**
Since the last commits, every some minutos or hours, it's random. Always get the same error, Segmentation fault (core dumped).

**To Reproduce**
1. Run the server, wait to player kill monsters or bosses
2. Sever restarts without error but if you use gdb shows error Segmentation fault (core dumped).
Note: include any configuration/script required to reproduce.

**Expected behavior**
Working properly.

**Desktop (please complete the following information):**
 - OS: Debian Linux

We found with @westwol this on gdb console:
<img width="1156" alt="Captura de pantalla 2019-08-27 a las 19 57 54" src="https://user-images.githubusercontent.com/33207582/63796106-b201e980-c905-11e9-901b-586da98cfcf9.png">

**Comment by Raphaellb** [comment]
this is happening with me too "Segmentation fault (core dumped)" on Linux Mint 18. this happens on boss fights. the first one I noticed is on The Baron From Below boss fight in Dangerous Depths quest, and Razzagorn in Ferumbras Ascension quest. I did kill both of these bosses in the past, and was not getting these crashes. I believe its something recent that is causing this. @gpedro @MajestyOTBR @Flyckks @eduardodantas95

**Comment by IvanMir014** [comment]
This commit https://github.com/opentibiabr/OTServBR-Global/commit/352502cf71a5b9fe78d69cf9cc693f4558696bdb fix this issue? Thanks.

**Comment by lBaah** [comment]
@IvanMir014 did https://github.com/opentibiabr/OTServBR-Global/commit/352502cf71a5b9fe78d69cf9cc693f4558696bdb fixed issue you had?

**Comment by IvanMir014** [comment]
I think not :/

**Comment by dudantas** [comment]
It's corrected!
