### ISSUE TITLE
Guildhalls

### ISSUE THREAD

**Issue by Emilianenko** [opentibiabr/otservbr-global-archived#487]
I would love to see a in game guildhall system like in old tfs.

**Comment by liontts** [comment]
There is already an open-source code that adds this request, just take a look at: https://github.com/otland/forgottenserver/pull/2214

**Comment by Emilianenko** [comment]
> There is already an open-source code that adds this request, just take a look at: [otland/forgottenserver#2214](https://github.com/otland/forgottenserver/pull/2214)

Correct me if i'm wrong, but i think there's a lot of stuff missing in this pull request.
All the c++ part, for example: show guild names on the door of guildhall , talckactions ,etc


I'm talking about a guildhall system like that:
https://github.com/otland/tfs-old-svn/commit/c65a49adbd173b3ae66f77b1eb4148c5d733f543
Isn't possible to convert this one?

**Comment by dudantas** [comment]
https://github.com/otland/forgottenserver/pull/2214
