### ISSUE TITLE
[Quest] Blood Herb 

### ISSUE THREAD

**Issue by omarcopires** [opentibiabr/otservbr-global-archived#49]
Wyda não troca a Blood herb pela witchesbroom. Ela também não fica chateada, que é uma das maneiras de trocar o blood herb por um torn teddy.

source: http://tibia.wikia.com/wiki/Blood_Herb_Quest

**Comment by lBaah** [comment]
Pelo que eu li do código está funcionando.
Você precisa ter pego a blood herb, na quest da blood herb primeiro.
Depois poderá trocar a blood herb, com uma chance de 30% apenas de conseguir o Torn Teddy.
Pelo código, só é possível entregar uma blood herb por char.

No global, no entanto, ela só troca por torn teddy em uma mini world change.

**Comment by dudantas** [comment]
Moving alls quests issues for one unique issue.
