### ISSUE TITLE
Itens Agrupáveis em Contêiners

### ISSUE THREAD

**Issue by Yumizak** [opentibiabr/otservbr-global-archived#5]
Quando todos os slot de um contêiner está cheio, e tentar arrastar algum item agrupável que não esteja dentro de contêiner algum para dentro dele, o item não vai.

![Buug](https://user-images.githubusercontent.com/23348646/57982191-5d9ec200-7a18-11e9-8516-e2ae702a1316.gif)

**Comment by gpedro** [comment]
e está errado? não há mais espaço, significa que está cheio e se está cheio, está cheio!
como que é o comportamento do tibia global? ele manda para a próxima bag com slot disponíve;?

**Comment by Yumizak** [comment]
"Quando todos os slot de um contêiner está cheio, e tentar arrastar algum item AGRUPÁVEL que não esteja dentro de contêiner algum para dentro dele, o item não vai."

Se o item é AGRUPÁVEL, ele tem que entrar na bp, mesmo com todos os slots dela cheio. (Tem que ter pelo menos um item desses agrupável já ocupando um slot)

**Comment by gpedro** [comment]
perdão, eu vi a gif várias vezes mas somente havia visto a parte que funcionava. por isso não havia entendido a issue. vou verificar.

**Comment by gpedro** [comment]
i cannot reproduce this issue, so i will close. thanks for reporting.
