### ISSUE TITLE
Monster error

### ISSUE THREAD

**Issue by genrider** [opentibiabr/otservbr-global-archived#507]
When you want to create a monster in a folder (\data\scripts\monsters), it shows an error

![2](https://user-images.githubusercontent.com/5441478/64073048-1374e000-cc99-11e9-8a7b-296042dfcc14.png)

**Comment by dudantas** [comment]
You using full and updated pack?

**Comment by genrider** [comment]
Yes

**Comment by liontts** [comment]
Invalid issue
