### ISSUE TITLE
prey things incompatibility datatype

### ISSUE THREAD

**Issue by gpedro** [opentibiabr/otservbr-global-archived#512]
preySlotState and preySlotUnlocked should be `uint8`, `uint16` or `uint16`?

![Screenshot_24](https://user-images.githubusercontent.com/2898638/64113807-467ea880-cd59-11e9-90dd-1a5c42df11bc.png)

![Screenshot_25](https://user-images.githubusercontent.com/2898638/64113870-775edd80-cd59-11e9-931d-04639eea95b7.png)

**Comment by gerotib** [comment]
That may be what causes crashes with for example 2 of 3 slots unlocked?

**Comment by FakeShinoda** [comment]
uint16_t was the last method that worked

**Comment by majestyotbr** [comment]
#528
