### ISSUE TITLE
[Client 12] Bug when you sell 20-30 items in trade

### ISSUE THREAD

**Issue by IvanMir014** [opentibiabr/otservbr-global-archived#518]
**Describe the bug**
The client bug when you sell more than 20-30 items to npc with trade.

**To Reproduce**
1. Go to some npc and sell more than 20-30 items.

**Expected behavior**
Sell it without bugs or crashes.

**Desktop (please complete the following information):**
 - OS: Linux debian.

**Comment by thatmichaelguy** [comment]
Yes this is confirmed.
If you buy OR sell many single items via the trade window ``(e.g. 20 wand of inferno)`` the client will freeze until closed.

**Comment by gpedro** [comment]
which client and server (revision) are you using ?

**Comment by cristianso** [comment]
I found a solution for this already. Is this still open?

**Comment by ivansho92** [comment]
i have same problem :(
