### ISSUE TITLE
Dragon Tower Quest

### ISSUE THREAD

**Issue by omarcopires** [opentibiabr/otservbr-global-archived#52]
Faltando tipo e número específico de monstros em cada andar.

Os monstros são os seguintes:

Primeiro andar: 3 Elf Scouts and 1 Elf Segundo andar: 4 Elf Scouts and 2 Elf Arcanists Terceiro andar: 2 Dragons Quarto andar: 6 Elf Scouts and 3 Elf Arcanists Quinto andar: 3 Elf Scout and 2 Elf Arcanists

Source:http://tibia.wikia.com/wiki/Dragon_Tower_Quest

**Comment by dudantas** [comment]
fixed
