### ISSUE TITLE
Open Prey bug

### ISSUE THREAD

**Issue by cys9211** [opentibiabr/otservbr-global-archived#522]
<a href="https://imgbb.com/"><img src="https://i.ibb.co/TKgZYpd/as.png" alt="as" border="0"></a>

And look this video
https://media.giphy.com/media/dx7DajrpL51lnJM14r/source.mov

**Comment by cellss** [comment]
Make sure you are using the right client version...  I had this error and I fixed using the official tools from this project

![PREY_PHOTO](https://user-images.githubusercontent.com/38795963/64219205-e55eee00-ce9a-11e9-9de4-3fdb92ae14f3.png)

**Comment by gpedro** [comment]
which client and server (revision) are you using ?

**Comment by gerotib** [comment]
I just downloaded server from develop branch, compiled it on windows x64, created new database on actual schema.sql, installed recent version of myaac from github, and im getting this crash on both recent and previous version of client from recommended "customized tools". Im also getting a crash while trying to open cyclopedia.

**Comment by westwol** [comment]
Test this pr: 
https://github.com/opentibiabr/OTServBR-Global/pull/528
