### ISSUE TITLE
Exercise bow quando você troca nick do char

### ISSUE THREAD

**Issue by cellss** [opentibiabr/otservbr-global-archived#524]
**Describe the bug**

Comprei uma exercise bow no NPC e fui no exercise dummy testar, enquanto isso abri a Store e comprei o 'change name', usei e troquei o nick do char, o exercise bow não funcionou mais... Comprei outro exercise bow no NPC com aquele char e não funcionava mais aparecendo a msg no rodapé  'You cannot use this object' quando dou 'use with'...
O server roda no ubuntu 16.04 e compilei há uns 5 dias atrás

P.S> Ao comprar esse item ele vai para a bp e não sai mais até ser consumido, ele não deveria ir para a Store Inbox?

**Comment by lBaah** [comment]
Fixed this issue on #539

**Comment by cellss** [comment]
Agora após usar 1 ou 2 exercise weapon aparece a msg de que eu não posso usar o item, se  eu re-logar consigo usar novamente mais uma vez... 

Deveria usar 2 vezes por SaveSserver a weapon... tá melhor agora, só n tá 100%

Apresentou esse erro primeiramente no terminal:

[Warning - Event::checkScript] Can not load script: scripts/others/login.lua
data/creaturescripts/scripts/others/login.lua:159: 'end' expected (to close 'function' at line 26) near <eof>

no login.lua eu acrescentei um "end" ficando assim:


```
		local hours = math.floor(worldTime / 60)
		local minutes = worldTime % 60
		player:sendTibiaTime(hours, minutes)
	end

	if player:getStorageValue(Storage.isTraining) == 1 then -- redefinir storage de exercise weapon
		player:setStorageValue(Storage.isTraining,0)
        end
    return true
end
```
