### ISSUE TITLE
Assassin Outfit Quest - Bug NPC Atrad

### ISSUE THREAD

**Issue by diegokrusz** [opentibiabr/otservbr-global-archived#529]
Hi!
Im testing all the outfit quests, and im having problems to talk with npc Atrad, the third npc of Assassin Outfit quest.When i try to talk, i get the error bellow:

![bug](https://user-images.githubusercontent.com/54739958/64275176-6231ac80-cf1b-11e9-8b10-8ba8dc958347.png)

**Comment by diegokrusz** [comment]
See the complete report bellow: 
- ¹Part outfit working perfectly. (Only bug is the name of a glass with beer or wine, which looks like (cup with unknow) .Outfit delivered normally
--²Part Addon 1: Working perfectly. The only problem is that the npc keyword is not blue, which makes it difficult for players to understand, who will try to say "blue piece of cloth" and will not work.

**Comment by newacc12** [comment]
This quest is also missing that you have to be invisible to go inside Erayo's hut.

Reference: https://tibia.fandom.com/wiki/Assassin_Outfits_Quest
