### ISSUE TITLE
[Quest] Panpipe

### ISSUE THREAD

**Issue by omarcopires** [opentibiabr/otservbr-global-archived#54]
A pedra oca (Hollow rock (Position: 32652, 32107, 7) deveria dar a key 4055 após dar use nela.

Baú de recompensa está vazio(Position: 32644, 32131, 8). Add as recompensas: Quest box containing a Bag with 1 Power Ring, Panpipes and 2 Small Amethysts

source:http://tibia.wikia.com/wiki/Panpipe_Quest

**Comment by dudantas** [comment]
Moving alls quests issues for one unique issue.

**Comment by dudantas** [comment]
Quest has been removed from the issue: #726
Fixed on the #1485
