### ISSUE TITLE
Stepin on item cause client to crash

### ISSUE THREAD

**Issue by lBaah** [opentibiabr/otservbr-global-archived#542]
**Describe the bug**
Stepin and stepout on certain item causes the both client 10 and 12 to crash
Known Item IDS:
35583
35582

**To Reproduce**
1. Stepin the itemid then stepout.

**Expected behavior**
Client should not crash

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10

**Comment by majestyotbr** [comment]
Fixed on https://github.com/opentibiabr/OTServBR-Global/commit/09c3c977f0108d8a18eb9d8f1a09e80e354a6aa8
