### ISSUE TITLE
Ghostsilver Latern fix

### ISSUE THREAD

**Issue by Fol2estz** [opentibiabr/otservbr-global-archived#547]
Ao clicar na spider web que está no mapa, você não ganha a Ghostsilver Lantern que é necessária para ter acesso a porta secreta da lady tenebris.

Id do item para ser adicionado em contents dentro da spiderweb - Item ID: 26402
Posição de onde está o objeto a ser corrigido - Position: 32825, 31664, 9

**Comment by Fol2estz** [comment]
@dudantas

**Comment by dudantas** [comment]
fixed here https://github.com/opentibiabr/OTServBR-Global/pull/525/commits/0e3b8037bed328b12d003842797beb432d5ccfac#diff-f6dedb225240d5a051dd0a8aabbeac6b

**Comment by dudantas** [comment]
But, thanks for the report.
Leave it open because I referenced it in pull request and when given merge will be closed automatically.
