### ISSUE TITLE
Some issues i found

### ISSUE THREAD

**Issue by ivansho92** [opentibiabr/otservbr-global-archived#548]
1. we have a problem wiht Backpacks, when is some heavy like 3k or more, we can drop inside of depot or can not move to both anohers backs cus is too heavy.

2. Problems with Jester OutfitQuest in somes NPC.

3. some new items like lanterns don't working with lite.

4. The Library Ticket don't work with fliying book, and already i put the action in mounts, actions but nothing happens.

5. Imbuiment system: mages just with the rod/wands can make Crititicals hits, can not produces only wiht spells, and the time always is wasting, if you not using the set, the time don't stop to wasting.

tfs 1.3

**Comment by newacc12** [comment]
@ivansho92 Thanks for reporting but please follow the template [here](https://github.com/opentibiabr/OTServBR-Global/issues/new?assignees=&labels=&template=bug_report.md&title=) to describe each one. It is very hard for developers to guess what they have to do to reproduce the bug.

**Comment by dudantas** [comment]
It's very disorganized and I don't understand almost anything ... Create issue for each problem and explains in detail how the bug works so we can analyze it.
