### ISSUE TITLE
Gold Converter

### ISSUE THREAD

**Issue by cellss** [opentibiabr/otservbr-global-archived#553]
O item gold converter existe com os IDs: 26378 e 29020 (se existirem outros n sei, creio q n)

No entanto na store o item que está para a venda é o com id: 29020 que não está configurado e apenas possui  a descrição correta do item, enquanto o de ID 26378 já estava com script feito em actions...

Então, para que ambos fiquem utilizáveis... 
em: /data/actions/actions.xml

Após:
`	<action itemid="26378" script="others/objects/goldConverter.lua"/>`
Adicionei:
`	<action itemid="29020" script="others/objects/goldConverter.lua"/>`

Agora ambos os items funcionam corretamente.

Só uma pequena correção, mas creio que toda ajuda é válida para o desenvolvimento do projeto...

**Comment by dudantas** [comment]
Na realidade o que ocorre é: um gold converter é o que você dá use with no item e no gold coin
O outro, você "Ativa o item" e ele converte automaticamente todos os items dentro da backpack. 
Logo, o correto é criar o script para o outro gold converter e adicionar os dois na store.
Por enquanto, acho que o problema é resolvido apenas trocando o id na store e criando um issue para o outro item que precisa de script.

**Comment by cellss** [comment]
Opa, na verdade também não, @dudantas... Esses dois aí são realmente apenas gold converter, o que diferencia e eu só percebi isso depois de ter aberto o Issue, é que um deles é aquele temporário que o player ganha no daily reward e que some com 7 dias caso não seja utilizado... O item ao qual vc se refere é o "magic gold converter", que encontrei em items.xml com os Ids:   32109 e 33299
...

**Comment by cellss** [comment]
Em items.xml existem 2 registros do item 29020, um deles diz que o item é temporário, eu apaguei esse registro e coloquei as informações no item 26378 que deverá ser configurado como temporário (Não sei fazer) mas vai ter que criar outro script pra ele...

Apaguei esse:
```
	<item id="29020" article="a" name="temporary gold converter">
		<attribute key="description" value="This item cannot be traded." />
		<attribute key="weight" value="300" />
		<attribute key="charges" value="100" />
		<attribute key="showcharges" value="1" />
	</item>
```
Deixei esse, é o que vende na Store:
```
	<item id="29020" article="a" name="gold converter">
		<attribute key="description" value="You bought this item in the Store or gained it as a daily reward. This item cannot be traded." />
		<attribute key="weight" value="300" />
		<attribute key="charges" value="500" />
		<attribute key="showcharges" value="1" />
```

e modifiquei o 26378 

de:
```
         <item id="26378" article="a" name="gold converter">
		<attribute key="weight" value="1800" />
		<attribute key="wrapableTo" value="26054" />
		<attribute key="charges" value="500" />
		<attribute key="showcharges" value="1" />
	</item>

```
Para: 
```
	<item id="26378" article="a" name="temporary gold converter">
		<attribute key="description" value="This item cannot be traded." />
		<attribute key="weight" value="300" />
		<attribute key="charges" value="100" />
		<attribute key="showcharges" value="1" />
	</item>
```

Creio que assim está como deve ser, os items magic gold converter também precisam dos scripts...

P.S> O item 29020 'gold converter' na Store custa 5 coins, deveria vim com 500 cargas, porem o que acontece é quem vem 5 items com 100 cargas cada...
