### ISSUE TITLE
Ingame buy house system

### ISSUE THREAD

**Issue by Davenorthern** [opentibiabr/otservbr-global-archived#556]
Hey!

Chances are once again, that I am a total moron. Have been searching data for talkactions regarding buying and selling houses ingame, but I cant find any. Is it implemented yet?

**Comment by Kojakzin** [comment]
U Just need create files in talkactions/scripts and talkactions.xml

**Comment by thatmichaelguy** [comment]
This function was removed in #435 along with other player talkactions that are not part of real tibia.
Personally I think we should keep some things that are used regularly, but I can also understand not wanting to maintain things that are not part of real tibia.

**Comment by Davenorthern** [comment]
Ahh I see. Yeah its a practical thing for a code-illiterat like myself. But No worries. Thanks alot for the answers. :)

**Comment by dudantas** [comment]
The buying / selling of houses can be done through the site (as it is globally) so we can remove the talkaction.
In the forums has all this content easily accessible, I believe it is not necessary to be in the repository.
Thanks for the discussion and any questions you can comment.
