### ISSUE TITLE
Bug When Equipe Festive Backpack and Relog

### ISSUE THREAD

**Issue by Kojakzin** [opentibiabr/otservbr-global-archived#558]
Hellow guys, Does anyone know how to fix this bug? It is present as much when on client 10 as on client 12. When you equip a Festive Backpack on the character and we relog it or when we put it inside someone else. She transforms into this statue (Item ID: 32767) that stays in the character and has no way to remove it except by Mysql. If anyone knows how to fix.
[Image:](https://i.imgur.com/Mwx4SOE.jpeg)
Thx

**Comment by majestyotbr** [comment]
Before create issue here, make sure you are reporting something on latest version of the server.

Make sure you are using the database of this repository: 
https://github.com/opentibiabr/OTServBR-Global/blob/develop/schema.sql

Tested on client 10 and client 12, bug unconfirmed.
