### ISSUE TITLE
[Quest] Power Bolts 

### ISSUE THREAD

**Issue by omarcopires** [opentibiabr/otservbr-global-archived#56]
Faltando o corpo de esqueleto na posição(Position: 32817, 32283, 8) contendo o restante da recompensa(02 handed sword, 06 throwing stars, talon).

Faltando pilhas de corpos de dead human, criaturas e animais no canto superior esquerdo.

source:http://tibia.wikia.com/wiki/Power_Bolts_Quest

**Comment by dudantas** [comment]
Moving alls quests issues for one unique issue.
