### ISSUE TITLE
Imposible to invoque with /i silvered trap

### ISSUE THREAD

**Issue by IvanMir014** [opentibiabr/otservbr-global-archived#561]
**Describe the bug**
The server starts to 100% cpu when I try to invoque silvered trap /i 24714.

**Comment by cellss** [comment]
What?

It's the wrong ID for this...

> You see a vial of liquid silver.
> It weighs 2.40 oz.
> It shimmers faintly, like the full moon.
> Item ID: 24714

/i silvered trap

> 00:23 You see a silvered trap.
> It looks like a common leghold trap, but the jags are coated in silver. The trap is closed and safe.
> Item ID: 24715

/i closed silvered trap

> 00:26 You see a closed silvered trap.
> It looks like a common leghold trap, but the jags are coated in silver. The trap is closed and safe.
> Item ID: 24730

There are no scripts for these items...


MIssing features issue...
