### ISSUE TITLE
Bug Backpack

### ISSUE THREAD

**Issue by ivansho92** [opentibiabr/otservbr-global-archived#562]
I found this problem, when you backpack is heavy, around 4k or more, u can't drop in the floor, can't put in your depot, can't put through another backpacks.

**Comment by dudantas** [comment]
Is one limitation on the source.

**Comment by ivansho92** [comment]
is possible fix this?

**Comment by dudantas** [comment]
> is possible fix this?

test this https://github.com/opentibiabr/OTServBR-Global/pull/565

**Comment by dudantas** [comment]
If not, test on player.cpp on line 5 swap: CONTAINER_WEIGHT = 100000
per CONTAINER_WEIGHT = 500000 (50k)
Be careful, because without this function or if you set it too high, you can use the WPE program to crash your source.
