### ISSUE TITLE
Bug Library ticket mount.

### ISSUE THREAD

**Issue by ivansho92** [opentibiabr/otservbr-global-archived#563]
The Library Ticket don't work with fliying book, and already i put the action in mounts, actions but nothing happens.

**Comment by Kojakzin** [comment]
man here is working perfectly this error does not proceed with what you are reporting check again if added in mounts.lua and actions.xml? It worked perfectly here. Not bugged

**Comment by newacc12** [comment]
That is the reason that we tell people to use the template to describe bugs which includes on how to simulate them.

**Comment by ivansho92** [comment]
already put the actions in Actions.xml but when you want use in the flying book, just say: you cannot use this object...
i test anothers like rhino stone, and the flies and they work!

**Comment by Kojakzin** [comment]
> already put the actions in Actions.xml but when you want use in the flying book, just say: you cannot use this object...
> i test anothers like rhino stone, and the flies and they work!

u put on mounts.lua? --'

**Comment by majestyotbr** [comment]
Use the issue template when you create issues here.
