### ISSUE TITLE
Looktype Feroxa

### ISSUE THREAD

**Issue by Kojakzin** [opentibiabr/otservbr-global-archived#566]
Hello, don't have looktype 731 to Feroxa boss? How can i add? thx

**Comment by Lycanzito** [comment]
Well.. The looktype 731 works fine. >.<

problably you need to fix something on talkactions :-)

put it like 
	if lookType >= 0 and lookType < 1256 

on the looktype.lua

**Comment by Kojakzin** [comment]
> Well.. The looktype 731 works fine. >.<
> 
> problably you need to fix something on talkactions :-)
> 
> put it like
> if lookType >= 0 and lookType < 1256
> 
> on the looktype.lua

Thanks <3 works fine!

**Comment by liontts** [comment]
This is not a bug or enhancement.
