### ISSUE TITLE
Monster Speed

### ISSUE THREAD

**Issue by Lycanzito** [opentibiabr/otservbr-global-archived#567]
Monsters still are slowly running on red health

monsters still are tooooo fast on chasing you

**Comment by Raphaellb** [comment]
I agree on the speed of the monsters. this was made fast from PR #304. monsters are too fast still. I found that by lowering the value below makes it better. 
src/monsters.cpp 
		mType->info.baseSpeed = pugi::cast<int32_t>(attr.value());
		mType->info.baseSpeed = pugi::cast<int32_t>(attr.value()) * **_2.55_**;
@gpedro

**Comment by lBaah** [comment]
Please be more specific in your issue. List which monsters are fast and which one are slow.

Also changing the monsters.cpp file might be a wrong thing to do if you dont check the speed="" tag on monstername.xml file.

**Comment by Lycanzito** [comment]
> I agree on the speed of the monsters. this was made fast from PR #304. monsters are too fast still. I found that by lowering the value below makes it better.
> src/monsters.cpp
> mType->info.baseSpeed = pugi::cast<int32_t>(attr.value());
> mType->info.baseSpeed = pugi::cast<int32_t>(attr.value()) * **_2.55_**;
> @gpedro

Thanks, looks fine now, the problem now is when the monster is running on red health, the monsters make some "steps" to walk

**Comment by dudantas** [comment]
@Lycanzito Solved. If you want to open another issue reporting the other issue, feel free, as this is resolved I will be closing.

**Comment by Alucard987** [comment]
superspeed monsters, why? :(

**Comment by majestyotbr** [comment]
This is a old issue, the monsters speed was fixed.
Download and use updated repository.

**Comment by dudantas** [comment]
> superspeed monsters, why? :(

You not using the actually source.

**Comment by Alucard987** [comment]
i'm using actual source and the monsters still faster in green and red health.

**Comment by dudantas** [comment]
> i'm using actual source and the monsters still faster in green and red health.

Source and datapack?

**Comment by Alucard987** [comment]
yes i download last night
