### ISSUE TITLE
Broken Docker compiling

### ISSUE THREAD

**Issue by biaggio12** [opentibiabr/otservbr-global-archived#573]
## CAUTION: OUR SERVER IS UPDATED DAILY. MAKE SURE YOU ARE REPORTING SOMETHING ON THE LATEST VERSION OF THE SERVER.

**Describe the bug**
Can't compile server with docker.

**To Reproduce**
1. Go to 'docker/all-in-one.' or whatever docker/server-only
2. Try to start script prepare-env.sh or 
3. See error
Don't have z:latest locally trying to pull, but there is none z repository at docker hub.

**Expected behavior**
Download container, and setup working server.

**Screenshots**
![image](https://user-images.githubusercontent.com/17850450/64735836-a60f4d80-d4e9-11e9-9828-c710a0fd0d69.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10
 - Docker Version: latest (installed 2 days ago 09.09.2019)
 - Latest files, cloned 09,09.2019

I think there is some steps missing in those shell scripts, or the repository "z" is not public. That's my guesses. Can't really do anything about it but try to make a new container with different setup, but what would be the point of that if it's already done. DRY my friends DRY

**Comment by Costallat** [comment]
Those scripts are for Linux environment, you can't run them on Windows

**Comment by biaggio12** [comment]
Actually what's the point of using docker then? I mean it's great that ot serv is sitting in a container not affecting your other stuff, but isn't it suppose to be crossplatform? Isn't this like one of concepts of using docker?

**Comment by Costallat** [comment]
Yep, but those scripts are not related to docker, they are related to help you starting/building a server using docker on a Linux environment, as I don't have a Windows machine and I don't have the knowledge of how to create those scripts on Windows so I kept that just for Linux, but if you open those files and know how run those commands on Windows, you will be able to build and run the server on Windows using docker.

**Comment by Costallat** [comment]
I know that I still need to write the tutorial and we need help to add support for more environments, but this is a V0.1 using Docker and I was able just to test it on Linux.

What you can try  is this for example:

Windows Prompt:
cd <otserver\docker\server-only>
docker build -f build-env\Dockerfile.build  -t otbuild .

Using the 'File Explorer'

Go to <otserver\docker\server-only>
Create directory  build-env\otserver\
Copy inside this directory:
cmake 
src/ 
CMakeLists.txt

Windows Prompt:
docker run  -v <C:\otserver-path\build\otserver\>:/tmp/otserver --rm otbuild

**Comment by Agomkay** [comment]
Excellent

**Comment by Costallat** [comment]
@biaggio12 Now you can use on windows, only the web content that you will have to download manually.

Thanks for your contribution
