### ISSUE TITLE
[Quest] Cults of Tibia

### ISSUE THREAD

**Issue by ivansho92** [opentibiabr/otservbr-global-archived#580]
i guees we don't have this script in this quest, The armored Voidborn never change at The Unarmored Voidborn, and the a containment crystal never summoner anothers creatures like voidshard, and the TP in the entrance, can't go inside another times cus always says: wait for 24 hours, but you can not go inside again is the same whit the TP in The Horned Fox

**Comment by dudantas** [comment]
Moving alls issues of the quests for one unique issue!
