### ISSUE TITLE
[Embuement] Capacity

### ISSUE THREAD

**Issue by Lycanzito** [opentibiabr/otservbr-global-archived#582]
![image](https://user-images.githubusercontent.com/52710697/64917114-196fc400-d763-11e9-9bed-ae28fe53b1aa.png)

Not giving the bonuses;

**Comment by IvanMir014** [comment]
Same bug will all updated.

**Comment by IgorCFG** [comment]
## PT-BR
Isso da pra ajustar até pelo lua no `OnEquip` dos itens, fazendo uma atualização do cap após verificar se o item tem o imbuement.

## EN-US
This can even be adjusted by the .lua file in the `OnEquip` of the item file, after verifing on the imbuements of item.

**Comment by oalbsilva** [comment]
@Lycanzito  can u test #1398 ?
