### ISSUE TITLE
Please Close this Issue, is everything ok!

### ISSUE THREAD

**Issue by Lycanzito** [opentibiabr/otservbr-global-archived#583]
![image](https://user-images.githubusercontent.com/52710697/64933711-c35f5700-d81c-11e9-8e5e-1e45dbcbbb64.png)

This bug only appears if you are trying to buy a exercise weapon, with a PLAYER.

with a ADM is working fine.

**Comment by cys9211** [comment]
https://imgur.com/a/tc0CywH
When you click on search, it falls into the category of others

**Comment by cellss** [comment]
It's possible to buy even when you don't have capacity...

exemple: If you buy 250x Sudden Death Runes and you have cap only for 50, 50 will come and you will pay for the 250x

**Comment by lBaah** [comment]
Please check if your server is up to date.

https://github.com/opentibiabr/OTServBR-Global/blob/develop/data/modules/scripts/gamestore/init.lua

**Comment by Lycanzito** [comment]
> Please check if your server is up to date.
> 
> https://github.com/opentibiabr/OTServBR-Global/blob/develop/data/modules/scripts/gamestore/init.lua

Yes, yes yes

now its fine. 

:-)
