### ISSUE TITLE
Debug

### ISSUE THREAD

**Issue by Lycanzito** [opentibiabr/otservbr-global-archived#584]
The client close when you click on the cyclopedia.

**Comment by majestyotbr** [comment]
Before create issue here, make sure you are reporting something on latest version of the server.

Tested on client 12, debug unconfirmed.

**Comment by Lycanzito** [comment]
> Before create issue here, make sure you are reporting something on latest version of the server.
> 
> Tested on client 12, debug unconfirmed.

You tested on the client 12 of the repository? If you did, something is wrong with me them kkkk

**Comment by majestyotbr** [comment]
Of course.
https://github.com/opentibiabr/tools

**Comment by gerotib** [comment]
Does your prey window crash client too? It happened before #528 , but crash can also occur while wrong prey states are set to a player. For example if you set 2 slots as active, and one as locked client crashes (also while opening cyclopedia). I think this should be separate issue, but I didnt test it good enough to report.

**Comment by Lycanzito** [comment]
> Of course.
> https://github.com/opentibiabr/tools

Actually, I have tested now and the same debug happens with the client of the repository

**Comment by majestyotbr** [comment]
I tested with updated database and it worked.

**Comment by cellss** [comment]
I tested this question and debugging happens on my char level 600, but on my char level 1 the encyclopedia is ok, I don't know when the problem comes up...

Using the latest project version

**Comment by Lycanzito** [comment]
> I tested this question and debugging happens on my char level 600, but on my char level 1 the encyclopedia is ok, I don't know when the problem comes up...
> 
> Using the latest project version

Well tried on lvl 8+ and the debugs happens xD  I dont think that level matters :o
but if u are saying that I trust on you.

**Comment by majestyotbr** [comment]
Do a test with updated database: 
https://github.com/opentibiabr/OTServBR-Global/blob/develop/schema.sql
After fix on prey, i tested the server and it works. I test the server everytime it is updated on repository.

**Comment by Lycanzito** [comment]
> Do a test with updated database:
> https://github.com/opentibiabr/OTServBR-Global/blob/develop/schema.sql
> After fix on prey, i tested the server and it works. I test the server everytime it is updated on repository.

Same debug.. '-' 
Any idea how to disable the cyclopedia?

**Comment by majestyotbr** [comment]
So, you are not using latest version of the server.
Apply the fix posted on #528, recompile and try again. Remember to use updated database too.
