### ISSUE TITLE
[Quest] Waterskin of Mead

### ISSUE THREAD

**Issue by omarcopires** [opentibiabr/otservbr-global-archived#59]
Adicionar a recompensa(a bag containing Berserk Potion, 82gp, Waterskin of Mead) no barril: 20:13 You see a barrel (Vol:25). Item ID: 1774 Position: 32214, 31060, 10

source:http://tibia.wikia.com/wiki/Waterskin_of_Mead_Quest

**Comment by dudantas** [comment]
Moving alls quests issues for one unique issue.
