### ISSUE TITLE
Cant look at items with imbuement slots

### ISSUE THREAD

**Issue by Davenorthern** [opentibiabr/otservbr-global-archived#607]
## CAUTION: OUR SERVER IS UPDATED DAILY. MAKE SURE YOU ARE REPORTING SOMETHING ON THE LATEST VERSION OF THE SERVER.
-Downloaded latest version today.

Items with imbuement slots cant be looked at. Error codes showing up. 

**Screenshots**
If applicable, add screenshots to help
![Screenshot (5)](https://user-images.githubusercontent.com/52839094/65504199-c4505280-dec6-11e9-8be0-3d028a718faa.png)

**Desktop (please complete the following information):**
Windows 10, client 10

**Additional context**

**Comment by majestyotbr** [comment]
Repeated, #368
