### ISSUE TITLE
Gaz'haragoth misspelled in raid, cant create monster.

### ISSUE THREAD

**Issue by Davenorthern** [opentibiabr/otservbr-global-archived#608]
Space between Gaz and ' in gazharagoth.xml

![Screenshot (6)](https://user-images.githubusercontent.com/52839094/65504531-7f78eb80-dec7-11e9-8ae6-990de0048ca8.png)

**Comment by cellss** [comment]
Thanks!

**Comment by majestyotbr** [comment]
Fixed on #609. Thanks for the report.
