### ISSUE TITLE
Adicionar escada

### ISSUE THREAD

**Issue by Lycanzito** [opentibiabr/otservbr-global-archived#610]
Add this attritube key on this item: items.xml

		<item id="18234" name="stairs">
		<attribute key="floorchange" value="north" />
	</item>

**Comment by liontts** [comment]
Is that really serious? How difficult is it to send a pullrequest with this fix?

**Comment by oualid6496** [comment]
Look at his profile he never commited anything so he probably doesn't know how to. Maybe explain it to him instead of giving such a response :)
