### ISSUE TITLE
Unable to sell tibia coins

### ISSUE THREAD

**Issue by liontts** [opentibiabr/otservbr-global-archived#614]
Expected Behavior: Tibia coins work like premium days and should be allocated to the account, not the characters.
* The sale must be made in the market automatically.
* Tibia coins are not physical items, the player has no direct contact with the item as above (works as premium days).

**Comment by dudantas** [comment]
What? Specify better. How to reproduce the problem.

**Comment by dudantas** [comment]
The bug was not described, so I will close.
