### ISSUE TITLE
Imbuement vampirism 

### ISSUE THREAD

**Issue by yatozin** [opentibiabr/otservbr-global-archived#616]
**Describe the bug**
Only leeches life from 1 monster in aoe situation tested on ek with exori and took same life with 1 as with 5 monsters.

**Expected behavior**
% of total damage life leeched

**Comment by FakeShinoda** [comment]
Leech imbuement are working in the same way of global tibia.
Exemple: 

**210** = Damage given on each monsters
**8** = Amount of monsters
**50%** = Percent that should heal

So... 210*8/8-50% = 105 healed points

It's not a bug..
