### ISSUE TITLE
[Quest] Rest in Hallowed Ground 

### ISSUE THREAD

**Issue by omarcopires** [opentibiabr/otservbr-global-archived#62]
Não é possível usar a vial of holy water nas tumbas, tornando a quest incompleta.

source:http://tibia.wikia.com/wiki/Rest_in_Hallowed_Ground_Quest

**Comment by dudantas** [comment]
Need the script for the tombs
AID from 4210 to 4224

pos: 33218, 31669, 7
33202, 31685, 8

**Comment by dudantas** [comment]
Moving alls quests issues for one unique issue.
