### ISSUE TITLE
Nothing re spawns

### ISSUE THREAD

**Issue by yatozin** [opentibiabr/otservbr-global-archived#622]
## CAUTION: OUR SERVER IS UPDATED DAILY. MAKE SURE YOU ARE REPORTING SOMETHING ON THE LATEST VERSION OF THE SERVER.

**Describe the bug**
monsters never respawn

**To Reproduce**
kill monsters and watch blue respawn portals stack up

**Expected behavior**
monster respawn

**Screenshots**
![never ever spawn](https://user-images.githubusercontent.com/55179288/65815319-1b955080-e242-11e9-919d-d1edac125164.PNG)

**Comment by Costallat** [comment]
It was my fault, I am looking that, if you need a fast fix you can revert my commit on your local git, sorry for that!

**Comment by Marvok95** [comment]
already managed to fix the bug respawn just need to know how I send the fix

**Comment by majestyotbr** [comment]
Fixed on #625
