### ISSUE TITLE
Tibia client 12 Battle window

### ISSUE THREAD

**Issue by Raphaellb** [opentibiabr/otservbr-global-archived#623]
Using the Latest build of this project, I am unable to use any of the battle window features such as hiding npc, monsters or other players. there is no option available.

**Comment by majestyotbr** [comment]
Fixed on https://github.com/opentibiabr/tools

Thanks for the report.

**Comment by gerotib** [comment]
This also fixed wrong icons in status bar window. There wasnt issue about this but just saying :)

**Comment by Raphaellb** [comment]
this is fixed, thank you.
