### ISSUE TITLE
GlobalEvent Interface bug?

### ISSUE THREAD

**Issue by yatozin** [opentibiabr/otservbr-global-archived#626]
## CAUTION: OUR SERVER IS UPDATED DAILY. MAKE SURE YOU ARE REPORTING SOMETHING ON THE LATEST VERSION OF THE SERVER.

**Describe the bug**
this starts spamming in console randomly sometimes when a player dies.
it makes so every player on server can no longer equip a backpack, dont know of any other effects it causes, sometimes crash the server.

Lua Script Error: [GlobalEvent Interface]
(Unknown scriptfile)
attempt to call a nil value
stack traceback:
        [C]: at 0x7ff7edb04c30

**To Reproduce**
its hard to reproduce the problem it happens randomly i have noticed it happening sometimes when a character dies.

**Comment by Costallat** [comment]
If you discover more information about this let me know, I tried to reproduce here, but without success.

Tks

**Comment by dudantas** [comment]
Well, as it was the only person who reported the problem, I will close. If you have any way to reproduce this bug, please comment that we will reopen.
Remember that you may be using something custom that is causing this, outdated database or datapack. Try to download the entire repository from scratch and install everything current and see if you get the same problem.

**Comment by Raphaellb** [comment]
I think I just found a way to reproduce this bug. for some reason when I have a bunch of BPs inside my main BP with a high amount of weight in. if I remove that backpack, I get this error along with a message that I cant dress the BP in the backpack slot when I try to put any BP in my slot, even if its an empty BP. 

Lua Script Error: [GlobalEvent Interface]
(Unknown scriptfile)
attempt to call a nil value
stack traceback:
        [C]: in ?

**Comment by Raphaellb** [comment]
also only way to bypass this is to restart the server. then I can dress my BPs again.

**Comment by Raphaellb** [comment]
@dudantas

**Comment by maper1** [comment]
10 min after turning on the server I already have this error  https://prnt.sc/qjhmew  i need help please

**Comment by kadeshop** [comment]
Have same problem, someone can help ? with tfs 1.3 globalevents c: at 0x013f5ca850

**Comment by majestyotbr** [comment]
Probably you are not using only our datapack. You can't just replace things between tfs 1.3 and our datapack without knowing what you are doing.
