### ISSUE TITLE
Bank bug

### ISSUE THREAD

**Issue by yatozin** [opentibiabr/otservbr-global-archived#627]
## CAUTION: OUR SERVER IS UPDATED DAILY. MAKE SURE YOU ARE REPORTING SOMETHING ON THE LATEST VERSION OF THE SERVER.

**Describe the bug**
When you deposit money into bank it disappears.

**To Reproduce**
deposit gold at bank

**Screenshots**
![bank is stealing money](https://user-images.githubusercontent.com/55179288/65829903-ca02c980-e306-11e9-948f-237f4b728586.PNG)

**Comment by gerotib** [comment]
I can confirm, also tested on build from like a week ago(dont know exactly after what commit), and it worked fine then.

**Comment by Costallat** [comment]
The problem is that it is not getting the correct balance, so it is not calculating the correct value, but if you withdraw everything and deposit it again it will work.

**Comment by Costallat** [comment]
Please test #631 to see if it is working now!

Tks

**Comment by yatozin** [comment]
> Please test #631 to see if it is working now!
> 
> Tks

ye tested bank and its working

**Comment by Costallat** [comment]
Tks

**Comment by majestyotbr** [comment]
Fixed on #631
