### ISSUE TITLE
The White Raven Monastery Quest

### ISSUE THREAD

**Issue by omarcopires** [opentibiabr/otservbr-global-archived#63]
NPC Costello script parece ok, não podemos prosseguir com a quest após usar as palavras corretas(Hi - Fugio).

source:http://tibia.wikia.com/wiki/The_White_Raven_Monastery_Quest

**Comment by dudantas** [comment]
Need to do a little quest to talk to npc, it's in the script, but it's a good idea to test the quest to be able to close the issue.

**Comment by dudantas** [comment]
It's not a bug, is needded the quest: 

> if player:getStorageValue(Storage.QuestChests.FamilyBrooch) == 1 then 

Family Brooch to initiate the quest.

Closing and thanks
