### ISSUE TITLE
Ferumbras ascension quest areas. Map and scripts missing. 

### ISSUE THREAD

**Issue by Davenorthern** [opentibiabr/otservbr-global-archived#632]
Ferumbras ascension areas missing. Map and scripts. 

I have only checked the south path in the hell hub though. 

![Screenshot (10)](https://user-images.githubusercontent.com/52839094/65986759-d0b74b00-e484-11e9-98da-08cbc685250b.png)

**Comment by FakeShinoda** [comment]
![lion](https://user-images.githubusercontent.com/23365432/65997809-73190380-e470-11e9-8cfe-940260fe3166.png)
Please, can you show me what are missing?

**Comment by Davenorthern** [comment]
I Will check it out further and get back to you 😃

**Comment by Davenorthern** [comment]
Starting from the top. Baby not letting me do it all at once :( Sorry for the trouble. Hope it is some help at least, you guys are doing such an awesome job. 

**Plagirath seal**: lever that should teleport you to the Lord of the Lice does not respond. 
It should teleport you to the mini boss, in order to reach the next area. 
![Screenshot (12)](https://user-images.githubusercontent.com/52839094/66041040-276e6480-e519-11e9-860c-8bfb75f62fb0.png)

**Zamulosh lever**: The lever to the boss room is not responding. 
![Screenshot (14)](https://user-images.githubusercontent.com/52839094/66051558-60b1cf00-e52f-11e9-8e85-aef1e897cf8e.png)

**Comment by miezaF** [comment]
Did you completed the mission on each part, or just tried to get to the boss?

**Comment by Davenorthern** [comment]
I'm completing the missions first. They seem to work as they should up until the levers. Plagirath has no missions save for defeating the mini boss Lord of the Lice, which is accessed through the lever on the screenshot. 

First I thought its because theres not enough players, but these bosses are supposed to work with 1-5 players so must be something else.

**Comment by miezaF** [comment]
Can I ask you to check the actionId on lever, and on actions.xml?
Probably it's different.

**Comment by Davenorthern** [comment]
oooh this is an opportunity for me to learn something. I'm sorry, I am dreadfully undereducated in stuff like this. How do I check the actionId on the lever?

**Comment by miezaF** [comment]
Go there with gamemaster, and look the level. It should appear like Item ID: 29068, Action ID: 61043
Position: 32372, 32231, 7 (Just example)
Or click on properties on map editor on level.
Then you go to data/actions/actions.xml and check the script, if it has "actionId" equals the lever, it should work. If doesnt, you found your bug. * ta-da *

**Comment by Davenorthern** [comment]
:) Awesome, thanks alot for the guidance and the patience. Will update when I checked.

**Comment by miezaF** [comment]
No problem. I just checked this a time ago, and replace actionIds on levers (on local project). So it should probably work.

**Comment by Davenorthern** [comment]
Alright, tried but might not be correctly done. The IDs didnt match as you said, so I did like this but still doesnt work. Open season on noobs havent started yet I hope. :) 

![Screenshot (17)](https://user-images.githubusercontent.com/52839094/66068890-b47fe080-e54e-11e9-865a-d52061e8f54a.png)

**Comment by oualid6496** [comment]
hmm when I tested it (maybe a month ago) everything was working fine except for the seal with the lava and levers. I'll double-check your problem later today but I'm pretty sure nobody has touched it since then

**Comment by Davenorthern** [comment]
Wierd, appreciate it. It would be interesting to know what I am doing wrong. Thanks!

Den 3 okt. 2019 1:52 em skrev Oualid6496 <notifications@github.com>:

hmm when I tested it (maybe a month ago) everything was working fine except for the seal with the lava and levers. I'll double-check your problem later today but I'm pretty sure nobody has touched it since then

**Comment by lBaah** [comment]
I've noticed you have an outdated version.
Check action.xml here: https://github.com/opentibiabr/OTServBR-Global/blob/develop/data/actions/actions.xml#L220

Please download all the files again at https://github.com/opentibiabr/OTServBR-Global/archive/develop.zip

If you've downloaded this from another place different than this repository there might be errors that was already been fixed.
There are some people sending bugged versions on purpose just to sell the fixes we do for free.

**Comment by Davenorthern** [comment]
Really??  No I always update from this repository, last update two days ago. I'll do it now!

**Comment by Davenorthern** [comment]
Same numbers in the updated version. BUT. Your first fix did it. Replaced uniqueid to actionid. And matched the Action ID on the lever with the one in actions.xml
Safe to say the other levers will work with the same fix. 
You guys are tibia legends. 
![Screenshot (18)](https://user-images.githubusercontent.com/52839094/66184007-01f96c00-e67b-11e9-8eaf-51f344521a44.png)

**Comment by lBaah** [comment]
@MajestyOTBR close
