### ISSUE TITLE
Magic Wall/ Wild Growth Duration

### ISSUE THREAD

**Issue by Lycanzito** [opentibiabr/otservbr-global-archived#635]
These runes should have a Random duration

Magic wall should be : between 16 ~ 20 seconds.

wg should be : between 38~ 45 seconds.

**Comment by lBaah** [comment]
I've looked into wikies and haven't found anything related to magic walls having random timers.
Where did you get that info?

**Comment by Lycanzito** [comment]
> I've looked into wikies and haven't found anything related to magic walls having random timers.
> Where did you get that info?

just throw a mw/wg xD
they made it random years ago

**Comment by oualid6496** [comment]
Ye im pretty sure he's right haven't played rl for a while but I believe they made such an update a while ago

**Comment by enzerah** [comment]
and if you look at the mw you can see who threw it.

**Comment by Lycanzito** [comment]
> and if you look at the mw you can see who threw it.

nope, is impossible to see who threw it only looking at the mw.

problably on open pvp, not on Retro pvp. 
and it this server is a retro server, since there is no ghosting/expert pvp
someone say something if I'm wrong xD

**Comment by lBaah** [comment]
I've tested on global and they have random timers. Moreover, you can't see who threw the field.

**Comment by enzerah** [comment]
Yes guys, its impossible to see, my mistake! sorry =D

**Comment by Lycanzito** [comment]
This thread can be closed, ive send the fix to @LucasCPrazeres , he will "upload" soon has possible.

<3

**Comment by enzerah** [comment]
> This thread can be closed, ive send the fix to @LucasCPrazeres , he will "upload" soon has possible.
> 
> <3

you can close it since you are op

**Comment by dudantas** [comment]
Is it solved?

**Comment by dudantas** [comment]
@Lycanzito pode enviar o script aqui ?
