### ISSUE TITLE
House Tapestry/carpets + ALSO ITENS getting vanish

### ISSUE THREAD

**Issue by Lycanzito** [opentibiabr/otservbr-global-archived#637]
When you change something in map (RME), the tapestry/carpets inside a house, get "removed" from the server.

these itens doenst going to the inbox.

**Comment by Lycanzito** [comment]
It seens that all "normal itens" like... everything is getting vanish inside the house, only the "store stuff " is still "alive"

before:
![image](https://user-images.githubusercontent.com/52710697/66713272-f135ae00-ed7e-11e9-91d7-4de26f8ede0d.png)

after:
![image](https://user-images.githubusercontent.com/52710697/66713280-01e62400-ed7f-11e9-97ff-bff31f58a8fc.png)

**Comment by rafaelmmendes** [comment]
That isn't the case on my fork but I'll test some more

**Comment by Lycanzito** [comment]
> That isn't the case on my fork but I'll test some more

You need to "change" the map, /close/open the server

**Comment by rafaelmmendes** [comment]
Yea, I tested it and it is quite the contrary on my case... some store items - like a few carpets and imbuing shrines - are indeed vanishing after server shutdown, but not "normal" items... at least on my server

Ps: sorry for the delayed response

**Comment by Lycanzito** [comment]
> Yea, I tested it and it is quite the contrary on my case... some store items - like a few carpets and imbuing shrines - are indeed vanishing after server shutdown, but not "normal" items... at least on my server
> 
> Ps: sorry for the delayed response

No problem..

Lets see if someoneelse is having the same problem...

**Comment by FakeShinoda** [comment]
![NOT](https://user-images.githubusercontent.com/23365432/66947103-a76ff080-f028-11e9-83de-1890f769ebb3.png)

It's not a OTServBR-Global bug.
Thanks.

**Comment by Lycanzito** [comment]
> ![NOT](https://user-images.githubusercontent.com/23365432/66947103-a76ff080-f028-11e9-83de-1890f769ebb3.png)
> 
> It's not a OTServBR-Global bug.
> Thanks.

Im not sure what should you do to make it vanish, I though that it happened when you change the map, well.. just let the itens inside the house, when they vanish, reopen the thread, thanks <3
