### ISSUE TITLE
[Imbuement] Combat should decay only while in fight

### ISSUE THREAD

**Issue by gerotib** [opentibiabr/otservbr-global-archived#638]
According to tibia wiki:

> Whether an imbuement is in use or not depends on the type of imbuement, in particular:
> 
> Non-combat imbuements, such as speed- or capacity-boosting imbuements, are in use while the item is equipped.
> Combat imbuements are active while the item is equipped and the player is in combat.
> In combat means that the wielder has been in combat. Note that the absence of the Logout Block does not indicate out-of-combat, because being in a Protection Zone merely hides the Logout Block.

So it should probably start decaying while player get `CONDITION_INFIGHT` and stop when he lose it.

Currently no matter what imbuement, it decays all the time while equipped. I dont know exactly which ones are considered as those "combat" imbuements, but I can ask/check it if needed.

**Comment by rafaelmmendes** [comment]
Confirmed

**Comment by gerotib** [comment]
I found how to change it for every imbuement:
[this line](https://github.com/opentibiabr/OTServBR-Global/blob/develop/src/game.cpp#L4907) change to:
```
			if (player->hasCondition(CONDITION_INFIGHT)) {
				duration -= decreaseTime;
			}
```
but I dont really know how to except this for speed and cap imbues. Maybe some id check from imbuements.xml `<category id="10" name="Increase Speed" />`, but dont know how to get this in cpp.

**Comment by gerotib** [comment]
Copy of my comment from other issue:

I found how to change it for every imbuement:
[this line](https://github.com/opentibiabr/OTServBR-Global/blob/develop/src/game.cpp#L4907) change to:
```
			if (player->hasCondition(CONDITION_INFIGHT)) {
				duration -= decreaseTime;
			}
```
but I dont really know how to except this for speed and cap imbues. Maybe some id check from imbuements.xml `<category id="10" name="Increase Speed" />`, but dont know how to get this in cpp.

**Comment by Lycanzito** [comment]
> Copy of my comment from other issue:
> 
> I found how to change it for every imbuement:
> [this line](https://github.com/opentibiabr/OTServBR-Global/blob/develop/src/game.cpp#L4907) change to:
> 
> ```
> 			if (player->hasCondition(CONDITION_INFIGHT)) {
> 				duration -= decreaseTime;
> 			}
> ```
> 
> but I dont really know how to except this for speed and cap imbues. Maybe some id check from imbuements.xml `<category id="10" name="Increase Speed" />`, but dont know how to get this in cpp.

Actually, both shoulnd be "add" to this duration timer, they should decrease their time, since they are equipped. =)

**Comment by vankk** [comment]
Above [this line](https://github.com/opentibiabr/OTServBR-Global/blob/develop/src/game.cpp#L4882) add 
```cpp
Player* player = item->getParent()->getCreature()->getPlayer();
if (!player->hasCondition(CONDITION_INFIGHT)) {
	it++;
	continue;
}
```
Also remove [this line](https://github.com/opentibiabr/OTServBR-Global/blob/develop/src/game.cpp#L4893).

**Comment by majestyotbr** [comment]
https://github.com/opentibiabr/otservbr-global/commit/0be4d52af2ccdf67d61fe4298da3df1e4c2a1303#diff-18513665750ef5adf42b5ec29e14162e
