### ISSUE TITLE
Hidden Threats Quest

### ISSUE THREAD

**Issue by omarcopires** [opentibiabr/otservbr-global-archived#64]
Faltando o novo caminho nessa posição (Position: 33056, 32012, 11) que leva até o teleport. Não é possível encontrar Corym Ratter ou Corym Servant

source:http://tibia.wikia.com/wiki/Hidden_Threats_Quest

**Comment by dudantas** [comment]
is all ok

![image](https://user-images.githubusercontent.com/8551443/58753043-42f43080-848f-11e9-8def-ed6dae862578.png)
