### ISSUE TITLE
client 12 creature if dead

### ISSUE THREAD

**Issue by DamianDEB** [opentibiabr/otservbr-global-archived#640]
hello somebody can navigate me where i can find solutions of this
if you kill creature you can move corpse instantly and if you want open corpse must 
press ctrl+"open in new window" you can open normal  corpse by right click if you move on other sqm

**Comment by enzerah** [comment]
are you doing it with a god char or a normal one ?

**Comment by cys9211** [comment]
I have the same problem

**Comment by DamianDEB** [comment]
normal character created* on website

**Comment by gerotib** [comment]
This may be cause there is no auto looting implemented. So if your "looting" in control options is set to "right" (mouse button), it wont open corpse. You can change it to "SHIFT+right" so you can open corpse immidiately with right mouse button. 
You can move every corpse instantly or just certain ones? This may be problem just with wrong creature corpse id.

**Comment by DamianDEB** [comment]
i kill 5 difference creature problem on cyclops  
dragon etc work normal  about open corpse maybe you right 

Thanks for all Guys
