### ISSUE TITLE
CONDITION PARAM 

### ISSUE THREAD

**Issue by Underewarr** [opentibiabr/otservbr-global-archived#643]
CONDITION PARAM FOR MAGIC LEVEL CANT BE USED WITH ALL ANOTHER PARAM LIKE.

   conditionFood:setParameter(CONDITION_PARAM_SKILL_CLUB, 30)
	conditionFood:setParameter(CONDITION_PARAM_SKILL_SWORD, 30)
	conditionFood:setParameter(CONDITION_PARAM_SKILL_AXE, 30)
	conditionFood:setParameter(CONDITION_PARAM_SKILL_DISTANCE, 30)
	conditionFood:setParameter(CONDITION_PARAM_SKILL_SHIELD, 30)

IF YOU PUT MAIG LEVEL THERE DONT WORK.
MasterMindPotion DONT GIVE MAGIC LEVEL Only Reduce SHIELD.
ty.

**Comment by dudantas** [comment]
Explain further and how to reproduce the error. Explain further and how to reproduce the error. And please do not use upper case.

**Comment by Underewarr** [comment]
Try to use a mastermind potion, on this potion you put all skills fish shield dist... etc
and the result is Magic level not are added, like i say all skills works, but magic level dont
