### ISSUE TITLE
Problemas que encontrei até o momento.

### ISSUE THREAD

**Issue by d0gw4r** [opentibiabr/otservbr-global-archived#644]
- [x] 1 - Ao comprar qualquer Cask na Store, o jogador recebe uma sacola vazia;

![image](https://user-images.githubusercontent.com/51352360/66624207-8bea8d00-ebc5-11e9-9baf-6e5fe1a366fc.png)

- [x] 2 - Ao usar uma stack de 100 Empty Potion Flasks, tanto as Casks como as Kegs retornam 1 flask cheio e os 99 restantes desaparecem da mochila;

![2 1](https://user-images.githubusercontent.com/51352360/66624158-59409480-ebc5-11e9-84fb-dba098c592e9.png) ![2 2](https://user-images.githubusercontent.com/51352360/66624159-59409480-ebc5-11e9-9cab-c6ccc501b4bc.png)

- [x] 3 - A porta para o mini boss **Grand Commander Soeren**, onde a mesma não se abre para poder enfrentá-lo (dentro ou fora);

![3](https://user-images.githubusercontent.com/51352360/66624282-e7b51600-ebc5-11e9-9d2d-9d93dbab850a.png)

- [x] 4 - Ao usar o imbuiment shrine, o client 12 crasha ao clicar no menu para escolher os tipos de bônus disponívels (mana leech, life leech, etc...). O mesmo ocorre ao clicar no botão "Most Popular First", na janela da store.

![4](https://user-images.githubusercontent.com/51352360/66624276-e257cb80-ebc5-11e9-8bfd-6f76893bc170.png)

**Comment by enzerah** [comment]
Couldn't reproduce the 4th, but 1, 2 and 3 confirmed.

also, this spot at edron entrance is bugged :

![image](https://user-images.githubusercontent.com/6455295/66673039-1ff43d00-ec36-11e9-93ba-81f66816d33e.png)
14:49 Your current position is: 33199, 31765, 2.

Also, I don't think this portal is teleporting to the right pos
![image](https://user-images.githubusercontent.com/6455295/66674957-ad399080-ec3a-11e9-9a9c-ac84205a1790.png)

**Comment by d0gw4r** [comment]
Acabei de perceber que o Client 12 também está dando crash ao tentar selecionar o **graphics engine**.

**Comment by lBaah** [comment]
@d0gw4r você está usando o client 12 do tools? https://github.com/opentibiabr/tools

**Comment by d0gw4r** [comment]
Estou sim.

**Comment by enzerah** [comment]
Não consegui reproduzir o erro, aqui consigo trocar as engines gráficas corretamente.

**Comment by d0gw4r** [comment]
Quando eu havia recém compilado o client, eu também consegui, agora não sei porque cargas d'água fica crashando.

**Comment by enzerah** [comment]
Espere, que client voce compilou? Client 12 não há necessidade de ser compilado!

**Comment by lBaah** [comment]
Também consigo alterar os gráficos @EnzzoCaaue .

@d0gw4r, preciso que vocẽ faça um teste.
Antes de tudo, verifique se o arquivo que você tem é o mesmo que esse: 
https://github.com/opentibiabr/OTServBR-Global/blob/develop/data/actions/scripts/others/variables/caskKegs.lua

Talvez isso resolva:
Abaixo de: 
https://github.com/opentibiabr/OTServBR-Global/blob/develop/data/actions/scripts/others/variables/caskKegs.lua#L36
Adicione:
`flaskCount = item:getCount()`

Substitua:
https://github.com/opentibiabr/OTServBR-Global/blob/develop/data/actions/scripts/others/variables/caskKegs.lua#L39
Por:
`item:remove(flaskCount)`
`player:addItem(targetId.transform, flaskCount)`

Não garanto que está certo porque não posso testar agora.

Sobre a porta: preciso do ID do item da porta fechada e aberta, tanto na vertical quanto na horizontal.

**Comment by enzerah** [comment]
@lBaah nao consegui achar os ids da porta aberta, apenas fechada: 12692 e 12701

**Comment by d0gw4r** [comment]
> Espere, que client voce compilou? Client 12 não há necessidade de ser compilado!

Acho que confundi a palavra apenas, desculpe!

Eu baixei o client 12 do repositório do opentibiabr/tools, baixei o programa que edita o executável e fiz tudo como manda, logo normal no servidor, mas ele crasha em algumas situações como essa agora.

**Comment by enzerah** [comment]
nao é nescessario editar o client, apenas abra o client 127.0.0.1_client que esta dentro da pasta bin

**Comment by d0gw4r** [comment]
> nao é nescessario editar o client, apenas abra o client 127.0.0.1_client que esta dentro da pasta bin

Mas meu servidor não é hospedado no meu computador, então preciso de um client com ip do meu servidor e para que eu e outras pessoas possam entrar também.

**Comment by d0gw4r** [comment]
Outra coisa que lembrei aqui agora. O comando !cast não está funcionando.
Quando executo a ação, é me mostrado isso no terminal do servidor:

`Lua Script Error: [TalkAction Interface]
data/talkactions/scripts/start_cast.lua:onSay
data/talkactions/scripts/start_cast.lua:6: attempt to call method 'startLiveCast' (a nil value)
stack traceback:
        [C]: in function 'startLiveCast'
        data/talkactions/scripts/start_cast.lua:6: in function <data/talkactions/scripts/start_cast.lua:1>`

**Comment by d0gw4r** [comment]
> Também consigo alterar os gráficos @EnzzoCaaue .
> 
> @d0gw4r, preciso que vocẽ faça um teste.
> Antes de tudo, verifique se o arquivo que você tem é o mesmo que esse:
> https://github.com/opentibiabr/OTServBR-Global/blob/develop/data/actions/scripts/others/variables/caskKegs.lua
> 
> Talvez isso resolva:
> Abaixo de:
> https://github.com/opentibiabr/OTServBR-Global/blob/develop/data/actions/scripts/others/variables/caskKegs.lua#L36
> Adicione:
> `flaskCount = item:getCount()`
> 
> Substitua:
> https://github.com/opentibiabr/OTServBR-Global/blob/develop/data/actions/scripts/others/variables/caskKegs.lua#L39
> Por:
> `item:remove(flaskCount)`
> `player:addItem(targetId.transform, flaskCount)`
> 
> Não garanto que está certo porque não posso testar agora.
> 
> Sobre a porta: preciso do ID do item da porta fechada e aberta, tanto na vertical quanto na horizontal.

O script de Cask e Kegs funcionou, após a adição das linhas sugeridas apenas tive que revisar os caminhos dos scripts, em actions.xml.

**Comment by lBaah** [comment]
@d0gw4r o sistema de cast foi removido do server.
Todos sistemas custom foram removidos, inclusive:
-change gold
-auto loot
-talkactions de bless, house, etc

O objetivo é deixar absolutamente como o global.

**Comment by d0gw4r** [comment]
A sim, sem problemas, é que eu achava que um sistema parecido também tinha no global.

**Comment by d0gw4r** [comment]
Só passando pra atualizar aqui, re-editei o client 12 e não está mais dando crash na seleção de **graphics engine** e **imbuements**.

**Comment by d0gw4r** [comment]
Ao comprar itens na store (ex: potions), em que a quantidade exceda o limite de cap do personagem, é cobrado o valor integral do produto, porém a quantia é somente enviada até o limite de cap suportado, ignorando o mesmo.

**Ex:**
Comprei um pack de 300 potions, eu só consigo carregar 256, então é me dado 200 e os outros 100 somem.

Esperava-se que a compra fosse impedida e que surgisse um aviso da faltada de cap do jogador.

**Comment by dudantas** [comment]
@d0gw4r no global é utilizado twitch tv, programas para fazer stream, o cast system era cheio de bug e deixava várias brechas no servidor, então achamos melhor por bem tirar ele.

**Comment by marcosogsantos** [comment]
> Ao comprar itens na store (ex: potions), em que a quantidade exceda o limite de cap do personagem, é cobrado o valor integral do produto, porém a quantia é somente enviada até o limite de cap suportado, ignorando o mesmo.
> 
> **Ex:**
> Comprei um pack de 300 potions, eu só consigo carregar 256, então é me dado 200 e os outros 100 somem.

> Esperava-se que a compra fosse impedida e que surgisse um aviso da faltada de cap do jogador.

[Fixed](https://github.com/opentibiabr/OTServBR-Global/pull/768/commits/d971abace45ac700a607e5f0e42a5176f87489e4)

**Comment by dudantas** [comment]
@d0gw4r ainda tá por aí ? preciso de umas informações.

**Comment by majestyotbr** [comment]
1 - Corrigido, ok.
2 - Corrigido, ok.
3 - Corrigido, ok.
4 - Inválido.
