### ISSUE TITLE
new items

### ISSUE THREAD

**Issue by yatozin** [opentibiabr/otservbr-global-archived#655]
[Warning - MoveEvents::addEvent] Duplicate move event found: 34067
[Warning - MoveEvents::addEvent] Duplicate move event found: 34982
[Warning - MoveEvents::addEvent] Duplicate move event found: 34982
[Warning - MoveEvents::addEvent] Duplicate move event found: 34066
[Warning - MoveEvents::addEvent] Duplicate move event found: 34980
[Warning - MoveEvents::addEvent] Duplicate move event found: 34980
[Warning - MoveEvents::addEvent] Duplicate move event found: 34981
[Warning - MoveEvents::addEvent] Duplicate move event found: 34067
[Warning - MoveEvents::addEvent] Duplicate move event found: 34982
[Warning - MoveEvents::addEvent] Duplicate move event found: 34982
[Warning - MoveEvents::addEvent] Duplicate move event found: 34066
[Warning - MoveEvents::addEvent] Duplicate move event found: 34980
[Warning - MoveEvents::addEvent] Duplicate move event found: 34980
[Warning - MoveEvents::addEvent] Duplicate move event found: 34981

**Comment by d0gw4r** [comment]
Open your movements.xml and check if there's not any duplicated ids.
