### ISSUE TITLE
Item charges not working.

### ISSUE THREAD

**Issue by yatozin** [opentibiabr/otservbr-global-archived#658]
You see a prismatic necklace (protection physical +10%, energy +15%) that has 1 charge left.
It can only be wielded properly by players of level 150 or higher.
It weighs 6.50 oz.
Item ID: 18407

`<item id="18407" article="a" name="prismatic necklace">
        <attribute key="weight" value="650" />
        <attribute key="slotType" value="necklace" />
        <attribute key="charges" value="750" />
        <attribute key="showcharges" value="1" />
        <attribute key="absorbPercentPhysical" value="10" />
        <attribute key="absorbPercentEnergy" value="15" />
        <attribute key="showattributes" value="1" />
    </item>`
all necklaces i have tested that have charges only have 1 charge in game. but shows correctly in items.

**Comment by lBaah** [comment]
How did you get these items? Drop/npc?

**Comment by yatozin** [comment]
made with god character is that the problem :s
tried buying from npc still same problem

**Comment by gerotib** [comment]
Yeah, if you creating it with god, the command works like "/i item, numer" where the number is charges amount. So "/i might ring, 20" will create correct might ring with 20 charges. In npc it works similar:
buyable:
`might ring, 2164, 5000,20;` where last numer (20) is charge amount.
If npc still sells you item with 1 charge then theres a problem.

**Comment by FakeShinoda** [comment]
Unconfirmed... All items sold by npc with charges ive tested are fine...
