### ISSUE TITLE
Imagens do store não estão funcionando

### ISSUE THREAD

**Issue by heron-belluzzi** [opentibiabr/otservbr-global-archived#659]
Coin store images are not loading, I tried to link externally and internally (same client PC) and none of the options worked, even with the correct url ...

![image](https://user-images.githubusercontent.com/15113966/66889910-7a84f480-efba-11e9-98b5-1e4b90169766.png)

![image](https://user-images.githubusercontent.com/15113966/66889836-43aede80-efba-11e9-99e1-b450fb2966d0.png)

![image](https://user-images.githubusercontent.com/15113966/66889878-66d98e00-efba-11e9-9243-c4968563cd15.png)

![image](https://user-images.githubusercontent.com/15113966/66889954-98525980-efba-11e9-82d9-4a68c101b4ee.png)

![image](https://user-images.githubusercontent.com/15113966/66890235-c4baa580-efbb-11e9-8d98-5b8082f3fc28.png)

**Comment by yatozin** [comment]
mine works
 `http://otserver.ddns.net/images/store`

**Comment by heron-belluzzi** [comment]
@yatozin how many time to update the image (client)? i upload mine and nothing until now...
i already restarted my server 3 times, and the client too...
Is there a cache I can clear?

**Comment by yatozin** [comment]
coinImagesURL = "http://otserver.ddns.net/images/store"

just write it correctly and it should work try remove "/ " at end

**Comment by heron-belluzzi** [comment]
i tried with your domain and nothing happens, i think is a kinda of cache, do you know how i clean?

**Comment by d0gw4r** [comment]
I use my own domain and it works fine.
![image](https://user-images.githubusercontent.com/51352360/66938754-2872bc00-f018-11e9-98d0-7ce4f6170d76.png)

Don't forget to check the image names inside **/images/store** with your **gamestore.lua**. It also has **case sensitive** form.
![image](https://user-images.githubusercontent.com/51352360/66938488-a08cb200-f017-11e9-8cad-e489d82a8afa.png)

Also, check if the folder has rights, I mean, if otserver can access the folder, or if something is blocking it. So don't forget to give it the permission to access **/images/store** folder.
![image](https://user-images.githubusercontent.com/51352360/66938559-c44ff800-f017-11e9-8f8c-e81ad9814272.png)

If you're using ubuntu, you can put this on terminal:
**chmod -R 660 /www/images/store**

For last, but not less important, you can try to clean your client's cache by deleting its **data8** and **prepared** inside **/storeimages** folder.
![image](https://user-images.githubusercontent.com/51352360/66938660-ff522b80-f017-11e9-96bf-d7e9c33b89ba.png)

Then log-in and test again.
![image](https://user-images.githubusercontent.com/51352360/66938942-7982b000-f018-11e9-88ca-bbcc2554c5ee.png)

**Comment by heron-belluzzi** [comment]
the url are fine, and the permissions too, you can check my store images in this url https://eleraglobal.com/images/store/64/xpboosticon.png
and i am using client 10.00... doesnt have data8 and prepared folders....

**Comment by d0gw4r** [comment]
So, for Client 10 you must look:

In Desktop:
Press: **win + R**
Type: **%appdata%**

Look for this path:
**C:\Users\your_user\AppData\Roaming\Tibia\ImageCache**

**Clean all files** inside there, then open your Client and test it.

**Comment by dudantas** [comment]
Solved, not is bug.

**Comment by heron-belluzzi** [comment]
@d0gw4r can you check my store folder in my website? https://eleraglobal.com/images/store/
are everything ok?

**Comment by d0gw4r** [comment]
No, it isn't. Try to change 'https' for 'http'. I'm getting page not found.
