### ISSUE TITLE
When the player dies the bless is not coming out

### ISSUE THREAD

**Issue by heron-belluzzi** [opentibiabr/otservbr-global-archived#665]
When the player dies the bless is not coming out, sometimes it comes out but mostly it doesn't come out...

**Comment by d0gw4r** [comment]
I've tried to reproduce it, but it's everything normal here.

**Comment by Lycanzito** [comment]
looks normal here..

**Comment by rafael-adcp** [comment]
looking normal here, only weird thing i noticed is that even with full bless if the player is using an amulet of loss the neck is removed together with the blessings

**Comment by enzerah** [comment]
> looking normal here, only weird thing i noticed is that even with full bless if the player is using an amulet of loss the neck is removed together with the blessings

this is what is expected, as rl
