### ISSUE TITLE
Error on compilling in Linux Ubuntu 14.04

### ISSUE THREAD

**Issue by jameesdavid** [opentibiabr/otservbr-global-archived#675]
On run cmake .. and make commands:
In file included from /home/pasta/otbr/src/cotire/tfs_CXX_prefix.cxx:4:0,
                 from /home/pasta/otbr/src/cotire/tfs_CXX_prefix.hxx:4:
/home/pasta/otbr/src/otpch.h:54:27: fatal error: spdlog/spdlog.h: No such file or directory
 #include <spdlog/spdlog.h>
                           ^
compilation terminated.
CMake Error at cmake/FindCotire.cmake:1783 (message):
  cotire: error 1 precompiling /home/pasta/otbr/src/cotire/tfs_CXX_prefix.hxx.
Call Stack (most recent call first):
  cmake/FindCotire.cmake:3332 (cotire_precompile_prefix_header)

make[2]: *** [cotire/tfs_CXX_prefix.hxx.gch] Error 1
make[1]: *** [CMakeFiles/tfs.dir/all] Error 2
make: *** [all] Error 2

**Comment by jameesdavid** [comment]
Complete log:

root@bla:/home/pasta/otbr/src# make
[  1%] Generating CXX prefix source cotire/tfs_CXX_prefix.cxx
[  2%] Generating CXX prefix header cotire/tfs_CXX_prefix.hxx
[  3%] Building CXX precompiled header cotire/tfs_CXX_prefix.hxx.gch
In file included from /home/pasta/otbr/src/cotire/tfs_CXX_prefix.cxx:4:0,
                 from /home/pasta/otbr/src/cotire/tfs_CXX_prefix.hxx:4:
/home/pasta/otbr/src/otpch.h:54:27: fatal error: spdlog/spdlog.h: No such file or directory
 #include <spdlog/spdlog.h>
                           ^
compilation terminated.
CMake Error at cmake/FindCotire.cmake:1783 (message):
  cotire: error 1 precompiling /home/pasta/otbr/src/cotire/tfs_CXX_prefix.hxx.
Call Stack (most recent call first):
  cmake/FindCotire.cmake:3332 (cotire_precompile_prefix_header)


make[2]: *** [cotire/tfs_CXX_prefix.hxx.gch] Error 1
make[1]: *** [CMakeFiles/tfs.dir/all] Error 2
make: *** [all] Error 2

**Comment by Costallat** [comment]
apt -y install git cmake build-essential liblua5.2-dev libgmp3-dev libmysqlclient-dev libboost-system-dev libboost-iostreams-dev libboost-filesystem-dev libpugixml-dev libcrypto++-dev **_` libspdlog-dev`_**

https://github.com/opentibiabr/OTServBR-Global/wiki/Compiling-on-Ubuntu-Debian


https://github.com/gabime/spdlog

$ git clone https://github.com/gabime/spdlog.git
$ cd spdlog && mkdir build && cd build
$ cmake .. && make -j



    Homebrew: brew install spdlog
    FreeBSD: cd /usr/ports/devel/spdlog/ && make install clean
    Fedora: yum install spdlog
    Gentoo: emerge dev-libs/spdlog
    Arch Linux: yaourt -S spdlog-git
    vcpkg: vcpkg install spdlog
    conan: spdlog/[>=1.4.1]@bincrafters/stable

**Comment by jameesdavid** [comment]
E: Unable to locate package libspdlog-dev

**Comment by Costallat** [comment]
https://github.com/gabime/spdlog

$ git clone https://github.com/gabime/spdlog.git
$ cd spdlog && mkdir build && cd build
$ cmake .. && make -j

Homebrew: brew install spdlog
FreeBSD: cd /usr/ports/devel/spdlog/ && make install clean
Fedora: yum install spdlog
Gentoo: emerge dev-libs/spdlog
Arch Linux: yaourt -S spdlog-git
vcpkg: vcpkg install spdlog
conan: spdlog/[>=1.4.1]@bincrafters/stable

**Comment by jameesdavid** [comment]
Nice! Thanks

**Comment by jameesdavid** [comment]
root@ot:/home/otp2/otbr/src/spdlog/build# cmake .. && make -j
-- The CXX compiler identification is GNU 4.8.4
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Build spdlog: 1.4.3
-- Looking for include file pthread.h
CMake Error at /usr/share/cmake-3.2/Modules/CheckIncludeFiles.cmake:74 (try_compile):
  Unknown extension ".c" for file

    /home/otp2/otbr/src/spdlog/build/CMakeFiles/CMakeTmp/CheckIncludeFiles.c

  try_compile() works only for enabled languages.  Currently these are:

    CXX

  See project() command to enable other languages.
Call Stack (most recent call first):
  /usr/share/cmake-3.2/Modules/FindThreads.cmake:123 (CHECK_INCLUDE_FILES)
  CMakeLists.txt:75 (find_package)


-- Looking for include file pthread.h - not found
CMake Error at /usr/share/cmake-3.2/Modules/FindPackageHandleStandardArgs.cmake:138 (message):
  Could NOT find Threads (missing: Threads_FOUND)
Call Stack (most recent call first):
  /usr/share/cmake-3.2/Modules/FindPackageHandleStandardArgs.cmake:374 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.2/Modules/FindThreads.cmake:204 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:75 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/otp2/otbr/src/spdlog/build/CMakeFiles/CMakeOutput.log".
See also "/home/otp2/otbr/src/spdlog/build/CMakeFiles/CMakeError.log".

**Comment by jameesdavid** [comment]
CMakeError.log

Determining if files pthread.h exist failed with the following output:

Source:
/* */
#include <pthread.h>


int main(void){return 0;}

**Comment by Costallat** [comment]
cd ~/Downloads
wget http://mirrors.kernel.org/ubuntu/pool/universe/s/spdlog/libspdlog-dev_1.6-1_amd64.deb
sudo dpkg -i libspdlog-dev_1.6-1_amd64.deb

**Comment by EleanorRigby1** [comment]
I have the same error for Debian Stretch

**Comment by Costallat** [comment]
@EleanorRigby1
Did you try to install libspdlog-dev ?

https://packages.debian.org/source/stretch/spdlog

@jameesdavid
Did you try those commands? If yes, the problem was solved?
Tks

**Comment by Costallat** [comment]
https://github.com/opentibiabr/OTServBR-Global/wiki/Compiling-on-Ubuntu-Debian

**Comment by EleanorRigby1** [comment]
> @EleanorRigby1
> Did you try to install libspdlog-dev ?
> 
> https://packages.debian.org/source/stretch/spdlog
> 
> @jameesdavid
> Did you try those commands? If yes, the problem was solved?
> Tks

Yes, my problem was solved with that, forget to say it here.
