### ISSUE TITLE
error compiling on linux debian 8

### ISSUE THREAD

**Issue by cocaocla** [opentibiabr/otservbr-global-archived#682]
[  3%] Building CXX precompiled header cotire/tfs_CXX_prefix.hxx.gch
In file included from /home/global/build/cotire/tfs_CXX_prefix.cxx:4:0,
                 from /home/global/build/cotire/tfs_CXX_prefix.hxx:4:
/home/global/src/otpch.h:54:27: fatal error: spdlog/spdlog.h: No such file or directory
 #include <spdlog/spdlog.h>
                           ^
compilation terminated.
CMake Error at cmake/FindCotire.cmake:1783 (message):
  cotire: error 1 precompiling /home/global/build/cotire/tfs_CXX_prefix.hxx.
Call Stack (most recent call first):
  cmake/FindCotire.cmake:3332 (cotire_precompile_prefix_header)

CMakeFiles/tfs.dir/build.make:54: recipe for target 'cotire/tfs_CXX_prefix.hxx.gch' failed
make[2]: *** [cotire/tfs_CXX_prefix.hxx.gch] Error 1
CMakeFiles/Makefile2:122: recipe for target 'CMakeFiles/tfs.dir/all' failed
make[1]: *** [CMakeFiles/tfs.dir/all] Error 2
Makefile:76: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by Costallat** [comment]
https://github.com/opentibiabr/OTServBR-Global/issues/675

**Comment by cocaocla** [comment]
did not work :/

**Comment by cocaocla** [comment]
https://github.com/gabime/spdlog

$ git clone https://github.com/gabime/spdlog.git
$ cd spdlog && mkdir build && cd build
$ cmake .. && make -j

Homebrew: brew install spdlog
FreeBSD: cd /usr/ports/devel/spdlog/ && make install clean
Fedora: yum install spdlog
Gentoo: emerge dev-libs/spdlog
Arch Linux: yaourt -S spdlog-git
vcpkg: vcpkg install spdlog
conan: spdlog/[>=1.4.1]@bincrafters/stable

me error

root@vps734905:~/spdlog/build# cmake ..
CMake Error at CMakeLists.txt:4 (cmake_minimum_required):
  CMake 3.2 or higher is required.  You are running version 3.0.2


-- Configuring incomplete, errors occurred!

**Comment by Costallat** [comment]
Like the error say -> 'CMake 3.2 or higher is required. You are running version 3.0.2'

You are running a too old version, it's better to upgrade to a more recent release.

**Comment by cocaocla** [comment]
will you help me with the update?

**Comment by Costallat** [comment]
sudo apt-get update -y && sudo apt-get dist-upgrade -y

sudo sed -i ‘s/jessie/stretch/g’ /etc/apt/sources.list

sudo apt-get update -y && sudo apt-get dist-upgrade -y

**Comment by cocaocla** [comment]
/usr/bin/ld: /usr/local/lib/liblua.a(loadlib.o): undefined reference to symbol 'dlclose@@GLIBC_2.2.5'
//lib/x86_64-linux-gnu/libdl.so.2: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
CMakeFiles/tfs.dir/build.make:2195: recipe for target 'tfs' failed
make[2]: *** [tfs] Error 1
CMakeFiles/Makefile2:122: recipe for target 'CMakeFiles/tfs.dir/all' failed
make[1]: *** [CMakeFiles/tfs.dir/all] Error 2
Makefile:76: recipe for target 'all' failed
make: *** [all] Error 2
root@vps734905:/home/global/build#
help?

**Comment by cocaocla** [comment]
> sudo apt-get update -y && sudo apt-get dist-upgrade -y
> 
> sudo sed -i ‘s/jessie/stretch/g’ /etc/apt/sources.list
> 
> sudo apt-get update -y && sudo apt-get dist-upgrade -y

not work :/ the same problem all the time

**Comment by Costallat** [comment]
you need to reboot after that, and try to install the packages again, as it was an system upgrade and not a simple package upgrade, you can also check on your VPS if they doesn't have a newer image, as we are using Ubuntu 18.04

If that does not solve your problem you need to search on google as it looks like it is a problem on your linux and not on the project.

Check also if you really upgrade it

**Comment by d0gw4r** [comment]
Have you installed all the required libs? It seems that cmake can't reconize some references, symbols, etc.

Try:

apt-get install git-core build-essential liblua5.2-dev libgmp3-dev libmysqlclient-dev libboost-system-dev libboost-iostreams-dev libpugixml-dev unzip unrar autoconf pkg-config automake libboost-all-dev libgmp3-dev libxml2-dev liblua5.1-0-dev libmysqlclient-dev libssl-dev libsqlite3-dev ack-grep

**Comment by cocaocla** [comment]
I did everything as you ordered, but when you try to install libraries and other errors, I think I will reinstall the system and it will be done without a problem

**Comment by cocaocla** [comment]
reinstalling the system will install the libraries and we will see if it works

**Comment by d0gw4r** [comment]
Yes, sometimes it's better going that way. I remember whe I fucked up the permissions of my whole system files, and in order to fix that I prefered to reinstall the whole system again. I guess it was the easy and fastest choice I made. Now it runs fine. :)
