### ISSUE TITLE
server after compilation does not start

### ISSUE THREAD

**Issue by cocaocla** [opentibiabr/otservbr-global-archived#689]
>> Loading vocations
>> Loading items
>> Loading script systems
>> Loading lua libs
terminate called after throwing an instance of 'std::runtime_error'
  what():  locale::facet::_S_create_c_locale name not valid
Aborted
please help

**Comment by cocaocla** [comment]
help men?

**Comment by majestyotbr** [comment]
Try this:
```
export DEBIAN_FRONTEND=noninteractive
apt-get install locales
echo "en_US.UTF-8 UTF-8" > /etc/locale.gen
locale-gen
```

**Comment by cocaocla** [comment]
not work

**Comment by cocaocla** [comment]
any suggestions?

**Comment by majestyotbr** [comment]
`apt-get install locales && dpkg-reconfigure locales`

**Comment by cocaocla** [comment]
root@vps734905:/home/ots# apt-get install locales
Reading package lists... Done
Building dependency tree
Reading state information... Done
locales is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
root@vps734905:/home/ots# dpkg-reconfigure locales
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
        LANGUAGE = (unset),
        LC_ALL = (unset),
        LANG = "pl_PL.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_MESSAGES to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory
Generating locales (this might take a while)...
  en_US.UTF-8... done
Generation complete.

>> Loading vocations
>> Loading items
>> Loading script systems
>> Loading lua libs
terminate called after throwing an instance of 'std::runtime_error'
  what():  locale::facet::_S_create_c_locale name not valid
Aborted
Not work bro
strange it's never been like that

**Comment by MajestyOTBR** [comment]
Missing locales are generated with locale-gen:
`locale-gen pl_PL.UTF-8`

Alternatively a locale file can be created manually with localedef:
`localedef -i pl_PL -f UTF-8 pl_PL.UTF-8`

Setting Locale Settings
The locale settings can be set (to pl_PL.UTF-8 in the example) as follows:
```
export LANGUAGE=pl_PL.UTF-8
export LANG=pl_PL.UTF-8
export LC_ALL=pl_PL.UTF-8
locale-gen pl_PL.UTF-8
dpkg-reconfigure locales
```
The `dpkg-reconfigure` locales command will open a dialog under Debian for selecting the desired locale.

**Comment by cocaocla** [comment]
root@vps734905:/home/ots# dpkg-reconfigure
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
        LANGUAGE = "pl_PL.UTF-8",
        LC_ALL = "pl_PL.UTF-8",
        LANG = "pl_PL.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_MESSAGES to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory
/usr/sbin/dpkg-reconfigure: please specify a package to reconfigure
root@vps734905:/home/ots# ^C
root@vps734905:/home/ots# locale-gen pl_PL.UTF-8
Generating locales (this might take a while)...
  en_US.UTF-8... done
Generation complete.
root@vps734905:/home/ots# localedef -i pl_PL -f UTF-8 pl_PL.UTF-8
root@vps734905:/home/ots# export LANGUAGE=pl_PL.UTF-8
root@vps734905:/home/ots# export LANG=pl_PL.UTF-8
root@vps734905:/home/ots# export LC_ALL=pl_PL.UTF-8
-bash: warning: setlocale: LC_ALL: cannot change locale (pl_PL.UTF-8)
root@vps734905:/home/ots# locale-gen pl_PL.UTF-8
Generating locales (this might take a while)...
  en_US.UTF-8... done
Generation complete.
root@vps734905:/home/ots# dpkg-reconfigure locales
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
        LANGUAGE = "pl_PL.UTF-8",
        LC_ALL = "pl_PL.UTF-8",
        LANG = "pl_PL.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_MESSAGES to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory
Generating locales (this might take a while)...
  en_US.UTF-8... done
Generation complete.
either I'm stupid and I'm doing something wrong or I don't know what

**Comment by majestyotbr** [comment]
Try now with `en_US.UTF-8`:

Missing locales are generated with locale-gen:
`locale-gen en_US.UTF-8`

Alternatively a locale file can be created manually with localedef:
`localedef -i en_US -f UTF-8 en_US.UTF-8`

Setting Locale Settings
The locale settings can be set (to en_US.UTF-8 in the example) as follows:
```
export LANGUAGE=en_US.UTF-8
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8
locale-gen en_US.UTF-8
dpkg-reconfigure locales
```
The `dpkg-reconfigure` locales command will open a dialog under Debian for selecting the desired locale.

**Comment by cocaocla** [comment]
everything works as it should be thank you for helping me have a nice day

**Comment by majestyotbr** [comment]
You're welcome.

**Comment by cocaocla** [comment]
hey bro one more question why do I have lags on a 10+ client? i have vps 8gb ram
