### ISSUE TITLE
Mad Mage Room Quest

### ISSUE THREAD

**Issue by omarcopires** [opentibiabr/otservbr-global-archived#69]
00:21 You see a closed door. Item ID: 1213 Position: 32578, 32197, 15

Essa porta necessita de um action ID para ser aberta somente utilizando a key 3666.

00:24 You see a silver key (Key:3666). It weighs 1.00 oz. Item ID: 2088, Action ID: 3666 Position: 32394, 32137, 14

source:http://tibia.wikia.com/wiki/Mad_Mage_Room_Quest

**Comment by dudantas** [comment]
fixed
