### ISSUE TITLE
Party list and multiple battle windows.

### ISSUE THREAD

**Issue by yatozin** [opentibiabr/otservbr-global-archived#690]
![party and battle](https://user-images.githubusercontent.com/55179288/67626544-28d94580-f8a9-11e9-9b9d-02f0463cdfd8.JPG)

new party widget and you can open multiple battle windows now.

**Comment by enzerah** [comment]
feel free to help and make a pr

**Comment by MajestyOTBR** [comment]
Feel free to help and make a PR.
