### ISSUE TITLE
Imbuiment System - Char não Crita no hit básico

### ISSUE THREAD

**Issue by luisbill1** [opentibiabr/otservbr-global-archived#694]
Bom dia, eu baixei aquele otserv novo 12.00 disponibilizado aqui no fórum e o mesmo está com um bug ou faltando algo aparentemente.

Eis a questão, todo o sistema de imbuimento está funcionando, porém o char não está dando crítico no ataque básico, apenas nas skills e eu não tenho conhecimento de como posso resolver isso, alguém poderia me ajudar?

Edit 1: Depois de um tempo o boneco para de dar o critico

Edit 2: Testei mais uma vez e a diamond arrow da critico no hit basico, como a burst arrow também... Porém as armas que não dão ataque em área não dão crítico

Edit 3: O critico "intricate" para de funcionar depois de um tempo, só continua funcionando o powerfull e mesmo assim sem dar critico no hit básico

Código abaixo do meu imbuiment (até botei o imbu lvl 3 100% para ver se dava, mas não funcionou também):

**Comment by luisbill1** [comment]
up

**Comment by lBaah** [comment]
Não confirmo que o intricate strike pare de funcionar.
