### ISSUE TITLE
[Docker] fatal error: bundled/core.h: No such file or directory

### ISSUE THREAD

**Issue by leoddias** [opentibiabr/otservbr-global-archived#702]
**Describe the bug**
While running the script docker/server-only/docker-build-server.sh i got this error:
`
In file included from /usr/include/spdlog/common.h:38,
                 from /usr/include/spdlog/spdlog.h:12,
                 from /tmp/otserver/src/otpch.h:54,
                 from /tmp/otserver/build/cotire/tfs_CXX_prefix.cxx:4,
                 from /tmp/otserver/build/cotire/tfs_CXX_prefix.hxx:4:
/usr/include/spdlog/fmt/fmt.h:22:10: fatal error: bundled/core.h: No such file or directory
   22 | #include "bundled/core.h"
      |          ^~~~~~~~~~~~~~~~
compilation terminated.
`

**To Reproduce**
1. Just exec the script docker/server-only/docker-build-server.sh

**Expected behavior**
Build the server.

**Desktop (please complete the following information):**
 - OS: [Linux Ubuntu]

**Comment by majestyotbr** [comment]
https://github.com/opentibiabr/OTServBR-Global/commit/e8d18c4c609a074e9ab39ffb8fee8028e0c56a44
