### ISSUE TITLE
Someone Have this file? [Quests.xml]

### ISSUE THREAD

**Issue by Kowzys** [opentibiabr/otservbr-global-archived#706]
>> Initializing gamestate
[Error - Quests::loadFromXml] Failed to load data/XML/quests.xml: File was not found

Hello everyone, I would like to know if anyone has the server compatible quests.xml file, because I am wanting to remove the server access missions, but for that, you need the quests.xml file to remove correctly through login.lua

Thanks

**Comment by yatozin** [comment]
data\lib\core quest.lua

**Comment by Kowzys** [comment]
Thanks @yatozin do you know how to show quests on quest log?
