### ISSUE TITLE
The Hidden City of Beregar Quest

### ISSUE THREAD

**Issue by omarcopires** [opentibiabr/otservbr-global-archived#71]
19:29 You see a chest (Vol:15). It weighs 120.00 oz. Item ID: 1740 Position: 32549, 31437, 14

Adicionar nesse baú a crystal of focus(item id 9941).

THE ROYAL RESCUE MISSION Há muitos bugs nessa missão em específico. Faltando muito respawn dos monstros dessa região.

source:http://tibia.wikia.com/wiki/The_Hidden_City_of_Beregar_Quest

**Comment by dudantas** [comment]
fixed
