### ISSUE TITLE
Imbuement Bugs

### ISSUE THREAD

**Issue by Lycanzito** [opentibiabr/otservbr-global-archived#710]
Imbuement:
a)Não dando critico no fisico(meele/distance single target, arrows,etc).
b) Tempo do imbuement contando mesmo dentro do depot + Tempo do Imbuement contando na backpack
(Deveria contar apenas com CONDITION_INFIGHT e ao perder essa condition, parar de decair o tempo)
c)Itens que já foram imbuidos anteriormente, mesmo com o imbuement removido,NÃO SÃO negociáveis no market.

ps : se alguém conhecer algum outro bug nos imbuiments, por favor, publicar a baixo =)

**Comment by lBaah** [comment]
a - confirmo
b - só diminui o tempo ao atacar monstro
c - confirmo

**Comment by Lycanzito** [comment]
> a - confirmo
> b - só diminui o tempo ao atacar monstro
> c - confirmo

Não entendi a resposta "b"
reduzir o tempo ao atacar monstro?oO
Ele desce o tempo normal já.. mas o problema que ele está descendo fora do pz

**Comment by gerotib** [comment]
b = #638 right?
I found how to change it for every imbuement:
[this line](https://github.com/opentibiabr/OTServBR-Global/blob/develop/src/game.cpp#L4907) change to:
```
			if (player->hasCondition(CONDITION_INFIGHT)) {
				duration -= decreaseTime;
			}
```
but I dont really know how to except this for speed and cap imbues. Maybe some id check from imbuements.xml `<category id="10" name="Increase Speed" />`, but dont know how to get this in cpp.

**Comment by heron-belluzzi** [comment]
@Lycanzito mana leech e life leech não está funcionando com ataque em area...

**Comment by Lycanzito** [comment]
@Heronbeluci eles já arrumaram isso a um tempo.

**Comment by Lycanzito** [comment]
> b = #638 right?
> I found how to change it for every imbuement:
> [this line](https://github.com/opentibiabr/OTServBR-Global/blob/develop/src/game.cpp#L4907) change to:
> 
> ```
> 			if (player->hasCondition(CONDITION_INFIGHT)) {
> 				duration -= decreaseTime;
> 			}
> ```
> 
> but I dont really know how to except this for speed and cap imbues. Maybe some id check from imbuements.xml `<category id="10" name="Increase Speed" />`, but dont know how to get this in cpp.

any news about it? @gerotib

**Comment by Lycanzito** [comment]
@MajestyOTBR Ainda existem 2 coisas a serem fixadas nesse tópico que eu abri :

b) Tempo do imbuement contando mesmo dentro do depot + Tempo do Imbuement contando na backpack
(Deveria contar apenas com CONDITION_INFIGHT e ao perder essa condition, parar de decair o tempo)
c)Itens que já foram imbuidos anteriormente, mesmo com o imbuement removido,NÃO SÃO negociáveis no market.

**Comment by lBaah** [comment]
@MajestyOTBR b) @gerotib provided a solution
c) is duplicated at #711 

This can be closed.

**Comment by Lycanzito** [comment]
> @MajestyOTBR b) @gerotib provided a solution
> c) is duplicated at #711
> 
> This can be closed.

I saw the solution, is working fine ! thanks for @gerotib 

@lBaah Em relação a letra C, então é diretamente um bug no market? e não no imbuiment?
