### ISSUE TITLE
Market Bug

### ISSUE THREAD

**Issue by Lycanzito** [opentibiabr/otservbr-global-archived#711]
Market ->
a)->Market Apenas está à Negociar com Dinheiro do Jogador<- ( e não do banco )
b)->Market calculando bugado os valores a cima de 5 digitos<-
c)->Só dá para criar offers com no máximo 100 itens<-
d)->Só dá para criar offers com no máximo 100 Coins<-
e)Itens que já foram imbuidos anteriormente, mesmo com o imbuement removido, não são negociaveis no market.

ps: um colega meu me informou que alguma das coisas citadas à cima já foram corrigidas, mas não custa nada, reportar.
:-)

**Comment by Lycanzito** [comment]
Esses bugs não foram confirmados? @dudantas

**Comment by dudantas** [comment]
Ainda não testamos, por isso o label Unconfirmed.

**Comment by dudantas** [comment]
O do Imbuement tem um PR em aberto para resolver, ainda em desenvolvimento e testes.

**Comment by Lycanzito** [comment]
only this bug remains : e)Itens que já foram imbuidos anteriormente, mesmo com o imbuement removido, não são negociaveis no market.
