### ISSUE TITLE
Client debug after I buy a house and restart server. BUG

### ISSUE THREAD

**Issue by christiangamaesilva** [opentibiabr/otservbr-global-archived#722]
Whenever I buy a house and I restart the server (doesn't matter how long I wait to restart), the next time I login my character that bought that house is going to get a debug error.

After 2 attemps of login, I am able to acess my character (if I do it quickly). However, whenever I close the game, I will receive the debug once again.

**Weird fact:** If my game debugs and I try to acess again quickly, I am able to login. If the game debugs and I wait a few seconds, I will receive another debug after I login.

I am using client 12
**There is no console error, only a debug error.**

**Comment by majestyotbr** [comment]
It's not a OTServBR-Global bug. Tested with talkactions **!buyhouse**, **!sellhouse**, **!leavehouse** removed from this commit https://github.com/opentibiabr/OTServBR-Global/commit/649ec416851f8e1a23418a48707e458f0d49489e and worked fine.

Unconfirmed.
