### ISSUE TITLE
Required revisions on monsters

### ISSUE THREAD

**Issue by dudantas** [opentibiabr/otservbr-global-archived#723]
I'm reviewing the monsters and arranging most things to stay the same as global, but spells are a lot of work (and I'm doing many things at once), so I'll leave a list of monsters in case anyone wants to do this work. This list will also tell you when a monster is missing other information, such as life, experience, speed, armor or even all of the above (general revision).

PS: This issue is for [monsters branch](https://github.com/opentibiabr/OTServBR-Global/tree/monsters)
The list will be updated according to what I am finding.

- [ ] Disgusting Ooze: need general informations and revision.
- [ ] Obujos: need speed and armor information and revision spells.
- [ ] Chayenne: need general informations and revision.
- [ ] Malofur Mangrinder: need general informations and revision.
- [ ] Lady Tenebris: need general informations and revision. 
- [ ] Grimeleech: need revision at the spells.
- [ ] Hellflayer: need revision at the spells.
- [ ] Sparkion: need revision at the spells.
- [ ] Knowledge Raider: need general informations and revision. Corpse wrong, is using the corpse of Breach Brood.
- [ ] Reality Reaver: need revision at the spells.
- [ ] Buster: need general informations and revision. 
- [ ] Dreadful Disruptor: need general informations and revision. 
- [ ] Aftershock: need general informations and revision. 
- [ ] The Souldespoiler: need general informations and revision. 
- [ ] Rupture: need general informations and revision. 
- [ ] Outburst: need general informations and revision. 
- [ ] Eradicator: need general informations and revision. 
- [ ] Eradicator (strong version): need general informations and revision. 
- [ ] Anomaly: need general informations and revision. 
- [ ] Realityquake: need general informations and revision.
- [ ] Overcharged Disruption: need general informations and revision.
- [ ] Soul of Dragonking Zyrtarch: need information of life, experience, armor, speed and possible revision on the spells.
- [ ] Broken Shaper: Need revision on the spells.
- [ ] Twisted Shaper: Need revision on the spells
- [ ] The Time Guardian: need general informations and revision.
- [ ] The Blazing Time Guardian: need informations (life, experience, speed, armor and etc).
- [ ] The Freezing Time Guardian: need informations (life, experience, speed, armor and etc).
- [ ] Kalyassa: need informations (speed, armor) and revision on the spells.
- [ ] Tazhadur: need informations (speed, armor) and revision on the spells.
- [ ] Gelidrazah the Frozen: need informations (speed, armor) and revision on the spells.
- [ ] Dragon Warden: need general informations.
- [ ] Animated Mummy: need informations (speed, armor) and spells revision.
- [ ] Arctic Faun: need revision spells.
- [ ] Minotaur Idol: need general informations and spells revision.
- [ ] The Sandking: need general informations and spells revision.
- [ ] Makeshift Home:  need general informations and spells revision.
- [ ] Cave Devourer: need spells revision.
- [ ] Chasm Spawn: need spells revision.
- [ ] Last Planegazer: need general revision.
- [ ] The Baron From Below: need general revision.
- [ ] The Hungry Baron From Below: need general revision.
- [ ] The Count Of The Core: need general revision.
- [ ] The Duke Of The Depths (and immortal version): need general revision.
- [ ] Mole: need spells revision.
- [ ] Cave Spider: need informations (speed, armor)
- [ ] Black Vixen: need informations (speed, armor)
- [ ] Bloodback: need informations (speed, armor)
- [ ] Shadowpelt: need informations (speed, armor)
- [ ] Brain Squid: need revision on the spells and loot chance.
- [ ] Animated Feather: need revision on the spells and loot chance.
- [ ] Flying Book: need revision on the spells and loot chance.
- [ ] Cursed Book: need revision on the spells and loot chance.
- [ ] Floating Savant: need revision on the spells.
- [ ] Ink Blob: need revision on the spells.
- [ ] Concentrated Death: need general informations and revision.
- [ ] Rift Breacher: revision on the corpse of monster.
- [ ] Knowledge Elemental: revision on spells and loot chances.
- [ ] Biting Book: revision on spells.
- [ ] Librarian: need general informations and revision.
- [ ] True Midnight Asura: need revision on the spells.
- [ ] Grand Master Oberon: need revision on the spells, information of armor and speed.
- [ ] Brokul: need revision on the spells, information of armor and speed.
- [ ] Thawing Dragon Lord: need revision on the spells, information of armor and speed.
- [ ] Preceptor Lazare: need general informations and revision.
- [ ] Zorvorax: need revision on the spells, information of armor and speed.
- [ ] True Dawnfire Asura: need revision on the spells.
- [ ] True Frost Flower Asura: need revision on the spells.
- [ ] Grand Commander Soeren: need revision on the spells, information of armor and speed.
- [ ] Grand Chaplain Gaunder: need revision on the spells, information of armor and speed.
- [ ] Grand Canon Dominus: need revision on the spells, information of armor and speed.
- [ ] Guardian of Tales: need revision on the spells.
- [ ] Icecold Book: need revision on the spells.
- [ ] Energitc Book: need revision on the spells.
- [ ] Rage Squid: need revision on the spells.
- [ ] Squid Warden: need revision on the spells.
- [ ] The Blazing Rose: need general informations and revision.
- [ ] The Diamond Blossom: need general informations and revision.
- [ ] The Lily of Night: need general informations and revision.
- [ ] Frost Flower Asura: need revision on the spells.
- [ ] Arctic Faun: need revision on the spells.
- [ ] Raxias: need revision on the spells and informations (armor and speed)
- [ ] Faceless Bane: need revision on the spells and informations (armor and speed).
- [ ] Malofur Mangrinder: Need general revision. (do not have informations for health, speed, armor, elements, loot chances, flags and attacks)
- [ ] Plagueroot: Need general revision. (do not have informations for health, speed, armor, elements, loot chances, flags and attacks)
- [ ] Ripper Spectre: need revision on the spells.
- [ ] Lumbering Carnivor: need revision on the spells.
- [ ] Thanatursus: need revision on the spells.
- [ ] Arachnophobica: need revision on the spells.
- [ ] Crazed Summer Vanguard: need revision on the spells.
- [ ] Crazed Summer Reaguard: need revision on the spells.
- [ ] Spiky Carnirvor: need revision on the spells.
- [ ] Menacing Carnirvor: need revision on the spells.

**Comment by dudantas** [comment]
Updated.

**Comment by taelg** [comment]
Water Elemental's body should not disappear when fishing it. It is also dropping the wrong items when fished.

**Comment by enzerah** [comment]
there's no monster branch atm
