### ISSUE TITLE
[Error - Quests::loadFromXml]

### ISSUE THREAD

**Issue by Kowzys** [opentibiabr/otservbr-global-archived#725]
Hello Everyone,

I have this little bug in my distro and would like to fix it as I do instead of loading the quests from the XML file TFS read the quests through the /data/lib/core/quests.lua 

Thanks Everybody

**Comment by gerotib** [comment]
If in your config.lua `loadQuestLua = true` change it to `loadQuestLua = false` and this should fix your problem
