### ISSUE TITLE
Condition to Magic Level

### ISSUE THREAD

**Issue by Underewarr** [opentibiabr/otservbr-global-archived#731]
Try to use a mastermind potion, on this potion you put all skills fish shield dist... etc
and the result is Magic level not are added, like i say all skills works, but magic level dont.

you can test with this condition + magic level condition, dont will work
conditionFood:setParameter(CONDITION_PARAM_SKILL_CLUB, 30)
conditionFood:setParameter(CONDITION_PARAM_SKILL_SWORD, 30)
conditionFood:setParameter(CONDITION_PARAM_SKILL_AXE, 30)
conditionFood:setParameter(CONDITION_PARAM_SKILL_DISTANCE, 30)
conditionFood:setParameter(CONDITION_PARAM_SKILL_SHIELD, 30)

**Comment by dudantas** [comment]
Try

> (CONDITION_PARAM_LEVELMAGICVALUE,30)

**Comment by dudantas** [comment]
What exactly do you want to do? The script for mastermind potion already exists.
Here: https://github.com/opentibiabr/OTServBR-Global/blob/650d9f3da87d401d014f57ecc0be52deb3822d32/data/actions/scripts/others/consumables/potions.lua#L7

And if you analyze it well, you'll find out how to apply it to other scripts.
