### ISSUE TITLE
A Prey está acabando após matar somente 1 bicho...

### ISSUE THREAD

**Issue by heron-belluzzi** [opentibiabr/otservbr-global-archived#735]
A Prey está acabando após matar somente 1 bicho...
Ela acaba após matar um bicho, pra ver se acabou basta acessar a interface de prey que lá estará disponivel para dar re-roll...

**Comment by majestyotbr** [comment]
![image](https://user-images.githubusercontent.com/32709570/68253444-b41fad00-0006-11ea-9654-c38bfc86e52f.png)

Não confirmado.

**Comment by dudantas** [comment]
Certifique-se de que você está usando a base completa e não tenham alterações que não são do repositório gerando algum problema. Baixe a base limpa, mais atual, compile, reinstale tudo novamente, inclusive site e faça o teste. 
Caso persista o erro, tente achar um padrão e retorne até aqui.
