### ISSUE TITLE
Bug related to container's weight over 1000 oz

### ISSUE THREAD

**Issue by kosicki123** [opentibiabr/otservbr-global-archived#739]
**Describe the bug**
Não é possível colocar uma backpack com mais de 1000 oz dentro da minha backpack atual arrastando ela para a backpack aberta, caso eu arraste para o slot da backpack, funciona. A mensagem diz que não tenho cap, apesar de ser Admin. Também testei com players com cap o suficiente e o resultado foi o mesmo. Este bug é relacionado ao PR https://github.com/opentibiabr/OTServBR-Global/pull/688 que foi mergeado e deve ter causado o problema. Até onde eu entendo, deveria ser possível mover containers pesados (até porque existe o loot bag que os players arrastam e no global é possível arrastar a backpack pesada e colocar na backpack vazia).

**To Reproduce**
1. Criar uma backpack com mais de 1000 de oz em items.
3. Em seguida, joguei a backpack no chão, criei uma nova backpack vazia e tentei pegar a backpack do chão.
4. A mensagem que me foi exibida foi: "Your cannot move this item too heavy.", que é gramaticalmente incorreta em inglês e não deveria ser aplicada neste cenário.

**Expected behavior**
O esperado era conseguir pegar a backpack. Pelos meus testes, com até exatamente 1000 de cap dá para pegar, com mais que isso (1000.1 oz por exemplo), o bug acontece. Comecei hoje a olhar o código, mas não parece que deveria cair neste bloco neste caso (tentei usar a tag code mas ficou tudo na mesma linha):
	-- No move parcel very heavy
	  if DISABLE_CONTAINER_WEIGHT == 0 and ItemType(item:getId()):isContainer() and item:getWeight() > CONTAINER_WEIGHT then
            self:sendCancelMessage("Your cannot move this item too heavy.")
            return false
          end

**Screenshots**
Na print abaixo, a backpack vazia é a do personagem e a do chão é a que contém crystal coins.
![print1](https://user-images.githubusercontent.com/1424811/68351365-08e42600-00e2-11ea-800f-9a0a0d640188.png)

**Comment by Lycanzito** [comment]
Acredito que é um sistema de "segurança", você pode aumentar para o valor que você achar interessante, no meu eu coloco até 10 k de cap.

**Comment by kosicki123** [comment]
Se o objetivo é seguir o desenvolvimento das features do global, não faz sentido, ou faz? Existe algum crash reportado relacionado a ter um container com determinada quantidade de cap?

**Comment by hygorrasec** [comment]
Criaram esse bloquei por algum motivo, talvez um bug no servidor que eu ainda não encontrei.
Eu criei uma variável que você pode habilitar ou desabilitar essa opção.
Vai em data/events/player.lua e aonde tá **DISABLE_CONTAINER_WEIGHT = 0** altera pra **1**

https://github.com/opentibiabr/OTServBR-Global/pull/688

**Comment by Lycanzito** [comment]
> Se o objetivo é seguir o desenvolvimento das features do global, não faz sentido, ou faz? Existe algum crash reportado relacionado a ter um container com determinada quantidade de cap?

Olha.. você vai encontrar outros mecanismos de segurança, como por exemplo: "exaust" ao dar look, em itens/players etc...

**Comment by kosicki123** [comment]
Tudo bem, mas ninguém sabe o motivo do mecanismo de segurança existir?

**Comment by lBaah** [comment]
Sim, esse sistema é uma solução temporária e incorreta pra evitar que os jogadores carreguem muitos itens leves. Por exemplo, experimente criar 30 mil items no inventário e ficar logando e deslogando. O server trava.
A solução pra isso é impedir que uma certa quantidade de items seja colocada no inventário, partindo do container principal.
