### ISSUE TITLE
PK Está saindo qnd desativa o battle!!!

### ISSUE THREAD

**Issue by heron-belluzzi** [opentibiabr/otservbr-global-archived#741]
* PK Está saindo assim que desativa o battle.
* Os danos foram diminuidos após o critical update, atrapalhando a jogabilidade (E MUITO).

**Comment by DamianDEB** [comment]
i translate this comment 
its true if you set pvp mode attack player when pvp mode turn off automatic loss pz 
;o

auto attack you get a skull if player exhaust loss skull next auto attack get skull

**Comment by DamianDEB** [comment]
i find problem 
pzLocked = 60 * 1000
if you change to this pzLocked = 15 * 10000
pzLocked = 60 * 600000
you stay on pz little bit longer maximum 20 sec ;/

**Comment by heron-belluzzi** [comment]
fixed: https://github.com/opentibiabr/OTServBR-Global/pull/745

**Comment by dudantas** [comment]
Inconfirmado. Testei com a base limpa e não deu nada disso.

**Comment by majestyotbr** [comment]
Confirmado.

**Comment by DamianDEB** [comment]
Thanks you this project rlly have amazing dev's and future to be great  !

**Comment by mattyx14** [comment]
this fixed on lasted

**Comment by majestyotbr** [comment]
Fixed on https://github.com/opentibiabr/OTServBR-Global/commit/97b4de9b1b8d95bd625927c029e992df63810da3
