### ISSUE TITLE
Exercise Weapon Bug 

### ISSUE THREAD

**Issue by Lycanzito** [opentibiabr/otservbr-global-archived#744]
After 15 minutes you get KICK even when you are training !

![image](https://user-images.githubusercontent.com/52710697/68437320-570b2f00-019f-11ea-89e1-5636de1fdefd.png)

After you get kicked from the game, you cant continue your training.

**Comment by Lycanzito** [comment]
even if you reopen the server, the "exaust" continues.
![image](https://user-images.githubusercontent.com/52710697/68437589-30012d00-01a0-11ea-9de7-3cf8450628e8.png)

**Comment by Lycanzito** [comment]
Actually, after reopen the server, all the characters that was training, get the same problem.

**Comment by lBaah** [comment]
Maybe you forgotten this (https://github.com/opentibiabr/OTServBR-Global/blob/3ab6f3e2254bb5b7c8300243262146b56255580c/data/creaturescripts/scripts/others/login.lua#L161) on your custom server not related to this repo.

**Comment by Lycanzito** [comment]
> Maybe you forgotten this (
> 
> https://github.com/opentibiabr/OTServBR-Global/blob/3ab6f3e2254bb5b7c8300243262146b56255580c/data/creaturescripts/scripts/others/login.lua#L161
> 
> ) on your custom server not related to this repo.

Actually, im using the same , only was missing these lines, on login.lua problably it was add , before this commit "Update exercise weapons Fix of Issue #321 (#619)"

Anyways, thanks again ! =)

going to close this thread.

**Comment by Lycanzito** [comment]
Na verdade, vou reabrir o tópico, pois existe um erro ainda a cima relatado.

:After 15 minutes you get KICK even when you are training !

deveria contar como idle time apenas após o termino do USO da arma, não de seu começo.

**Comment by lBaah** [comment]
https://github.com/opentibiabr/otservbr-global/blob/develop/src/player.cpp#L1547
Try:
`if (!getTile()->hasFlag(TILESTATE_NOLOGOUT) && !isAccessPlayer() && !getStorageValue(**YOUR TRAINING STORAGE**,1) ) {`

**Comment by Lycanzito** [comment]
> https://github.com/opentibiabr/otservbr-global/blob/develop/src/player.cpp#L1547
> Try:
> `if (!getTile()->hasFlag(TILESTATE_NOLOGOUT) && !isAccessPlayer() && !getStorageValue(**YOUR TRAINING STORAGE**,1) ) {`

Acabei optando por diminuir a quantidade de cargas, esse storage, já tá definido lá no .lua ?

**Comment by Lycanzito** [comment]
> https://github.com/opentibiabr/otservbr-global/blob/develop/src/player.cpp#L1547
> Try:
> `if (!getTile()->hasFlag(TILESTATE_NOLOGOUT) && !isAccessPlayer() && !getStorageValue(**YOUR TRAINING STORAGE**,1) ) {`

Testei e não obtive sucesso.

![image](https://user-images.githubusercontent.com/52710697/69921499-e4753280-1470-11ea-92a8-580197e5dce8.png)

**Comment by JoaoCRDias** [comment]
Onde está **YOUR TRAINING STORAGE** vc deve colocar o storage correto e não deixar como esta, esse erro se deu pois vc não modificou essa parte!

**Comment by Lycanzito** [comment]
> Onde está **YOUR TRAINING STORAGE** vc deve colocar o storage correto e não deixar como esta, esse erro se deu pois vc não modificou essa parte!

Opa meu querido, mas qual seria esse storage? e devo retirar, as ** ?

**Comment by chriscarp** [comment]
nao consegui fazer aqui... compilo certinho mas ai nao desloga nunca... nem sem fazer nada

**Comment by JoaoCRDias** [comment]
Troque ** YOUR TRAINING STORAGE ** por Storage.isTraining

**Comment by chriscarp** [comment]
c:\otservbr-global-develop\src\player.cpp(1579): error C2065: 'Storage': undeclared identifier

**Comment by chriscarp** [comment]
It worked this way for me:
change 
if (!getTile()->hasFlag(TILESTATE_NOLOGOUT) && !isAccessPlayer()) {

for
	const uint32_t storageTraining = 37;
	int32_t valueTraining = 1;
	auto it = storageMap.find(storageTraining);
	if (it == storageMap.end()) {
		valueTraining = -1;
	}
	else {
		valueTraining = it->second;
	}
if (!getTile()->hasFlag(TILESTATE_NOLOGOUT) && !isAccessPlayer() && !valueTraining == 1) {

**Comment by Lycanzito** [comment]
> It worked this way for me:
> change
> if (!getTile()->hasFlag(TILESTATE_NOLOGOUT) && !isAccessPlayer()) {
> 
> for
> const uint32_t storageTraining = 37;
> int32_t valueTraining = 1;
> auto it = storageMap.find(storageTraining);
> if (it == storageMap.end()) {
> valueTraining = -1;
> }
> else {
> valueTraining = it->second;
> }
> if (!getTile()->hasFlag(TILESTATE_NOLOGOUT) && !isAccessPlayer() && !valueTraining == 1) {

I will try this.
in 15 min i give an answer about it

**Comment by Lycanzito** [comment]
Well..
15:43 You started training.
15:43 You advanced to distance fighting level 11.
15:43 You advanced to distance fighting level 12.
15:43 You advanced to distance fighting level 13.
15:43 You advanced to distance fighting level 14.
15:43 You advanced to distance fighting level 15.
15:43 You advanced to distance fighting level 16.
15:43 You advanced to distance fighting level 17.
15:43 You advanced to distance fighting level 18.
15:43 You advanced to distance fighting level 19.
15:44 You advanced to distance fighting level 20.
15:44 You advanced to distance fighting level 21.
15:44 You advanced to distance fighting level 22.
15:45 You advanced to distance fighting level 23.
15:46 You advanced to distance fighting level 24.
15:48 You advanced to distance fighting level 25.
15:50 You advanced to distance fighting level 26.
15:53 You advanced to distance fighting level 27.
15:57 You advanced to distance fighting level 28.
15:59 You have been idle for 15 minutes. You will be disconnected in one minute if you are still idle then.

Still have the same problem :/

**Comment by chriscarp** [comment]
U recompile the .exe? If yes check storage as the same. 37

**Comment by Lycanzito** [comment]
> U recompile the .exe? If yes check storage as the same. 37

Yes, recompiled the tfs.
Where should I put this storage value? on lib storages ?
data/lib/miscellaneous 051-storages

Only can see this storage:
	Exercisedummy = {
		exaust = 98231521
	},

**Comment by chriscarp** [comment]
https://github.com/opentibiabr/otservbr-global/blob/b517b82ce260b15fd6bec179ddb66ae3a63fa54d/data/lib/miscellaneous/051-storages.lua#L1363

**Comment by Lycanzito** [comment]
Sorry for the delay, with these changes its now working properly, thanks.

**Comment by VitorNM** [comment]
Please, im sorry for reopening this issue, but i still have the problem of the player being kicked for inactivity when training with the exercise weapons. I've tried all the suggestions on the comments and all changes made on player.cpp causes error when compiling the source...

i'm pretty newbie in C++ programming, but i've tried all logical possibilities, something like !getStorageValue() == 37 but nothing works ;s

Please can somebody help me? I've checked and i have all the commits updated in my local repository and all files are identical from the git repo. I think if we can solve this issue, we can help the project with a pull request.

This is what i've tried, and the error i've got:

https://github.com/opentibiabr/otservbr-global/issues/744#issuecomment-558284654
`if (!getTile()->hasFlag(TILESTATE_NOLOGOUT) && !isAccessPlayer() && !getStorageValue(37,1) ) {`

![image](https://user-images.githubusercontent.com/29928255/73522183-83bd9400-43e6-11ea-9eb8-9e4b01bb4173.png)


https://github.com/opentibiabr/otservbr-global/issues/744#issuecomment-567021675
`if (!getTile()->hasFlag(TILESTATE_NOLOGOUT) && !isAccessPlayer() && !getStorageValue(Storage.isTraining,1) ) {`

![image](https://user-images.githubusercontent.com/29928255/73522293-caab8980-43e6-11ea-9b9a-8a39b393c634.png)


https://github.com/opentibiabr/otservbr-global/issues/744#issuecomment-567504997
`const uint32_t storageTraining = 37;
int32_t valueTraining = 1;
auto it = storageMap.find(storageTraining);
if (it == storageMap.end()) {
valueTraining = -1;
}
else {
valueTraining = it->second;
}
if (!getTile()->hasFlag(TILESTATE_NOLOGOUT) && !isAccessPlayer() && !valueTraining == 1) {`


![image](https://user-images.githubusercontent.com/29928255/73522472-3c83d300-43e7-11ea-81dd-44913c5774e9.png)


Again, i'm sorry for reopening the issue report.

**Comment by Costallat** [comment]
!valueTraining == 1) -> !(valueTraining == 1))

**Comment by VitorNM** [comment]
Thanks for the help @Costallat, i will try it and reply as soon as possible .

**Comment by VitorNM** [comment]
Solved. Again, thanks for the help @Costallat.
