### ISSUE TITLE
Bug "runonhealth" + "limit of run"

### ISSUE THREAD

**Issue by Lycanzito** [opentibiabr/otservbr-global-archived#749]
When the monsters starts to run, he get a few "steps" to move, and keep moving , like 1/2 second.
Also.. The "limit" of running is too close, it should be atleast 24~30 sqms from the player.

Is kinda simple to be explained, but i've produce a video to show it.

https://www.youtube.com/watch?v=inb61vaGANI

**Comment by vankk** [comment]
Try change the boolean value to false in [this line](https://github.com/opentibiabr/otservbr-global/blob/develop/src/creature.cpp#L909).

**Comment by Lycanzito** [comment]
Fazendo isso, o erro só piora.

Os monstros continuam correndo com "pausas" ..

mas agora, pra piorar, não correm em uma direção em relação ao jogador. Até voltando para próximos do player, eles voltam. E o limite de 3~4 sqms fora da tela, continua.

**Comment by Lycanzito** [comment]
only the limit of running is the problem now.

**Comment by heberholanda** [comment]
@Lycanzito can test my fix ?
