### ISSUE TITLE
Exp Gain Rate + Exp Boost

### ISSUE THREAD

**Issue by Lycanzito** [opentibiabr/otservbr-global-archived#750]
If you take  look on the Skills Bars, you can see that the exp isnt been calculated correctly.

1x Experience without boost = should be 150% not 225%
with boost should be 225%

Video:
https://www.youtube.com/watch?v=exfYHyS_uRs

**Comment by Lycanzito** [comment]
also after you kill a monster, you receive more 75%

for no reason.
![image](https://user-images.githubusercontent.com/52710697/68549704-eef45d00-03d9-11ea-9210-49decce16acc.png)

**Comment by Lycanzito** [comment]
Also.. After made a few tests..

The exp boost isnt giving 75% on bonus hour, only 50%.


so... With bonus+boost, you are receiving 200% instead of 225% ( and is showing 300%)
and after kill a monter, it update to 375% without reason, but you still receive 200%.

**Comment by lBaah** [comment]
Check there: https://github.com/opentibiabr/otservbr-global/blob/develop/data/events/scripts/player.lua#L733

**Comment by Lycanzito** [comment]
> Check there: https://github.com/opentibiabr/otservbr-global/blob/develop/data/events/scripts/player.lua#L733

checked

```
function Player:onGainExperience(source, exp, rawExp)
	if not source or source:isPlayer() then
		return exp
	end

	-- Soul Regeneration
	local vocation = self:getVocation()
	if self:getSoul() < vocation:getMaxSoul() and exp >= self:getLevel() then
		soulCondition:setParameter(CONDITION_PARAM_SOULTICKS, vocation:getSoulGainTicks() * 1000)
		self:addCondition(soulCondition)
	end

	-- Experience Stage Multiplier
	exp = exp * Game.getExperienceStage(self:getLevel())
	baseExp = rawExp * Game.getExperienceStage(self:getLevel())
	if Game.getStorageValue(GlobalStorage.XpDisplayMode) > 0 then
		displayRate = Game.getExperienceStage(self:getLevel())
		else
		displayRate = 1
	end


	-- Store Bonus
	local Boost = self:getExpBoostStamina()
	useStaminaXp(self) -- Use store boost stamina
	self:setStoreXpBoost(Boost > 0 and 50 or 0)
	if (self:getExpBoostStamina() <= 0 and self:getStoreXpBoost() > 0) then
		self:setStoreXpBoost(0) -- Reset Store boost to 0 if boost stamina has ran out
	end
	if (self:getStoreXpBoost() > 0) then
		exp = exp + (baseExp * (self:getStoreXpBoost()/100)) -- Exp Boost
		displayRate = displayRate * ((self:getStoreXpBoost()+100)/100)
	end

	-- Stamina Bonus
	if configManager.getBoolean(configKeys.STAMINA_SYSTEM) then
		useStamina(self)
		local staminaMinutes = self:getStamina()
		if staminaMinutes > 2400 and self:isPremium() then
			exp = exp + baseExp * 0.5
			displayRate = displayRate + Game.getExperienceStage(self:getLevel()) * 0.5
			self:setStaminaXpBoost(150)
		elseif staminaMinutes <= 840 then
			exp = exp * 0.5
			self:setStaminaXpBoost(50)
			displayRate = displayRate * 0.5
		else
			self:setStaminaXpBoost(100)
		end
	end

	self:setBaseXpGain(displayRate * 100)
	return exp
end
```

the unique difference beetwhen mine and this one, is that i've removed the prey system
the problem is still the same.

**Comment by Lycanzito** [comment]
Fiz um outro vídeo para demonstrar o problema.
https://www.youtube.com/watch?v=584mSvmvYTE

@lBaah

**Comment by lBaah** [comment]
Com as informações que você tem, tenho certeza que você consegue resolver isso.

**Comment by Lycanzito** [comment]
> Com as informações que você tem, tenho certeza que você consegue resolver isso.

pior que, se não pegar na minha mão, e me levar eu não consigo não, sou horrível em qualquer coisa que envolva programação. 
=/

**Comment by Lycanzito** [comment]
Alguém ? =/

**Comment by EleanorRigby1** [comment]
> Alguém ? =/

I do not know if it is damaging the syntax, but it worked perfect and there are no errors, someone who tells me if the correction is wrong?

Change this in player.lua
`self:setBaseXpGain(displayRate * 100)`

for this
`self:setBaseXpGain(100)`

**Comment by thatmichaelguy** [comment]
I've been aware of this issue for quite a while but have not had time to revisit it. Might have some time this weekend though.
@Lycanzito The initial display of the exp rate % is set on login, it then updates after each creature kill. There is an issue between the rate calculation in login.lua and player.lua currently, that is why it randomly changes up 75% after first kill.

**Comment by majestyotbr** [comment]
Fixed: https://github.com/opentibiabr/otservbr-global/commit/35fa40acdae2064e72c307b03d4224280ea2d23b
