### ISSUE TITLE
Secret Service Quest

### ISSUE THREAD

**Issue by omarcopires** [opentibiabr/otservbr-global-archived#76]
Mission 2 - Operation Green Claw 21:57 You see a gate of expertise for level 30. Item ID: 5103, Action ID: 1030 Position: 32872, 31957, 11

Esta tem que ser uma porta selada(sealed door) unicamente disponível para completar a missão 2.

source:http://tibia.wikia.com/wiki/Secret_Service_Quest#Mission_2_-_Operation_Green_Claw

**Comment by dudantas** [comment]
fixed
