### ISSUE TITLE
Open Monster Corpse

### ISSUE THREAD

**Issue by Kowzys** [opentibiabr/otservbr-global-archived#765]
Hello erveryone,

Today I found a small bug that can't open the Worm Priestess Body (ID: 23470, 23471)
nor does the message "you cannot use this object" appear how do i fix it?

**Comment by Lycanzito** [comment]
they're working fine..

![image](https://user-images.githubusercontent.com/52710697/68986583-8ce38f80-07ff-11ea-9570-3ee3d4cb0288.png)

problably not using the correct items.xml + items.otb

**Comment by dudantas** [comment]
Please make sure you are using the clean base without modification before opening issue.
