### ISSUE TITLE
Error while compiling on ubuntu 14.04

### ISSUE THREAD

**Issue by mattos123** [opentibiabr/otservbr-global-archived#767]
```
/OTServBR-Global/src/luascript.h:25:18: error: missing binary operator before token "("
 #if __has_include("luajit/lua.hpp")
                  ^
make[2]: *** [CMakeFiles/tfs.dir/src/actions.cpp.o] Error 1
make[1]: *** [CMakeFiles/tfs.dir/all] Error 2
make: *** [all] Error 2
```

i got this error while compiling on ubuntu 14.04 lts(on 16.04 lts i dont get the error while compiling)

**Comment by MajestyOTBR** [comment]
https://forums.otserv.com.br/index.php?/forums/topic/168882-erro-compilação-otbr-global/

**Comment by MajestyOTBR** [comment]
Ops, wrong link...

**Comment by majestyotbr** [comment]
https://forums.otserv.com.br/index.php?/forums/topic/168921-linux-erro-ao-compilar-otservbr-global-12x/

**Comment by MajestyOTBR** [comment]
"Thank you."
