### ISSUE TITLE
Server won't run after compile ubuntu 14.04

### ISSUE THREAD

**Issue by mattos123** [opentibiabr/otservbr-global-archived#769]
```
 ./tfs
The OTServBR - Global - Version: (Based on TFS 1.3)
Compiled with: GNU C++ version 4.8.4
Compiled on Nov 18 2019 00:16:18 for platform x64

Special Credits for: OTServBR Team and Contributors, OTXServer (Mattyx Gomez) and The Forgotten Server Developers.
Visit our forum for updates, support, and resources: https://forums.otserv.com.br/
Link of repository: https://github.com/opentibiabr/OTServBR-Global/
List of contributors: https://github.com/opentibiabr/OTServBR-Global/graphs/contributors

>> Loading config: config.lua
terminate called after throwing an instance of 'std::runtime_error'
  what():  Missing RSA private key header.
Aborted (core dumped)

```

after compiling i get this message when runing tfs

**Comment by majestyotbr** [comment]
You need this archive on the folder:
https://github.com/opentibiabr/OTServBR-Global/blob/develop/key.pem

Btw, you could have answered in another issue even closed.

Please, stop doing issues for the troubles you are having with the server. The issue tracker isn't a support forum.

Download full repository and try again.

**Comment by MajestyOTBR** [comment]
Btw, you could have answered in another issue even closed

**Comment by MajestyOTBR** [comment]
Please, stop doing issues for the troubles you are having with the server. The issue tracker isn't a support forum.

**Comment by MajestyOTBR** [comment]
Download full repository and try again.

**Comment by MajestyOTBR** [comment]
"Thank you."
