### ISSUE TITLE
[Quest] The Hunt for the Sea Serpent

### ISSUE THREAD

**Issue by omarcopires** [opentibiabr/otservbr-global-archived#77]
Não é possível usar as iscas no guindaste Não há um teleport que te leva até o topo do mastro para poder utilizar o telescópio. Há um monte de teleports espalhados como atalho, fazendo com que você pule boa parte da quest e vá direto ao fundo do mar.

source:http://tibia.wikia.com/wiki/The_Hunt_for_the_Sea_Serpent_Quest

**Comment by dudantas** [comment]
Scripts nonexistent or incomplete, revision needed
Need to change the quest

**Comment by dudantas** [comment]
Moving alls issues of the quests for one unique issue!
