### ISSUE TITLE
Autoloot not Run

### ISSUE THREAD

**Issue by fabianofvd** [opentibiabr/otservbr-global-archived#771]
would it be possible to enable client autoloot?

**Comment by lBaah** [comment]
There is no "autoloot".
Quickloot should be scripted.

**Comment by htc16** [comment]
Tem autoloot?

**Comment by vagnerkuntz** [comment]
Não possui.

**Comment by htc16** [comment]
Puts que chato, estou tentando colocar mas não consigo, acho que não sou tao expert em programação.

Mas de resto, esse projeto é muito bom, ótima iniciativa!

**Comment by majestyotbr** [comment]
You can use this modal autoloot that was removed from the base.

Autoloot code: https://github.com/opentibiabr/otservbr-global/commit/85f92ff99bc9363883a7c84091efc48b494ca13b

Autoloot Talkactions:
https://github.com/opentibiabr/otservbr-global/blob/6ad2f75c116be09dd09ff5f70ff9af5a300d00e1/data/talkactions/scripts/player/add_autoloot.lua
https://github.com/opentibiabr/otservbr-global/blob/6ad2f75c116be09dd09ff5f70ff9af5a300d00e1/data/talkactions/scripts/player/autoloot.lua

Talkactions.xml:
`<talkaction words="!autoloot" separator=" " script="player/autoloot.lua"/>`

`<talkaction words="!add" separator=" " script="player/add_autoloot.lua" />`

The quickloot should be scripted.
