### ISSUE TITLE
Roshamuul Quest / Uper/lower/Morax

### ISSUE THREAD

**Issue by ronyxz** [opentibiabr/otservbr-global-archived#779]
**Hi, i think you can add full roshamuul..**
I'm frustrated because serv not have this quest
This quest are fun [...]

**Links**
https://www.tibiawiki.com.br/wiki/Roshamuul_(Lower_Roshamuul)_Quest
https://www.tibiawiki.com.br/wiki/Roshamuul_Quest
https://tibia.fandom.com/wiki/Roshamuul_Quest/Spoiler

**Additional context**
i think you can add this in future, thank you so much for serv :+1:

**Comment by enzerah** [comment]
feel free to help and make a pr !

**Comment by majestyotbr** [comment]
Added to #726
