### ISSUE TITLE
[Quest] The Gravedigger of Drefia

### ISSUE THREAD

**Issue by omarcopires** [opentibiabr/otservbr-global-archived#78]
Vol.2, Ch.4: Ashes To Ashes / Cinder Sparks / A Taste Of Ashes Não consegue usar o giz(chalk) na chama roxa para obter as cinzas da sombra. Não consegue prosseguir com a quest após essa parte.

02:50 You see a strange fire. Item ID: 21430, Action ID: 4637 Decays to: 21431 Position: 32983, 32376, 11
source:http://tibia.wikia.com/wiki/The_Gravedigger_of_Drefia_Quest

**Comment by dudantas** [comment]
Needs to be tested

**Comment by dudantas** [comment]
Moving alls issues of the quests for one unique issue!
