### ISSUE TITLE
"cautious monsters"

### ISSUE THREAD

**Issue by Lycanzito** [opentibiabr/otservbr-global-archived#782]
Monstros cautelosos..
Eles evitam passar por fields.
Explicação: Monstros como "demon", não deveriam ter medo/receio de passar por uma energy field.
deveriam simplesmente passar por cima, e chegar até o player.
Mas.. o que se vê , é que os monstros ficam com medo da field, e tentam passar pelos sqms vagos, para não tomar dano.

Vídeo explicativo:
https://www.youtube.com/watch?v=OKohlC-Bl64

**Comment by lBaah** [comment]
```
		<flag canwalkonenergy="0" />
		<flag canwalkonfire="0" />
		<flag canwalkonpoison="0" />
```

**Comment by Lycanzito** [comment]
> ```
> 		<flag canwalkonenergy="0" />
> 		<flag canwalkonfire="0" />
> 		<flag canwalkonpoison="0" />
> ```

Se colocar 0, fica pior ainda a situação..
kkkk


![image](https://user-images.githubusercontent.com/52710697/70206090-2b7b5600-1705-11ea-8da4-32d6a29c8961.png)

**Comment by Lycanzito** [comment]
O problema é que o Demon, com 
```
<flag canwalkonenergy="1" />
<flag canwalkonfire="1" />
<flag canwalkonpoison="1" />
```
Dessa maneira, ele PASSA pelo energy, MAAAAAAS, ele evita ao máximo passar por ele, como demonstrado no video.
com a opção que vc sugeriu, ele simplesmente fica lá parado, até ser atacado.

**Comment by travisani** [comment]
Tem que alterar uma coisa em monsters.cpp na source, vou verificar o que eu fiz e posto.

**Comment by Lycanzito** [comment]
> Tem que alterar uma coisa em monsters.cpp na source, vou verificar o que eu fiz e posto.

ok, muito obrigado <3

**Comment by Lycanzito** [comment]
> Tem que alterar uma coisa em monsters.cpp na source, vou verificar o que eu fiz e posto.

alguma novidade?=x

**Comment by cadugtx** [comment]
estou com esse problema também.
salve lycan :D

**Comment by Lycanzito** [comment]
> estou com esse problema também.
> salve lycan :D

Salve :-) 
se alguem tiver uma solução , por favor disponibilize :/

**Comment by vankk** [comment]
Try [replace thoses line](https://github.com/opentibiabr/otservbr-global/blob/develop/src/tile.cpp#L542-L558) with 
```cpp
if (field && !field->isBlocking()) {
	CombatType_t combatType = field->getCombatType();

	//There is 3 options for a monster to enter a magic field
	if (!(monster->isImmune(combatType) || monster->canWalkOnFieldType(combatType) || monster->getIgnoreFieldDamage())) {
		//1) Monster is able to walk over field type
		//2) Monster is already afflicated by this type of condition
		//3) Being attacked while random stepping will make it ignore field damages
		return RETURNVALUE_NOTPOSSIBLE;
	}
}
```

**Comment by Lycanzito** [comment]
Didnt work here. Only errors come from these changes T.T

**Comment by Lycanzito** [comment]
> Try [replace thoses line](https://github.com/opentibiabr/otservbr-global/blob/develop/src/tile.cpp#L542-L558) with
> 
> ```c++
> if (field && !field->isBlocking()) {
> 	CombatType_t combatType = field->getCombatType();
> 
> 	//There is 3 options for a monster to enter a magic field
> 	if (!(monster->isImmune(combatType) || monster->canWalkOnFieldType(combatType) || monster->getIgnoreFieldDamage())) {
> 		//1) Monster is able to walk over field type
> 		//2) Monster is already afflicated by this type of condition
> 		//3) Being attacked while random stepping will make it ignore field damages
> 		return RETURNVALUE_NOTPOSSIBLE;
> 	}
> }
> ```

Infelizmente, mesmo erro ocorrendo.

**Comment by Lycanzito** [comment]
Consegui essa correção, de outro repositório, poderiam abrir um pull request? eu não sei fazer :(

https://github.com/otland/forgottenserver/pull/2809


Obrigado, ao subirem, por gentileza fechar o tópico <3 

@MajestyOTBR @dudantas

**Comment by dudantas** [comment]
Valeu por avisar @Lycanzito vamos puxar para cá.
