### ISSUE TITLE
Skills Reduction (Pixie)

### ISSUE THREAD

**Issue by ghost** [opentibiabr/otservbr-global-archived#785]
When Pixie uses debuff the skills are going to 65k
Allowing even a Paladin using a knife with skills 10 to hit kill a Orshabaal

It is as if it decreases more than you own and so goes to the maximum value.

**pixie skill reducer.lua** 

local combat = Combat()
combat:setParameter(COMBAT_PARAM_EFFECT, CONST_ME_PIXIE_EXPLOSION)

local condition = Condition(CONDITION_ATTRIBUTES)
condition:setParameter(CONDITION_PARAM_TICKS, 6000)
condition:setParameter(CONDITION_PARAM_SKILL_DISTANCE, -70)
condition:setParameter(CONDITION_PARAM_SKILL_SHIELD, -70)
condition:setParameter(CONDITION_PARAM_SKILL_MELEE, -70)

local area = createCombatArea(AREA_CIRCLE2X2)

combat:setArea(area)
combat:addCondition(condition)

function onCastSpell(creature, var)
	return combat:execute(creature, var)
end

![image](https://user-images.githubusercontent.com/42786694/70944707-639e6500-2032-11ea-9fde-8c54bf942b57.png)

**Comment by meandrolenezes** [comment]
![image](https://user-images.githubusercontent.com/42786694/70944403-c2afaa00-2031-11ea-8527-c3bca16211de.png)

**Comment by ghost** [comment]
I looked at similar skills and made this correction, please confirm if it was the correct way (and if it is do a pr)
Now it's reducing 70% (remaining 30% of skills)

local combat = Combat()
combat:setParameter(COMBAT_PARAM_EFFECT, CONST_ME_PIXIE_EXPLOSION)

local condition = Condition(CONDITION_ATTRIBUTES)
condition:setParameter(CONDITION_PARAM_TICKS, 6000)
condition:setParameter(CONDITION_PARAM_SKILL_DISTANCEPERCENT, 30)
condition:setParameter(CONDITION_PARAM_SKILL_SHIELDPERCENT, 30)
condition:setParameter(CONDITION_PARAM_SKILL_MELEEPERCENT, 30)

local area = createCombatArea(AREA_CIRCLE2X2)

combat:setArea(area)
combat:addCondition(condition)

function onCastSpell(creature, var)
    return combat:execute(creature, var)
end

**Comment by gerotib** [comment]
Yeah, that was the problem, I will create pr for this.

**Comment by ghost** [comment]
Thank you, I read all other skills reducers found in spells, no other problem!
