### ISSUE TITLE
Unique Itens Bug

### ISSUE THREAD

**Issue by ghost** [opentibiabr/otservbr-global-archived#787]
**Describe the bug**
Products that should be unique can be moved through containers.

**To Reproduce**
1. Open store and buy an exercise weapon
2. Move the bag to the floor (should not come in a bag)
3. Now other players can take it, this goes for all equipment that comes in containers.

**Expected behavior**
Should receive only blocked item (unique)

**Screenshots**
![image](https://user-images.githubusercontent.com/42786694/70948600-8c2a5d00-203a-11ea-867f-c0731e2a53ec.png)
![image](https://user-images.githubusercontent.com/42786694/70948881-3a360700-203b-11ea-85b9-2de41486d2ee.png)

Note:
• NPC's exercise weapons goes into the backpack and can be moved the same way.
• The funny thing is, I can't move a unique item to depot, but I can move them through the bags.

**Comment by majestyotbr** [comment]
https://github.com/opentibiabr/otservbr-global/commit/3cc9d0102a210d4d6b8f19db2d32ce3426f031af
