### ISSUE TITLE
Exercise Dummy "Store" bug

### ISSUE THREAD

**Issue by Lycanzito** [opentibiabr/otservbr-global-archived#790]
is possible to move it, while someone is training.

![image](https://user-images.githubusercontent.com/52710697/71284014-82597000-2340-11ea-9de3-bbd768d07a05.png)

**Comment by smowking** [comment]
Its not a bug. In global if you move the trainining dummy when anyone is training, only stop training.

**Comment by Lycanzito** [comment]
> Its not a bug. In global if you move the trainining dummy when anyone is training, only stop training.

The bug is that: The "effect" is still on the screen, and the player is still training.

Even after someone move the dummy.

**Comment by lBaah** [comment]
Thats really matter. We are only checking if the player has moved, but not if the dummy as moved. We'll have to check if the dummy has moved from position also.
