### ISSUE TITLE
NEW summons flag disappears

### ISSUE THREAD

**Issue by EleanorRigby1** [opentibiabr/otservbr-global-archived#793]
**Describe the bug**
I am using the most recent version of OTBR and the summons that only each vocation has have an error in the flag that indicates that it is a summon, when you go up or down the stairs the flag disappears, and will only reappear if you reconnect.

**To Reproduce**
1. Use the spell of your summon, of your vocation.
2. Go up some stairs or down, it also happens when you enter a teleport.

After this the flag disappeared.

 - OS: [Windows 10, Linux Debian 9]

**Comment by EleanorRigby1** [comment]
This is not corrected yet. At least on this side it didn't work

**Comment by FakeShinoda** [comment]
Yes THIS IS FIXED. do it agian.. and again until you get it work.
![wtf](https://user-images.githubusercontent.com/23365432/77861078-3cd2fb80-71e9-11ea-8408-379941e4e9b1.png)

**Comment by EleanorRigby1** [comment]
I think they confuse my issue. I referred to the new summons. ThunderGiant, Emberwing etc ...

I mention that the bug only happens on client 10, on client 12 it works without problem.

**Comment by gpedro** [comment]
client 10 is not supported anymore
