### ISSUE TITLE
Market 

### ISSUE THREAD

**Issue by Joaosudo** [opentibiabr/otservbr-global-archived#796]
O bug consiste em o jogador coloca um item a no makert para **compra** e fica offline
agora outro jogador irá no item e irá vende para este jogador. 
ele irá receber o dinheiro do jogador  e o item irá sumi mais o jogador que está offline não vai recebe o item e o dinheiro irá sai da conta dele

The bug is that the player puts an item on makert for purchase and goes offline
Now another player will go on the item and will sell to this player.
he will receive the player's money and the item will disappear but the player who is offline will not receive the item and the money will go out of his account

**Comment by Lycanzito** [comment]
Realmente.. Testei e o bug é verdadeiro.

Temos um grande problema ai.. =/

**Comment by vankk** [comment]
It is possible that you create a video explaning @Lycanzito ?

**Comment by Lycanzito** [comment]
> It is possible that you create a video explaning @Lycanzito ?

Sent

**Comment by Costallat** [comment]
@Lycanzito @Joaosudo

Please test #800 , also re-test using bank money

Tks
