### ISSUE TITLE
Market Imbuiment Item

### ISSUE THREAD

**Issue by Lycanzito** [opentibiabr/otservbr-global-archived#797]
Itens que já foram imbuidos anteriormente, mesmo com o imbuement removido, 
não são negociáveis no market.

**Comment by cadugtx** [comment]
Estou com este problema também, preciso falar com você lycan, se possivel

**Comment by Lycanzito** [comment]
> Estou com este problema também, preciso falar com você lycan, se possivel

opa parceiro, Lycanzito#8205 meu discord
