### ISSUE TITLE
Unwrap Itens + House Bugs (3 in 1 )

### ISSUE THREAD

**Issue by Lycanzito** [opentibiabr/otservbr-global-archived#798]
Esta dando para dar Unwrap, com o item dentro da inbox ou até mesmo dentro de uma Backpack.

![image](https://user-images.githubusercontent.com/52710697/71551854-563c8f80-29cf-11ea-8216-d9bf0a54589c.png)
![image](https://user-images.githubusercontent.com/52710697/71551860-648aab80-29cf-11ea-8da4-143936c7dc25.png)
![image](https://user-images.githubusercontent.com/52710697/71551861-6c4a5000-29cf-11ea-9bdf-095e394486ab.png)
![image](https://user-images.githubusercontent.com/52710697/71551863-73715e00-29cf-11ea-8c1c-e43bd84a4181.png)

Também esta sendo possível retirar os itens de dentro da casa
![image](https://user-images.githubusercontent.com/52710697/71551883-bb908080-29cf-11ea-85cf-218833e36637.png)
![image](https://user-images.githubusercontent.com/52710697/71551885-c0edcb00-29cf-11ea-9a64-b92a12cca74a.png)

Também ao dar leavehouse, os itens da store ficam na casa.

![image](https://user-images.githubusercontent.com/52710697/71551896-dc58d600-29cf-11ea-8d14-179119de131f.png)

**Comment by gerotib** [comment]
I tried to fix this leave house bug (wrapable items not being sent to inbox like other items), but I couldnt get anywhere. 
[Theres a part of code](https://github.com/opentibiabr/otservbr-global/blob/develop/src/house.cpp#L224-L262) if anyone would like to take a look.
