### ISSUE TITLE
Exit Bug ?

### ISSUE THREAD

**Issue by Lycanzito** [opentibiabr/otservbr-global-archived#799]
Ao Exitar um personagem, ele deve cair em 60 segundos, isso não acontece.

![image](https://user-images.githubusercontent.com/52710697/71551932-55582d80-29d0-11ea-96c7-a5dc3e3d847f.png)

![image](https://user-images.githubusercontent.com/52710697/71551941-889abc80-29d0-11ea-9e8b-2a459c46b8f7.png)

continuando logado por vários e vários minutos.
![image](https://user-images.githubusercontent.com/52710697/71551946-9fd9aa00-29d0-11ea-9fed-63780d1cc350.png)

**Comment by majestyotbr** [comment]
Testei o exit aqui e o personagem desloga em 60 segundos. Bug não confirmado.
