### ISSUE TITLE
Pits of Inferno

### ISSUE THREAD

**Issue by omarcopires** [opentibiabr/otservbr-global-archived#8]
Remover o buraco(32795, 32335, 8) porque já tem um buraco oculto na posição(32794, 32334, 8). Faltando a lápide(32791, 32333, 9) para derramar o blood e ser teleportado para o andar de baixo.
Remover o meio da ponte(32801, 32336, 11) para que, após usar o óleo e puxar a alavanca, a ponte fique completa.

Na sala das vocações(32829, 32333, 11), ativar as 4 paredes de fogo do caminho. Na sala das alavancas(15 alavancas), a pedra que bloqueia o caminho não existe, fazendo assim essa parte da quest totalmente inútil.

Faltando o corpo de um orc escondendo a alavanca correta(32821, 32346, 13).

O trono(32717, 32381, 13) não está sendo ativado quando se anda em cima, ao invés, está apenas teleportando, fazendo com que a última barreira impeça você de ir para a parte final da POI.

source:http://tibia.wikia.com/wiki/The_Pits_of_Inferno_Quest

**Comment by Raphaellb** [comment]
@marcomoa @eduardodantas95 can one of you guys update realmap-spawn.xml with the following for the missing 2 Dragon Lords in final room of naginata quest. The wiki states a longer respawn, but you dont have to use 3600.

	<spawn centerx="32348" centery="32070" centerz="12" radius="3">
		<monster name="Dragon Lord" x="1" y="0" z="12" spawntime="3600" />
	</spawn>
	<spawn centerx="32347" centery="32066" centerz="12" radius="3">
		<monster name="Dragon Lord" x="1" y="0" z="12" spawntime="3600" />
	</spawn>

**Comment by dudantas** [comment]
fixed 
o bug  "O trono(32717, 32381, 13) não está sendo ativado quando se anda em cima, ao invés, está apenas teleportando, fazendo com que a última barreira impeça você de ir para a parte final da POI." 

ta confirmado? olhei aqui nos scripts e tá tudo normal, aparentemente
