### ISSUE TITLE
[Quest] The Shattered Isles 

### ISSUE THREAD

**Issue by omarcopires** [opentibiabr/otservbr-global-archived#80]
Os portais que garante acesso para Talahu e Malada já estão free sem precisar que você complete o achievement primeiro. Accesso para Talahu - Após colocar os 4 cogumelos diferentes nos basins para o sacrifício, você não consegue acesso para o portal.

Ferumbras Citadel tem acesso livre para qualquer um. Você deve ganhar a permissão(pagando taxa de 500 gold) para poder entrar no Citadel através do NPC Zoltan.

source:http://tibia.wikia.com/wiki/The_Shattered_Isles_Quest

**Comment by dudantas** [comment]
Moving alls issues of the quests for one unique issue!
