### ISSUE TITLE
Login Screen ISSUE

### ISSUE THREAD

**Issue by Lycanzito** [opentibiabr/otservbr-global-archived#801]
Sometimes when you logout from a character, some characters get "over" the others, also the "getaddons" isnt working properly
![image](https://user-images.githubusercontent.com/52710697/71607378-b2322000-2b57-11ea-936e-6387aa75f98b.png)
Also, The Info from the characters only be "loaded" after you log in with your account again.

**Comment by majestyotbr** [comment]
![thinking](https://user-images.githubusercontent.com/32709570/71607418-194fd480-2b58-11ea-8aae-35cdd4490b49.png)

**Comment by lBaah** [comment]
Looks like you have modified your login.php.
Not an issue related to this repo.

![image](https://user-images.githubusercontent.com/40009702/71614010-3ef4d200-2b88-11ea-8818-17fb4e91c14b.png)
Working fine.

**Comment by Lycanzito** [comment]
> Looks like you have modified your login.php.
> Not an issue related to this repo.
> 
> ![image](https://user-images.githubusercontent.com/40009702/71614010-3ef4d200-2b88-11ea-8818-17fb4e91c14b.png)
> Working fine.

Try with more than 4 characters on the same account, problably will get the same problem :-)

Also, the getaddons arent working or it does?

**Comment by Lycanzito** [comment]
Also, Added + 1 "bug"

**Comment by lBaah** [comment]
This is not related to this repo.
Check your login.php

**Comment by majestyotbr** [comment]
This is not related to this repository.
Check your login.php.

![loginscreen](https://user-images.githubusercontent.com/32709570/71637947-9fd7e500-2c30-11ea-9f38-0c9c823607ae.png)

**Comment by Lycanzito** [comment]
> This is not related to this repository.
> Check your login.php.
> 
> ![loginscreen](https://user-images.githubusercontent.com/32709570/71637947-9fd7e500-2c30-11ea-9f38-0c9c823607ae.png)

Sorry for the delay, Where should I find these changes? and these files? such login.php and the others of the Website stuff?
