### ISSUE TITLE
Quick looting

### ISSUE THREAD

**Issue by vescape12** [opentibiabr/otservbr-global-archived#802]
Hi

Is the quick looting system supposed to be working?

I can't get it working, compiled the latest release and using tibia 12 client.

Thanks in advance

**Comment by majestyotbr** [comment]
Quick looting should be scripted.

**Comment by vescape12** [comment]
Thank you for your fast reply

I am new to this so sorry for not understanding all terms, do you mean I have to do scripting myself to get it working?

**Comment by majestyotbr** [comment]
This is a open-source project. If anyone wants, feel free to contribute.

**Comment by vescape12** [comment]
It's a really nice project. I'll see if I can learn some and contribute.
