### ISSUE TITLE
Analyzer + Loot bug

### ISSUE THREAD

**Issue by skovdota** [opentibiabr/otservbr-global-archived#804]
The analyzer is not counting how many creatures were killed, let alone when adding an !Autoloot and pulling gold and items, it is not being counted in any analyzer.

If I drag the loot to the backpack, now the loot has been counted in the analyzer.

anyone check this?
Thanks in advance

**Comment by lBaah** [comment]
There are no support for autoloot.

**Comment by mattyx14** [comment]
yep autoloot is modal
