### ISSUE TITLE
Redskull don't drop backpack and itens

### ISSUE THREAD

**Issue by skovdota** [opentibiabr/otservbr-global-archived#805]
Hello, again!
I was testing some things, and when redskull dies to junk or player is not dropping all items and backpack as it should.

Please, someone else analyzes.

**Comment by majestyotbr** [comment]
Tested, unconfirmed.

**Comment by mattyx14** [comment]
check if your account no are admin

**Comment by majestyotbr** [comment]
With a normal character works normally.
