### ISSUE TITLE
The NPCs have disappeared

### ISSUE THREAD

**Issue by EleanorRigby1** [opentibiabr/otservbr-global-archived#815]
I download the most current version of OtservBr and the NPCs in RME are not loaded. I checked the spawn.xml and it has no NPC, I tried to search for NPC with CTRL + F but they were all removed.

 - OS: [Windows]
 - Version: [10]

**Comment by Costallat** [comment]
The NPCs are now loaded when the server is started

**Comment by majestyotbr** [comment]
https://github.com/opentibiabr/otservbr-global/blob/develop/data/lib/miscellaneous/npcsSpawnList.lua

Before create issue here, first understand the server, consult the files.
