### ISSUE TITLE
compile error?

### ISSUE THREAD

**Issue by cocaocla** [opentibiabr/otservbr-global-archived#816]
root@vps775208:/home/ots/build# cmake ..
-- The C compiler identification is GNU 4.9.2
-- The CXX compiler identification is GNU 4.9.2
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
CMake Error at CMakeLists.txt:41 (message):
  Insufficient gcc version.  It has to be equal or greater than version 5.X

-- Configuring incomplete, errors occurred!
See also "/home/ots/build/CMakeFiles/CMakeOutput.log".
Whats is problem?

**Comment by Costallat** [comment]
Insufficient **gcc** **version**. It has to be equal or greater than version 5.X

**Comment by cocaocla** [comment]
could you help me update it

**Comment by Costallat** [comment]
https://github.com/opentibiabr/otservbr-global/issues/767

https://github.com/opentibiabr/otservbr-global/issues/682

https://github.com/opentibiabr/otservbr-global/issues/675

**Comment by cocaocla** [comment]
im have next problem

root@vps775208:/home/ots/build# make
[  1%] Building CXX precompiled header cotire/tfs_CXX_prefix.hxx.gch
In file included from /home/ots/build/cotire/tfs_CXX_prefix.cxx:4:0,
                 from /home/ots/build/cotire/tfs_CXX_prefix.hxx:4:
/home/ots/src/otpch.h:54:27: fatal error: spdlog/spdlog.h: No such file or directory
 #include <spdlog/spdlog.h>
                           ^
compilation terminated.
CMake Error at cmake/FindCotire.cmake:1783 (message):
  cotire: error 1 precompiling /home/ots/build/cotire/tfs_CXX_prefix.hxx.
Call Stack (most recent call first):
  cmake/FindCotire.cmake:3332 (cotire_precompile_prefix_header)


CMakeFiles/tfs.dir/build.make:62: recipe for target 'cotire/tfs_CXX_prefix.hxx.gch' failed
make[2]: *** [cotire/tfs_CXX_prefix.hxx.gch] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/tfs.dir/all' failed
make[1]: *** [CMakeFiles/tfs.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by Costallat** [comment]
You don't have the spdlog library

https://github.com/opentibiabr/otservbr-global/wiki/Compiling-on-Ubuntu-Debian

**Comment by cocaocla** [comment]
root@vps775208:~# apt -y install git cmake build-essential liblua5.2-dev libgmp3-dev libmysqlclient-dev libboost-system-dev libboost-iostreams-dev libboost-filesystem-dev libpugixml-dev libcrypto++-dev libspdlog-dev
Reading package lists... Done
Building dependency tree
Reading state information... Done
Package libmysqlclient-dev is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'libmysqlclient-dev' has no installation candidate
this problem :/
What is problem?

**Comment by Costallat** [comment]
https://askubuntu.com/questions/1043900/package-libmysqlclient-dev-has-no-installation-candidate

**Comment by cocaocla** [comment]
Thank you, compilation! you are master
