### ISSUE TITLE
Tiles rookgaard

### ISSUE THREAD

**Issue by htc16** [opentibiabr/otservbr-global-archived#818]
Os tiles de P.A e level 02 da ponte saída, cidade de rookgaard, ambos não estão funcionando, ou seja, mesmo quem não tem p.a passa na ponte e mesmo quem esta level 01 passa na ponte para fora da cidade.

**Comment by majestyotbr** [comment]
Ponte saída (level 2) está normal aqui.
![saídalevel2](https://user-images.githubusercontent.com/32709570/72858019-2dda4500-3c9e-11ea-96ed-3c19ca091659.png)


Ponte premium:
Em **data/movements/scripts/rookgaard**, crie um arquivo **premiumbridge.lua**:
```
local failPosition = Position(32066, 32192, 7)

function onStepIn(creature, item, position, fromPosition)
	local player = creature:getPlayer()
	if not player then
		return true
	end

	if player:isPremium() then
		return true
	end

	failPosition:sendMagicEffect(CONST_ME_MAGIC_BLUE)
	player:teleportTo(failPosition)
	return true
end
```

Depois em **data/movements/movements.xml** adicione:
`<movevent event="StepIn" actionid="50241" script="rookgaard/premiumbridge.lua" />`

**Comment by htc16** [comment]
Muito bom o projeto, nota 10!
