### ISSUE TITLE
Demona Ring Quest

### ISSUE THREAD

**Issue by omarcopires** [opentibiabr/otservbr-global-archived#82]
Faltando as recompensas(Energy Ring, Stealth Ring) nos baús.

03:24 You see a chest (Vol:15). Item ID: 1740 Position: 32504, 31596, 14
03:24 You see a chest (Vol:15). Item ID: 1740 Position: 32515, 31596, 14
source:http://tibia.wikia.com/wiki/Demona_Ring_Quest

**Comment by gpedro** [comment]
"with the left one containing a Stealth Ring and the right one an Energy Ring"

**Comment by dudantas** [comment]
fixed

soon will be up
