### ISSUE TITLE
Oberon Lever

### ISSUE THREAD

**Issue by EleanorRigby1** [opentibiabr/otservbr-global-archived#821]
The lever of the Grand Master Oberon works only 1 time, that is, it says that you can do it in 20 hours but after those 20 hours it still does not work.

**Comment by MajestyOTBR** [comment]
Follow the issue template when create issue here.

**Comment by EleanorRigby1** [comment]
Okay, sorry :(

**Comment by mattyx14** [comment]
I formated scrip is lite solutions

**Comment by dudantas** [comment]
Ok ... Look, if I'm not mistaken the oberon quest does not exist in the repository, so this is not a problem but missing development.

**Comment by dudantas** [comment]
Apparently the setExhaustion function (which does not exist on the server) is being used for this reason.

**Comment by dudantas** [comment]
![image](https://user-images.githubusercontent.com/8551443/75085877-68890480-550c-11ea-8d6d-06ed4deba89b.png)

The problem is that the time check is not done.

`if player:getStorageValue(Storage.TheSecretLibrary.TheOrderOfTheFalcon.OberonTimer) < os.time() then`
