### ISSUE TITLE
Premium

### ISSUE THREAD

**Issue by htc16** [opentibiabr/otservbr-global-archived#822]
Olá, estou tendo problemas com sistema premium do servidor. 

Ocorre que, através dos comandos que já havia no servidor de !buypremium, as premiuns eram todas liberadas normalmente, por X valor por X dias. 

Só que agora, qualquer pessoa que executa o comando consegue premium, mesmo sem dinheiro, inclusive, com a finalidade de testar o erro, adicionei um npc que vende premium, e acontece a mesma coisa. 

Última coisa que fiz no servidor foi atualizar as últimas scripts que foi disponibilizado aqui no github.
Estou meio sem saber o que fazer, poderiam me ajudar?

**Comment by EleanorRigby1** [comment]
I believe that it is a problem on your side and not OTBR, I successfully implemented the premium scroll system. Check your scripts well.

**Comment by htc16** [comment]
have any suggestions where i can look?
Because I already looked at everything I imagined was with this problem, from config.lua to lua scripts, I didn't find it.

**Comment by lBaah** [comment]
Use `player:removeMoneyNPC(value)` to remove money.
For example:

```
> if player:removeMoneyNpc(1000) then
> ...
> end
```
