### ISSUE TITLE
depot does not work and the wrong texture is displayed, store,

### ISSUE THREAD

**Issue by manifex30890** [opentibiabr/otservbr-global-archived#825]
I open the inbox from the depot
![depot](https://user-images.githubusercontent.com/60244156/73143214-9c9d1100-4097-11ea-8a5f-0ec990be77cc.png)
and there are wrong textures
![depo dwa](https://user-images.githubusercontent.com/60244156/73143229-c81ffb80-4097-11ea-9b01-fbfa59ef008d.png)
![depo trzy](https://user-images.githubusercontent.com/60244156/73143234-e554ca00-4097-11ea-8563-133807d08344.png)
by opening store and entering the outfit, mount section, debug client appears
![debug](https://user-images.githubusercontent.com/60244156/73143269-5e542180-4098-11ea-8891-d55aed4d1189.png)

**Comment by majestyotbr** [comment]
Very nice, create issue without information and only with images. Do you think we are prophets?

What server, client are you using, what made this happen?

**Comment by manifex30890** [comment]
I'm using client 10.
otserverbr engine

**Comment by VitorNM** [comment]
This is probably a client issue... Im using the Tibia 12 Client from https://github.com/opentibiabr/tools and nothing's wrong with it.

**Comment by majestyotbr** [comment]
Brown Bear Fur:
![image](https://user-images.githubusercontent.com/32709570/73143962-c4cc4600-407e-11ea-908b-1247084b1bb7.png)

Polar Bear Fur:
![image](https://user-images.githubusercontent.com/32709570/73143972-f34a2100-407e-11ea-8388-136a73770a15.png)

Depot Box:
![image](https://user-images.githubusercontent.com/32709570/73144027-adda2380-407f-11ea-86a8-3b442087ce5f.png)


About Store:
- The debug happens because each category on client 10 doesn't support more than 50 itens. A solution is separate mounts and houses in more categories.

To complete my answer, update your client.

**Comment by manifex30890** [comment]
on client 12 I am fine too. but I prefer client 10 and I wanted to play it, I don't really like 12 and I ask for help. it used to work normally

**Comment by manifex30890** [comment]
majesty and does your depot work normally?

**Comment by majestyotbr** [comment]
Updated my answer above.

**Comment by manifex30890** [comment]
only that I have items.otb from ots server 1.0 because on original otb otserverbr instead of door slides I had other items, addons, legi, helmets

**Comment by majestyotbr** [comment]
No, you can't use things from 1.0 on develop. The otservbr-global-1.0 is a new server, the itens are registered in ClientID.

**Comment by manifex30890** [comment]
yes, but on client 10 I don't have textures that should be with the original otb

**Comment by majestyotbr** [comment]
What textures? I'm saying you are using the wrong archive. Understand that.

The server that is working fine is here: https://github.com/opentibiabr/otservbr-global

**Comment by manifex30890** [comment]
yes i use it but with osterverbr 1.0 i have items.otb because on otserverbr i didn't have the right textures on the map

**Comment by manifex30890** [comment]
after your client update, nothing works hah

**Comment by majestyotbr** [comment]
Nothing works because you don't know how to use the things.

**Comment by manifex30890** [comment]
from 2 months ago when I have a previous customer everything worked

**Comment by manifex30890** [comment]
acch miss click

**Comment by majestyotbr** [comment]
Stop mixing the things from 1.0 and this server. 

It's so difficult to understand?

**Comment by majestyotbr** [comment]
I repeat, this [server](https://github.com/opentibiabr/otservbr-global) and [tools](https://github.com/opentibiabr/tools) are working normally with the exception of some bugs.

**Comment by manifex30890** [comment]
wait I'll give you ss with original files

**Comment by majestyotbr** [comment]
I'm using original files and it's working here.

**Comment by majestyotbr** [comment]
Original means the updated repository.

**Comment by manifex30890** [comment]
otserverbr files downloaded from 3-4 hours ago are updated

**Comment by manifex30890** [comment]
![image](https://user-images.githubusercontent.com/60244156/73144214-b2b0ce80-40a3-11ea-9d19-2832282f989a.png)
Orginal files

**Comment by majestyotbr** [comment]
Downloaded again [server](https://github.com/opentibiabr/otservbr-global) and [tools](https://github.com/opentibiabr/tools) and reconfigured all things.

Result:
![image](https://user-images.githubusercontent.com/32709570/73144312-70779500-4083-11ea-9e06-6670053c4126.png)

**Comment by MajestyOTBR** [comment]
Very funny.

**Comment by manifex30890** [comment]
wait 3 minutes to download again

**Comment by manifex30890** [comment]
![image](https://user-images.githubusercontent.com/60244156/73144635-09200c00-40a8-11ea-88f1-e23a0d5a64f0.png)
I downloaded the same problem again, tools, engine

**Comment by majestyotbr** [comment]
It's weird only you with the problem. You are still doing something wrong.

**Comment by majestyotbr** [comment]
Server: https://github.com/opentibiabr/otservbr-global
Compiled Server: https://ci.appveyor.com/project/opentibiabr/otservbr-global
Database: https://github.com/opentibiabr/otservbr-global/blob/develop/schema.sql
Tools: https://github.com/opentibiabr/tools

**Comment by manifex30890** [comment]
but I use what you gave so stupid I am not.

**Comment by manifex30890** [comment]
it does not work

**Comment by Costallat** [comment]
@manifex30890 you have to delete everything and use only stuff from @MajestyOTBR links, you can't mix 1.0 repository with otservbr repository, they are not compatible, the same for the client, you have to use things **ONLY** from **otservbr-global**

**Comment by dudantas** [comment]
You need to download everything again from the otservbr-global repository (links Majesty sent above)
It is obvious that you mixed the two repositories (1.0 is used client id and otservbr (develop) uses server id.
