### ISSUE TITLE
OTClientV8 Features

### ISSUE THREAD

**Issue by OTCv8** [opentibiabr/otservbr-global-archived#826]
Hey,

OTClientV8 will soon fully support 11.00 protocol, including prey system. 
https://github.com/OTCv8/otclientv8
I'm ready to make pull request with some cool otcv8 features like new walking system and extended aware range, everything will be optional and won't affect cipsoft client. Will you accept pull request with such things?

Here's an example of new walking system:
https://www.youtube.com/watch?v=05PAFF58Dzs
https://www.youtube.com/watch?v=HxT0jARByUs
https://www.twitch.tv/videos/539989882?t=2h42m2s

Can be testes on retrocores and kasteria currently, soon other servers will support it. It will also include fixes for path finding.

**Comment by mattyx14** [comment]
Add imbuid window is missing and dialy reward

**Comment by OTCv8** [comment]
Planned for 2.1 release (~2-3weeks)

**Comment by majestyotbr** [comment]
Your otclient is a closed source project, i disagree to link that with a open source server. 

My answer is no.

**Comment by Costallat** [comment]
Hi @OTCv8, thanks for that but the idea of the project is to keep everything open source so everyone can contribute with the project and we can have a single OT base with everything working. If we accept your changes users that use your client will have 'buffs' that others will not.

I understand that you spent a lot of effort doing your client and don't want to open source it.

The OT community today is full of leecher that only wants to copy and sell things, and keep things 'closed source'(servers fixes, map fixes, etc) and the idea is to 'ban/erase' those people and try to create a 'real community' where people helps to create a good base so people can use it to create their custom servers and contribute to improve the base.

But today all that we have are 'copy and sell dudes', so it's better to keep your client 'source closed' until we have a better community.

BR,

**Comment by OTCv8** [comment]
Ok, if you change your mind, let me know
