### ISSUE TITLE
Crystal Wand Quest

### ISSUE THREAD

**Issue by omarcopires** [opentibiabr/otservbr-global-archived#83]
O baú está dando de recompensa 6 sudden death runes ao invés da Silver Rune Emblem (Sudden Death)

03:49 You see a chest. It weighs 124.20 oz. Item ID: 1740, Action ID: 2000, Unique ID: 9143 Position: 32481, 31611, 15
source:http://tibia.wikia.com/wiki/Crystal_Wand_Quest

**Comment by dudantas** [comment]
fixed

soon will be up
