### ISSUE TITLE
store images Not work?!

### ISSUE THREAD

**Issue by manifex30890** [opentibiabr/otservbr-global-archived#832]
Hello, after uploading store images, and assigning a link does not display them in the client

**Comment by majestyotbr** [comment]
The store images work. Configure correctly in your server.
https://forums.otserv.com.br/index.php?/forums/topic/168735-gesioraacmyaacznoteaac-store-para-tibia-12/

**Comment by manifex30890** [comment]
Dont Work :/ my server nginx blocked acces page /images/store/ WTF?

**Comment by majestyotbr** [comment]
Google and search how to use nginx.

**Comment by Sargitarium** [comment]
Work fine to me too..... all img.....

**Comment by manifex30890** [comment]
very strange because I don't load in client 10 or 12. I know how to use nginx.

**Comment by ivansho92** [comment]
my store is not working, we can't see the pictures.

**Comment by majestyotbr** [comment]
Update your gamestore.lua and the images, the store is working normally here.

**Comment by ivansho92** [comment]
> Update your gamestore.lua and the images, the store is working normally here.

already, uploaded but still not working bro :C

**Comment by majestyotbr** [comment]
Configure correctly in: https://github.com/opentibiabr/otservbr-global/blob/develop/config.lua.dist#L109

`coinImagesURL = "http://127.0.0.1/images/store/"`

And change for your ip or domain.
