### ISSUE TITLE
Bug in pets?

### ISSUE THREAD

**Issue by ivansho92** [opentibiabr/otservbr-global-archived#834]
i have this problem with the pets, don't care if we're in party, the pet can hit another players, without pk, so, how i can fix this?

**Comment by majestyotbr** [comment]
Repeated, #326

**Comment by ivansho92** [comment]
> Repeated, #326

but still, i can't see the fix or need to wait?

**Comment by majestyotbr** [comment]
Feel free to fix and send a PR.

**Comment by ivansho92** [comment]
> Feel free to fix and send a PR.


It is not my intention to make you feel bad, sorry, thank you

**Comment by majestyotbr** [comment]
We are trying to fix the things, but we need the collaboration of the users too.

**Comment by ivansho92** [comment]
> We are trying to fix the things, but we need the collaboration of the users too.

ohh understand, but i'm nor good in this scripts haha only fixing easy things like loot in monsters, hp, attack, etc... and a little bit of Remere but not in scripts :l

**Comment by majestyotbr** [comment]
Any contribution is welcome.

**Comment by ivansho92** [comment]
> Any contribution is welcome.

if i found another problem, how i can post it?
i mean, label or what? xd

**Comment by majestyotbr** [comment]
Create a new issue, look at issues list before if doesn't exist one about the same thing.

**Comment by matheuspergher** [comment]
Hey guys. 

Does anyone have any progress on this bug? 

Thank you.
