### ISSUE TITLE
Carpet Improvement

### ISSUE THREAD

**Issue by Lycanzito** [opentibiabr/otservbr-global-archived#835]
1-
(Should be possible to see the "open carpet" in browse field");

it should be possible unwrap it under stairs , also should be possible be wrap from of doors.

![image](https://user-images.githubusercontent.com/52710697/73967805-5fd2e480-48f7-11ea-9a69-c834b95e9376.png)

![image](https://user-images.githubusercontent.com/52710697/73967848-737e4b00-48f7-11ea-8c16-78daddacd92e.png)

**Comment by dudantas** [comment]
É com todos os carpets ou apenas este aí em específico? Deixa também o ID do item sempre que for fazer um issue.

**Comment by dudantas** [comment]
![image](https://user-images.githubusercontent.com/8551443/74797359-b3efa880-52a9-11ea-909c-5e5d9ea7494e.png)

**Comment by Lycanzito** [comment]
> É com todos os carpets ou apenas este aí em específico? Deixa também o ID do item sempre que for fazer um issue.

Sim, todos os carpets, independente do ID xD

**Comment by Lycanzito** [comment]
Um colega meu conseguiu fixar o problema de "stackar" os carpets, posso mandar pra ti, e vc faz um pull request? mas os outros problemas eu não consegui resolver =/ @dudantas

**Comment by dudantas** [comment]
> Um colega meu conseguiu fixar o problema de "stackar" os carpets, posso mandar pra ti, e vc faz um pull request? mas os outros problemas eu não consegui resolver =/ @dudantas

Como te mandei a print, testei com um carpet e não bugou. Me manda o id de alguns carpets para que eu possa testar, por gentileza.

**Comment by Lycanzito** [comment]
> > Um colega meu conseguiu fixar o problema de "stackar" os carpets, posso mandar pra ti, e vc faz um pull request? mas os outros problemas eu não consegui resolver =/ @dudantas
> 
> Como te mandei a print, testei com um carpet e não bugou. Me manda o id de alguns carpets para que eu possa testar, por gentileza.

Qualquer um amigo, como ti falei..
Testa sei lá..
You see a decorated carpet.
Item ID: 29390

da para "abrir" eles, um em cima do outro e dai acontece aquele bug de entrar no chão ^.-

**Comment by dudantas** [comment]
Ata. O problema é quando usa ele dentro dele mesmo né. Não tinha entendido essa parte. Vou subir a correção mais tarde.

Me manda essa solução de stalkar os carpets.

**Comment by Lycanzito** [comment]
> Ata. O problema é quando usa ele dentro dele mesmo né. Não tinha entendido essa parte. Vou subir a correção mais tarde.
> 
> Me manda essa solução de stalkar os carpets.

Por onde ti mando?

**Comment by dudantas** [comment]
> > Ata. O problema é quando usa ele dentro dele mesmo né. Não tinha entendido essa parte. Vou subir a correção mais tarde.
> > Me manda essa solução de stalkar os carpets.
> 
> Por onde ti mando?

Pode enviar aqui mesmo. É só jogar o arquivo no comentário que ele vai anexar.

**Comment by Lycanzito** [comment]
> > > Ata. O problema é quando usa ele dentro dele mesmo né. Não tinha entendido essa parte. Vou subir a correção mais tarde.
> > > Me manda essa solução de stalkar os carpets.
> > 
> > 
> > Por onde ti mando?
> 
> Pode enviar aqui mesmo. É só jogar o arquivo no comentário que ele vai anexar.
Na real, eu arrastei  e ele disse que não suporta o formato.. '-' vou mandar ai.





local foldedCarpet = {
	[25393] = 25392,
	[25392] = 25393, --rift carpet
	[26193] = 26192,
	[26192] = 26193, --void carpet
	[26087] = 26109, --yalahahari carpet
	[26109] = 26087, --yalahahari carpet
	[26088] = 26110, --white fur carpet
	[26110] = 26088, --white fur carpet
	[26089] = 26111, --bamboo mat carpet
	[26111] = 26089, --bamboo matr carpet
	[26371] = 26363, --crimson carpet
	[26363] = 26371, --crimson carpet
	[26366] = 26372, --azure carpet
	[26372] = 26366, --azure carpet
	[26367] = 26373, --emerald carpet
	[26373] = 26367, --emerald carpet
	[26368] = 26374, --light parquet carpet
	[26374] = 26368, --light parquet carpet
	[26369] = 26375, --dark parquet carpet
	[26375] = 26369, --dark parquet carpet
	[26370] = 26376, --mable floor
	[26376] = 26370, --marble floor
	[27084] = 27092, --flowery carpet
	[27092] = 27084, --flowery carpet
	[27085] = 27093, --Colourful Carpet
	[27093] = 27085, --Colourful Carpet
	[27086] = 27094, --striped carpet
	[27094] = 27086, --striped carpet
	[27087] = 27095, --fur carpet
	[27095] = 27087, --fur carpet
	[27088] = 27096, --diamond carpet
	[27096] = 27088, --diamond carpet
	[27089] = 27097, --patterned carpet
	[27097] = 27089, --patterned carpet
	[27090] = 27098, --night sky carpet
	[27098] = 27090, --night sky carpet
	[27091] = 27099, --star carpet
	[27099] = 27091, --star carpet
	[29350] = 29351, --verdant carpet
	[29351] = 29350, --verdant carpet
	[29352] = 29353, --shaggy carpet
	[29353] = 29352, --shaggy carpet
	[29355] = 29354, --mystic carpet
	[29354] = 29355, --mystic carpet
	[29356] = 29357, --stone tile
	[29357] = 29356, --stone tile
	[29359] = 29358, --wooden plank
	[29358] = 29359, --wooden plank
	[29386] = 29387, --wheat carpet
	[29387] = 29386, --wheat carpet
	[29388] = 29389, --crested carpet
	[29389] = 29388, --crested carpet
	[29390] = 29391, --decorated carpet
	[29391] = 29390, --decorated carpet

}

function onUse(player, item, fromPosition, target, toPosition, isHotkey)
	local carpet = foldedCarpet[item.itemid]
	if not carpet then
		return false
	end

	local tile = Tile(fromPosition)

	if fromPosition.x == CONTAINER_POSITION then
		player:sendTextMessage(MESSAGE_STATUS_SMALL, "Put the item on the floor first.")
	elseif not fromPosition:getTile():getHouse() then
		player:sendTextMessage(MESSAGE_STATUS_SMALL, "You may use this only inside a house.")
	elseif tile:getItemCountById(item.itemid) == 1 then

		for k,v in pairs(foldedCarpet) do
			if tile:getItemCountById(k) > 0 and k ~= item.itemid then 
				player:sendTextMessage(MESSAGE_STATUS_SMALL, "Ja tem um tapete ai embaixo")
				return false
			end
		end

		item:transform(carpet)

	end
	return true
end

**Comment by Lycanzito** [comment]
> > > Ata. O problema é quando usa ele dentro dele mesmo né. Não tinha entendido essa parte. Vou subir a correção mais tarde.
> > > Me manda essa solução de stalkar os carpets.
> > 
> > 
> > Por onde ti mando?
> 
> Pode enviar aqui mesmo. É só jogar o arquivo no comentário que ele vai anexar.

Ele não carregava o lua.

**Comment by dudantas** [comment]
> > > > Ata. O problema é quando usa ele dentro dele mesmo né. Não tinha entendido essa parte. Vou subir a correção mais tarde.
> > > > Me manda essa solução de stalkar os carpets.
> > > 
> > > 
> > > Por onde ti mando?
> > 
> > 
> > Pode enviar aqui mesmo. É só jogar o arquivo no comentário que ele vai anexar.
> 
> Ele não carregava o lua.

Coloca aqui mesmo o código. 

Outra pergunta, você pode criar uma tabela com todos os ids dos carpets? Pra gente criar a verificação de não abrir um em cima do outro? 

Exemplo 

local carpets = {id 1, id 2, id 3} 

E assim vai.

Se puder fazer isso, eu crio o script de verificação.

**Comment by dudantas** [comment]
> > > > Ata. O problema é quando usa ele dentro dele mesmo né. Não tinha entendido essa parte. Vou subir a correção mais tarde.
> > > > Me manda essa solução de stalkar os carpets.
> > > 
> > > 
> > > Por onde ti mando?
> > 
> > 
> > Pode enviar aqui mesmo. É só jogar o arquivo no comentário que ele vai anexar.
> > Na real, eu arrastei  e ele disse que não suporta o formato.. '-' vou mandar ai.
> 
> local foldedCarpet = {
> [25393] = 25392,
> [25392] = 25393, --rift carpet
> [26193] = 26192,
> [26192] = 26193, --void carpet
> [26087] = 26109, --yalahahari carpet
> [26109] = 26087, --yalahahari carpet
> [26088] = 26110, --white fur carpet
> [26110] = 26088, --white fur carpet
> [26089] = 26111, --bamboo mat carpet
> [26111] = 26089, --bamboo matr carpet
> [26371] = 26363, --crimson carpet
> [26363] = 26371, --crimson carpet
> [26366] = 26372, --azure carpet
> [26372] = 26366, --azure carpet
> [26367] = 26373, --emerald carpet
> [26373] = 26367, --emerald carpet
> [26368] = 26374, --light parquet carpet
> [26374] = 26368, --light parquet carpet
> [26369] = 26375, --dark parquet carpet
> [26375] = 26369, --dark parquet carpet
> [26370] = 26376, --mable floor
> [26376] = 26370, --marble floor
> [27084] = 27092, --flowery carpet
> [27092] = 27084, --flowery carpet
> [27085] = 27093, --Colourful Carpet
> [27093] = 27085, --Colourful Carpet
> [27086] = 27094, --striped carpet
> [27094] = 27086, --striped carpet
> [27087] = 27095, --fur carpet
> [27095] = 27087, --fur carpet
> [27088] = 27096, --diamond carpet
> [27096] = 27088, --diamond carpet
> [27089] = 27097, --patterned carpet
> [27097] = 27089, --patterned carpet
> [27090] = 27098, --night sky carpet
> [27098] = 27090, --night sky carpet
> [27091] = 27099, --star carpet
> [27099] = 27091, --star carpet
> [29350] = 29351, --verdant carpet
> [29351] = 29350, --verdant carpet
> [29352] = 29353, --shaggy carpet
> [29353] = 29352, --shaggy carpet
> [29355] = 29354, --mystic carpet
> [29354] = 29355, --mystic carpet
> [29356] = 29357, --stone tile
> [29357] = 29356, --stone tile
> [29359] = 29358, --wooden plank
> [29358] = 29359, --wooden plank
> [29386] = 29387, --wheat carpet
> [29387] = 29386, --wheat carpet
> [29388] = 29389, --crested carpet
> [29389] = 29388, --crested carpet
> [29390] = 29391, --decorated carpet
> [29391] = 29390, --decorated carpet
> 
> }
> 
> function onUse(player, item, fromPosition, target, toPosition, isHotkey)
> local carpet = foldedCarpet[item.itemid]
> if not carpet then
> return false
> end
> 
> ```
> local tile = Tile(fromPosition)
> 
> if fromPosition.x == CONTAINER_POSITION then
> 	player:sendTextMessage(MESSAGE_STATUS_SMALL, "Put the item on the floor first.")
> elseif not fromPosition:getTile():getHouse() then
> 	player:sendTextMessage(MESSAGE_STATUS_SMALL, "You may use this only inside a house.")
> elseif tile:getItemCountById(item.itemid) == 1 then
> 
> 	for k,v in pairs(foldedCarpet) do
> 		if tile:getItemCountById(k) > 0 and k ~= item.itemid then 
> 			player:sendTextMessage(MESSAGE_STATUS_SMALL, "Ja tem um tapete ai embaixo")
> 			return false
> 		end
> 	end
> 
> 	item:transform(carpet)
> 
> end
> return true
> ```
> 
> end

Ué... Esse é o script para não usar o item 2 vezes no mesmo tile, não ?

**Comment by dudantas** [comment]
@Lycanzito eu acabei de testar o que você falou e não ocorre o bug.
Abri um em cima do outro e continuou tudo normal. Quanto a door, ta bugado sim, dá pra abrir ele na door e ele fica lá preso.

**Comment by dudantas** [comment]
![gif](https://user-images.githubusercontent.com/8551443/74855057-eab3d600-531e-11ea-98e9-98169271edfe.gif)


É assim que se reproduz o erro de ficar preso dentro do carpet? Aqui n aconteceu.

**Comment by Lycanzito** [comment]
> ![gif](https://user-images.githubusercontent.com/8551443/74855057-eab3d600-531e-11ea-98e9-98169271edfe.gif)
> 
> É assim que se reproduz o erro de ficar preso dentro do carpet? Aqui n aconteceu.

Sim, faz isso com 10 carpets. dai acontece.

**Comment by majestyotbr** [comment]
https://github.com/opentibiabr/otservbr-global/commit/a8c9fbd95b8662ddcd25c63ecdfbfa06727d3b67

**Comment by Lycanzito** [comment]
Só a titulo de curiosidade mesmo, são 3 coisas que estão em questão nessa ISSUE, não deveria continuar aberto? @MajestyOTBR

**Comment by Lycanzito** [comment]
@MajestyOTBR obrigado por reabrir ! =)
vou modificar lá em cima.

**Comment by Lycanzito** [comment]
1:
For some reason , the carpets are just dissapearing from player's houses;
Talvez
tenha relação com o sistema doCheckhouses, que eu reportei , mas não consigo entender, o pq teria relação com as outras casas, pq ele limpa toooodos os carpetes, de tooodas as casas.

**Comment by Lycanzito** [comment]
acredito que a solução para a problema numero 2, seja "ser possível" visualizar o tapete aberto, pelo browse field, mas como fazer isso?^.-

**Comment by barack3006** [comment]
Faça você mesmo jovem gafanhoto.

**Comment by Lycanzito** [comment]
Acredito que o problema que era relatado do sumiço dos carpets, tinha relação com o docheckhouse, como o problema não voltou a ocorrer, vou apagar, e deixar apenas o "Enhancement" necessário, por gentileza remover a tag de bug, e colocar Enhancement, obrigado ^.-

@dudantas @MajestyOTBR ( tô marcando vocês 2, pq só conheco os 2 que podem fazer isso) xD

**Comment by dudantas** [comment]
@Lycanzito vou fechar esse, caso queira abre outro issue com a outra questão, fica mais organizado assim.

Obrigado.

**Comment by Lycanzito** [comment]
> @Lycanzito vou fechar esse, caso queira abre outro issue com a outra questão, fica mais organizado assim.
> 
> Obrigado.

ok, o farei assim =)
