### ISSUE TITLE
in-game store mounts and houses category client debug

### ISSUE THREAD

**Issue by milkersky** [opentibiabr/otservbr-global-archived#845]
im using client 10, when i open in game store and choose mounts or houses category then my client go closed

**Comment by MajestyOTBR** [comment]
The debug happens because each category on client 10 doesn't support more than 50 iten, the reason is the description of the itens on client 12. A solution is separate mounts and houses in more categories on client 10.

**Comment by majestyotbr** [comment]
The debug happens because each category on client 10 doesn't support more than 50 itens. A solution is separate mounts and houses in more categories on client 10.

**Comment by milkersky** [comment]
Thanks for answer :)
