### ISSUE TITLE
Amount of Itens/ Buyin Npc itens (LAG)

### ISSUE THREAD

**Issue by Lycanzito** [opentibiabr/otservbr-global-archived#846]
Hi Everyone ! =)
Ive started this issue, thinking the problem was with the Weight Secury System.
But the real problem is with the amount of itens, when you have more than 1k itens or something close to that, when you buy more things or just trough things on the ground, use itens like, ssas
(changing the cap), it gives to the server a giant lag.

The solution ? Problably limit the max itens for "main backpacks" 1000 slots

**Comment by IgorCFG** [comment]
## PT-BR
> When Someone change his cap, like.. using stone skin amulet, might rings, drop potions/ etc...

Não entendi essa parte.. Desde quando SSA muda o cap?

> And, if die and your backpack is over than 10k cap, you dont drop it.

Talvez seja algo sobre a quantidade de itens dropadas no chão ao mesmo tempo.. 🤔

> When you have over than 10k cap, and you buy alot of things from the npcs,
It is giving a strong/massive lag.

Só se for 10k+? Se você tiver menos, cerca de 7k+, não dá lag? Mesmo que seja menos?

## EN-US
> When Someone change his cap, like.. using stone skin amulet, might rings, drop potions/ etc...

I can't understand that.. how SSA changes player cap?

> And, if die and your backpack is over than 10k cap, you dont drop it.

Maybe.. something about amount of items on the floor make this bug.. 🤔

> When you have over than 10k cap, and you buy alot of things from the npcs,
It is giving a strong/massive lag.

Only 10k+? And if u have less (about 7k+)?

**Comment by dudantas** [comment]
This is the number of items, not the cap.
The solution is to limit the number of items in a bag.

**Comment by IgorCFG** [comment]
## PT-BR
Se não estou enganado eu já mexi em algo relacionado a esse limite de itens, acho que ele está em uma constante em um arquivo .lua, talvez no login mesmo, não to lembrando agora, daí é só editar lá, provavelmente por ser `CM, GOD ou GM` o sistema deve ignorar esse limite e daí dar esse lag absurdo (talvez né).

## EN-US
If I'm not mistaken I already touched something related to this item limit, I think it is in a constant in a .lua file, maybe in login file.. I don't remember it now, so just edit it there, probably because it is `CM , GOD or GM` the system must ignore this limit and then give this absurd lag (maybe..).

**Comment by Lycanzito** [comment]
> ## PT-BR
> > When Someone change his cap, like.. using stone skin amulet, might rings, drop potions/ etc...
> 
> Não entendi essa parte.. Desde quando SSA muda o cap?
>  R: A partir do momento, que o SSA perde suas cargas, ele libera 6 de cap ( peso dele )
> > And, if die and your backpack is over than 10k cap, you dont drop it.
>  
> Talvez seja algo sobre a quantidade de itens dropadas no chão ao mesmo tempo.. 🤔
>  R : Não acredito que isso seja o problema, morrer com 3500 Strong mana potions, na bp, já impossibilita o drop da bp ( 10k de cap )
> > When you have over than 10k cap, and you buy alot of things from the npcs,
> > It is giving a strong/massive lag.
> 
> Só se for 10k+? Se você tiver menos, cerca de 7k+, não dá lag? Mesmo que seja menos?
Aparentemente o LAG apenas acontece, se você tiver com + de 10k de cap

**Comment by Lycanzito** [comment]
> This is the number of items, not the cap.
> The solution is to limit the number of items in a bag.

I dont think that is the problem, but dont dismiss this possibility

**Comment by Lycanzito** [comment]
> ## PT-BR
> Se não estou enganado eu já mexi em algo relacionado a esse limite de itens, acho que ele está em uma constante em um arquivo .lua, talvez no login mesmo, não to lembrando agora, daí é só editar lá, provavelmente por ser `CM, GOD ou GM` o sistema deve ignorar esse limite e daí dar esse lag absurdo (talvez né).
> 
> ## EN-US
> If I'm not mistaken I already touched something related to this item limit, I think it is in a constant in a .lua file, maybe in login file.. I don't remember it now, so just edit it there, probably because it is `CM , GOD or GM` the system must ignore this limit and then give this absurd lag (maybe..).

Will make a video explaining with a Player, and will post it here.

**Comment by Lycanzito** [comment]
https://www.youtube.com/watch?v=h_b9iAGZjj4

**Comment by Lycanzito** [comment]
> ## PT-BR
> Se não estou enganado eu já mexi em algo relacionado a esse limite de itens, acho que ele está em uma constante em um arquivo .lua, talvez no login mesmo, não to lembrando agora, daí é só editar lá, provavelmente por ser `CM, GOD ou GM` o sistema deve ignorar esse limite e daí dar esse lag absurdo (talvez né).
> 
> ## EN-US
> If I'm not mistaken I already touched something related to this item limit, I think it is in a constant in a .lua file, maybe in login file.. I don't remember it now, so just edit it there, probably because it is `CM , GOD or GM` the system must ignore this limit and then give this absurd lag (maybe..).

Thats the solution!

The problem is with the amount of itens! :DDD

**Comment by Lycanzito** [comment]
> This is the number of items, not the cap.
> The solution is to limit the number of items in a bag.

The problem is with the amount of itens! :DDD
thanks !=D

**Comment by Lycanzito** [comment]
anyone have a solution for limit it?

**Comment by Lycanzito** [comment]
Updated the name/the first comment

**Comment by IgorCFG** [comment]
hm, try comment [this part](https://github.com/opentibiabr/otservbr-global/blob/develop/data/events/scripts/player.lua#L298-L301) and see what happen, but i'm not sure about it works

or

change the constant `DISABLE_CONTAINER_WEIGHT` value to `1`

**Comment by Lycanzito** [comment]
> hm, try comment [this part](https://github.com/opentibiabr/otservbr-global/blob/develop/data/events/scripts/player.lua#L298-L301) and see what happen, but i'm not sure about it works
> 
> or
> 
> change the constant `DISABLE_CONTAINER_WEIGHT` value to `1`

o problema é de fato, com a quantidade de itens, isso dai, é sobre o Check do Weight né? ^.-

**Comment by IgorCFG** [comment]
decide se vai no inglês ou no português tio, kkk

sim, por isso disse que provavelmente não ajustaria, mas se tiver problema de weight pelo menos isso aí já resolve.

**Comment by IgorCFG** [comment]
sobre a limitação de item na bp, é um trampo hard pra achar.

a não ser que:
1. tenha um limite exato de itens daí tu pode procurar no projeto pelo valor do limite ex: 10000
2. dê alguma mensagem de log quando tu excede esse limite

se não tiver nenhum desses casos, vai ter que procurar na mão e nos zói pela parte que tá fazendo esse limitador ser ativado

**Comment by Lycanzito** [comment]
> sobre a limitação de item na bp, é um trampo hard pra achar.
> 
> a não ser que:
> 
> 1. tenha um limite exato de itens daí tu pode procurar no projeto pelo valor do limite ex: 10000
> 2. dê alguma mensagem de log quando tu excede esse limite
> 
> se não tiver nenhum desses casos, vai ter que procurar na mão e nos zói pela parte que tá fazendo esse limitador ser ativado

Vamos ver se alguém se pronuncia ^.-

**Comment by Lycanzito** [comment]
Peço desculpas, o problema não é desse repositório.

Vou fechar o issue;

**Comment by guiismiti** [comment]
I'm not sure if this is related, but try to wear a backpack with ~10 free slots and buy 20 items from a NPC without shopping bags - the server freezes.
