### ISSUE TITLE
updated items.xml

### ISSUE THREAD

**Issue by milkersky** [opentibiabr/otservbr-global-archived#860]
now its impossible to put cobra weapons in character weapon slot so i updated items.xml file

[items.zip](https://github.com/opentibiabr/otservbr-global/files/4227501/items.zip)

**Comment by MajestyOTBR** [comment]
I know, i will update items.xml.

Your items.xml is outdated than the items.xml of the repository. Anyway, thanks.

**Comment by majestyotbr** [comment]
Thanks, i will update items.xml later.

**Comment by majestyotbr** [comment]
Fixed: https://github.com/opentibiabr/otservbr-global/commit/dcf06015882b0c0170cd2382e9de77bbdb1ae018
