### ISSUE TITLE
Compile

### ISSUE THREAD

**Issue by gustavotfs** [opentibiabr/otservbr-global-archived#864]
root@tibia:/home/otservbr-global-develop/build# **cmake ..**
-- The C compiler identification is GNU 7.4.0
-- The CXX compiler identification is GNU 7.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- cotire 1.7.6 loaded.
-- Performing Test COMPILER_KNOWS_LTO
-- Performing Test COMPILER_KNOWS_LTO - Success
-- Performing Test COMPILER_KNOWS_CXX11
-- Performing Test COMPILER_KNOWS_CXX11 - Success
-- Performing Test COMPILER_KNOWS_STDLIB
-- Performing Test COMPILER_KNOWS_STDLIB - Failed
-- Found Crypto++: /usr/include
-- Found PugiXML: /usr/include
-- MySQL Include dir: /usr/include/mysql  library dir: /usr/lib/x86_64-linux-gnu
-- MySQL client libraries: /usr/lib/x86_64-linux-gnu/libmysqlclient.so
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Found Spdlog: /usr/include
-- Boost version: 1.65.1
-- Found the following Boost libraries:
--   system
--   filesystem
--   iostreams
--   regex
-- Found LuaJIT: /usr/lib/x86_64-linux-gnu/libluajit-5.1.so;/usr/lib/x86_64-linux-gnu/libm.so (found version "2.1.0-beta3")
-- CXX target tfs cotired without unity build.
-- Configuring done
-- Generating done
-- Build files have been written to: /home/otservbr-global-develop/build

MAKE:

root@tibia:/home/otservbr-global-develop/build# make
[  1%] Generating CXX prefix source cotire/tfs_CXX_prefix.cxx
[  2%] Generating CXX prefix header cotire/tfs_CXX_prefix.hxx
[  3%] Building CXX precompiled header cotire/tfs_CXX_prefix.hxx.gch
In file included from /home/otservbr-global-develop/build/cotire/tfs_CXX_prefix.cxx:4:0,
                 from /home/otservbr-global-develop/build/cotire/tfs_CXX_prefix.hxx:4:
/home/otservbr-global-develop/src/otpch.h:54:10: fatal error: spdlog/spdlog.h: No such file or directory
 #include <spdlog/spdlog.h>
          ^~~~~~~~~~~~~~~~~
compilation terminated.
CMake Error at cmake/FindCotire.cmake:1783 (message):
  cotire: error 1 precompiling
  /home/otservbr-global-develop/build/cotire/tfs_CXX_prefix.hxx.
Call Stack (most recent call first):
  cmake/FindCotire.cmake:3332 (cotire_precompile_prefix_header)

CMakeFiles/tfs.dir/build.make:62: recipe for target 'cotire/tfs_CXX_prefix.hxx.gch' failed
make[2]: *** [cotire/tfs_CXX_prefix.hxx.gch] Error 1
CMakeFiles/Makefile2:99: recipe for target 'CMakeFiles/tfs.dir/all' failed
make[1]: *** [CMakeFiles/tfs.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by dudantas** [comment]
You need to be more attentive, it is clear there that the problem is the lack of lib spdlog. Install it.

The build is normal, the last commit went through Travis normally.

**Comment by majestyotbr** [comment]
https://github.com/opentibiabr/otservbr-global/wiki/Compiling-on-Ubuntu-and-Debian

**Comment by MajestyOTBR** [comment]
READ THE WIKI!

**Comment by majestyotbr** [comment]
We have our own wiki: https://github.com/opentibiabr/otservbr-global/wiki
