### ISSUE TITLE
Debug in players

### ISSUE THREAD

**Issue by ivansho92** [opentibiabr/otservbr-global-archived#869]
Hi everyone, i have a problem, i don't know what is causing the client to close and have to enter twice in a row but when this happens, neither cyclopedia or preys works.

**Comment by FakeShinoda** [comment]
> 
> 
> Hi everyone, i have a problem, i don't know what is causing the client to close and have to enter twice in a row but when this happens, neither cyclopedia or preys works.

Truncate your **prey_slots** table in you database

**Comment by ivansho92** [comment]
> > Hola a todos, tengo un problema, no sé qué está causando que el cliente se cierre y tenga que ingresar dos veces seguidas, pero cuando esto sucede, ni la ciclopedia ni las presas funcionan.
> 
> **Trunca** tu tabla **prey_slots** en tu base de datos

Bro but this debug happen if use or not preys, is the same?

if i'll truncate this table, i guess we can't use preys or i'm wrong?

**Comment by FakeShinoda** [comment]
> 
> 
> > > Hola a todos, tengo un problema, no sé qué está causando que el cliente se cierre y tenga que ingresar dos veces seguidas, pero cuando esto sucede, ni la ciclopedia ni las presas funcionan.
> > 
> > 
> > **Trunca** tu tabla **prey_slots** en tu base de datos
> 
> Bro but this debug happen if use or not preys, is the same?
> 
> if i'll truncate this table, i guess we can't use preys or i'm wrong?

Your login.lua send a function related with prey, if something in you system are wrong then your players client will crash when they log in.

If you truncate the table like i said you'll probably fix the bug.

**Comment by ivansho92** [comment]
> > > > Hola a todos, tengo un problema, no sé qué está causando que el cliente se cierre y tenga que ingresar dos veces seguidas, pero cuando esto sucede, ni la ciclopedia ni las presas operativas.
> > > 
> > > 
> > > **Trunca** tu tabla **prey_slots** en tu base de datos
> > 
> > 
> > Bro, pero esta depuración ocurre si se usan o no presas, ¿es lo mismo?
> > si voy a truncar esta tabla, supongo que no podemos usar presas o me equivoco.
> 
> Su login.lua envía una función relacionada con la presa, si algo en su sistema está mal, el cliente de su jugador se bloqueará cuando inicie sesión.
> 
> Si trunca la tabla como dije, probablemente solucionará el error.

is not working, now my console was crashed.

say many problems and finish with this words:
prey data could not be loaded.

**Comment by FakeShinoda** [comment]
So you did not update your server correctly. Make it right.
Solved and closed.
