### ISSUE TITLE
Teleport with 20hours bug?

### ISSUE THREAD

**Issue by ivansho92** [opentibiabr/otservbr-global-archived#870]
hi everyone, i have a question haha
what happen with all teleports that you need wait about 20 hours, not working, but I think it has something to do with globalsave, i think when have a Globalsave, the time is restored, I don't know if I explain myself well

**Comment by dudantas** [comment]
what script is this? send his link here.

**Comment by dudantas** [comment]
When creating an issue, be sure to describe it correctly. We are not prophets.

You need to quote the script, position, as you do to reproduce the error, it is difficult for you to just create an issue saying what happens without explaining anything.
Create another issue using the guide that is offered when you create a new issue.

**Comment by ivansho92** [comment]
that's the reason cus this was a question haha, cus is in every teleport with time to back, for example, the false god, the horned fox, but i think it has something to do with globalsave, so i apologize for my post.

**Comment by dudantas** [comment]
> that's the reason cus this was a question haha, cus is in every teleport with time to back, for example, the false god, the horned fox, but i think it has something to do with globalsave, so i apologize for my post.

Make a new issue citing the positions and if possible the link to the quest informing the time / place and we review it.
Most of the quests were not done by us, so it is difficult to know where these problems are.

**Comment by dudantas** [comment]
@ivansho92 
![image](https://user-images.githubusercontent.com/8551443/75086645-5bbcde80-5515-11ea-9989-2b50deb22cc2.png)

solving...
