### ISSUE TITLE
Question (Limit maxPacketsPerSecond)

### ISSUE THREAD

**Issue by Lycanzito** [opentibiabr/otservbr-global-archived#871]
Hello again =)

why do we have this limitation?

Is something about that WPE ? 

Cuz, I've find a problem, that if you have the limit has the default ( 25 )
it crashes the server, but when it is rise to (40 is fine)

**Comment by dudantas** [comment]
Isso garante que não seja possível enviar vários pacotes seguidamente, evitando assim o uso de wpe para crashar a distro. O recomendado é o valor entre 25 e 35.

Quanto ao crash, não entendi. Explica como isso acontece.

**Comment by Lycanzito** [comment]
> Isso garante que não seja possível enviar vários pacotes seguidamente, evitando assim o uso de wpe para crashar a distro. O recomendado é o valor entre 25 e 35.
> 
> Quanto ao crash, não entendi. Explica como isso acontece.

Então.. meio difícil de explicar, mas tá sobrecarregando o servidor, pelo market, se eu coloco 40 <- não sobrecarrega.
será q seria um grande problema ?

**Comment by Lycanzito** [comment]
O cara tá tipo, sobrecarregando, ele toma uns 3~4 kicks do servidor, 
e dai dps o servidor crasha, segmentation fault (core dumped)
