### ISSUE TITLE
Summon Attack Issue

### ISSUE THREAD

**Issue by Lycanzito** [opentibiabr/otservbr-global-archived#887]
Se você já esta atacando a creatura, os summons ficam parados . ( se você summonar um pouco + distante da creatura).

Video:

https://www.youtube.com/watch?v=1mzAM8lFxPY

**Comment by FakeShinoda** [comment]
Do it by yourself [9]

**Comment by Lycanzito** [comment]
Mais uma informação ! 

O problema não acontece em relação a DISTANCIA, que eu tinha colocado primeiramente no video, o problema de fato, acontece se o jogador estiver movimentando-se no ato, ou movimentar-se logo após summonar a creatura, acredito que seja um problema com o onthink? da creatura?

^.-

**Comment by heberholanda** [comment]
Bug has already been fixed.
