### ISSUE TITLE
Missing Page

### ISSUE THREAD

**Issue by Lycanzito** [opentibiabr/otservbr-global-archived#893]
Missing the "Home page" from the Store
![image](https://user-images.githubusercontent.com/52710697/75480329-d8b9df00-597f-11ea-9c59-739caec5d526.png)

**Comment by FakeShinoda** [comment]
Do it by yourself [3]

**Comment by majestyotbr** [comment]
Updated gamestore:
https://github.com/opentibiabr/otservbr-global/blob/develop/data/modules/scripts/gamestore/gamestore.lua
https://github.com/opentibiabr/otservbr-global/blob/develop/data/modules/scripts/gamestore/init.lua
