### ISSUE TITLE
Reward System

### ISSUE THREAD

**Issue by Lycanzito** [opentibiabr/otservbr-global-archived#894]
Reward System sem funcionar corretamente:
apenas 1 jogador esta recebendo a recompensa.

![image](https://user-images.githubusercontent.com/52710697/75480601-5382fa00-5980-11ea-83a1-e3b538594170.png)

**Comment by FakeShinoda** [comment]
Do it by yourself [2]

**Comment by gerotib** [comment]
@Lycanzito Both players were regular characters, or one of them was god/gm? Because this reward system doesnt allow gods to open corpses

**Comment by Lycanzito** [comment]
> @Lycanzito Both players were regular characters, or one of them was god/gm? Because this reward system doesnt allow gods to open corpses

both were players

**Comment by Lycanzito** [comment]
> @Lycanzito Both players were regular characters, or one of them was god/gm? Because this reward system doesnt allow gods to open corpses

sometimes it gives the reward, only to 1 player, and sometimes, everyone takes nothing.

**Comment by barack3006** [comment]
Faça você mesmo jovem gafanhoto.

**Comment by Lycanzito** [comment]
> Faça você mesmo jovem gafanhoto.

Então, kkk.. 
Não é que eu já não tenha tentado/esteja tentando, ^.-

**Comment by Lycanzito** [comment]
Encontrei os problemas, vou fechar&abrir outra Issue que encontrei decorrente disso;
Obrigado =D
