### ISSUE TITLE
Enhancement ( Limiting Client )

### ISSUE THREAD

**Issue by Lycanzito** [opentibiabr/otservbr-global-archived#895]
It should be possible to put a "connect", "disconnect" and limit the access only to the client 12. excluding client 10 access.

or just removing the acess to the client 10 ^.-

Since this repo only supports the client 12;

**Comment by FakeShinoda** [comment]
Do it by yourself [1]

**Comment by majestyotbr** [comment]
No.

**Comment by Lycanzito** [comment]
> No.

Opa, poderia me dizer o por quê?
É muito difícil de ser feito?
Não é do interesse desse repositório?
Tem algum erro por trás dessa mudança?

**Comment by dudantas** [comment]
Você tem que remofe

**Comment by dudantas** [comment]
Você tem que remover da source todos os "if is Client Version ==)

E colocar um if isClientVersion < 1200
Return false 

Não é exatamente assim as funções, mas é bem semelhante.

**Comment by Lycanzito** [comment]
> Você tem que remover da source todos os "if is Client Version ==)
> 
> E colocar um if isClientVersion < 1200
> Return false
> 
> Não é exatamente assim as funções, mas é bem semelhante.

opa parceiro, obrigado pela informação :-)

mas pelo que eu entendi pelo "no" , não deve ser algo do interesse deste repositório.
se quiser, pode fechar ^^

**Comment by majestyotbr** [comment]
Será mantido por enquanto, até surgir um protocolo que impossibilite a compatibilidade dos dois clientes.
