### ISSUE TITLE
Good morning, i need some help.

### ISSUE THREAD

**Issue by Ulrashirt** [opentibiabr/otservbr-global-archived#896]
Hello everyone, so i downloaded everything and got pretty much all of it up, the server was up, the website was online, but whenever i tried to connect from the Tibia 12 client, i would get a message saying that the host was unreacheable, so my question is, did u guys made a Login.php to got into the game? how did you guys do?

**Comment by majestyotbr** [comment]
MyAAC + login.php for MyAAC:
https://github.com/slawkens/myaac
https://github.com/opentibiabr/myaac-tibia12-login

GesiorAAC + login.php for GesiorAAC:
https://github.com/gesior/Gesior2012/tree/TFS-1.2
https://github.com/opentibiabr/gesioraac-tibia12-login

ZnoteAAC (login.php included):
https://github.com/Znote/ZnoteAAC
