### ISSUE TITLE
DailyRewardSystem

### ISSUE THREAD

**Issue by neykos** [opentibiabr/otservbr-global-archived#9]
Não está funcionando quando você clica para escolher sua recompensa diária aparece a seguinte mensagem "**you have already collected your daily reward**".
Quando você clica em ver o histórico aparece a seguinte mensagem "**you don't have any entries yet**" e aparece um erro no console com a seguinte mensagem **"[Error - mysql_real_query] Query: SELECT * From `dailyreward_history` where `player_id` = 7 ORDER BY `timestamp` DESC LIMIT 15;
Message: Table 'ot.dailyreward_history' doesn't exist**

**Comment by ivenspontes** [comment]
correção no #10

**Comment by dudantas** [comment]
Very good

**Comment by neykos** [comment]
O que seria #10? poderia me informar sou meio leigo...
