### ISSUE TITLE
Question : Reward System

### ISSUE THREAD

**Issue by Lycanzito** [opentibiabr/otservbr-global-archived#902]
Hello, everyone.

I've a question about the 'unique item' from the reward system.

<item id="5903" chance="100000" unique="1" />				

with this tag, I should receive just 1 f hat, from each Ferumbras, right?

but this is happening:

1st player:
![image](https://user-images.githubusercontent.com/52710697/75648869-2a889080-5c30-11ea-9314-cb1c8abcf6b8.png)

2nd player:
![image](https://user-images.githubusercontent.com/52710697/75648891-3c6a3380-5c30-11ea-9a76-6eb299cbe818.png)

**Comment by omarcopires** [comment]
Boa noite, eu conversei com o @LucasCPrazeres uma vez, ele me disse que o problema foi ocasionado na remoção de um creaturescript em um commit posterior ao de correção, tentarei encontra-lo e farei um PR com a correção.

**Comment by Lycanzito** [comment]
> Boa noite, eu conversei com o @LucasCPrazeres uma vez, ele me disse que o problema foi ocasionado na remoção de um creaturescript em um commit posterior ao de correção, tentarei encontra-lo e farei um PR com a correção.

Dorme não, menino Belobriano? xD kkk, ok, obrigado.

**Comment by omarcopires** [comment]
> > Boa noite, eu conversei com o @LucasCPrazeres uma vez, ele me disse que o problema foi ocasionado na remoção de um creaturescript em um commit posterior ao de correção, tentarei encontra-lo e farei um PR com a correção.
> 
> Dorme não, menino Belobriano? xD kkk, ok, obrigado.

As correções foram feitas nesse commit https://github.com/opentibiabr/otservbr-global/commit/57dda31b5054e870bc9990cac47fb9bfd727ba49, basta acompanhar os arquivos que foram modificados, infelizmente não encontrei em qual commit foi removido.

Sobre dormir, creio que isso não dê XP, rsrs!

**Comment by MajestyOTBR** [comment]
data/creaturescripts/scripts/rewardChest/boss.lua, try change:
`local lootFactor = 1`
to:
`local lootFactor = 0.1`

**Comment by Lycanzito** [comment]
> data/creaturescripts/scripts/rewardChest/boss.lua, try change:
> `local lootFactor = 1`
> to:
> `local lootFactor = 0.1`

Testarei assim que possível, obrigado! =)

**Comment by Lycanzito** [comment]
22:29 The following items are available in your reward chest: nothing.

22:29 The following items are available in your reward chest: 63 gold coins, 100 gold coins.

Matando um Ferumbras, 2 jogadores
deu certo não =/

**Comment by dudantas** [comment]
O problema é no script do reward chest, vou corrigir quando tiver com tempo.
