### ISSUE TITLE
The Explorer Society Quest

### ISSUE THREAD

**Issue by omarcopires** [opentibiabr/otservbr-global-archived#91]
Missão Inicial: Faltando o item Family Brooch(item 4845) no baú(32598, 31934, 15). The Ice Delivery: Não é possível usar o Ice Pick no Sharp Icicles(32133, 31688, 9) para obter um Icicle(item 4848). Mesmo criando o item icicle, não é possível entregar ao npc, fazendo essa e as próximas missões ficarem travadas.

source:http://tibia.wikia.com/wiki/The_Explorer_Society_Quest

**Comment by gpedro** [comment]
- [x] falta uma rope dentro deste bau
```
16:30 You see a chest (Vol:15).
It weighs 120.00 oz.
Item ID: 1740
Position: 32604, 31908, 3
```

- [x] falta bloquear as portas da prisão para somente abrir com a chave (confirmar)
```
16:17 You see a closed door.
Item ID: 8545
Position: 32603, 31975, 14
16:17 You see a closed door.
Item ID: 8545
Position: 32602, 31975, 14
16:17 You see a copper key (Key:3802).
It weighs 1.00 oz.
Item ID: 2089, Action ID: 3802
Position: 32603, 31977, 14
```

- [x] retirar a shovel do buraco do brooch (sabemos que ela existe mas seria bom retirar para não deixar tão fácil assim)
```
16:19 You see a shovel.
It weighs 35.00 oz.
Item ID: 2554
Position: 32597, 31928, 14
```

- [x] faltando actionid 3802(mesmo número da chave) da porta de frente do bau que pega o brooch
```
16:55 You see a closed door.
Item ID: 5105
Position: 32598, 31933, 15
```

- [ ] o NPC Uzgod "trava" porque ele espera um brooch (itemid: 4845) e o que é recebido no bau é o brooch (itemid: 2318). é necessario fazer uma verificação e mostrar alguma mensagem de não encontrado.
```
17:26 You see a family brooch.
It weighs 1.10 oz.
You see the familyname Windtrouser engraved on this brooch.
Item ID: 2318
Position: 32664, 31895, 9
17:26 You see a family brooch.
It weighs 1.10 oz.
The emblem of a dwarven family is engraved on it.
Item ID: 4845
Position: 32664, 31895, 9
17:24 Community Manager [1]: hi
17:24 Uzgod: Hiho Community Manager! Wanna weapon, eh?
17:24 Community Manager [1]: brooch
17:24 Uzgod: You got me brooch?
17:24 Community Manager [1]: yes
17:24 Uzgod: Thanking you for brooch. Me guessing you now want your pickaxe?
17:24 Community Manager [1]: yes
17:24 Uzgod: Here you have it.
```

- [x] não é possível criar Icicle porque falta a uniqueid 3000 no sharp icicles 
```lua
-- icicle.lua
if target.itemid == 4995 and target.uid == 3000 and player:getStorageValue(Storage.ExplorerSociety.TheIceDelivery) == 5  and player:getStorageValue(Storage.ExplorerSociety.QuestLine) == 5 then
```

**Comment by gpedro** [comment]
aguardando correções, que aparentemente são apenas corrigidos no mapa pelo @eduardodantas95,  para testar e continuar os testes da quest inteira

**Comment by dudantas** [comment]
corrigidas, mais tarde upo o mapa inteiro e os testes podem continuar
caso haja outro bug, criar novo issue
