### ISSUE TITLE
Carpet Improvement

### ISSUE THREAD

**Issue by Lycanzito** [opentibiabr/otservbr-global-archived#912]
Hi everyone! :-)

(Should be possible to see the "open carpet" in browse field");

With it, should be possible unwrap it under stairs, doors,etc.

![image](https://user-images.githubusercontent.com/52710697/75944725-3b771300-5e77-11ea-8e5f-34236c01c22c.png)

**Comment by dudantas** [comment]
> Hi everyone! :-)
> 
> (Should be possible to see the "open carpet" in browse field");
> 
> With it, should be possible unwrap it under stairs, doors,etc.
> 
> ![image](https://user-images.githubusercontent.com/52710697/75944725-3b771300-5e77-11ea-8e5f-34236c01c22c.png)

We have to change it to not be possible to put them on stairs / doors or see how it is in the global and develop the same.
To appear in the browse field you have to change the .dat and as you know, we have no way to modify the client 12's .dat yet.

**Comment by Lycanzito** [comment]
> > Hi everyone! :-)
> > (Should be possible to see the "open carpet" in browse field");
> > With it, should be possible unwrap it under stairs, doors,etc.
> > ![image](https://user-images.githubusercontent.com/52710697/75944725-3b771300-5e77-11ea-8e5f-34236c01c22c.png)
> 
> We have to change it to not be possible to put them on stairs / doors or see how it is in the global and develop the same.
> To appear in the browse field you have to change the .dat and as you know, we have no way to modify the client 12's .dat yet.

No global, é possivel dar browse field nos carpets abertos&abri-los em escadas/portas;
1 seg, vou logar e ti mando umas fotos do global

**Comment by Lycanzito** [comment]
@dudantas aqui ó:
porta aberta:
![image](https://user-images.githubusercontent.com/52710697/75947107-ff937c00-5e7d-11ea-9112-b9109295b14d.png)

porta fechada( com o tapete lá )

![image](https://user-images.githubusercontent.com/52710697/75947120-0cb06b00-5e7e-11ea-9a67-b2639f1da40d.png)

**Comment by dudantas** [comment]
Então no global a solução é essa? Certo, vou ver aqui como fazemos.

**Comment by Lycanzito** [comment]
> Então no global a solução é essa? Certo, vou ver aqui como fazemos.
Yes SIr! :D
