### ISSUE TITLE
The New Frontier Quest

### ISSUE THREAD

**Issue by omarcopires** [opentibiabr/otservbr-global-archived#92]
Mission 01: As 3 portas do lado direito (33061, 31529, 14) deveriam ser portas seladas, e não portas de experiência 1. A alavanca não funciona, sendo impossível o teleport para dar continuidade a missão.

Fonte:http://tibia.wikia.com/wiki/The_New_Frontier_Quest

**Comment by Raphaellb** [comment]
The lever at position x=33061, y=31529, z=14, tem q colocar o ActionId 9123 
The lever at position x=33061, y=31529, z=12, tem q colocar o ActionId 9122 
This will make the teleport work.

**Comment by dudantas** [comment]
@marcomoa already fixed
@Raphaellb thanks, fixed
