### ISSUE TITLE
Poltergeist Outfit & Addons

### ISSUE THREAD

**Issue by cys9211** [opentibiabr/otservbr-global-archived#925]
Add actions to addon Poltergeist Outfit & Addons
Add script
First addon - Spooky Hood 
![spooky_hood](https://user-images.githubusercontent.com/7588103/76320860-882c7500-62e1-11ea-9063-2b892eb0f999.gif)

Second addon - Ghost Claw 
![ghost_claw](https://user-images.githubusercontent.com/7588103/76320875-8c589280-62e1-11ea-9ac3-a884f9050bd3.gif)

**Comment by oualid6496** [comment]
Im not familiar with the latest updates but do the players get the addon when these items are being used? Also what unlocks the outfit (without addons)? Is it only possible to unlock addon 2 after unlocking addon 1? If there is anything else special about it let me know and I'll add it later today.

**Comment by aurelion5670** [comment]
> 
> 
> Im not familiar with the latest updates but do the players get the addon when these items are being used? Also what unlocks the outfit (without addons)? Is it only possible to unlock addon 2 after unlocking addon 1? If there is anything else special about it let me know and I'll add it later today.

You need to complete the full quest in order to unlock the outfit, by the rest, you can get the mount (without even having the quest) and addons just clicking their items.

**Comment by dudantas** [comment]
This quest is not developed, the outfits are related to the Feaster of Souls quest, I'm moving to the issue of quests that need revision or development #726

Thanks for reporting.

**Comment by dudantas** [comment]
Moved for the #726, thanks
