### ISSUE TITLE
[Quest] The Paradox Tower 

### ISSUE THREAD

**Issue by omarcopires** [opentibiabr/otservbr-global-archived#93]
NPC Oldrak não consegue iniciar a missão. Faltando a linha "myth" na conversa.

source:http://tibia.wikia.com/wiki/The_Paradox_Tower_Quest

**Comment by dudantas** [comment]
está faltando toda a quest nos scripts
há apenas as falas em modo de keyword
mas não funciona como mission e nem dá storage ou verifica... 
analisar todo o spoil da quest e criar os scripts que estiverem faltando, verifiquei os dois npcs iniciais e ambos estão sem os devidos scripts
