### ISSUE TITLE
Reward Container / Reward Chest

### ISSUE THREAD

**Issue by EleanorRigby1** [opentibiabr/otservbr-global-archived#932]
**Describe the bug**
Hello everyone, I am using the most recent version of OTBR, a few days ago I was using an old one but now I updated to be able to report without problem. The following happens:

When I take out a boss for example a Ferumbras and 5 people kill it, everyone gets loot normally. But, if there are +15 people, some do not receive loot, that is, the reward container appears empty and the message appears to the players that they have achieved loot.

Do you have any idea what it could be? I was thinking that the DB is very full there are currently 183449 rows in player_rewards.

**Desktop (please complete the following information):**
 - OS: [e.g. Linux Debian 9]
 - Version: [e.g. 10.100]

**Additional context**

**Comment by EleanorRigby1** [comment]
I tried truncating the player_rewards table and the problem was solved. I don't know if it is fixed permanently or only partially.

**Comment by gpedro** [comment]
do you have made backup to we check?
