### ISSUE TITLE
Summons Atravessando Paredes

### ISSUE THREAD

**Issue by rtsrick2017** [opentibiabr/otservbr-global-archived#934]
Quando um monstro invocado por utevo res pisa em um field (imune ou não), ele atravessa paredes e objetos (de houses apenas) para encontrar uma forma de seguir seu mestre ou chegar ao seu alvo.

para reproduzir o bug basta:
- criar um druid ou sorcerer com level suficiente para utilizar utevo res
- ir em um ambiente fechado por uma porta ou paredes (exemplo simples: entre as casas Harbour Place 2 e Harbour Place 3, localizadas no norte do depot de Thais)
- invocar com um fire elemental (pode ser dentro ou fora do local)
- usar uma fire bomb rune sob os pés do summon
- faze-lo se mover
- tranca-lo (dentro ou fora do ambiente), e ficar no lado oposto da parede/porta

o summon irá buscar uma rota para acompanhar seu mestre, atravessando assim, qualquer objetivo, 
seja uma cama, parede, porta, janela, etc...

tive casos em que o summon até mesmo abriu a porta para passar (não consegui mais reproduzir o ocorrido

![summonbug](https://user-images.githubusercontent.com/36482994/77188086-355a7680-6ab4-11ea-9ccb-3fa44fd6fd3b.png)

após reproduzido o bug, o monstro continuará bugado e afetará sua outra summon, até ser morto

Reproduzido em um Windows Server 2012

**Comment by Lycanzito** [comment]
ñ consegui reproduzir o erro.

**Comment by rtsrick2017** [comment]
@Lycanzito o problema é com o reward chest, estou testando pra descobrir exatamente o que tá rolando

**Comment by rtsrick2017** [comment]
Ainda não encontrei um motivo

**Comment by rtsrick2017** [comment]
Fixed! Thanks @FakeShinoda
