### ISSUE TITLE
NPC - Falando Com Múltiplas Pessoas / Andando Além do Spawn

### ISSUE THREAD

**Issue by rtsrick2017** [opentibiabr/otservbr-global-archived#935]
Ao mais de um player falar com um determinado NPC, este irá mandar suas respostas para todos os players com quem ele está focado.

exemplo:
NPC Albinius (Forgotten Knnowledge)
Ao falar temple ou outras keywords, as respostas serão transmitidas a todos os players que falaram hi para ele, conforme ilustrado abaixo:

![npctalkbug](https://user-images.githubusercontent.com/36482994/77188655-18727300-6ab5-11ea-8aeb-2405c61b58ab.png)

Além disso, os NPCs estão andando muito além de sua spawn, muitas vezes ficando inacessíveis aos players, até que ele tenha range para tal (Xodet na loja de potion de Thais por ex.)

Reproduzido em um Windows Server 2012

**Comment by EleanorRigby1** [comment]
Try to update your server or change to Linux, I currently use Debian 9 and the latest version of OTBR, this problem does not happen to me. The problem is on your side.

**Comment by rtsrick2017** [comment]
I see... I will investigate further then. Thanks!
