### ISSUE TITLE
About spells on monsters

### ISSUE THREAD

**Issue by ivansho92** [opentibiabr/otservbr-global-archived#936]
hi everyone, i have a problem with my monsters, i mean attacks like exori vis for example in midnight asuras, could be around a hit by 10k 12k, thats same with exori vis or "waves"
how i can fix that?

**Comment by MajestyOTBR** [comment]
STOP USING CAPSLOCK ON THE ISSUE TITLE!

**Comment by dudantas** [comment]
> hi everyone, i have a problem with my monsters, i mean attacks like exori vis for example in midnight asuras, could be around a hit by 10k 12k, thats same with exori vis or "waves"
> how i can fix that?

I didn't understand what you meant.

**Comment by ivansho92** [comment]
ohhh i think is a problem with multiplier damage in type attacks:  WAVES, Exori vis, Exori mort for example, Scarlett Etzel have this attack:
		<attack name="Sudden Death" interval="2000" chance="16" distance="7" target="1" min="-400" max="-600"/>

But in players this attack means a damage of 15k or more, i mean is like this 600 was multiplier for 20 hahaha and lloyd is same with waves, arachnophobia with dicewave, another bosses with attacks like that, asura midnight for example this attack is exori vis:

<!--		<attack name="energy strike" interval="2000" chance="10" range="1" min="-10" max="-100">

players receive a damage around 8k

**Comment by ivansho92** [comment]
i still have this problem, im trying to understand where is the failured but i thing coul be in src, cus is with every monster with attacks types, energy strike, death strike, sudden dead, waves, have like a mulplier, for example already was dying a player by a Vexclaw cus have this attack 

attack name="death" interval="2000" chance="20" radius="4" target="1" min="-150" max="-400">
			<attribute key="shootEffect" value="suddendeath"

so, hits could be aroung in a range about 8k to 15k

same problem with lloyf for waves, arachnofobica with dicewave, scarlett with this:

attack name="Sudden Death" interval="2000" chance="16" distance="7" target="1" min="-400" max="-600"

**Comment by ivansho92** [comment]
![image](https://user-images.githubusercontent.com/54079212/78500903-d9802680-771e-11ea-8de5-5595b1f4c3d4.png)
![image](https://user-images.githubusercontent.com/54079212/78500915-e735ac00-771e-11ea-8602-4b7807ea851f.png)
