### ISSUE TITLE
Pet not following

### ISSUE THREAD

**Issue by ivansho92** [opentibiabr/otservbr-global-archived#937]
hi guys, when you summon your pet, and then you go to anothers level floors, the pet don't go with you, for example if i invoke my pet in floor 6 and i go to 7 floor the pet stay in level 6 xd

**Comment by ivansho92** [comment]
bro already use your fix, i was be carefully in everything, i was compiled again & now when you put exevo gran res... nothing happen, dont say, sorry not possible, dont waste mana, dont reflect the spell, nothing.

**Comment by rtsrick2017** [comment]
@FakeShinoda still takes quite a few steps for the pet to teleport close to the player, should be instantly as soon as the player moves from a floor to another (that is, if I recall correctly).
