### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by EleanorRigby1** [opentibiabr/otservbr-global-archived#938]
## CAUTION: 
Has anyone had a similar problem? What happens is that out there, there must be an item, script that is giving +20000 magic level. New charts are killing my players with a single sd.R.

**To Reproduce**
IDK :(

**Desktop (please complete the following information):**
 - OS: [e.g. Linux Debian 9]
 - Version: [e.g. 10]

**Comment by majestyotbr** [comment]
Advice: stop using capslock on issue title.

**Comment by Lycanzito** [comment]
> ## CAUTION:
> Has anyone had a similar problem? What happens is that out there, there must be an item, script that is giving +20000 magic level. New charts are killing my players with a single sd.R.
> 
> **To Reproduce**
> IDK :(
> 
> **Desktop (please complete the following information):**
> 
> * OS: [e.g. Linux Debian 9]
> * Version: [e.g. 10]

not really.

**Comment by dudztroyer** [comment]
Someone has probably leveled up your sample vocations to get big ml, so new players might start with that ml lvl up.
