### ISSUE TITLE
Prey System

### ISSUE THREAD

**Issue by omarcopires** [opentibiabr/otservbr-global-archived#95]
No momento, o prey system está funcionando de forma que todo carregamento de dados do banco para esse sistema é feito on-demand, em tempo de execução.

Esse fato abre uma brecha pra explorar o serviço de banco de dados do servidor e potencialmente crashar por causa do acesso simultâneo e execisso ao DB.

ele puxa a lista completa de monstros.. vindo bosses etc..

ele não puxa bixos por lvl

Quando dar rerroll no bonus ele troca toda lista de bixos. (deveria somente trocar o bonus)

**Comment by westwol** [comment]
The system needs to be rewritten with some changes in C++, for example loading prey information onLogin and then store it into tables so we don't have to lookup on the database for the value.

The crash has something to with getMonsterType though.

I don't have enough time to rewrite it but if someone has the raw packet structure I can colaborate something and we can start a WIP.

**Comment by dudantas** [comment]
the development is almost ready in the pull #https://github.com/opentibiabr/OTServBR-Global/pull/234,
thanks for the contribution @westwol

**Comment by westwol** [comment]
You can pull it now, let the tests begin.

**Comment by Raphaellb** [comment]
testing the pray system. the monsters selection based on level are coming up correctly, however I only get pray bonus of XP and damage boosts. it seems like the colums are always giving out same pray bonues. first column on left shows up damage boost, second shows damage, and third always XP bonus. @westwol

**Comment by westwol** [comment]
This is pretty normal, to get a new bonus you'll need to use a bonus reroll if you just click on free list reroll you'll get the same bonus. Also you can wait until the prey expires and pick another monster that will receive a completely new bonus.

**Comment by Raphaellb** [comment]
got it, thank you.
