### ISSUE TITLE
Critical bugged with 65.000% of critical

### ISSUE THREAD

**Issue by IvanMir014** [opentibiabr/otservbr-global-archived#953]
**Describe the bug**
When I apply a critical imbuement to weapon it works correctly but If I change the weapon with another weapon it don't care which one the critical ups to 65000% aprox.

**To Reproduce**
1. Go to imbuement machines and apply critical imbuement to some weapon.
2. Change your weapon with another one, it don't care which.
3. Hit to someone and you will kill it with 1 hit.

**Expected behavior**
Normal critical.

**Screenshots**
https://drive.google.com/file/d/1hIb3LwqGfnhPt9W7yWUMQkSYSewqoKI4/view?usp=sharing

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]

**Comment by majestyotbr** [comment]
#933
