### ISSUE TITLE
Bug in prey?

### ISSUE THREAD

**Issue by ivansho92** [opentibiabr/otservbr-global-archived#954]
http://imgfz.com/i/dDvyb0W.png

we can see the preys, but don't select anyone :C

**Comment by majestyotbr** [comment]
Before create issue here, make sure you are reporting something on latest version of the server.

Unconfirmed.

**Comment by ivansho92** [comment]
> Before create issue here, make sure you are reporting something on latest version of the server.
> 
> Unconfirmed.

what you mean?  im using this files otservbr tfs 1.3 e.e

**Comment by majestyotbr** [comment]
I mean the updated server of the repository, the prey is working.

**Comment by ivansho92** [comment]
but i change all my files just 2 days ago :s  
i'll try to do something, thak you

**Comment by ivansho92** [comment]
> I mean the updated server of the repository, the prey is working.

already fix, thank you <3
