### ISSUE TITLE
Store Two+ Offers Bug

### ISSUE THREAD

**Issue by rtsrick2017** [opentibiabr/otservbr-global-archived#955]
If you have two or more offers of the same item with different configurations, the first one will be forced onto the second+ options

To reproduce it use the current setting provided on this git and then:

1- login on a character with tibia coins
2- go to the store / potions section
3- buy 250 ultimate health potions
4- result: the message displayed is the one of buying 100 potions
5- buy it anyway and receive 100 instead of 250

![image](https://user-images.githubusercontent.com/36482994/77854022-05028e80-71be-11ea-8d42-529311977377.png)

![image](https://user-images.githubusercontent.com/36482994/77854027-0fbd2380-71be-11ea-906b-aba485fa930b.png)

![image](https://user-images.githubusercontent.com/36482994/77854043-29f70180-71be-11ea-9240-9850070ffaed.png)

same happens with exercise weapons, which are charge based.

**Comment by dudztroyer** [comment]
Confirmed here, i'll look into it

**Comment by gpedro** [comment]
confirmed here too. the real problem is ID attribute. currently id attribute is used as offer id and item id. so if we got a purchase with same item id, he will get the first one. I will make some rework on shop system soon

**Comment by majestyotbr** [comment]
Updated gamestore: 
https://github.com/opentibiabr/otservbr-global/blob/develop/data/modules/scripts/gamestore/gamestore.lua 
https://github.com/opentibiabr/otservbr-global/blob/develop/data/modules/scripts/gamestore/init.lua
