### ISSUE TITLE
Not loosing stamina.

### ISSUE THREAD

**Issue by ivansho92** [opentibiabr/otservbr-global-archived#957]
i has configurate to loose stamina but when youre in 41.55 refilled automacally so, how stopped this?

**Comment by gerotib** [comment]
It refilled while your character was in game (maybe stamina refill from daily reward streak?), after relog / after server restart (in this case you could have closed server without saving player)?

**Comment by ivansho92** [comment]
while player was online recharged, withot reward >.<

**Comment by EleanorRigby1** [comment]
I see that you issues old bugs or they do not correspond. None of the bugs that I have mentioned on my server, try to update your server to the latest version of OTBR

**Comment by ivansho92** [comment]
i change all my files for this new so, idk whyhappen this xd
