### ISSUE TITLE
World devourer summon and More

### ISSUE THREAD

**Issue by travisani** [opentibiabr/otservbr-global-archived#967]
**When World Devourer try to summon something.**

Lua Script Error: [Spell Interface]
data/spells/scripts/monster/devourer summon.lua:onCastSpell
data/spells/scripts/monster/devourer summon.lua:13: attempt to compare nil with number
stack traceback:
        [C]: in function '__lt'
        data/spells/scripts/monster/devourer summon.lua:13: in function <data/spells/scripts/monster/devourer summon.lua:8>

--------------------------------------------------------------
**When World Devourer summon Disruption.**

Lua Script Error: [CreatureScript Interface]
data/creaturescripts/scripts/quests/heart of destruction/heartMinionDeath.lua:onDeath
...scripts/quests/heart of destruction/heartMinionDeath.lua:9: attempt to perform arithmetic on global 'destructionSummon' (a nil value)
stack traceback:
        [C]: in function '__sub'
        ...scripts/quests/heart of destruction/heartMinionDeath.lua:9: in function <...scripts/quests/heart of destruction/heartMinionDeath.lua:1>

---------------------------------------------------------
**Debug when try to open loot from: **

Monster: The Scourge Of Oblivion
**Loot ID**: 26217

Client 10 and 12 from otbr tools.

**Comment by majestyotbr** [comment]
#990
