### ISSUE TITLE
Missing rope feature

### ISSUE THREAD

**Issue by travisani** [opentibiabr/otservbr-global-archived#968]
Deathling area.

32881, 32439, 8

![image](https://user-images.githubusercontent.com/13306169/78164221-d126a380-741f-11ea-800b-17209a8aec4b.png)

**Comment by dudantas** [comment]
Are you sure this should not be used through exani hur up?

**Comment by travisani** [comment]
Maybe no, idk really

**Comment by dudantas** [comment]
> Maybe no, idk really

Is exani hur up/down

Thanks.
