### ISSUE TITLE
Party System

### ISSUE THREAD

**Issue by omarcopires** [opentibiabr/otservbr-global-archived#97]
Bug party system não shareia ao usar magia

**Comment by LukSrT** [comment]
Ao usar qualquer magia, o shared irá funcionar? Ou só algumas especificas?

**Comment by dudantas** [comment]
o bug é inconfirmado, fui testar e está normal mano

![image](https://user-images.githubusercontent.com/8551443/61195268-42110a00-a69d-11e9-900f-c72dac526b35.png)


![image](https://user-images.githubusercontent.com/8551443/61195260-37ef0b80-a69d-11e9-9997-7d67d0af6e28.png)

vou fechar o issue, ele foi aberto de acordo com os issues de um repositório salvo engano da OTX free, trouxeram vários issues de lá para cá, esse aí é um deles e nessa pack que está aí já deve ter sido arrumado. 

mas agradeço pela colaboração
