### ISSUE TITLE
Bug On Latest Changes (#958)

### ISSUE THREAD

**Issue by rtsrick2017** [opentibiabr/otservbr-global-archived#971]
unless I missed something, the lastest changes in this piece of code:

data/creaturescripts/scripts/others/login.lua

```
-- Set Client XP Gain Rate
	if Game.getStorageValue(GlobalStorage.XpDisplayMode) > 0 then
		displayRate = Game.getExperienceStage(player:getLevel())
		displayRate = getRateFromTable(experienceStages, self:getLevel(), configManager.getNumber(configKeys.RATE_EXP))
		else
		displayRate = 1
	end
```

resulted into this:

![image](https://user-images.githubusercontent.com/36482994/78199667-bb869d80-7462-11ea-82de-3f06fbc7d167.png)

and

![image](https://user-images.githubusercontent.com/36482994/78199521-516df880-7462-11ea-9f09-1dffea51d3e7.png)

players are unable to login properly

![image](https://user-images.githubusercontent.com/36482994/78199737-ebce3c00-7462-11ea-8ac9-7ac0d1bc2d9f.png)

**Comment by dudantas** [comment]
![image](https://user-images.githubusercontent.com/8551443/78201968-6ac67300-7469-11ea-9910-a51df9c5c101.png)

Download the entire repository and use or know how to pull the commits manually, we are not responsible for incorrect installation of the files.

**Comment by rtsrick2017** [comment]
@dudantas man, I have double checked, and everything else is working just fine!
If I comment the exp section out of login.lua, everything works just fine, the problem is just with that function and that only!

**Comment by dudantas** [comment]
@rtsrick2017 look #972
