### ISSUE TITLE
Client 12 question

### ISSUE THREAD

**Issue by EleanorRigby1** [opentibiabr/otservbr-global-archived#982]
Hello, why can't I enter with Tibia 12? Download everything updated. It tells me that it is under maintenance. Note: With an OTBR server from 1 month old I can enter without problems.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Version: [e.g. 8.1]

**Comment by gpedro** [comment]
have you any error reported in console?

**Comment by EleanorRigby1** [comment]
None:( It would be nice if someone confirmed the error or told me that I am doing wrong. But I am 100% sure that everything is well configured.

**Comment by gpedro** [comment]
did you check your login.php?

**Comment by EleanorRigby1** [comment]
Yes, I already verified that it is not a page or login.php because I checked it in a version of Otbr 1 month ago and it works perfectly, only today I downloaded the most updated server and I can no longer connect, i check if there was any commit in gesior login but there is nothing.

**Comment by EleanorRigby1** [comment]
As you can see, in the old version of OTBR it works.

![Captura de pantalla (1423)](https://user-images.githubusercontent.com/56990575/78323609-990e8600-752f-11ea-93ce-20ede7357d48.png)

**Comment by EleanorRigby1** [comment]
And that in the current version of OTBR, I was thinking, can it be the gesior?

![image](https://user-images.githubusercontent.com/56990575/78323770-1c2fdc00-7530-11ea-9923-6ca474040ca3.png)

**Comment by gpedro** [comment]
hm, this error looks like a problems on login.php. can you check wamp logs?

**Comment by majestyotbr** [comment]
With [updated repository](https://github.com/opentibiabr/otservbr-global) + [MyAAC](https://github.com/slawkens/myaac) + [MyAAC tibia12-login.php](https://github.com/opentibiabr/myaac-tibia12-login/releases/tag/1.3) the login is working.

**Comment by EleanorRigby1** [comment]
> With [updated repository](https://github.com/opentibiabr/otservbr-global) + [MyAAC](https://github.com/slawkens/myaac) + [MyAAC tibia12-login.php](https://github.com/opentibiabr/myaac-tibia12-login/releases/tag/1.3) the login is working.

Hi Majesty, so for Gesior it won't be working?

**Comment by EleanorRigby1** [comment]
This is log https://pastebin.com/m7je7xP5

**Comment by MajestyOTBR** [comment]
Which gesior?

**Comment by EleanorRigby1** [comment]
The one from marcooliveira, as I was saying, worked well before. But if there is no support I understand.

**Comment by majestyotbr** [comment]
Try with our login.php for gesior: 
https://github.com/opentibiabr/gesioraac-tibia12-login

**Comment by EleanorRigby1** [comment]
Thanks for your help! I will use myacc, likewise I have the web separated from the server. Ty

**Comment by majestyotbr** [comment]
Ok.
