### ISSUE TITLE
Modules - Gamestore

### ISSUE THREAD

**Issue by travisani** [opentibiabr/otservbr-global-archived#986]
When Open Store get **Debug** when click:
**Houses** - Sometimes
**Outfits.**

File: data\modules\scripts\gamestore
Packet size does not fit to symmetric encryption (packtzie = 24573)
Using OTBR TOOLS client 10.

**Comment by majestyotbr** [comment]
https://github.com/opentibiabr/otservbr-global/issues/845#issuecomment-585953037
