### ISSUE TITLE
Network Error - Connection:paserHeader Invalid Client

### ISSUE THREAD

**Issue by mrhultin** [opentibiabr/otservbr-global-archived#989]
## CAUTION: OUR SERVER IS UPDATED DAILY. MAKE SURE YOU ARE REPORTING SOMETHING ON THE LATEST VERSION OF THE SERVER.

**Describe the bug**
When running a fresh installation of both your client (Tried both client from Tools, and from Forums) I connect fine, but when entering world I get Remote host closed connection in Client, and in server console, I get [Network error - Connection::parseHeader] Invalid Client Login. 

Tried with my own compile, and nightly compiles.

**To Reproduce**
Note: include any configuration/script required to reproduce.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows] Windows 
 - Version: [e.g. 10] 10

**Additional context**

**Comment by dudantas** [comment]
This is not a bug.
Which site are you using?

**Comment by majestyotbr** [comment]
With [updated repository](https://github.com/opentibiabr/otservbr-global) + [MyAAC](https://github.com/slawkens/myaac) + [MyAAC tibia12-login.php](https://github.com/opentibiabr/myaac-tibia12-login/releases/tag/1.3) the login is working.

If you are using gesior, try our login.php:
https://github.com/opentibiabr/gesioraac-tibia12-login

**Comment by mrhultin** [comment]
Okay, I am currently using Znote which is linked on your forum thread. I will try with MyAAC and see if the error persist. Else I will close.

**Comment by dudantas** [comment]
Check if you are setting the path correctly (it must be the same where the executable is)

**Comment by mrhultin** [comment]
MyAAC imported everything fine, Tibia 10 works fine. 

Getting this error now; https://imgur.com/a/9MoQ3RG

**Comment by majestyotbr** [comment]
Do you have key.pem in the folder?
https://github.com/opentibiabr/otservbr-global/blob/develop/key.pem

**Comment by mrhultin** [comment]
Yes. I do. This is driving me nuts, now I am unable to login through Tibia 10 aswell. I run config.lua stock, only updated DB credentials ofc.

**Comment by majestyotbr** [comment]
https://github.com/opentibiabr/otservbr-global/commit/72ac288b9d4cd13209327d297746205fa2f0a858

Apply this, recompile and try again. Make sure you are using client 12 with RSA changed for OT.

**Comment by mrhultin** [comment]
All of a sudden Tibia 10 works, both with recompiled and old compilation (aswell as latest nightly compilation.)

**Comment by majestyotbr** [comment]
It's working now? If yes, the issue can be closed.

**Comment by mrhultin** [comment]
Not on Tibia 12. Only Tibia 10.

**Comment by majestyotbr** [comment]
I tested yesterday and it's working fine. It's your server/client side.

**Comment by mrhultin** [comment]
Yeah I recompiled a second time, and this 3rd compile worked. Thanks for your help, though I really don't get the error being but I am just happy all work ^^

**Comment by majestyotbr** [comment]
Ok.
