### ISSUE TITLE
Gold Pouch

### ISSUE THREAD

**Issue by omarcopires** [opentibiabr/otservbr-global-archived#99]
Não pode conseguir inserir itens dentro dela de modo algum. nem mesmo parcel comprada da store.

Somente gold, platinum e crystal coin vão pra dentro dela.

Quando converter dentro da bolsa 100 gold coin para virar 1 platinum coin está indo para a bp do char ou dropando no chao, aonde deveria ser mudado dentro da bolsa mesmo.

**Comment by Olimpotibia** [comment]
-- Store Inbox
	local containerIdFrom = fromPosition.y - 64
	local containerFrom = self:getContainerById(containerIdFrom)
	if (containerFrom) then
		if (containerFrom:getId() == ITEM_STORE_INBOX and toPosition.y >= 1 and toPosition.y <= 11 and toPosition.y ~= 3) then
			self:sendCancelMessage(RETURNVALUE_CONTAINERNOTENOUGHROOM)
			return false
		end
	end

	local containerTo = self:getContainerById(toPosition.y-64)
	if (containerTo) then
		if (containerTo:getId() == ITEM_STORE_INBOX) then
			self:sendCancelMessage(RETURNVALUE_CONTAINERNOTENOUGHROOM)
			return false
		end
		-- Gold Pounch
		if (containerTo:getId() == GOLD_POUNCH) then
			if (not (item:getId() == ITEM_CRYSTAL_COIN or item:getId() == ITEM_PLATINUM_COIN or item:getId() == ITEM_GOLD_COIN)) then
				self:sendCancelMessage("You can move only money to this container.")
				return false
			end
		end

**Comment by gpedro** [comment]
not applicable once not have this system with easy change coins.
