### ISSUE TITLE
UE with various monsters.

### ISSUE THREAD

**Issue by travisani** [opentibiabr/otservbr-global-archived#992]
Only part of this monsters receive all damage from all UE's

![image](https://user-images.githubusercontent.com/13306169/78451002-1550b880-7659-11ea-993f-d40cd5ac1f48.png)

**Comment by travisani** [comment]
Exemples
![image](https://user-images.githubusercontent.com/13306169/78451057-71b3d800-7659-11ea-9951-016df5722fb3.png)

**Comment by Lycanzito** [comment]
Im pretty sure that, they receive the damage, but it doenst is showing up,

In global, it's the same.

WHen there is alot of spam, it happens.

**Comment by felipe2g** [comment]
Please, make a test with a normal character and a another monsters.

See if all monsters in area die.

**Comment by luucassoares** [comment]
I did a test with a regular character and it did not happen. All monsters on screen took same damage.
