### ISSUE TITLE
NPC LYNDA

### ISSUE THREAD

**Issue by emb1990** [opentibiabr/otservbr-global-archived#994]
NPC Lynda does not respond ''Ankh'' in quest of mage outfit, i looked archive .lua and .xml and it looks ok, i dont kknow what is happening. can u help me?

## CAUTION: OUR SERVER IS UPDATED DAILY. MAKE SURE YOU ARE REPORTING SOMETHING ON THE LATEST VERSION OF THE SERVER.

**Describe the bug**

**To Reproduce**
Note: include any configuration/script required to reproduce.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Version: [e.g. 10]

**Additional context**

**Comment by majestyotbr** [comment]
You need `(Storage.OutfitQuest.MageSummoner.AddonWand) == 5` to talk with NPC Lynda with "ankh".
