### ISSUE TITLE
Willcard in prey not working.

### ISSUE THREAD

**Issue by ivansho92** [opentibiabr/otservbr-global-archived#997]
if someone get willcards for tibia coins in store, when you want to change a creature just can do thats for money, willcard not working, can't choice another creatures with thats cards.

![as](https://user-images.githubusercontent.com/54079212/78571013-57116880-77eb-11ea-98fc-d7eb5bdd480d.png)

**Comment by rviniciuss** [comment]
I got the same problem, would anyone have the solution?

**Comment by Tazer89** [comment]
Confirm same prbolem here.

**Comment by gerotib** [comment]
Thats missing feature I think, not a bug, just sayig.

**Comment by Tazer89** [comment]
@gerotib its not a missing feature. Its a bug.

**Comment by dudztroyer** [comment]
It's a missing feature.

**Comment by FakeShinoda** [comment]
It's a missing feature, not a bug.. will be added soon ^^
